-- Drop existing table if it exists
DROP TABLE IF EXISTS "Equities";
DROP TABLE IF EXISTS equities;
-- Drop existing table if it exists
DROP TABLE IF EXISTS "Equities";
DROP TABLE IF EXISTS equities;

-- Create equities table with appropriate data types
CREATE TABLE equities
(
    "Ticker"                                   TEXT,
    "ISIN"                                     TEXT,
    "Name"                                     TEXT,
    "Description"                              TEXT,
    "Exchange"                                 TEXT,
    "Unit"                                     TEXT,
    "Sector"                                   TEXT,
    "Industry"                                 TEXT,
    "Last Updated"                             DATE,
    "Income Statement Report Date"             DATE,
    "Next Earnings"                            DATE,
    "Style Class"                              TEXT,
    "Next Earnings (Status)"                   TEXT,
    "Size Class"                               TEXT,
    "Flag"                                     TEXT,
    "Region"                                   TEXT,
    "Country"                                  TEXT,
    "Trading Country"                          TEXT,
    "Market Cap"                               NUMERIC,
    "Enterprise Value"                         NUMERIC,
    "Last Price"                               NUMERIC,
    "Price Target (YTD Ago)"                   NUMERIC,
    "Total Return (YTD)"                       NUMERIC,
    "Price Target"                             NUMERIC,
    "Price Target - Low"                       NUMERIC,
    "Price Target - Median"                    NUMERIC,
    "Price Target - High"                      NUMERIC,
    "Price Target - #"                         NUMERIC,
    "P/E (NTM)"                                NUMERIC,
    "P/E (LTM)"                                NUMERIC,
    "Altman Z-Score (FY)"                      NUMERIC,
    "Altman Z-Score (FQ)"                      NUMERIC,
    "Altman Z-Score (LTM)"                     NUMERIC,
    "Beta (1Y)"                                NUMERIC,
    "Beta (2Y)"                                NUMERIC,
    "Beta (5Y)"                                NUMERIC,
    "Analyst Rating"                           NUMERIC,
    "# Strong Sell Ratings"                    NUMERIC,
    "# Strong Buys Ratings"                    NUMERIC,
    "# Hold Ratings"                           NUMERIC,
    "# Buys Ratings"                           NUMERIC,
    "# Sell Ratings"                           NUMERIC,
    "Total Revenues/CAGR (5Y FY)"              NUMERIC,
    "Total Revenues (FQ)"                      NUMERIC,
    "Total Revenues (-1FY)"                    NUMERIC,
    "Total Revenues (FY)"                      NUMERIC,
    "Total Revenues (LTM)"                     NUMERIC,
    "Total Operating Expenses (LTM)"           NUMERIC,
    "P/TBV (LTM)"                              NUMERIC,
    "TBV (FY)"                                 NUMERIC,
    "TBV (LTM)"                                NUMERIC,
    "Market Cap (Country R)"                   NUMERIC,
    "Tot. Return %/CAGR (3Y)"                  NUMERIC,
    "Tot. Return %/CAGR (10Y)"                 NUMERIC,
    "Total Return (5Y)"                        NUMERIC,
    "Total Return (10Y)"                       NUMERIC,
    "Net Income/Adj. (-1FY)"                   NUMERIC,
    "CFF (LTM)"                                NUMERIC,
    "CFI (LTM)"                                NUMERIC,
    "FCF (LTM)"                                NUMERIC,
    "CFO (LTM)"                                NUMERIC,
    "EBITDA (FQ)"                              NUMERIC,
    "EBITDA (LTM)"                             NUMERIC,
    "EBITDA (FY)"                              NUMERIC,
    "EBITDA (-1FY)"                            NUMERIC,
    "EBITDA/Adj. (LTM)"                        NUMERIC,
    "EBITDA/Adj. (FY)"                         NUMERIC,
    "EBITDA/Adj. (-1FY)"                       NUMERIC,
    "EBIT (FQ)"                                NUMERIC,
    "EBIT (LTM)"                               NUMERIC,
    "EBIT (FY)"                                NUMERIC,
    "EBIT (-1FY)"                              NUMERIC,
    "EBIT/Adj. (-1FY)"                         NUMERIC,
    "EBIT/Adj. (FY)"                           NUMERIC,
    "EBIT/Adj. (LTM)"                          NUMERIC,
    "EBIT - Est Med (FY1E)"                    NUMERIC,
    "EBIT - Est Med (NTM)"                     NUMERIC,
    "Return On Equity % (LTM)"                 NUMERIC,
    "Return On Equity % (FY)"                  NUMERIC,
    "Net Income - (IS) (FY)"                   NUMERIC,
    "Net Income - (IS) (LTM)"                  NUMERIC,
    "Normalized Net Income (FY)"               NUMERIC,
    "Normalized Net Income (LTM)"              NUMERIC,
    "Net Income/Adj. (FY)"                     NUMERIC,
    "Net Income/Adj. (LTM)"                    NUMERIC,
    "Net Income Margin % (FY)"                 NUMERIC,
    "Net Income Margin % (LTM)"                NUMERIC,
    "Volatility (1M)"                          NUMERIC,
    "Volatility (3M)"                          NUMERIC,
    "Volatility (6M)"                          NUMERIC,
    "Volatility (1Y)"                          NUMERIC,
    "Volume (Shrs)"                            NUMERIC,
    "Short Int. (%)"                           NUMERIC,
    "Dividend Per Share (LTM)"                 NUMERIC,
    "Div Yield (Ind)"                          NUMERIC,
    "Div Yield (LTM)"                          NUMERIC,
    "Total Debt (FY)"                          NUMERIC,
    "Total Equity (FY)"                        NUMERIC,
    "Total Equity (LTM)"                       NUMERIC,
    "Total Debt (LTM)"                         NUMERIC,
    "Total Assets (LTM)"                       NUMERIC,
    "Total Assets (FY)"                        NUMERIC,
    "Current Ratio (FY)"                       NUMERIC,
    "Current Ratio (LTM)"                      NUMERIC,
    "Gross Profit Margin % (FY)"               NUMERIC,
    "Gross Profit Margin % (LTM)"              NUMERIC,
    "Asset Turnover (FY)"                      NUMERIC,
    "Asset Turnover (LTM)"                     NUMERIC,
    "Gross Profit (LTM)"                       NUMERIC,
    "Gross Profit (FY)"                        NUMERIC,
    "EPS Norm - Est Avg (NTM)"                 NUMERIC,
    "EPS/Adj. (-1FY)"                          NUMERIC,
    "EPS/Adj. (FY)"                            NUMERIC,
    "EPS/Adj. (LTM)"                           NUMERIC,
    "EPS Norm - Est Avg (FY1E)"                NUMERIC,
    "Gain (Loss) On Sale Of Assets (LTM)"      NUMERIC,
    "Cost Of Revenues (LTM)"                   NUMERIC,
    "Cash Acquisitions (LTM)"                  NUMERIC,
    "Cash Acquisitions (FY)"                   NUMERIC,
    "Cash Acquisitions (-1FY)"                 NUMERIC,
    "Inventory (LTM)"                          NUMERIC,
    "Goodwill (FQ)"                            NUMERIC,
    "Goodwill (LTM)"                           NUMERIC,
    "Goodwill (FY)"                            NUMERIC,
    "Goodwill (-1FY)"                          NUMERIC,
    "Impairment of Goodwill (FQ)"              NUMERIC,
    "Impairment of Goodwill (LTM)"             NUMERIC,
    "Impairment of Goodwill (-1FY)"            NUMERIC,
    "Impairment of Goodwill (FY)"              NUMERIC,
    "Operating Income (LTM)"                   NUMERIC,
    "Asset Writedown (LTM)"                    NUMERIC,
    "Asset Writedown (FY)"                     NUMERIC,
    "Asset Writedown (-1FY)"                   NUMERIC,
    "Operating Income (FY)"                    NUMERIC,
    "Capital Expenditure (LTM)"                NUMERIC,
    "Capital Expenditure (-1FY)"               NUMERIC,
    "Capital Expenditure (FY)"                 NUMERIC,
    "Retained Earnings (LTM)"                  NUMERIC,
    "Total Current Assets (LTM)"               NUMERIC,
    "Total Current Liabilities (LTM)"          NUMERIC,
    "R&D Expenses (LTM)"                       NUMERIC,
    "Restructuring Charges (LTM)"              NUMERIC,
    "Restructuring Charges (FQ)"               NUMERIC,
    "Restructuring Charges (-1FY)"             NUMERIC,
    "Restructuring Charges (FY)"               NUMERIC,
    "Interest Expense/Total (LTM)"             NUMERIC,
    "Merger & Restructuring Charges (LTM)"     NUMERIC,
    "Working Capital (LTM)"                    NUMERIC,
    "Other Unusual Items/Total (LTM)"          NUMERIC,
    "Interest Income On Investments (LTM)"     NUMERIC,
    "Buyback Yield (LTM)"                      NUMERIC,
    "Return on Assets (ROA) % (LTM)"           NUMERIC,
    "Return on Assets (ROA) % (FY)"            NUMERIC,
    "Net Income - (IS) (-1FY)"                 NUMERIC,
    "Normalized Net Income (-1FY)"             NUMERIC,
    "P/E (-1FYLTM)"                            NUMERIC,
    "CFF (FY)"                                 NUMERIC,
    "CFF (-1FY)"                               NUMERIC,
    "CFI (FY)"                                 NUMERIC,
    "CFI (-1FY)"                               NUMERIC,
    "CFO (FY)"                                 NUMERIC,
    "CFO (-1FY)"                               NUMERIC,
    "Div Yield (-1FYInd)"                      NUMERIC,
    "FCF (FY)"                                 NUMERIC,
    "Capital Expenditure (FQ)"                 NUMERIC,
    "Capital Expenditure (5YAVGFQ)"            NUMERIC,
    "CFF (FQ)"                                 NUMERIC,
    "CFI (FQ)"                                 NUMERIC,
    "CFO (FQ)"                                 NUMERIC,
    "FCF (FQ)"                                 NUMERIC,
    "Total Revenues (5YAVGFQ)"                 NUMERIC,
    "EBITDA (5YAVGFQ)"                         NUMERIC,
    "EBIT (5YAVGFQ)"                           NUMERIC,
    "P/E (5YAVGLTM)"                           NUMERIC,
    "FCF (5YAVGFQ)"                            NUMERIC,
    "Cash Acquisitions (FQ)"                   NUMERIC,
    "Cash Acquisitions (5YAVGFQ)"              NUMERIC,
    "Asset Writedown (FQ)"                     NUMERIC,
    "Asset Writedown (5YAVGFQ)"                NUMERIC,
    "Impairment of Goodwill (5YAVGFQ)"         NUMERIC,
    "Operating Income (FQ)"                    NUMERIC,
    "Operating Income (5YAVGFQ)"               NUMERIC,
    "P/B (LTM)"                                NUMERIC,
    "P/B (-1FY)"                               NUMERIC,
    "P/B (5YAVG)"                              NUMERIC,
    "Cash And Equivalents (LTM)"               NUMERIC,
    "Cash And Equivalents (FQ)"                NUMERIC,
    "Cash And Equivalents (FY)"                NUMERIC,
    "Cash And Equivalents (5YAVGFQ)"           NUMERIC,
    "Inventory (FQ)"                           NUMERIC,
    "Inventory (FY)"                           NUMERIC,
    "Goodwill (5YAVGFQ)"                       NUMERIC,
    "Inventory (5YAVGFQ)"                      NUMERIC,
    "Avg Employees (LTM)"                      NUMERIC,
    "Avg Employees (FY)"                       NUMERIC,
    "Avg Employees (5YAVGFY)"                  NUMERIC,
    "Retained Earnings (FQ)"                   NUMERIC,
    "Retained Earnings (FY)"                   NUMERIC,
    "Retained Earnings (5YAVGFQ)"              NUMERIC,
    "Working Capital (FQ)"                     NUMERIC,
    "Working Capital (FY)"                     NUMERIC,
    "Working Capital (5YAVGFY)"                NUMERIC,
    "Div Yield (TTM)"                          NUMERIC,
    "Div Yield (NTM)"                          NUMERIC,
    "Div Yield (5YAVGLTM)"                     NUMERIC,
    "Gross Intangible Assets (LTM)"            NUMERIC,
    "Gross Intangible Assets (FY)"             NUMERIC,
    "Gross Intangible Assets (5YAVGFQ)"        NUMERIC,
    "Restructuring Charges (5YAVGFQ)"          NUMERIC,
    "Merger & Restructuring Charges (FQ)"      NUMERIC,
    "Merger & Restructuring Charges (FY)"      NUMERIC,
    "Merger & Restructuring Charges (5YAVGFQ)" NUMERIC,
    "Normalized Net Income (FQ)"               NUMERIC,
    "Normalized Net Income (5YAVGFQ)"          NUMERIC,
    "Net Income/Adj. (FQ)"                     NUMERIC,
    "Net Income/Adj. (5YAVGFQ)"                NUMERIC,
    "Net Income - (IS) (FQ)"                   NUMERIC,
    "Net Income - (IS) (5YAVGFQ)"              NUMERIC,
    "Net Income - (IS) (5YAVGLTM)"             NUMERIC,
    "Normalized Net Income (5YAVGLTM)"         NUMERIC,
    "EBITDA (5YAVGLTM)"                        NUMERIC,
    "EBIT (5YAVGLTM)"                          NUMERIC,
    "Total Revenues (5YAVGLTM)"                NUMERIC,
    "Revenues - Est YoY % (FY1E)"                      NUMERIC,
    "Price Chg. % (1M)"                                NUMERIC,
    "Price Chg. % (3M)"                                NUMERIC,
    "1-Day %"                                          NUMERIC,
    "Price (5D Ago)"                                   NUMERIC,
    "Price (1W Ago)"                                   NUMERIC,
    "Price (1M Ago)"                                   NUMERIC,
    "Price (3M Ago)"                                   NUMERIC,
    "Price (6M Ago)"                                   NUMERIC,
    "Price (1Y Ago)"                                   NUMERIC,
    "Price (3Y Ago)"                                   NUMERIC,
    "Price (5Y Ago)"                                   NUMERIC,
    "Price (QTD Ago)"                                  NUMERIC,
    "Rel. Volume"                                      NUMERIC,
    "Shrs Out"                                         NUMERIC,
    "Shrs Out (-1FY)"                                  NUMERIC,
    "Common Dividends Paid (LTM)"                      NUMERIC,
    "Common Dividends Paid (FY)"                       NUMERIC,
    "Selling General & Admin Expenses/Total (FQ)"      NUMERIC,
    "Selling General & Admin Expenses/Total (FY)"      NUMERIC,
    "Selling General & Admin Expenses/Total (-1FY)"    NUMERIC,
    "Selling General & Admin Expenses/Total (5YAVGFQ)" NUMERIC,
    "Accounts Receivable/Total (FY)"                   NUMERIC,
    "Accounts Receivable/Total (-1FY)"                 NUMERIC,
    "Accounts Receivable/Total (5YAVGFQ)"              NUMERIC,
    "Marketing Expenses (FQ)"                          NUMERIC,
    "Marketing Expenses (FY)"                          NUMERIC,
    "Marketing Expenses (-1FY)"                        NUMERIC,
    "Marketing Expenses (5YAVGLTM)"            NUMERIC,
    -- Phase 9.3 Schema Version 1.3 additions: 48 new columns
    -- Category 1: Revenue Forecasting Estimates (4 columns)
    "Revenues - Est Avg (NTM)"                 NUMERIC,
    "Revenues - Est Avg (FY1E)"                NUMERIC,
    "Revenues - Est Med (NTM)"                 NUMERIC,
    "Revenues - Est Med (FY1E)"                NUMERIC,
    -- Category 2: EV/Sales Time-Series (11 columns)
    "EV/Sales (EST FY1)"                       NUMERIC,
    "EV/Sales (LTM)"                           NUMERIC,
    "EV/Sales (NTM)"                           NUMERIC,
    "EV/Sales (-1FYLTM)"                       NUMERIC,
    "EV/Sales (-2FYLTM)"                       NUMERIC,
    "EV/Sales (-3FYLTM)"                       NUMERIC,
    "EV/Sales (3YAVGLTM)"                      NUMERIC,
    "EV/Sales (-1FQLTM)"                       NUMERIC,
    "EV/Sales (-2FQLTM)"                       NUMERIC,
    "EV/Sales (-3FQLTM)"                       NUMERIC,
    "EV/Sales (-4FQLTM)"                       NUMERIC,
    -- Category 3: Employment Metrics (2 columns)
    "Total Employees (FY)"                     NUMERIC,
    "Total Employees (FQ)"                     NUMERIC,
    -- Category 4: Technical Indicators (6 columns)
    "52W High/Adj"                             NUMERIC,
    "52W Low/Adj"                              NUMERIC,
    "EMA (20D)"                                NUMERIC,
    "EMA (50D)"                                NUMERIC,
    "EMA (100D)"                               NUMERIC,
    "EMA (250D)"                               NUMERIC,
    -- Category 5: EV/EBITDA Extended Time-Series (6 columns)
    "EV/EBITDA (LTM)"                          NUMERIC,
    "EV/EBITDA (NTM)"                          NUMERIC,
    "EV/EBITDA (-1FYLTM)"                      NUMERIC,
    "EV/EBITDA (-1FQLTM)"                      NUMERIC,
    "EV/EBITDA (3YAVGLTM)"                     NUMERIC,
    "EV/EBITDA (EST FY1)"                      NUMERIC,
    -- Category 6: P/E Extended Time-Series (11 columns)
    "P/E (EST FY1)"                            NUMERIC,
    "P/E (-2FYLTM)"                            NUMERIC,
    "P/E (-3FYLTM)"                            NUMERIC,
    "P/E (3YAVGLTM)"                           NUMERIC,
    "P/E (-1FQLTM)"                            NUMERIC,
    "P/E (-2FQLTM)"                            NUMERIC,
    "P/E (-3FQLTM)"                            NUMERIC,
    "P/E (-0FQQoQLTM)"                         NUMERIC,
    "P/E (-0FYYoYLTM)"                         NUMERIC,
    "P/E (-1FYYoYLTM)"                         NUMERIC,
    "P/E (-0FQYoYLTM)"                         NUMERIC,
    -- Category 7: Dividend Record Information (8 columns)
    "Dividend Record (Announce Date)"          DATE,
    "Dividend Record (Ex Date)"                DATE,
    "Dividend Record (Payable Date)"           DATE,
    "Dividend Record (Record Date)"            DATE,
    "Dividend Record (Frequency)"              TEXT,
    "Dividend Record (Currency)"               TEXT,
    "Dividend Record (Amount)"                 NUMERIC,
    "Dividend Streak"                          NUMERIC
) TABLESPACE pg_default;

-- Set table ownership
ALTER TABLE equities
    OWNER TO postgres;

-- Add comments
COMMENT ON TABLE equities IS 'Equities screening data with financial metrics and company information';
