"""
Phase 9.3 Feature Category Registry

Maps Phase 9.3 engineered features to their categorical families for
EDA, evaluation, and reporting purposes.

This module provides a centralized registry of Phase 9.3 feature families
to enable explicit tracking and analysis in EDA summaries, dashboards,
and analytics workflows.

UPDATED: Registry synchronized with actual generator outputs from advanced.py
All feature names verified to match what generator functions actually produce.
"""

from typing import Dict, List, Optional
import pandas as pd


# Phase 9.3 Feature Categories Registry
# Maps category names to lists of feature column names generated by advanced.py functions
PHASE93_FEATURE_CATEGORIES: Dict[str, List[str]] = {
    "Momentum & Technical": [
        "52w_range_position",
        "breakout_signal",
        "ema_crossover_20_50",
        "ema_crossover_50_250",
        "ema_slope_20d",
        "ema_trend_consistency",
        "ma_20d_simple",
        "ma_50d_simple",
        "ma_crossover_signal",
        "near_52w_high_flag",
        "near_52w_low_flag",
        "pct_above_52w_low",
        "pct_off_52w_high",
        "price_acceleration_3m",
        "price_distance_from_ma",
        "price_momentum_1m",
        "price_momentum_1y",
        "price_momentum_3m",
        "price_momentum_6m",
        "price_vs_ema_20d",
        "price_vs_ema_250d",
        "return_stability_score",
        "rsi_14d",
        "rsi_30d",
        "sharpe_proxy",
        "total_return_1y_pct",
        "volume_momentum_score",
    ],
    "Valuation Ratios": [
        "dividend_yield",
        "ev_ebitda_forward_discount",
        "ev_ebitda_momentum",
        "ev_ebitda_ratio",
        "ev_ebitda_vs_3y_avg",
        "ev_sales_forward_discount",
        "ev_sales_quarterly_volatility",
        "ev_sales_ratio",
        "ev_sales_trend_1y",
        "ev_sales_trend_3y",
        "ev_sales_vs_3y_avg",
        "growth_implied_by_valuation",
        "p_b_ratio",
        "p_e_forward_discount",
        "p_e_momentum_qoq",
        "p_e_momentum_yoy",
        "p_e_ratio",
        "p_e_vs_3y_avg",
        "p_s_ratio",
        "peg_ratio",
        "valuation_extreme_flag",
        "valuation_stability_score",
        "valuation_trend_consistency",
    ],
    "Profitability": [
        "earnings_quality_score",
        "ebit_adjustment_ratio",
        "ebitda_adjustment_ratio",
        "ebitda_margin_trend",
        "gross_margin_pct",
        "gross_margin_trend",
        "net_margin_pct",
        "operating_leverage",
        "operating_margin_pct",
        "roa",
        "roe",
        "roic",
    ],
    "Quality & Risk": [
        "accounting_quality_score",
        "altman_z_trend",
        "distress_risk_score",
        "exceptional_items_to_ebitda",
        "exceptional_items_to_ni_pct",
        "exceptional_items_trend",
        "goodwill_change_rate",
        "goodwill_impairment_flag",
        "goodwill_to_assets",
        "goodwill_to_assets_pct",
        "has_asset_writedown",
        "has_goodwill_impairment",
        "has_restructuring",
        "intangible_intensity",
        "intangibles_to_assets_pct",
        "restructuring_intensity",
        "total_exceptional_items_ltm",
        "z_score_volatility",
    ],
    "Cash Flow": [
        "cfo_growth_yoy",
        "cfo_to_net_income",
        "fcf_margin",
        "fcf_stability",
        "fcf_to_net_income",
    ],
    "Capital Allocation": [
        "acquisition_intensity",
        "capex_growth_rate",
        "capex_intensity",
        "capex_to_depreciation",
        "capex_volatility",
        "currency_risk_flag",
        "days_since_ex_date",
        "dividend_aristocrat_flag",
        "dividend_consistency_score",
        "dividend_frequency_encoded",
        "dividend_growth_trend",
        "dividend_payout_ratio",
        "dividend_safety_score",
        "dividend_streak_years",
        "dividend_yield_vs_sector",
        "fcf_dividend_coverage",
        "income_stock_flag",
        "payout_ratio",
        "reinvestment_rate",
        "total_shareholder_return_yield",
        "working_capital_efficiency",
        "working_capital_trend",
    ],
    "Analyst Sentiment": [
        "analyst_bearish_pct",
        "analyst_bullish_pct",
        "analyst_conviction",
        "analyst_coverage_quality",
        "consensus_strength",
        "price_target_range",
        "price_target_revision",
        "price_target_spread_pct",
        "target_price_upside_pct",
        "upside_potential",
    ],
    "Market Sentiment": [
        "beta_stability",
        "momentum_20d",
        "price_range_pct",
        "short_interest_ratio",
        "systematic_risk_trend",
    ],
    "Leverage & Liquidity": [
        "cash_ratio",
        "current_ratio",
        "debt_to_assets",
        "debt_to_equity",
        "equity_ratio",
        "interest_coverage",
        "net_debt_to_ebitda",
        "quick_ratio",
        "working_capital_to_sales",
    ],
    "Temporal Patterns": [
        "days_since_reference",
        "days_to_earnings",
        "earnings_report_recency",
        "fiscal_quarter",
        "fq_vs_5yavg_ebitda",
        "ltm_vs_5yavg_revenue",
        "month",
        "quarterly_volatility_score",
        "reporting_lag",
        "year",
    ],
    "Composite Scores": [
        "altman_z_score",
        "beneish_m_score",
        "composite_quality_score",
        "momentum_score",
        "piotroski_f_score",
    ],
}


def get_feature_category(feature_name: str) -> Optional[str]:
    """
    Get the Phase 9.3 category for a given feature name.

    Args:
        feature_name: Name of the feature column

    Returns:
        Category name if found, None otherwise
    """
    for category, features in PHASE93_FEATURE_CATEGORIES.items():
        if feature_name in features:
            return category
    return None


def categorize_dataframe_columns(df: pd.DataFrame) -> Dict[str, List[str]]:
    """
    Categorize all DataFrame columns by Phase 9.3 feature family.

    Args:
        df: DataFrame with potential Phase 9.3 features

    Returns:
        Dictionary mapping category names to lists of present column names
    """
    categorized = {category: [] for category in PHASE93_FEATURE_CATEGORIES.keys()}

    for col in df.columns:
        category = get_feature_category(col)
        if category:
            categorized[category].append(col)

    # Remove empty categories
    categorized = {k: v for k, v in categorized.items() if v}

    return categorized


def get_phase93_coverage_stats(df: pd.DataFrame) -> Dict[str, int]:
    """
    Get count of Phase 9.3 features present in DataFrame by category.

    Args:
        df: DataFrame with potential Phase 9.3 features

    Returns:
        Dictionary mapping category names to feature counts
    """
    categorized = categorize_dataframe_columns(df)
    return {category: len(features) for category, features in categorized.items()}


def list_all_phase93_features() -> List[str]:
    """
    Get flat list of all Phase 9.3 feature names.

    Returns:
        List of all feature names across all categories
    """
    all_features = []
    for features in PHASE93_FEATURE_CATEGORIES.values():
        all_features.extend(features)
    return all_features


def get_category_description(category: str) -> str:
    """
    Get description of a Phase 9.3 category.

    Args:
        category: Category name

    Returns:
        Description string
    """
    descriptions = {
        "Momentum & Technical": "Price momentum, technical indicators, EMA signals, volume patterns",
        "Valuation Ratios": "EV/EBITDA, P/E, P/B, and other valuation multiples with time-series trends",
        "Profitability": "ROE, ROA, profit margins, and profitability trends",
        "Quality & Risk": "Accounting quality, earnings quality, distress indicators, Altman Z-Score",
        "Cash Flow": "Operating cash flow, FCF metrics, cash conversion, and quality indicators",
        "Capital Allocation": "Dividends, buybacks, reinvestment, M&A intensity, dividend reliability",
        "Analyst Sentiment": "Analyst ratings, consensus strength, target revisions",
        "Market Sentiment": "Market microstructure, liquidity, short interest, sentiment indicators",
        "Leverage & Liquidity": "Debt ratios, coverage ratios, liquidity metrics, financial flexibility",
        "Temporal Patterns": "Seasonality, trend consistency, cyclicality indicators",
        "Composite Scores": "Multi-factor composite scores combining quality, growth, value, momentum",
    }
    return descriptions.get(category, "")
