create table all_stocks_features
(
    "Ticker"                            text,
    "ISIN"                              text,
    "Name"                              text,
    "Region"                            text,
    "Country"                           text,
    "Sector"                            text,
    "Industry"                          text,
    "Trading Country"                   text,
    "Exchange"                          text,
    "Next Earnings"                     date,
    "Next Earnings (When)"              text,
    "Next Earnings (Status)"            text,
    "FY End Date"                       date,
    "Next FY End Date"                  date,
    "Income Statement Report Date"      date,
    "Next Income Statement Report Date" date,
    "Current Fiscal Quarter"            text,
    "Next Fiscal Quarter"               text,
    "Next Earnings (Report)"            text,
    "Reporting Interval"                integer,
    "Earnings Report (Frequency)"       text,
    "Price Target"                      numeric,
    "Price Target - Median"             numeric,
    "Price Target (YTD Ago)"            numeric,
    "Price Target - Low"                numeric,
    "Price Target - High"               numeric,
    "Market Cap (Country R)"            numeric,
    "Volume (Shrs)"                     numeric,
    "Dividend Per Share (LTM)"          numeric,
    "Last Price"                        numeric,
    "Market Cap"                        numeric,
    "Enterprise Value"                  numeric,
    p_e_ratio                           numeric,
    p_b_ratio                           numeric,
    ev_ebitda_ratio                     numeric,
    ev_sales_ratio                      numeric,
    dividend_yield                      numeric,
    peg_ratio                           numeric,
    ev_sales_trend_1y                   numeric,
    ev_ebitda_momentum                  numeric,
    p_e_momentum_yoy                    numeric,
    p_e_momentum_qoq                    numeric,
    ev_sales_vs_3y_avg                  numeric,
    ev_ebitda_vs_3y_avg                 numeric,
    p_e_vs_3y_avg                       numeric,
    ev_sales_forward_discount           numeric,
    ev_ebitda_forward_discount          numeric,
    p_e_forward_discount                numeric,
    p_b_vs_5y_avg                       numeric,
    ev_sales_qoq_1q                     numeric,
    p_e_vs_5y_avg                       numeric,
    valuation_compression               numeric,
    forward_pe_premium                  numeric,
    p_b_momentum_yoy                    numeric,
    price_momentum_1m                   numeric,
    price_momentum_3m                   numeric,
    price_momentum_6m                   numeric,
    price_momentum_1y                   numeric,
    price_momentum_5d                   numeric,
    ema_crossover_20_50                 integer,
    ema_crossover_50_250                integer,
    price_vs_ema_20d                    numeric,
    price_vs_ema_250d                   numeric,
    pct_off_52w_high                    numeric,
    pct_above_52w_low                   numeric,
    range_52w_position                  numeric,
    beta_momentum                       numeric,
    volatility_regime                   numeric,
    ema_slope_20d                       numeric,
    ema_trend_consistency               integer,
    price_vs_ema_100d                   numeric,
    near_52w_high_flag                  integer,
    near_52w_low_flag                   integer,
    volume_momentum_score               numeric,
    breakout_signal                     integer,
    high_volume_flag                    integer,
    low_volume_flag                     integer,
    volatility_compression              numeric,
    volatility_term_structure           numeric,
    roe                                 numeric,
    roa                                 numeric,
    gross_margin_pct                    numeric,
    operating_margin_pct                numeric,
    net_margin_pct                      numeric,
    ebitda_margin_pct                   numeric,
    roic                                numeric,
    rnd_intensity                       numeric,
    equity_multiplier                   numeric,
    gross_margin_trend_yoy              numeric,
    operating_margin_trend              numeric,
    net_margin_trend_yoy                numeric,
    ebitda_margin_trend                 numeric,
    margin_expansion_flag               integer,
    margin_stability_score              numeric,
    has_goodwill_impairment             integer,
    has_asset_writedown                 integer,
    has_restructuring                   integer,
    goodwill_to_assets_pct              numeric,
    intangible_intensity                numeric,
    exceptional_items_to_ebitda         numeric,
    altman_z_score                      numeric,
    altman_z_trend                      numeric,
    current_ratio                       numeric,
    quick_ratio                         numeric,
    distress_risk_score                 numeric,
    liquidity_stress_score              numeric,
    working_capital_trend               numeric,
    cash_runway_months                  numeric,
    wc_deteriorating_flag               integer,
    retained_earnings_growth            numeric,
    accumulated_deficit_flag            integer,
    adequate_cash_buffer                integer,
    goodwill_change_rate                numeric,
    restructuring_intensity             numeric,
    exceptional_items_frequency         integer,
    merger_impact_ratio                 numeric,
    non_operating_income_share          numeric,
    asset_sale_boost                    integer,
    accounting_quality_score            integer,
    debt_to_equity                      numeric,
    debt_to_assets                      numeric,
    equity_ratio                        numeric,
    interest_coverage                   numeric,
    cash_ratio                          numeric,
    working_capital_ratio               numeric,
    asset_turnover                      numeric,
    inventory_turnover                  numeric,
    receivables_days                    numeric,
    working_capital_turns               numeric,
    cash_to_assets_pct                  numeric,
    cash_change_qoq                     numeric,
    cash_vs_5y_avg                      numeric,
    inventory_change_yoy                numeric,
    inventory_vs_5y_avg                 numeric,
    receivables_change_yoy              numeric,
    working_capital_vs_5y_avg           numeric,
    retained_earnings_vs_5y             numeric,
    intangibles_growth_flag             integer,
    asset_quality_score                 numeric,
    balance_sheet_strength              integer,
    debt_maturity_risk                  numeric,
    analyst_bullish_pct                 numeric,
    analyst_bearish_pct                 numeric,
    upside_potential                    numeric,
    price_target_spread_pct             numeric,
    price_target_revision_1m            numeric,
    price_target_revision_3m            numeric,
    eps_revision_momentum               numeric,
    analyst_rating_normalized           numeric,
    analyst_coverage_quality            numeric,
    pt_momentum_1w                      numeric,
    pt_momentum_1m                      numeric,
    pt_momentum_3m                      numeric,
    pt_momentum_6m                      numeric,
    pt_momentum_1y                      numeric,
    pt_median_momentum_1m               numeric,
    pt_median_momentum_3m               numeric,
    pt_consensus_convergence            numeric,
    analyst_coverage_change_1m          integer,
    analyst_coverage_change_3m          integer,
    analyst_coverage_change_1y          integer,
    eps_surprise_pct                    numeric,
    revenue_surprise_pct                numeric,
    eps_adjustment_ratio                numeric,
    ebitda_adjustment_ratio             numeric,
    eps_quarterly_trend                 numeric,
    eps_yoy_growth                      numeric,
    eps_positive_streak                 integer,
    eps_cagr_3y                         numeric,
    eps_cagr_5y                         numeric,
    eps_trajectory_score                numeric,
    eps_adjustment_spread               numeric,
    eps_adjustment_pct                  numeric,
    net_income_adjustment_ratio         numeric,
    ebitda_adjustment_pct               numeric,
    earnings_quality_score              numeric,
    earnings_quality_warning            integer,
    gaap_revision_momentum              numeric,
    gaap_vs_norm_revision_spread        numeric,
    gaap_positive_revision_flag         integer,
    revenue_growth_yoy                  numeric,
    ebitda_growth_yoy                   numeric,
    operating_income_growth             numeric,
    fcf_growth                          numeric,
    revenue_cagr_5y                     numeric,
    forward_revenue_growth              numeric,
    revenue_vs_5y_avg                   numeric,
    revenue_est_spread                  numeric,
    revenue_beat_potential              numeric,
    forward_revenue_multiple            numeric,
    consensus_revenue_growth            numeric,
    forward_ebitda_margin               numeric,
    revenue_acceleration                numeric,
    estimate_confidence_score           numeric,
    dividend_streak                     integer,
    dividend_yield_ltm                  numeric,
    dividend_yield_ntm                  numeric,
    dividend_payout_ratio               numeric,
    fcf_dividend_coverage               numeric,
    buyback_yield                       numeric,
    total_shareholder_yield             numeric,
    dividend_growth_expectation         numeric,
    days_since_ex_date                  integer,
    days_to_payment                     integer,
    dividend_announced_flag             integer,
    ex_date_approaching_flag            integer,
    dividend_consistency                numeric,
    dividend_yield_vs_5y_avg            numeric,
    revenue_per_employee                numeric,
    profit_per_employee                 numeric,
    ebitda_per_employee                 numeric,
    fte_growth_1y_pct                   numeric,
    fte_growth_3y_pct                   numeric,
    workforce_stability                 numeric,
    layoff_risk_flag                    integer,
    rapid_hiring_flag                   integer,
    sustainable_growth_flag             integer,
    cfo_to_net_income                   numeric,
    fcf_to_net_income                   numeric,
    fcf_margin                          numeric,
    cfo_growth_yoy                      numeric,
    fcf_positive_ratio                  numeric,
    acquisition_intensity               numeric,
    self_funding_ratio                  numeric,
    fcf_positive_years                  integer,
    fcf_always_positive                 integer,
    capex_vs_5y_avg                     numeric,
    underinvestment_flag                integer,
    self_funding_flag                   integer,
    cash_flow_quality_score             numeric,
    cfo_quarterly_trend                 numeric,
    fcf_quarterly_trend                 numeric,
    cfo_positive_quarters               integer,
    cash_burn_rate                      numeric,
    financing_dependency                numeric,
    "Fiscal Quarter"                    integer,
    "Fiscal Month"                      integer,
    "Fiscal Year"                       integer,
    days_to_earnings                    integer,
    earnings_report_recency             integer,
    "Reporting Lag"                     numeric,
    fiscal_year_progress                numeric,
    days_since_last_report              integer,
    days_to_fy_end                      integer,
    is_quarter_end_month                integer,
    earnings_season_flag                integer,
    pre_earnings_window                 integer,
    post_earnings_window                integer,
    reporting_freshness_score           numeric,
    piotroski_f_score                   integer,
    dilution_score                      numeric,
    quality_momentum_score              numeric
);

alter table all_stocks_features
    owner to postgres;

