create table equities
(
    "Ticker"                                           text,
    "ISIN"                                             text,
    "Name"                                             text,
    "Description"                                      text,
    "Region"                                           text,
    "Country"                                          text,
    "Trading Country"                                  text,
    "Exchange"                                         text,
    "Unit"                                             text,
    "Sector"                                           text,
    "Industry"                                         text,
    "Style Class"                                      text,
    "Size Class"                                       text,
    "Next Earnings (When)"                             text,
    "Next Earnings (Status)"                           text,
    "Dividend Record (Currency)"                       text,
    "Dividend Record (Frequency)"                      text,
    "FY End"                                           text,
    "Last Updated"                                     date,
    "Income Statement Report Date"                     date,
    "Next Earnings"                                    date,
    "Dividend Record (Announce Date)"                  date,
    "Dividend Record (Payable Date)"                   date,
    "Dividend Record (Record Date)"                    date,
    "Dividend Record (Ex Date)"                        date,
    "FY End Date"                                      date,
    "Fiscal Month"                                     integer,
    "Next Fiscal Quarter"                              text,
    "Reference Date"                                   date default CURRENT_DATE,
    "Last Price"                                       numeric,
    "Price Target"                                     numeric,
    "Price Target (YTD Ago)"                           numeric,
    "Price Target - Low"                               numeric,
    "Price Target - Median"                            numeric,
    "Price Target - High"                              numeric,
    "Price (5D Ago)"                                   numeric,
    "Price (1W Ago)"                                   numeric,
    "Price (1M Ago)"                                   numeric,
    "Price (3M Ago)"                                   numeric,
    "Price (6M Ago)"                                   numeric,
    "Price (1Y Ago)"                                   numeric,
    "Price (3Y Ago)"                                   numeric,
    "Price (5Y Ago)"                                   numeric,
    "Price (QTD Ago)"                                  numeric,
    "52W High/Adj"                                     numeric,
    "52W Low/Adj"                                      numeric,
    "EMA (20D)"                                        numeric,
    "EMA (50D)"                                        numeric,
    "EMA (100D)"                                       numeric,
    "EMA (250D)"                                       numeric,
    "Market Cap"                                       numeric,
    "Enterprise Value"                                 numeric,
    "Market Cap (Country R)"                           numeric,
    "Volume (Shrs)"                                    numeric,
    "Rel. Volume"                                      numeric,
    "Shrs Out"                                         numeric,
    "Shrs Out (-1FY)"                                  numeric,
    "Dividend Record (Amount)"                         numeric,
    "Dividend Per Share (LTM)"                         numeric,
    "Common Dividends Paid (LTM)"                      numeric,
    "Common Dividends Paid (FY)"                       numeric,
    "Total Revenues (FQ)"                              numeric,
    "Total Revenues (-1FY)"                            numeric,
    "Total Revenues (FY)"                              numeric,
    "Total Revenues (LTM)"                             numeric,
    "Total Revenues (5YAVGFQ)"                         numeric,
    "Total Revenues (5YAVGLTM)"                        numeric,
    "Revenues - Est Avg (NTM)"                         numeric,
    "Revenues - Est Avg (FY1E)"                        numeric,
    "Revenues - Est Med (NTM)"                         numeric,
    "Revenues - Est Med (FY1E)"                        numeric,
    "EBITDA (FQ)"                                      numeric,
    "EBITDA (LTM)"                                     numeric,
    "EBITDA (FY)"                                      numeric,
    "EBITDA (-1FY)"                                    numeric,
    "EBITDA/Adj. (LTM)"                                numeric,
    "EBITDA/Adj. (FY)"                                 numeric,
    "EBITDA/Adj. (-1FY)"                               numeric,
    "EBITDA (5YAVGFQ)"                                 numeric,
    "EBITDA (5YAVGLTM)"                                numeric,
    "EBITDA - Est Avg (NTM)"                           numeric,
    "EBITDA - Est Avg (FY1E)"                          numeric,
    "EBIT (FQ)"                                        numeric,
    "EBIT (LTM)"                                       numeric,
    "EBIT (FY)"                                        numeric,
    "EBIT (-1FY)"                                      numeric,
    "EBIT/Adj. (-1FY)"                                 numeric,
    "EBIT/Adj. (FY)"                                   numeric,
    "EBIT/Adj. (LTM)"                                  numeric,
    "EBIT (5YAVGFQ)"                                   numeric,
    "EBIT (5YAVGLTM)"                                  numeric,
    "EBIT - Est Med (FY1E)"                            numeric,
    "EBIT - Est Med (NTM)"                             numeric,
    "Net Income - (IS) (FY)"                           numeric,
    "Net Income - (IS) (LTM)"                          numeric,
    "Net Income - (IS) (FQ)"                           numeric,
    "Net Income - (IS) (-1FY)"                         numeric,
    "Net Income - (IS) (5YAVGFQ)"                      numeric,
    "Net Income - (IS) (5YAVGLTM)"                     numeric,
    "Normalized Net Income (FY)"                       numeric,
    "Normalized Net Income (LTM)"                      numeric,
    "Normalized Net Income (FQ)"                       numeric,
    "Normalized Net Income (-1FY)"                     numeric,
    "Normalized Net Income (5YAVGFQ)"                  numeric,
    "Normalized Net Income (5YAVGLTM)"                 numeric,
    "Net Income/Adj. (FY)"                             numeric,
    "Net Income/Adj. (LTM)"                            numeric,
    "Net Income/Adj. (FQ)"                             numeric,
    "Net Income/Adj. (-1FY)"                           numeric,
    "Net Income/Adj. (5YAVGFQ)"                        numeric,
    "Operating Income (LTM)"                           numeric,
    "Operating Income (FY)"                            numeric,
    "Operating Income (FQ)"                            numeric,
    "Operating Income (5YAVGFQ)"                       numeric,
    "Total Operating Expenses (LTM)"                   numeric,
    "Gross Profit (LTM)"                               numeric,
    "Gross Profit (FY)"                                numeric,
    "Cost Of Revenues (LTM)"                           numeric,
    "R&D Expenses (LTM)"                               numeric,
    "Selling General & Admin Expenses/Total (FQ)"      numeric,
    "Selling General & Admin Expenses/Total (FY)"      numeric,
    "Selling General & Admin Expenses/Total (-1FY)"    numeric,
    "Selling General & Admin Expenses/Total (5YAVGFQ)" numeric,
    "Marketing Expenses (FQ)"                          numeric,
    "Marketing Expenses (FY)"                          numeric,
    "Marketing Expenses (-1FY)"                        numeric,
    "Marketing Expenses (5YAVGLTM)"                    numeric,
    "Restructuring Charges (LTM)"                      numeric,
    "Restructuring Charges (FQ)"                       numeric,
    "Restructuring Charges (-1FY)"                     numeric,
    "Restructuring Charges (FY)"                       numeric,
    "Restructuring Charges (5YAVGFQ)"                  numeric,
    "Merger & Restructuring Charges (LTM)"             numeric,
    "Merger & Restructuring Charges (FQ)"              numeric,
    "Merger & Restructuring Charges (FY)"              numeric,
    "Merger & Restructuring Charges (5YAVGFQ)"         numeric,
    "Asset Writedown (LTM)"                            numeric,
    "Asset Writedown (FY)"                             numeric,
    "Asset Writedown (FQ)"                             numeric,
    "Asset Writedown (-1FY)"                           numeric,
    "Asset Writedown (5YAVGFQ)"                        numeric,
    "Impairment of Goodwill (FQ)"                      numeric,
    "Impairment of Goodwill (LTM)"                     numeric,
    "Impairment of Goodwill (-1FY)"                    numeric,
    "Impairment of Goodwill (FY)"                      numeric,
    "Impairment of Goodwill (5YAVGFQ)"                 numeric,
    "Other Unusual Items/Total (LTM)"                  numeric,
    "Gain (Loss) On Sale Of Assets (LTM)"              numeric,
    "Interest Expense/Total (LTM)"                     numeric,
    "Interest Income On Investments (LTM)"             numeric,
    "Total Assets (LTM)"                               numeric,
    "Total Assets (FY)"                                numeric,
    "Total Equity (FY)"                                numeric,
    "Total Equity (LTM)"                               numeric,
    "Total Debt (FY)"                                  numeric,
    "Total Debt (LTM)"                                 numeric,
    "Total Current Assets (LTM)"                       numeric,
    "Total Current Liabilities (LTM)"                  numeric,
    "Working Capital (LTM)"                            numeric,
    "Working Capital (FQ)"                             numeric,
    "Working Capital (FY)"                             numeric,
    "Working Capital (5YAVGFY)"                        numeric,
    "TBV (FY)"                                         numeric,
    "TBV (LTM)"                                        numeric,
    "Cash And Equivalents (LTM)"                       numeric,
    "Cash And Equivalents (FQ)"                        numeric,
    "Cash And Equivalents (FY)"                        numeric,
    "Cash And Equivalents (5YAVGFQ)"                   numeric,
    "Retained Earnings (LTM)"                          numeric,
    "Retained Earnings (FQ)"                           numeric,
    "Retained Earnings (FY)"                           numeric,
    "Retained Earnings (5YAVGFQ)"                      numeric,
    "Inventory (LTM)"                                  numeric,
    "Inventory (FQ)"                                   numeric,
    "Inventory (FY)"                                   numeric,
    "Inventory (5YAVGFQ)"                              numeric,
    "Goodwill (FQ)"                                    numeric,
    "Goodwill (LTM)"                                   numeric,
    "Goodwill (FY)"                                    numeric,
    "Goodwill (-1FY)"                                  numeric,
    "Goodwill (5YAVGFQ)"                               numeric,
    "Gross Intangible Assets (LTM)"                    numeric,
    "Gross Intangible Assets (FY)"                     numeric,
    "Gross Intangible Assets (5YAVGFQ)"                numeric,
    "Accounts Receivable/Total (FY)"                   numeric,
    "Accounts Receivable/Total (-1FY)"                 numeric,
    "Accounts Receivable/Total (5YAVGFQ)"              numeric,
    "CFF (LTM)"                                        numeric,
    "CFF (FY)"                                         numeric,
    "CFF (FQ)"                                         numeric,
    "CFF (-1FY)"                                       numeric,
    "CFI (LTM)"                                        numeric,
    "CFI (FY)"                                         numeric,
    "CFI (FQ)"                                         numeric,
    "CFI (-1FY)"                                       numeric,
    "FCF (LTM)"                                        numeric,
    "FCF (FY)"                                         numeric,
    "FCF (FQ)"                                         numeric,
    "FCF (5YAVGFQ)"                                    numeric,
    "CFO (LTM)"                                        numeric,
    "CFO (FY)"                                         numeric,
    "CFO (FQ)"                                         numeric,
    "CFO (-1FY)"                                       numeric,
    "Capital Expenditure (LTM)"                        numeric,
    "Capital Expenditure (-1FY)"                       numeric,
    "Capital Expenditure (FY)"                         numeric,
    "Capital Expenditure (FQ)"                         numeric,
    "Capital Expenditure (5YAVGFQ)"                    numeric,
    "Cash Acquisitions (LTM)"                          numeric,
    "Cash Acquisitions (FY)"                           numeric,
    "Cash Acquisitions (FQ)"                           numeric,
    "Cash Acquisitions (-1FY)"                         numeric,
    "Cash Acquisitions (5YAVGFQ)"                      numeric,
    "P/E (NTM)"                                        numeric,
    "P/E (LTM)"                                        numeric,
    "P/E (EST FY1)"                                    numeric,
    "P/E (-1FYLTM)"                                    numeric,
    "P/E (-2FYLTM)"                                    numeric,
    "P/E (-3FYLTM)"                                    numeric,
    "P/E (3YAVGLTM)"                                   numeric,
    "P/E (-1FQLTM)"                                    numeric,
    "P/E (-2FQLTM)"                                    numeric,
    "P/E (-3FQLTM)"                                    numeric,
    "P/E (5YAVGLTM)"                                   numeric,
    "P/E (-0FQQoQLTM)"                                 numeric,
    "P/E (-0FYYoYLTM)"                                 numeric,
    "P/E (-1FYYoYLTM)"                                 numeric,
    "P/E (-0FQYoYLTM)"                                 numeric,
    "P/B (LTM)"                                        numeric,
    "P/B (-1FY)"                                       numeric,
    "P/B (5YAVG)"                                      numeric,
    "P/TBV (LTM)"                                      numeric,
    "EV/Sales (EST FY1)"                               numeric,
    "EV/Sales (LTM)"                                   numeric,
    "EV/Sales (NTM)"                                   numeric,
    "EV/Sales (-1FYLTM)"                               numeric,
    "EV/Sales (-2FYLTM)"                               numeric,
    "EV/Sales (-3FYLTM)"                               numeric,
    "EV/Sales (3YAVGLTM)"                              numeric,
    "EV/Sales (-1FQLTM)"                               numeric,
    "EV/Sales (-2FQLTM)"                               numeric,
    "EV/Sales (-3FQLTM)"                               numeric,
    "EV/Sales (-4FQLTM)"                               numeric,
    "EV/EBITDA (LTM)"                                  numeric,
    "EV/EBITDA (NTM)"                                  numeric,
    "EV/EBITDA (-1FYLTM)"                              numeric,
    "EV/EBITDA (-1FQLTM)"                              numeric,
    "EV/EBITDA (3YAVGLTM)"                             numeric,
    "EV/EBITDA (EST FY1)"                              numeric,
    "Return On Equity % (LTM)"                         numeric,
    "Return On Equity % (FY)"                          numeric,
    "Return on Assets (ROA) % (LTM)"                   numeric,
    "Return on Assets (ROA) % (FY)"                    numeric,
    "Current Ratio (FY)"                               numeric,
    "Current Ratio (LTM)"                              numeric,
    "Asset Turnover (FY)"                              numeric,
    "Asset Turnover (LTM)"                             numeric,
    "Altman Z-Score (FY)"                              numeric,
    "Altman Z-Score (FQ)"                              numeric,
    "Altman Z-Score (LTM)"                             numeric,
    "EPS/Adj. (-1FY)"                                  numeric,
    "EPS/Adj. (FY)"                                    numeric,
    "EPS/Adj. (LTM)"                                   numeric,
    "EPS Norm - Est Avg (FY1E)"                        numeric,
    "EPS Norm - Est Avg (NTM)"                         numeric,
    "Net EPS - Basic (LTM)"                            numeric,
    "Net EPS - Basic (FQ)"                             numeric,
    "Net EPS - Basic (FY)"                             numeric,
    "Net EPS - Basic (-1FQFQ)"                         numeric,
    "Net EPS - Basic (-2FQFQ)"                         numeric,
    "Net EPS - Basic (-3FQFQ)"                         numeric,
    "Net EPS - Basic (-4FQFQ)"                         numeric,
    "Net EPS - Basic (-1FY)"                           numeric,
    "Net EPS - Basic (-2FY)"                           numeric,
    "Net EPS - Basic (-3FY)"                           numeric,
    "Net EPS - Basic (-4FY)"                           numeric,
    "Net EPS - Basic (-5FY)"                           numeric,
    "EPS GAAP - Est Avg (NTM)"                         numeric,
    "EPS GAAP - Est Avg (FY1E)"                        numeric,
    "Total Return (YTD)"                               numeric,
    "Total Return (5Y)"                                numeric,
    "Total Return (10Y)"                               numeric,
    "Tot. Return %/CAGR (3Y)"                          numeric,
    "Tot. Return %/CAGR (10Y)"                         numeric,
    "Price Chg. % (1M)"                                numeric,
    "Price Chg. % (3M)"                                numeric,
    "1-Day %"                                          numeric,
    "Total Revenues/CAGR (5Y FY)"                      numeric,
    "Revenues - Est YoY % (FY1E)"                      numeric,
    "Net Income Margin % (FY)"                         numeric,
    "Net Income Margin % (LTM)"                        numeric,
    "Gross Profit Margin % (FY)"                       numeric,
    "Gross Profit Margin % (LTM)"                      numeric,
    "Volatility (1M)"                                  numeric,
    "Volatility (3M)"                                  numeric,
    "Volatility (6M)"                                  numeric,
    "Volatility (1Y)"                                  numeric,
    "Beta (1Y)"                                        numeric,
    "Beta (2Y)"                                        numeric,
    "Beta (5Y)"                                        numeric,
    "Div Yield (Ind)"                                  numeric,
    "Div Yield (LTM)"                                  numeric,
    "Div Yield (TTM)"                                  numeric,
    "Div Yield (NTM)"                                  numeric,
    "Div Yield (-1FYInd)"                              numeric,
    "Div Yield (-2FYInd)"                              numeric,
    "Div Yield (-3FYInd)"                              numeric,
    "Div Yield (-4FYInd)"                              numeric,
    "Div Yield (-5FYInd)"                              numeric,
    "Div Yield (5YAVGLTM)"                             numeric,
    "Buyback Yield (LTM)"                              numeric,
    "EPS Est Avg Rev % (FY1E - 1W)"                    numeric,
    "EPS Est Avg Rev % (FY1E - 1M)"                    numeric,
    "EPS Est Avg Rev % (FY1E - 3M)"                    numeric,
    "EPS Est Avg Rev % (FY1E - 6M)"                    numeric,
    "EPS Est Avg Rev % (FY1E - 1Y)"                    numeric,
    "EPS GAAP Est Avg Rev % (FY1E - 1M)"               numeric,
    "EPS GAAP Est Avg Rev % (FY1E - 3M)"               numeric,
    "EPS GAAP Est Avg Rev % (FY1E - 6M)"               numeric,
    "EPS GAAP Est Avg Rev % (FY1E - 1Y)"               numeric,
    "Price Target - #"                                 numeric,
    "Analyst Rating"                                   numeric,
    "# Strong Sell Ratings"                            numeric,
    "# Strong Buys Ratings"                            numeric,
    "# Hold Ratings"                                   numeric,
    "# Buys Ratings"                                   numeric,
    "# Sell Ratings"                                   numeric,
    "EPS Norm - Est # (FY1E)"                          numeric,
    "Dividend Streak"                                  numeric,
    "Full Time Employees (FQ)"                         numeric,
    "Full Time Employees (FY)"                         numeric,
    "Full Time Employees (-1FY)"                       numeric,
    "Full Time Employees (-2FY)"                       numeric,
    "Full Time Employees (-3FY)"                       numeric,
    "Avg Employees (5YAVGFY)"                          numeric
);

comment on table equities is 'Equities screening data with financial metrics and company information (semantic roles aligned with preprocessing pipeline)';

alter table equities
    owner to postgres;

