create materialized view mv_feature_registry_enhanced as
SELECT e."Ticker"                                        AS ticker,
       e."ISIN"                                          AS isin,
       e."Name"                                          AS name,
       e."Region"                                        AS region,
       e."Country"                                       AS country,
       e."Trading Country"                               AS trading_country,
       e."Exchange"                                      AS exchange,
       e."Unit"                                          AS unit,
       e."Sector"                                        AS sector,
       e."Industry"                                      AS industry,
       e."Style Class"                                   AS style_class,
       e."Size Class"                                    AS size_class,
       e."FY End"                                        AS fy_end,
       e."Next Earnings (When)"                          AS next_earnings_when,
       e."Next Earnings (Status)"                        AS next_earnings_status,
       e."Current Fiscal Quarter"                        AS current_fiscal_quarter,
       e."Next Fiscal Quarter"                           AS next_fiscal_quarter,
       e."Next Earnings (Report)"                        AS next_earnings_report,
       e."Reporting Interval"                            AS reporting_interval,
       e."Earnings Report (Frequency)"                   AS earnings_report_frequency,
       e."Income Statement Report Date"                  AS income_statement_report_date,
       e."Next Earnings"                                 AS next_earnings,
       e."FY End Date"                                   AS fy_end_date,
       e."Next FY End Date"                              AS next_fy_end_date,
       e."Next Income Statement Report Date"             AS next_income_statement_date,
       e."Price Target"                                  AS price_target,
       e."Price Target - Median"                         AS price_target_median,
       e."Market Cap"                                    AS market_cap,
       e."Enterprise Value"                              AS enterprise_value,
       e."Last Price"                                    AS last_price,
       e."Price Target (YTD Ago)"                        AS price_target_ytd_ago,
       e."Price Target - Low"                            AS price_target_low,
       e."Price Target - High"                           AS price_target_high,
       e."Dividend Record (Currency)"                    AS dividend_record_currency,
       e."Dividend Record (Frequency)"                   AS dividend_record_frequency,
       e."Dividend Record (Amount)"                      AS dividend_record_amount,
       e."Dividend Record (Announce Date)"               AS dividend_announce_date,
       e."Dividend Record (Payable Date)"                AS dividend_payable_date,
       e."Dividend Record (Record Date)"                 AS dividend_record_date,
       e."Dividend Record (Ex Date)"                     AS dividend_ex_date,
       e."Dividend Per Share (LTM)"                      AS dividend_per_share_ltm,
       e."Dividend Streak"                               AS dividend_streak,
       e."Analyst Rating"                                AS analyst_rating,
       e."# Strong Sell Ratings"                         AS strong_sell_ratings,
       e."# Strong Buys Ratings"                         AS strong_buy_ratings,
       e."# Hold Ratings"                                AS hold_ratings,
       e."# Buys Ratings"                                AS buy_ratings,
       e."# Sell Ratings"                                AS sell_ratings,
       e."Price Target - #"                              AS price_target_count,
       e."Shrs Out"                                      AS shares_outstanding,
       e."Shrs Out (-1FY)"                               AS shares_outstanding_1fy,
       e."Volume (Shrs)"                                 AS volume_shares,
       e."Rel. Volume"                                   AS relative_volume,
       e."Price (5D Ago)"                                AS price_5d_ago,
       e."Price (1W Ago)"                                AS price_1w_ago,
       e."Price (1M Ago)"                                AS price_1m_ago,
       e."Price (3M Ago)"                                AS price_3m_ago,
       e."Price (6M Ago)"                                AS price_6m_ago,
       e."Price (1Y Ago)"                                AS price_1y_ago,
       e."Price (3Y Ago)"                                AS price_3y_ago,
       e."Price (5Y Ago)"                                AS price_5y_ago,
       e."Price (QTD Ago)"                               AS price_qtd_ago,
       e."52W High/Adj"                                  AS high_52w,
       e."52W Low/Adj"                                   AS low_52w,
       e."EMA (20D)"                                     AS ema_20d,
       e."EMA (50D)"                                     AS ema_50d,
       e."EMA (100D)"                                    AS ema_100d,
       e."EMA (250D)"                                    AS ema_250d,
       e."Volatility (1M)"                               AS volatility_1m,
       e."Volatility (3M)"                               AS volatility_3m,
       e."Volatility (6M)"                               AS volatility_6m,
       e."Volatility (1Y)"                               AS volatility_1y,
       e."Beta (1Y)"                                     AS beta_1y,
       e."Beta (2Y)"                                     AS beta_2y_base,
       e."Beta (5Y)"                                     AS beta_5y,
       e."Total Return (YTD)"                            AS total_return_ytd,
       e."Total Return (5Y)"                             AS total_return_5y,
       e."Total Return (10Y)"                            AS total_return_10y,
       e."Tot. Return %/CAGR (3Y)"                       AS return_cagr_3y,
       e."Tot. Return %/CAGR (10Y)"                      AS return_cagr_10y,
       e."1-Day %"                                       AS return_1d,
       e."Price Chg. % (1M)"                             AS price_change_1m,
       e."Price Chg. % (3M)"                             AS price_change_3m,
       e."Total Revenues (FQ)"                           AS revenue_fq,
       e."Total Revenues (FY)"                           AS revenue_fy,
       e."Total Revenues (LTM)"                          AS revenue_ltm,
       e."Total Revenues (-1FY)"                         AS revenue_1fy,
       e."Total Revenues (5YAVGFQ)"                      AS revenue_5yavg_fq,
       e."Total Revenues (5YAVGLTM)"                     AS revenue_5yavg_ltm,
       e."Total Revenues/CAGR (5Y FY)"                   AS revenue_cagr_5y,
       e."EBITDA (FQ)"                                   AS ebitda_fq,
       e."EBITDA (LTM)"                                  AS ebitda_ltm,
       e."EBITDA (FY)"                                   AS ebitda_fy,
       e."EBITDA (-1FY)"                                 AS ebitda_1fy,
       e."EBITDA (5YAVGFQ)"                              AS ebitda_5yavg_fq,
       e."EBITDA (5YAVGLTM)"                             AS ebitda_5yavg_ltm,
       e."EBITDA/Adj. (LTM)"                             AS ebitda_adj_ltm,
       e."EBITDA/Adj. (FY)"                              AS ebitda_adj_fy,
       e."EBIT (FQ)"                                     AS ebit_fq,
       e."EBIT (LTM)"                                    AS ebit_ltm,
       e."EBIT (FY)"                                     AS ebit_fy,
       e."EBIT (-1FY)"                                   AS ebit_1fy,
       e."EBIT (5YAVGFQ)"                                AS ebit_5yavg_fq,
       e."EBIT (5YAVGLTM)"                               AS ebit_5yavg_ltm,
       e."EBIT/Adj. (LTM)"                               AS ebit_adj_ltm,
       e."EBIT/Adj. (FY)"                                AS ebit_adj_fy,
       e."Net Income - (IS) (FQ)"                        AS net_income_fq,
       e."Net Income - (IS) (FY)"                        AS net_income_fy,
       e."Net Income - (IS) (LTM)"                       AS net_income_ltm,
       e."Net Income - (IS) (-1FY)"                      AS net_income_1fy,
       e."Normalized Net Income (FQ)"                    AS normalized_ni_fq,
       e."Normalized Net Income (FY)"                    AS normalized_ni_fy,
       e."Normalized Net Income (LTM)"                   AS normalized_ni_ltm,
       e."Net Income/Adj. (FQ)"                          AS net_income_adj_fq,
       e."Net Income/Adj. (FY)"                          AS net_income_adj_fy,
       e."Net Income/Adj. (LTM)"                         AS net_income_adj_ltm,
       e."Gross Profit (FQ)"                             AS gross_profit_fq,
       e."Gross Profit (FY)"                             AS gross_profit_fy,
       e."Gross Profit (LTM)"                            AS gross_profit_ltm,
       e."Operating Income (FQ)"                         AS operating_income_fq,
       e."Operating Income (FY)"                         AS operating_income_fy,
       e."Operating Income (LTM)"                        AS operating_income_ltm,
       e."Operating Income (5YAVGFQ)"                    AS operating_income_5yavg_fq,
       e."Total Operating Expenses (LTM)"                AS total_opex_ltm,
       e."Cost Of Revenues (LTM)"                        AS cost_of_revenues_ltm,
       e."R&D Expenses (LTM)"                            AS rd_expenses_ltm,
       e."Selling General & Admin Expenses/Total (FQ)"   AS sga_fq,
       e."Selling General & Admin Expenses/Total (FY)"   AS sga_fy,
       e."Selling General & Admin Expenses/Total (-1FY)" AS sga_1fy,
       e."Marketing Expenses (FQ)"                       AS marketing_fq,
       e."Marketing Expenses (FY)"                       AS marketing_fy,
       e."Interest Expense/Total (LTM)"                  AS interest_expense_ltm,
       e."Interest Income On Investments (LTM)"          AS interest_income_ltm,
       e."Total Assets (FQ)"                             AS total_assets_fq,
       e."Total Assets (FY)"                             AS total_assets_fy,
       e."Total Assets (LTM)"                            AS total_assets_ltm,
       e."Total Debt (FQ)"                               AS total_debt_fq,
       e."Total Debt (FY)"                               AS total_debt_fy,
       e."Total Debt (LTM)"                              AS total_debt_ltm,
       e."Total Equity (FY)"                             AS total_equity_fy,
       e."Total Equity (LTM)"                            AS total_equity_ltm,
       e."TBV (FY)"                                      AS tbv_fy,
       e."TBV (LTM)"                                     AS tbv_ltm,
       e."Cash And Equivalents (FQ)"                     AS cash_fq,
       e."Cash And Equivalents (FY)"                     AS cash_fy,
       e."Cash And Equivalents (LTM)"                    AS cash_ltm,
       e."Inventory (FQ)"                                AS inventory_fq,
       e."Inventory (FY)"                                AS inventory_fy,
       e."Inventory (LTM)"                               AS inventory_ltm,
       e."Goodwill (FQ)"                                 AS goodwill_fq,
       e."Goodwill (FY)"                                 AS goodwill_fy,
       e."Goodwill (LTM)"                                AS goodwill_ltm,
       e."Gross Intangible Assets (LTM)"                 AS intangible_assets_ltm,
       e."Retained Earnings (FQ)"                        AS retained_earnings_fq,
       e."Retained Earnings (FY)"                        AS retained_earnings_fy,
       e."Retained Earnings (LTM)"                       AS retained_earnings_ltm,
       e."Total Current Assets (LTM)"                    AS current_assets_ltm,
       e."Total Current Liabilities (LTM)"               AS current_liabilities_ltm,
       e."Working Capital (FQ)"                          AS working_capital_fq,
       e."Working Capital (FY)"                          AS working_capital_fy,
       e."Working Capital (LTM)"                         AS working_capital_ltm,
       e."CFO (FQ)"                                      AS cfo_fq,
       e."CFO (FY)"                                      AS cfo_fy,
       e."CFO (LTM)"                                     AS cfo_ltm,
       e."CFO (-1FY)"                                    AS cfo_1fy,
       e."CFI (FQ)"                                      AS cfi_fq,
       e."CFI (FY)"                                      AS cfi_fy,
       e."CFI (LTM)"                                     AS cfi_ltm,
       e."CFF (FQ)"                                      AS cff_fq,
       e."CFF (FY)"                                      AS cff_fy,
       e."CFF (LTM)"                                     AS cff_ltm,
       e."FCF (FQ)"                                      AS fcf_fq,
       e."FCF (FY)"                                      AS fcf_fy,
       e."FCF (LTM)"                                     AS fcf_ltm,
       e."FCF (-1FY)"                                    AS fcf_1fy,
       e."Capital Expenditure (FQ)"                      AS capex_fq,
       e."Capital Expenditure (FY)"                      AS capex_fy,
       e."Capital Expenditure (LTM)"                     AS capex_ltm,
       e."P/E (LTM)"                                     AS pe_ltm,
       e."P/E (NTM)"                                     AS pe_ntm,
       e."Forward P/E"                                   AS forward_pe,
       e."PEG Ratio"                                     AS peg_ratio,
       e."P/B (LTM)"                                     AS pb_ltm,
       e."P/B (-1FY)"                                    AS pb_1fy,
       e."P/B (5YAVG)"                                   AS pb_5yavg,
       e."P/TBV (LTM)"                                   AS ptbv_ltm,
       e."P/FCF"                                         AS p_fcf,
       e."EV/FCF"                                        AS ev_fcf,
       e."EV/Sales (LTM)"                                AS ev_sales_ltm,
       e."EV/Sales (NTM)"                                AS ev_sales_ntm,
       e."EV/EBITDA (LTM)"                               AS ev_ebitda_ltm,
       e."EV/EBITDA (NTM)"                               AS ev_ebitda_ntm,
       e."FCF Per Share"                                 AS fcf_per_share,
       e."Revenue Per Share"                             AS revenue_per_share,
       e."Return On Equity % (LTM)"                      AS roe_ltm,
       e."Return On Equity % (FY)"                       AS roe_fy,
       e."Return on Assets (ROA) % (LTM)"                AS roa_ltm,
       e."Return on Assets (ROA) % (FY)"                 AS roa_fy,
       e."Asset Turnover (LTM)"                          AS asset_turnover_ltm,
       e."Asset Turnover (FY)"                           AS asset_turnover_fy,
       e."Current Ratio (LTM)"                           AS current_ratio_ltm,
       e."Current Ratio (FY)"                            AS current_ratio_fy,
       e."Altman Z-Score (FQ)"                           AS altman_z_fq,
       e."Altman Z-Score (FY)"                           AS altman_z_fy,
       e."Altman Z-Score (LTM)"                          AS altman_z_ltm,
       e."Gross Profit Margin % (LTM)"                   AS gross_margin_ltm,
       e."Gross Profit Margin % (FY)"                    AS gross_margin_fy,
       e."Net Income Margin % (LTM)"                     AS net_margin_ltm,
       e."Net Income Margin % (FY)"                      AS net_margin_fy,
       e."FCF Margin"                                    AS fcf_margin,
       e."Div Yield (LTM)"                               AS div_yield_ltm,
       e."Div Yield (TTM)"                               AS div_yield_ttm,
       e."Div Yield (NTM)"                               AS div_yield_ntm,
       e."Div Yield (Ind)"                               AS div_yield_ind,
       e."Div Yield (5YAVGLTM)"                          AS div_yield_5yavg,
       e."Payout Ratio (TTM)"                            AS payout_ratio,
       e."Buyback Yield (LTM)"                           AS buyback_yield_ltm,
       e."DPS Growth"                                    AS dps_growth,
       e."Net EPS - Basic (LTM)"                         AS eps_basic_ltm,
       e."Net EPS - Basic (FQ)"                          AS eps_basic_fq,
       e."Net EPS - Basic (FY)"                          AS eps_basic_fy,
       e."EPS/Adj. (LTM)"                                AS eps_adj_ltm,
       e."EPS/Adj. (FY)"                                 AS eps_adj_fy,
       e."EPS/Adj. (-1FY)"                               AS eps_adj_1fy,
       e."EPS Norm - Est Avg (NTM)"                      AS eps_est_ntm,
       e."EPS Norm - Est Avg (FY1E)"                     AS eps_est_fy1e,
       e."EPS GAAP - Est Avg (NTM)"                      AS eps_gaap_est_ntm,
       e."EPS GAAP - Est Avg (FY1E)"                     AS eps_gaap_est_fy1e,
       e."EPS Growth (TTM)"                              AS eps_growth_ttm,
       e."EPS Growth (3Y)"                               AS eps_growth_3y,
       e."EPS Growth (5Y)"                               AS eps_growth_5y,
       e."Revenues - Est Avg (NTM)"                      AS revenue_est_ntm,
       e."Revenues - Est Avg (FY1E)"                     AS revenue_est_fy1e,
       e."Revenues - Est Med (NTM)"                      AS revenue_est_med_ntm,
       e."Revenues - Est Med (FY1E)"                     AS revenue_est_med_fy1e,
       e."Revenues - Est YoY % (FY1E)"                   AS revenue_est_yoy,
       e."Revenue Growth (3Y)"                           AS revenue_growth_3y,
       e."Revenue Growth (5Y)"                           AS revenue_growth_5y,
       e."EBITDA - Est Avg (NTM)"                        AS ebitda_est_ntm,
       e."EBITDA - Est Avg (FY1E)"                       AS ebitda_est_fy1e,
       e."EBIT - Est Med (NTM)"                          AS ebit_est_ntm,
       e."EBIT - Est Med (FY1E)"                         AS ebit_est_fy1e,
       e."EPS Est Avg Rev % (FY1E - 1W)"                 AS eps_rev_1w,
       e."EPS Est Avg Rev % (FY1E - 1M)"                 AS eps_rev_1m,
       e."EPS Est Avg Rev % (FY1E - 3M)"                 AS eps_rev_3m,
       e."EPS Est Avg Rev % (FY1E - 6M)"                 AS eps_rev_6m,
       e."EPS Est Avg Rev % (FY1E - 1Y)"                 AS eps_rev_1y,
       e."EPS GAAP Est Avg Rev % (FY1E - 1M)"            AS eps_gaap_rev_1m,
       e."EPS GAAP Est Avg Rev % (FY1E - 3M)"            AS eps_gaap_rev_3m,
       e."Full Time Employees (FQ)"                      AS employees_fq,
       e."Full Time Employees (FY)"                      AS employees_fy,
       e."Full Time Employees (-1FY)"                    AS employees_1fy,
       e."Full Time Employees (-2FY)"                    AS employees_2fy,
       e."Avg Employees (5YAVGFY)"                       AS employees_5yavg,
       e."Impairment of Goodwill (LTM)"                  AS impairment_ltm,
       e."Impairment of Goodwill (FY)"                   AS impairment_fy,
       e."Asset Writedown (LTM)"                         AS writedown_ltm,
       e."Asset Writedown (FY)"                          AS writedown_fy,
       e."Restructuring Charges (LTM)"                   AS restructuring_ltm,
       e."Restructuring Charges (FY)"                    AS restructuring_fy,
       e."Merger & Restructuring Charges (LTM)"          AS merger_charges_ltm,
       e."Gain (Loss) On Sale Of Assets (LTM)"           AS asset_sale_gain_ltm,
       e."Other Unusual Items/Total (LTM)"               AS other_unusual_ltm,
       e."Price Target (1W Ago)"                         AS pt_1w_ago,
       e."Price Target (1M Ago)"                         AS pt_1m_ago,
       e."Price Target (3M Ago)"                         AS pt_3m_ago,
       e."Price Target (6M Ago)"                         AS pt_6m_ago,
       e."Price Target (1Y Ago)"                         AS pt_1y_ago,
       e."Fiscal Month"                                  AS fiscal_month,
       e."Fiscal Quarter"                                AS fiscal_quarter,
       e."Fiscal Year"                                   AS fiscal_year,
       e."Reporting Lag"                                 AS reporting_lag,
       aef.revenue_fq_vs_5yavg,
       aef.revenue_qoq_growth,
       aef.revenue_seasonality_factor,
       aef.sga_to_revenue_fy,
       aef.sga_trend_yoy,
       aef.marketing_to_revenue_fy,
       aef.operating_leverage_score,
       aef.cost_efficiency_trend,
       aef.price_to_tbv,
       aef.tbv_per_share,
       aef.tangible_equity_ratio,
       aef.tbv_margin_of_safety,
       aef.net_interest_income,
       aef.interest_coverage_ebitda,
       aef.financial_income_quality,
       aef.interest_burden_ratio,
       aef.price_momentum_3y,
       aef.price_momentum_5y,
       aef.momentum_acceleration_3y,
       aef.long_term_trend_score,
       aef.momentum_consistency,
       aef.secular_trend_flag,
       aef.beta_2y,
       aef.beta_trend_short,
       aef.beta_trend_long,
       aef.beta_stability,
       aef.beta_regime_change,
       aef.systematic_risk_score,
       aef.defensive_stock_flag,
       aef.high_beta_flag,
       aef.estimate_skew_fy1e,
       aef.revenue_consensus_confidence,
       aef.upside_to_consensus,
       aef.total_unusual_items,
       aef.unusual_to_net_income_ratio,
       aef.clean_earnings_flag,
       aef.recurring_unusual_flag,
       aef.earnings_noise_score,
       aef.quality_adjusted_ni,
       aef.pe_forward_discount,
       aef.peg_adjusted,
       aef.peg_forward,
       aef.earnings_yield,
       aef.fcf_yield,
       aef.shareholder_yield_total,
       aef.valuation_composite_score,
       aef.defensive_interval,
       aef.working_capital_turnover,
       aef.liquidity_score,
       aef.working_capital_efficiency
FROM equities e
         LEFT JOIN calc_all_enhanced_features() aef(ticker, name, sector, industry, revenue_fq_vs_5yavg,
                                                    revenue_qoq_growth, revenue_seasonality_factor, sga_to_revenue_fy,
                                                    sga_trend_yoy, marketing_to_revenue_fy, operating_leverage_score,
                                                    cost_efficiency_trend, price_to_tbv, tbv_per_share,
                                                    tangible_equity_ratio, tbv_margin_of_safety, net_interest_income,
                                                    interest_coverage_ebitda, financial_income_quality,
                                                    interest_burden_ratio, price_momentum_3y, price_momentum_5y,
                                                    momentum_acceleration_3y, long_term_trend_score,
                                                    momentum_consistency, secular_trend_flag, beta_2y, beta_trend_short,
                                                    beta_trend_long, beta_stability, beta_regime_change,
                                                    systematic_risk_score, defensive_stock_flag, high_beta_flag,
                                                    estimate_skew_fy1e, revenue_consensus_confidence,
                                                    upside_to_consensus, total_unusual_items,
                                                    unusual_to_net_income_ratio, clean_earnings_flag,
                                                    recurring_unusual_flag, earnings_noise_score, quality_adjusted_ni,
                                                    pe_forward_discount, peg_adjusted, peg_forward, earnings_yield,
                                                    fcf_yield, shareholder_yield_total, valuation_composite_score,
                                                    defensive_interval, working_capital_turnover, liquidity_score,
                                                    working_capital_efficiency) ON e."Ticker" = aef.ticker;

comment on materialized view mv_feature_registry_enhanced is 'Comprehensive feature registry with 200+ features from equities table and calc_all_enhanced_features function';

alter materialized view mv_feature_registry_enhanced owner to postgres;

create index idx_mv_registry_ticker
    on mv_feature_registry_enhanced (ticker);

create index idx_mv_registry_isin
    on mv_feature_registry_enhanced (isin);

create index idx_mv_registry_sector
    on mv_feature_registry_enhanced (sector);

create index idx_mv_registry_industry
    on mv_feature_registry_enhanced (industry);

create index idx_mv_registry_country
    on mv_feature_registry_enhanced (country);

create index idx_mv_registry_region
    on mv_feature_registry_enhanced (region);

create index idx_mv_registry_size
    on mv_feature_registry_enhanced (size_class);

create index idx_mv_registry_style
    on mv_feature_registry_enhanced (style_class);

create index idx_mv_registry_market_cap
    on mv_feature_registry_enhanced (market_cap desc);

create index idx_mv_registry_valuation
    on mv_feature_registry_enhanced (valuation_composite_score);

create index idx_mv_registry_liquidity
    on mv_feature_registry_enhanced (liquidity_score desc);

create index idx_mv_registry_defensive
    on mv_feature_registry_enhanced (defensive_stock_flag)
    where (defensive_stock_flag = 1);

create index idx_mv_registry_secular
    on mv_feature_registry_enhanced (secular_trend_flag)
    where (secular_trend_flag = 1);

create index idx_mv_registry_clean
    on mv_feature_registry_enhanced (clean_earnings_flag)
    where (clean_earnings_flag = 1);

