create view mw_feature_registry_enhanced
            (ticker, isin, name, region, country, trading_country, exchange, unit, sector, industry, style_class,
             size_class, fy_end, next_earnings_when, next_earnings_status, current_fiscal_quarter, next_fiscal_quarter,
             next_earnings_report, reporting_interval, earnings_report_frequency, income_statement_report_date,
             next_earnings, fy_end_date, next_fy_end_date, next_income_statement_date, price_target,
             price_target_median, market_cap, enterprise_value, last_price, price_target_ytd_ago, price_target_low,
             price_target_high, dividend_record_currency, dividend_record_frequency, dividend_record_amount,
             dividend_announce_date, dividend_payable_date, dividend_record_date, dividend_ex_date,
             dividend_per_share_ltm, dividend_streak, analyst_rating, strong_sell_ratings, strong_buy_ratings,
             hold_ratings, buy_ratings, sell_ratings, price_target_count, shares_outstanding, shares_outstanding_1fy,
             volume_shares, relative_volume, price_5d_ago, price_1w_ago, price_1m_ago, price_3m_ago, price_6m_ago,
             price_1y_ago, price_3y_ago, price_5y_ago, price_qtd_ago, high_52w, low_52w, ema_20d, ema_50d, ema_100d,
             ema_250d, volatility_1m, volatility_3m, volatility_6m, volatility_1y, beta_1y, beta_2y_base, beta_5y,
             total_return_ytd, total_return_5y, total_return_10y, return_cagr_3y, return_cagr_10y, return_1d,
             price_change_1m, price_change_3m, revenue_fq, revenue_fy, revenue_ltm, revenue_1fy, revenue_5yavg_fq,
             revenue_5yavg_ltm, revenue_cagr_5y, ebitda_fq, ebitda_ltm, ebitda_fy, ebitda_1fy, ebitda_5yavg_fq,
             ebitda_5yavg_ltm, ebitda_adj_ltm, ebitda_adj_fy, ebit_fq, ebit_ltm, ebit_fy, ebit_1fy, ebit_5yavg_fq,
             ebit_5yavg_ltm, ebit_adj_ltm, ebit_adj_fy, net_income_fq, net_income_fy, net_income_ltm, net_income_1fy,
             normalized_ni_fq, normalized_ni_fy, normalized_ni_ltm, net_income_adj_fq, net_income_adj_fy,
             net_income_adj_ltm, gross_profit_fq, gross_profit_fy, gross_profit_ltm, operating_income_fq,
             operating_income_fy, operating_income_ltm, operating_income_5yavg_fq, total_opex_ltm, cost_of_revenues_ltm,
             rd_expenses_ltm, sga_fq, sga_fy, sga_1fy, marketing_fq, marketing_fy, interest_expense_ltm,
             interest_income_ltm, total_assets_fq, total_assets_fy, total_assets_ltm, total_debt_fq, total_debt_fy,
             total_debt_ltm, total_equity_fy, total_equity_ltm, tbv_fy, tbv_ltm, cash_fq, cash_fy, cash_ltm,
             inventory_fq, inventory_fy, inventory_ltm, goodwill_fq, goodwill_fy, goodwill_ltm, intangible_assets_ltm,
             retained_earnings_fq, retained_earnings_fy, retained_earnings_ltm, current_assets_ltm,
             current_liabilities_ltm, working_capital_fq, working_capital_fy, working_capital_ltm, cfo_fq, cfo_fy,
             cfo_ltm, cfo_1fy, cfi_fq, cfi_fy, cfi_ltm, cff_fq, cff_fy, cff_ltm, fcf_fq, fcf_fy, fcf_ltm, fcf_1fy,
             capex_fq, capex_fy, capex_ltm, pe_ltm, pe_ntm, forward_pe, peg_ratio, pb_ltm, pb_1fy, pb_5yavg, ptbv_ltm,
             p_fcf, ev_fcf, ev_sales_ltm, ev_sales_ntm, ev_ebitda_ltm, ev_ebitda_ntm, fcf_per_share, revenue_per_share,
             roe_ltm, roe_fy, roa_ltm, roa_fy, asset_turnover_ltm, asset_turnover_fy, current_ratio_ltm,
             current_ratio_fy, altman_z_fq, altman_z_fy, altman_z_ltm, gross_margin_ltm, gross_margin_fy,
             net_margin_ltm, net_margin_fy, fcf_margin, div_yield_ltm, div_yield_ttm, div_yield_ntm, div_yield_ind,
             div_yield_5yavg, payout_ratio, buyback_yield_ltm, dps_growth, eps_basic_ltm, eps_basic_fq, eps_basic_fy,
             eps_adj_ltm, eps_adj_fy, eps_adj_1fy, eps_est_ntm, eps_est_fy1e, eps_gaap_est_ntm, eps_gaap_est_fy1e,
             eps_growth_ttm, eps_growth_3y, eps_growth_5y, revenue_est_ntm, revenue_est_fy1e, revenue_est_med_ntm,
             revenue_est_med_fy1e, revenue_est_yoy, revenue_growth_3y, revenue_growth_5y, ebitda_est_ntm,
             ebitda_est_fy1e, ebit_est_ntm, ebit_est_fy1e, eps_rev_1w, eps_rev_1m, eps_rev_3m, eps_rev_6m, eps_rev_1y,
             eps_gaap_rev_1m, eps_gaap_rev_3m, employees_fq, employees_fy, employees_1fy, employees_2fy,
             employees_5yavg, impairment_ltm, impairment_fy, writedown_ltm, writedown_fy, restructuring_ltm,
             restructuring_fy, merger_charges_ltm, asset_sale_gain_ltm, other_unusual_ltm, pt_1w_ago, pt_1m_ago,
             pt_3m_ago, pt_6m_ago, pt_1y_ago, fiscal_month, fiscal_quarter, fiscal_year, reporting_lag,
             revenue_fq_vs_5yavg, revenue_qoq_growth, revenue_seasonality_factor, sga_to_revenue_fy, sga_trend_yoy,
             marketing_to_revenue_fy, operating_leverage_score, cost_efficiency_trend, price_to_tbv, tbv_per_share,
             tangible_equity_ratio, tbv_margin_of_safety, net_interest_income, interest_coverage_ebitda,
             financial_income_quality, interest_burden_ratio, price_momentum_3y, price_momentum_5y,
             momentum_acceleration_3y, long_term_trend_score, momentum_consistency, secular_trend_flag, beta_2y,
             beta_trend_short, beta_trend_long, beta_stability, beta_regime_change, systematic_risk_score,
             defensive_stock_flag, high_beta_flag, estimate_skew_fy1e, revenue_consensus_confidence,
             upside_to_consensus, total_unusual_items, unusual_to_net_income_ratio, clean_earnings_flag,
             recurring_unusual_flag, earnings_noise_score, quality_adjusted_ni, pe_forward_discount, peg_adjusted,
             peg_forward, earnings_yield, fcf_yield, shareholder_yield_total, valuation_composite_score,
             defensive_interval, working_capital_turnover, liquidity_score, working_capital_efficiency)
as
SELECT ticker,
       isin,
       name,
       region,
       country,
       trading_country,
       exchange,
       unit,
       sector,
       industry,
       style_class,
       size_class,
       fy_end,
       next_earnings_when,
       next_earnings_status,
       current_fiscal_quarter,
       next_fiscal_quarter,
       next_earnings_report,
       reporting_interval,
       earnings_report_frequency,
       income_statement_report_date,
       next_earnings,
       fy_end_date,
       next_fy_end_date,
       next_income_statement_date,
       price_target,
       price_target_median,
       market_cap,
       enterprise_value,
       last_price,
       price_target_ytd_ago,
       price_target_low,
       price_target_high,
       dividend_record_currency,
       dividend_record_frequency,
       dividend_record_amount,
       dividend_announce_date,
       dividend_payable_date,
       dividend_record_date,
       dividend_ex_date,
       dividend_per_share_ltm,
       dividend_streak,
       analyst_rating,
       strong_sell_ratings,
       strong_buy_ratings,
       hold_ratings,
       buy_ratings,
       sell_ratings,
       price_target_count,
       shares_outstanding,
       shares_outstanding_1fy,
       volume_shares,
       relative_volume,
       price_5d_ago,
       price_1w_ago,
       price_1m_ago,
       price_3m_ago,
       price_6m_ago,
       price_1y_ago,
       price_3y_ago,
       price_5y_ago,
       price_qtd_ago,
       high_52w,
       low_52w,
       ema_20d,
       ema_50d,
       ema_100d,
       ema_250d,
       volatility_1m,
       volatility_3m,
       volatility_6m,
       volatility_1y,
       beta_1y,
       beta_2y_base,
       beta_5y,
       total_return_ytd,
       total_return_5y,
       total_return_10y,
       return_cagr_3y,
       return_cagr_10y,
       return_1d,
       price_change_1m,
       price_change_3m,
       revenue_fq,
       revenue_fy,
       revenue_ltm,
       revenue_1fy,
       revenue_5yavg_fq,
       revenue_5yavg_ltm,
       revenue_cagr_5y,
       ebitda_fq,
       ebitda_ltm,
       ebitda_fy,
       ebitda_1fy,
       ebitda_5yavg_fq,
       ebitda_5yavg_ltm,
       ebitda_adj_ltm,
       ebitda_adj_fy,
       ebit_fq,
       ebit_ltm,
       ebit_fy,
       ebit_1fy,
       ebit_5yavg_fq,
       ebit_5yavg_ltm,
       ebit_adj_ltm,
       ebit_adj_fy,
       net_income_fq,
       net_income_fy,
       net_income_ltm,
       net_income_1fy,
       normalized_ni_fq,
       normalized_ni_fy,
       normalized_ni_ltm,
       net_income_adj_fq,
       net_income_adj_fy,
       net_income_adj_ltm,
       gross_profit_fq,
       gross_profit_fy,
       gross_profit_ltm,
       operating_income_fq,
       operating_income_fy,
       operating_income_ltm,
       operating_income_5yavg_fq,
       total_opex_ltm,
       cost_of_revenues_ltm,
       rd_expenses_ltm,
       sga_fq,
       sga_fy,
       sga_1fy,
       marketing_fq,
       marketing_fy,
       interest_expense_ltm,
       interest_income_ltm,
       total_assets_fq,
       total_assets_fy,
       total_assets_ltm,
       total_debt_fq,
       total_debt_fy,
       total_debt_ltm,
       total_equity_fy,
       total_equity_ltm,
       tbv_fy,
       tbv_ltm,
       cash_fq,
       cash_fy,
       cash_ltm,
       inventory_fq,
       inventory_fy,
       inventory_ltm,
       goodwill_fq,
       goodwill_fy,
       goodwill_ltm,
       intangible_assets_ltm,
       retained_earnings_fq,
       retained_earnings_fy,
       retained_earnings_ltm,
       current_assets_ltm,
       current_liabilities_ltm,
       working_capital_fq,
       working_capital_fy,
       working_capital_ltm,
       cfo_fq,
       cfo_fy,
       cfo_ltm,
       cfo_1fy,
       cfi_fq,
       cfi_fy,
       cfi_ltm,
       cff_fq,
       cff_fy,
       cff_ltm,
       fcf_fq,
       fcf_fy,
       fcf_ltm,
       fcf_1fy,
       capex_fq,
       capex_fy,
       capex_ltm,
       pe_ltm,
       pe_ntm,
       forward_pe,
       peg_ratio,
       pb_ltm,
       pb_1fy,
       pb_5yavg,
       ptbv_ltm,
       p_fcf,
       ev_fcf,
       ev_sales_ltm,
       ev_sales_ntm,
       ev_ebitda_ltm,
       ev_ebitda_ntm,
       fcf_per_share,
       revenue_per_share,
       roe_ltm,
       roe_fy,
       roa_ltm,
       roa_fy,
       asset_turnover_ltm,
       asset_turnover_fy,
       current_ratio_ltm,
       current_ratio_fy,
       altman_z_fq,
       altman_z_fy,
       altman_z_ltm,
       gross_margin_ltm,
       gross_margin_fy,
       net_margin_ltm,
       net_margin_fy,
       fcf_margin,
       div_yield_ltm,
       div_yield_ttm,
       div_yield_ntm,
       div_yield_ind,
       div_yield_5yavg,
       payout_ratio,
       buyback_yield_ltm,
       dps_growth,
       eps_basic_ltm,
       eps_basic_fq,
       eps_basic_fy,
       eps_adj_ltm,
       eps_adj_fy,
       eps_adj_1fy,
       eps_est_ntm,
       eps_est_fy1e,
       eps_gaap_est_ntm,
       eps_gaap_est_fy1e,
       eps_growth_ttm,
       eps_growth_3y,
       eps_growth_5y,
       revenue_est_ntm,
       revenue_est_fy1e,
       revenue_est_med_ntm,
       revenue_est_med_fy1e,
       revenue_est_yoy,
       revenue_growth_3y,
       revenue_growth_5y,
       ebitda_est_ntm,
       ebitda_est_fy1e,
       ebit_est_ntm,
       ebit_est_fy1e,
       eps_rev_1w,
       eps_rev_1m,
       eps_rev_3m,
       eps_rev_6m,
       eps_rev_1y,
       eps_gaap_rev_1m,
       eps_gaap_rev_3m,
       employees_fq,
       employees_fy,
       employees_1fy,
       employees_2fy,
       employees_5yavg,
       impairment_ltm,
       impairment_fy,
       writedown_ltm,
       writedown_fy,
       restructuring_ltm,
       restructuring_fy,
       merger_charges_ltm,
       asset_sale_gain_ltm,
       other_unusual_ltm,
       pt_1w_ago,
       pt_1m_ago,
       pt_3m_ago,
       pt_6m_ago,
       pt_1y_ago,
       fiscal_month,
       fiscal_quarter,
       fiscal_year,
       reporting_lag,
       revenue_fq_vs_5yavg,
       revenue_qoq_growth,
       revenue_seasonality_factor,
       sga_to_revenue_fy,
       sga_trend_yoy,
       marketing_to_revenue_fy,
       operating_leverage_score,
       cost_efficiency_trend,
       price_to_tbv,
       tbv_per_share,
       tangible_equity_ratio,
       tbv_margin_of_safety,
       net_interest_income,
       interest_coverage_ebitda,
       financial_income_quality,
       interest_burden_ratio,
       price_momentum_3y,
       price_momentum_5y,
       momentum_acceleration_3y,
       long_term_trend_score,
       momentum_consistency,
       secular_trend_flag,
       beta_2y,
       beta_trend_short,
       beta_trend_long,
       beta_stability,
       beta_regime_change,
       systematic_risk_score,
       defensive_stock_flag,
       high_beta_flag,
       estimate_skew_fy1e,
       revenue_consensus_confidence,
       upside_to_consensus,
       total_unusual_items,
       unusual_to_net_income_ratio,
       clean_earnings_flag,
       recurring_unusual_flag,
       earnings_noise_score,
       quality_adjusted_ni,
       pe_forward_discount,
       peg_adjusted,
       peg_forward,
       earnings_yield,
       fcf_yield,
       shareholder_yield_total,
       valuation_composite_score,
       defensive_interval,
       working_capital_turnover,
       liquidity_score,
       working_capital_efficiency
FROM mv_feature_registry_enhanced;

alter table mw_feature_registry_enhanced
    owner to postgres;

