create table screening_us
(
    ticker                                             text,
    isin                                               text,
    name                                               text,
    description                                        text,
    region                                             text,
    country                                            text,
    "Trading Country"                                  text,
    exchange                                           text,
    unit                                               text,
    sector                                             text,
    industry                                           text,
    "Style Class"                                      text,
    "Size Class"                                       text,
    "Last Updated"                                     text,
    "Income Statement Report Date"                     text,
    "FY End"                                           text,
    "Next Earnings"                                    text,
    "Next Earnings (When)"                             text,
    "Next Earnings (Status)"                           text,
    "Dividend Record (Currency)"                       text,
    "Dividend Record (Amount)"                         double precision,
    "Dividend Record (Frequency)"                      text,
    "Dividend Streak"                                  integer,
    "Dividend Record (Announce Date)"                  text,
    "Dividend Record (Payable Date)"                   text,
    "Dividend Record (Record Date)"                    text,
    "Dividend Record (Ex Date)"                        text,
    "Market Cap"                                       double precision,
    "Enterprise Value"                                 double precision,
    "Last Price"                                       double precision,
    "Price Target (YTD Ago)"                           double precision,
    "Total Return (YTD)"                               double precision,
    "Price Target"                                     double precision,
    "Price Target - Low"                               double precision,
    "Price Target - Median"                            double precision,
    "Price Target - High"                              double precision,
    "Price Target - #"                                 double precision,
    "P/E (NTM)"                                        double precision,
    "P/E (LTM)"                                        double precision,
    "Altman Z-Score (FY)"                              double precision,
    "Altman Z-Score (FQ)"                              double precision,
    "Altman Z-Score (LTM)"                             double precision,
    "Beta (1Y)"                                        double precision,
    "Beta (2Y)"                                        double precision,
    "Beta (5Y)"                                        double precision,
    "Analyst Rating"                                   double precision,
    "# Strong Sell Ratings"                            integer,
    "# Strong Buys Ratings"                            integer,
    "# Hold Ratings"                                   integer,
    "# Buys Ratings"                                   integer,
    "# Sell Ratings"                                   integer,
    "Total Revenues/CAGR (5Y FY)"                      double precision,
    "Total Revenues (FQ)"                              double precision,
    "Total Revenues (-1FY)"                            double precision,
    "Total Revenues (FY)"                              double precision,
    "Total Revenues (LTM)"                             double precision,
    "Total Operating Expenses (LTM)"                   double precision,
    "P/TBV (LTM)"                                      double precision,
    "TBV (FY)"                                         double precision,
    "TBV (LTM)"                                        double precision,
    "Market Cap (Country R)"                           integer,
    "Tot. Return %/CAGR (3Y)"                          double precision,
    "Tot. Return %/CAGR (10Y)"                         double precision,
    "Total Return (5Y)"                                double precision,
    "Total Return (10Y)"                               double precision,
    "Net Income/Adj. (-1FY)"                           double precision,
    "CFF (LTM)"                                        double precision,
    "CFI (LTM)"                                        double precision,
    "FCF (LTM)"                                        double precision,
    "CFO (LTM)"                                        double precision,
    "EBITDA (FQ)"                                      double precision,
    "EBITDA (LTM)"                                     double precision,
    "EBITDA (FY)"                                      double precision,
    "EBITDA (-1FY)"                                    double precision,
    "EBITDA/Adj. (LTM)"                                double precision,
    "EBITDA/Adj. (FY)"                                 double precision,
    "EBITDA/Adj. (-1FY)"                               double precision,
    "EBIT (FQ)"                                        double precision,
    "EBIT (LTM)"                                       double precision,
    "EBIT (FY)"                                        double precision,
    "EBIT (-1FY)"                                      double precision,
    "EBIT/Adj. (-1FY)"                                 double precision,
    "EBIT/Adj. (FY)"                                   double precision,
    "EBIT/Adj. (LTM)"                                  double precision,
    "EBIT - Est Med (FY1E)"                            double precision,
    "EBIT - Est Med (NTM)"                             double precision,
    "Return On Equity % (LTM)"                         double precision,
    "Return On Equity % (FY)"                          double precision,
    "Net Income - (IS) (FY)"                           double precision,
    "Net Income - (IS) (LTM)"                          double precision,
    "Normalized Net Income (FY)"                       double precision,
    "Normalized Net Income (LTM)"                      double precision,
    "Net Income/Adj. (FY)"                             double precision,
    "Net Income/Adj. (LTM)"                            double precision,
    "Net Income Margin % (FY)"                         double precision,
    "Net Income Margin % (LTM)"                        double precision,
    "Volatility (1M)"                                  double precision,
    "Volatility (3M)"                                  double precision,
    "Volatility (6M)"                                  double precision,
    "Volatility (1Y)"                                  double precision,
    "Volume (Shrs)"                                    integer,
    "Dividend Per Share (LTM)"                         double precision,
    "Div Yield (Ind)"                                  double precision,
    "Div Yield (LTM)"                                  double precision,
    "Total Debt (FY)"                                  double precision,
    "Total Equity (FY)"                                double precision,
    "Total Equity (LTM)"                               double precision,
    "Total Debt (LTM)"                                 double precision,
    "Total Assets (LTM)"                               double precision,
    "Total Assets (FY)"                                double precision,
    "Current Ratio (FY)"                               double precision,
    "Current Ratio (LTM)"                              double precision,
    "Gross Profit Margin % (FY)"                       double precision,
    "Gross Profit Margin % (LTM)"                      double precision,
    "Asset Turnover (FY)"                              double precision,
    "Asset Turnover (LTM)"                             double precision,
    "Gross Profit (LTM)"                               double precision,
    "Gross Profit (FY)"                                double precision,
    "EPS Norm - Est Avg (NTM)"                         double precision,
    "EPS/Adj. (-1FY)"                                  double precision,
    "EPS/Adj. (FY)"                                    double precision,
    "EPS/Adj. (LTM)"                                   double precision,
    "EPS Norm - Est Avg (FY1E)"                        double precision,
    "Gain (Loss) On Sale Of Assets (LTM)"              text,
    "Cost Of Revenues (LTM)"                           double precision,
    "Cash Acquisitions (LTM)"                          double precision,
    "Cash Acquisitions (FY)"                           double precision,
    "Cash Acquisitions (-1FY)"                         double precision,
    "Inventory (LTM)"                                  double precision,
    "Goodwill (FQ)"                                    double precision,
    "Goodwill (LTM)"                                   double precision,
    "Goodwill (FY)"                                    double precision,
    "Goodwill (-1FY)"                                  double precision,
    "Impairment of Goodwill (FQ)"                      text,
    "Impairment of Goodwill (LTM)"                     text,
    "Impairment of Goodwill (-1FY)"                    text,
    "Impairment of Goodwill (FY)"                      text,
    "Operating Income (LTM)"                           double precision,
    "Asset Writedown (LTM)"                            text,
    "Asset Writedown (FY)"                             text,
    "Asset Writedown (-1FY)"                           text,
    "Operating Income (FY)"                            double precision,
    "Capital Expenditure (LTM)"                        double precision,
    "Capital Expenditure (-1FY)"                       double precision,
    "Capital Expenditure (FY)"                         double precision,
    "Retained Earnings (LTM)"                          double precision,
    "Total Current Assets (LTM)"                       double precision,
    "Total Current Liabilities (LTM)"                  double precision,
    "R&D Expenses (LTM)"                               double precision,
    "Restructuring Charges (LTM)"                      text,
    "Restructuring Charges (FQ)"                       text,
    "Restructuring Charges (-1FY)"                     text,
    "Restructuring Charges (FY)"                       text,
    "Interest Expense/Total (LTM)"                     double precision,
    "Merger & Restructuring Charges (LTM)"             text,
    "Working Capital (LTM)"                            double precision,
    "Other Unusual Items/Total (LTM)"                  text,
    "Interest Income On Investments (LTM)"             text,
    "Buyback Yield (LTM)"                              double precision,
    "Return on Assets (ROA) % (LTM)"                   double precision,
    "Return on Assets (ROA) % (FY)"                    double precision,
    "Net Income - (IS) (-1FY)"                         double precision,
    "Normalized Net Income (-1FY)"                     double precision,
    "CFF (FY)"                                         double precision,
    "CFF (-1FY)"                                       double precision,
    "CFI (FY)"                                         double precision,
    "CFI (-1FY)"                                       double precision,
    "CFO (FY)"                                         double precision,
    "CFO (-1FY)"                                       double precision,
    "Div Yield (-1FYInd)"                              double precision,
    "FCF (FY)"                                         double precision,
    "FCF (-1FY)"                                       double precision,
    "Capital Expenditure (FQ)"                         double precision,
    "Capital Expenditure (5YAVGFQ)"                    double precision,
    "CFF (FQ)"                                         double precision,
    "CFI (FQ)"                                         double precision,
    "CFO (FQ)"                                         double precision,
    "FCF (FQ)"                                         double precision,
    "Total Revenues (5YAVGFQ)"                         double precision,
    "EBITDA (5YAVGFQ)"                                 double precision,
    "EBIT (5YAVGFQ)"                                   double precision,
    "FCF (5YAVGFQ)"                                    double precision,
    "Cash Acquisitions (FQ)"                           double precision,
    "Cash Acquisitions (5YAVGFQ)"                      double precision,
    "Asset Writedown (FQ)"                             text,
    "Asset Writedown (5YAVGFQ)"                        double precision,
    "Impairment of Goodwill (5YAVGFQ)"                 text,
    "Operating Income (FQ)"                            double precision,
    "Operating Income (5YAVGFQ)"                       double precision,
    "P/B (LTM)"                                        double precision,
    "P/B (-1FY)"                                       double precision,
    "P/B (5YAVG)"                                      double precision,
    "Cash And Equivalents (LTM)"                       double precision,
    "Cash And Equivalents (FQ)"                        double precision,
    "Cash And Equivalents (FY)"                        double precision,
    "Cash And Equivalents (5YAVGFQ)"                   double precision,
    "Inventory (FQ)"                                   double precision,
    "Inventory (FY)"                                   double precision,
    "Goodwill (5YAVGFQ)"                               double precision,
    "Inventory (5YAVGFQ)"                              double precision,
    "Retained Earnings (FQ)"                           double precision,
    "Retained Earnings (FY)"                           double precision,
    "Retained Earnings (5YAVGFQ)"                      double precision,
    "Working Capital (FQ)"                             double precision,
    "Working Capital (FY)"                             double precision,
    "Working Capital (5YAVGFY)"                        double precision,
    "Div Yield (TTM)"                                  double precision,
    "Div Yield (NTM)"                                  double precision,
    "Div Yield (5YAVGLTM)"                             double precision,
    "Gross Intangible Assets (LTM)"                    double precision,
    "Gross Intangible Assets (FY)"                     double precision,
    "Gross Intangible Assets (5YAVGFQ)"                double precision,
    "Restructuring Charges (5YAVGFQ)"                  double precision,
    "Merger & Restructuring Charges (FQ)"              text,
    "Merger & Restructuring Charges (FY)"              text,
    "Merger & Restructuring Charges (5YAVGFQ)"         double precision,
    "Normalized Net Income (FQ)"                       double precision,
    "Normalized Net Income (5YAVGFQ)"                  double precision,
    "Net Income/Adj. (FQ)"                             double precision,
    "Net Income/Adj. (5YAVGFQ)"                        double precision,
    "Net Income - (IS) (FQ)"                           double precision,
    "Net Income - (IS) (5YAVGFQ)"                      double precision,
    "Net Income - (IS) (5YAVGLTM)"                     double precision,
    "Normalized Net Income (5YAVGLTM)"                 double precision,
    "EBITDA (5YAVGLTM)"                                double precision,
    "EBIT (5YAVGLTM)"                                  double precision,
    "Total Revenues (5YAVGLTM)"                        double precision,
    "Revenues - Est YoY % (FY1E)"                      double precision,
    "Price Chg. % (1M)"                                double precision,
    "Price Chg. % (3M)"                                double precision,
    "1-Day %"                                          double precision,
    "Price (5D Ago)"                                   double precision,
    "Price (1W Ago)"                                   double precision,
    "Price (1M Ago)"                                   double precision,
    "Price (3M Ago)"                                   double precision,
    "Price (6M Ago)"                                   double precision,
    "Price (1Y Ago)"                                   double precision,
    "Price (3Y Ago)"                                   double precision,
    "Price (5Y Ago)"                                   double precision,
    "Price (QTD Ago)"                                  double precision,
    "Rel. Volume"                                      double precision,
    "Shrs Out"                                         double precision,
    "Shrs Out (-1FY)"                                  double precision,
    "Common Dividends Paid (LTM)"                      double precision,
    "Common Dividends Paid (FY)"                       double precision,
    "Selling General & Admin Expenses/Total (FQ)"      double precision,
    "Selling General & Admin Expenses/Total (FY)"      double precision,
    "Selling General & Admin Expenses/Total (-1FY)"    double precision,
    "Selling General & Admin Expenses/Total (5YAVGFQ)" double precision,
    "Accounts Receivable/Total (FY)"                   double precision,
    "Accounts Receivable/Total (-1FY)"                 double precision,
    "Accounts Receivable/Total (5YAVGFQ)"              double precision,
    "Marketing Expenses (FQ)"                          text,
    "Marketing Expenses (FY)"                          text,
    "Marketing Expenses (-1FY)"                        text,
    "Marketing Expenses (5YAVGLTM)"                    text,
    "Revenues - Est Avg (NTM)"                         double precision,
    "Revenues - Est Avg (FY1E)"                        double precision,
    "Revenues - Est Med (NTM)"                         double precision,
    "Revenues - Est Med (FY1E)"                        double precision,
    "EV/Sales (EST FY1)"                               double precision,
    "EV/Sales (LTM)"                                   double precision,
    "EV/Sales (NTM)"                                   double precision,
    "EV/Sales (-1FYLTM)"                               double precision,
    "EV/Sales (-2FYLTM)"                               double precision,
    "EV/Sales (-3FYLTM)"                               double precision,
    "EV/Sales (3YAVGLTM)"                              double precision,
    "EV/Sales (-1FQLTM)"                               double precision,
    "EV/Sales (-2FQLTM)"                               double precision,
    "EV/Sales (-3FQLTM)"                               double precision,
    "EV/Sales (-4FQLTM)"                               double precision,
    "52W High/Adj"                                     double precision,
    "52W Low/Adj"                                      double precision,
    "EMA (20D)"                                        double precision,
    "EMA (50D)"                                        double precision,
    "EMA (100D)"                                       double precision,
    "EMA (250D)"                                       double precision,
    "EV/EBITDA (LTM)"                                  double precision,
    "EV/EBITDA (NTM)"                                  double precision,
    "EV/EBITDA (-1FYLTM)"                              double precision,
    "EV/EBITDA (-1FQLTM)"                              double precision,
    "EV/EBITDA (3YAVGLTM)"                             double precision,
    "EV/EBITDA (EST FY1)"                              double precision,
    "P/E (EST FY1)"                                    double precision,
    "P/E (-1FYLTM)"                                    double precision,
    "P/E (-2FYLTM)"                                    double precision,
    "P/E (-3FYLTM)"                                    double precision,
    "P/E (3YAVGLTM)"                                   double precision,
    "P/E (-1FQLTM)"                                    double precision,
    "P/E (-2FQLTM)"                                    double precision,
    "P/E (-3FQLTM)"                                    double precision,
    "P/E (5YAVGLTM)"                                   double precision,
    "P/E (-0FQQoQLTM)"                                 double precision,
    "P/E (-0FYYoYLTM)"                                 double precision,
    "P/E (-1FYYoYLTM)"                                 double precision,
    "P/E (-0FQYoYLTM)"                                 double precision,
    "Full Time Employees (FQ)"                         text,
    "Full Time Employees (FY)"                         integer,
    "Full Time Employees (-1FY)"                       integer,
    "Full Time Employees (-2FY)"                       integer,
    "Full Time Employees (-3FY)"                       integer,
    "Avg Employees (5YAVGFY)"                          text,
    "Net EPS - Basic (LTM)"                            double precision,
    "Net EPS - Basic (FQ)"                             double precision,
    "Net EPS - Basic (FY)"                             double precision,
    "Net EPS - Basic (-1FQFQ)"                         double precision,
    "Net EPS - Basic (-2FQFQ)"                         double precision,
    "Net EPS - Basic (-3FQFQ)"                         double precision,
    "Net EPS - Basic (-4FQFQ)"                         double precision,
    "Net EPS - Basic (-1FY)"                           double precision,
    "Net EPS - Basic (-2FY)"                           double precision,
    "Net EPS - Basic (-3FY)"                           double precision,
    "Net EPS - Basic (-4FY)"                           double precision,
    "Net EPS - Basic (-5FY)"                           double precision,
    "EPS Est Avg Rev % (FY1E - 1W)"                    double precision,
    "EPS Est Avg Rev % (FY1E - 1M)"                    double precision,
    "EPS Est Avg Rev % (FY1E - 3M)"                    double precision,
    "EPS Est Avg Rev % (FY1E - 6M)"                    double precision,
    "EPS Est Avg Rev % (FY1E - 1Y)"                    double precision,
    "Div Yield (-2FYInd)"                              double precision,
    "Div Yield (-3FYInd)"                              double precision,
    "Div Yield (-4FYInd)"                              double precision,
    "Div Yield (-5FYInd)"                              double precision,
    "EBITDA - Est Avg (NTM)"                           double precision,
    "EBITDA - Est Avg (FY1E)"                          double precision,
    "EPS GAAP - Est Avg (NTM)"                         double precision,
    "EPS GAAP - Est Avg (FY1E)"                        double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 1M)"               double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 3M)"               double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 6M)"               double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 1Y)"               double precision,
    "EPS Norm - Est # (FY1E)"                          integer,
    "CFO (-1FQFQ)"                                     double precision,
    "CFO (-2FQFQ)"                                     double precision,
    "CFO (-3FQFQ)"                                     double precision,
    "CFO (-4FQFQ)"                                     double precision,
    "CFI (-1FQFQ)"                                     double precision,
    "CFI (-2FQFQ)"                                     double precision,
    "CFI (-3FQFQ)"                                     double precision,
    "CFI (-4FQFQ)"                                     double precision,
    "CFI (-2FY)"                                       double precision,
    "CFI (-3FY)"                                       double precision,
    "CFI (-4FY)"                                       double precision,
    "FCF (-1FQFQ)"                                     double precision,
    "FCF (-2FQFQ)"                                     double precision,
    "FCF (-3FQFQ)"                                     double precision,
    "FCF (-4FQFQ)"                                     double precision,
    "CFF (-2FY)"                                       double precision,
    "CFF (-3FY)"                                       double precision,
    "CFF (-4FY)"                                       double precision,
    "CFF (-1FQFQ)"                                     double precision,
    "CFF (-2FQFQ)"                                     double precision,
    "CFF (-3FQFQ)"                                     double precision,
    "CFF (-4FQFQ)"                                     double precision,
    "CFO (-2FY)"                                       double precision,
    "CFO (-3FY)"                                       double precision,
    "CFO (-4FY)"                                       double precision,
    "Cash Acquisitions (-1FQFQ)"                       double precision,
    "Cash Acquisitions (-2FQFQ)"                       double precision,
    "Cash Acquisitions (-3FQFQ)"                       double precision,
    "Cash Acquisitions (-4FQFQ)"                       double precision,
    "FCF (-2FY)"                                       double precision,
    "FCF (-3FY)"                                       double precision,
    "FCF (-4FY)"                                       double precision,
    "Price Target (1W Ago)"                            double precision,
    "Price Target (1M Ago)"                            double precision,
    "Price Target (3M Ago)"                            double precision,
    "Price Target (6M Ago)"                            double precision,
    "Price Target (MTD Ago)"                           double precision,
    "Price Target (QTD Ago)"                           double precision,
    "Price Target (1Y Ago)"                            double precision,
    "Price Target - # (3M Ago)"                        text,
    "Price Target - # (6M Ago)"                        text,
    "Price Target - # (YTD Ago)"                       text,
    "Price Target - # (1Y Ago)"                        text,
    "Price Target - # (1W Ago)"                        text,
    "Price Target - # (1M Ago)"                        text,
    "Price Target - # (MTD Ago)"                       text,
    "Price Target - # (QTD Ago)"                       text,
    "Price Target - High (1W Ago)"                     text,
    "Price Target - High (1M Ago)"                     text,
    "Price Target - High (6M Ago)"                     text,
    "Price Target - High (MTD Ago)"                    text,
    "Price Target - High (3M Ago)"                     text,
    "Price Target - High (QTD Ago)"                    text,
    "Price Target - High (1Y Ago)"                     text,
    "Price Target - High (YTD Ago)"                    text,
    "Price Target - Low (1W Ago)"                      text,
    "Price Target - Low (1M Ago)"                      text,
    "Price Target - Low (3M Ago)"                      text,
    "Price Target - Low (6M Ago)"                      text,
    "Price Target - Low (MTD Ago)"                     text,
    "Price Target - Low (QTD Ago)"                     text,
    "Price Target - Low (YTD Ago)"                     text,
    "Price Target - Low (1Y Ago)"                      text,
    "Price Target - Median (1W Ago)"                   text,
    "Price Target - Median (1M Ago)"                   text,
    "Price Target - Median (3M Ago)"                   text,
    "Price Target - Median (6M Ago)"                   text,
    "Price Target - Median (MTD Ago)"                  text,
    "Price Target - Median (QTD Ago)"                  text,
    "Price Target - Median (YTD Ago)"                  text,
    "Price Target - Median (1Y Ago)"                   text,
    "Impairment of Goodwill (-1FQFQ)"                  text,
    "Impairment of Goodwill (-2FQFQ)"                  text,
    "Impairment of Goodwill (-3FQFQ)"                  text,
    "Impairment of Goodwill (-4FQFQ)"                  text,
    "Impairment of Goodwill (-2FY)"                    text,
    "Impairment of Goodwill (-3FY)"                    text,
    "Impairment of Goodwill (-4FY)"                    text,
    "Asset Writedown (-1FQFQ)"                         text,
    "Asset Writedown (-2FQFQ)"                         text,
    "Asset Writedown (-3FQFQ)"                         text,
    "Asset Writedown (-4FQFQ)"                         text,
    "Asset Writedown (-2FY)"                           text,
    "Asset Writedown (-3FY)"                           text,
    "Asset Writedown (-4FY)"                           text,
    "Asset Writedown (-5FY)"                           text,
    "Gain (Loss) On Sale Of Assets (FQ)"               text,
    "Gain (Loss) On Sale Of Assets (FY)"               text,
    "Gain (Loss) On Sale Of Assets (-1FQFQ)"           text,
    "Gain (Loss) On Sale Of Assets (-2FQFQ)"           text,
    "Gain (Loss) On Sale Of Assets (-3FQFQ)"           text,
    "Gain (Loss) On Sale Of Assets (-4FQFQ)"           text,
    "Gain (Loss) On Sale Of Assets (-1FY)"             text,
    "Gain (Loss) On Sale Of Assets (-2FY)"             text,
    "Gain (Loss) On Sale Of Assets (-3FY)"             text,
    "Gain (Loss) On Sale Of Assets (-4FY)"             text,
    "Restructuring Charges (-1FQFQ)"                   text,
    "Restructuring Charges (-2FQFQ)"                   text,
    "Restructuring Charges (-3FQFQ)"                   text,
    "Restructuring Charges (-4FQFQ)"                   text,
    "Restructuring Charges (-2FY)"                     text,
    "Restructuring Charges (-3FY)"                     text,
    "Restructuring Charges (-4FY)"                     text,
    "Net Income - (IS) (-1FQFQ)"                       text,
    "Net Income - (IS) (-2FQFQ)"                       text,
    "Net Income - (IS) (-3FQFQ)"                       text,
    "Net Income - (IS) (-4FQFQ)"                       text,
    "Net Income - (IS) (-2FY)"                         text,
    "Net Income - (IS) (-3FY)"                         text,
    "Net Income - (IS) (-4FY)"                         text,
    "Normalized Net Income (-1FQFQ)"                   text,
    "Normalized Net Income (-2FQFQ)"                   text,
    "Normalized Net Income (-3FQFQ)"                   text,
    "Normalized Net Income (-4FQFQ)"                   text,
    "Normalized Net Income (-2FY)"                     text,
    "Normalized Net Income (-3FY)"                     text,
    "Normalized Net Income (-4FY)"                     text,
    "Net Income/Adj. (-1FQFQ)"                         text,
    "Net Income/Adj. (-2FQFQ)"                         text,
    "Net Income/Adj. (-3FQFQ)"                         text,
    "Net Income/Adj. (-4FQFQ)"                         text,
    "Net Income/Adj. (-2FY)"                           text,
    "Net Income/Adj. (-3FY)"                           text,
    "Net Income/Adj. (-4FY)"                           text,
    "EBIT (-1FQFQ)"                                    text,
    "EBIT (-2FQFQ)"                                    text,
    "EBIT (-3FQFQ)"                                    text,
    "EBIT (-4FQFQ)"                                    text,
    "EBIT (-2FY)"                                      text,
    "EBIT (-3FY)"                                      text,
    "EBIT (-4FY)"                                      text,
    "EBIT/Adj. (FQ)"                                   text,
    "EBIT/Adj. (-1FQFQ)"                               text,
    "EBIT/Adj. (-2FQFQ)"                               text,
    "EBIT/Adj. (-3FQFQ)"                               text,
    "EBIT/Adj. (-4FQFQ)"                               text,
    "EBIT/Adj. (-2FY)"                                 text,
    "EBIT/Adj. (-3FY)"                                 text,
    "EBIT/Adj. (-4FY)"                                 text,
    "EBITDA (-1FQFQ)"                                  text,
    "EBITDA (-2FQFQ)"                                  text,
    "EBITDA (-3FQFQ)"                                  text,
    "EBITDA (-4FQFQ)"                                  text,
    "EBITDA (-2FY)"                                    text,
    "EBITDA (-4FY)"                                    text,
    "EBITDA (-3FY)"                                    text,
    "EBITDA/Adj. (FQ)"                                 text,
    "EBITDA/Adj. (-1FQFQ)"                             text,
    "EBITDA/Adj. (-2FQFQ)"                             text,
    "EBITDA/Adj. (-3FQFQ)"                             text,
    "EBITDA/Adj. (-4FQFQ)"                             text,
    "EBITDA/Adj. (-2FY)"                               text,
    "EBITDA/Adj. (-3FY)"                               text,
    "EBITDA/Adj. (-4FY)"                               text,
    "Basic EPS - Cont (LTM)"                           text,
    "Basic EPS - Cont (FQ)"                            text,
    "Basic EPS - Cont (FY)"                            text,
    "Basic EPS - Cont (-1FQFQ)"                        text,
    "Basic EPS - Cont (-2FQFQ)"                        text,
    "Basic EPS - Cont (-4FQFQ)"                        text,
    "Basic EPS - Cont (-3FQFQ)"                        text,
    "Basic EPS - Cont (-1FY)"                          text,
    "Basic EPS - Cont (-2FY)"                          text,
    "Basic EPS - Cont (-3FY)"                          text,
    "Basic EPS - Cont (-4FY)"                          text,
    "EPS/Adj. (FQ)"                                    text,
    "EPS/Adj. (-1FQFQ)"                                text,
    "EPS/Adj. (-3FQFQ)"                                text,
    "EPS/Adj. (-4FQFQ)"                                text,
    "EPS/Adj. (-2FQFQ)"                                text,
    "EPS/Adj. (-2FY)"                                  text,
    "EPS/Adj. (-3FY)"                                  text,
    "EPS/Adj. (-4FY)"                                  text,
    "Cash Acquisitions (-2FY)"                         text,
    "Cash Acquisitions (-3FY)"                         text,
    "Cash Acquisitions (-4FY)"                         text,
    "Capital Expenditure (-1FQFQ)"                     text,
    "Capital Expenditure (-3FQFQ)"                     text,
    "Capital Expenditure (-4FQFQ)"                     text,
    "Capital Expenditure (-2FQFQ)"                     text,
    "Capital Expenditure (-2FY)"                       text,
    "Capital Expenditure (-3FY)"                       text,
    "Capital Expenditure (-4FY)"                       text,
    "Working Capital (-1FQ)"                           text,
    "Working Capital (-2FQ)"                           text,
    "Working Capital (-3FQ)"                           text,
    "Working Capital (-4FQ)"                           text,
    "Working Capital (-1FY)"                           text,
    "Working Capital (-2FY)"                           text,
    "Working Capital (-3FY)"                           text,
    "Working Capital (-4FY)"                           text,
    "Total Debt (FQ)"                                  text,
    "Total Debt (-1FQ)"                                text,
    "Total Debt (-2FQ)"                                text,
    "Total Debt (-3FQ)"                                text,
    "Total Debt (-4FQ)"                                text,
    "Total Debt (-1FY)"                                text,
    "Total Debt (-2FY)"                                text,
    "Total Debt (-3FY)"                                text,
    "Total Debt (-4FY)"                                text,
    "Total Assets (FQ)"                                text,
    "Total Assets (-1FQ)"                              text,
    "Total Assets (-2FQ)"                              text,
    "Total Assets (-3FQ)"                              text,
    "Total Assets (-4FQ)"                              text,
    "Total Assets (-1FY)"                              text,
    "Total Assets (-2FY)"                              text,
    "Total Assets (-3FY)"                              text,
    "Total Assets (-4FY)"                              text,
    "Gross Profit (FQ)"                                text,
    "Gross Profit (-1FQFQ)"                            text,
    "Gross Profit (-3FQFQ)"                            text,
    "Gross Profit (-4FQFQ)"                            text,
    "Gross Profit (-2FQFQ)"                            text,
    "Gross Profit (-1FY)"                              text,
    "Gross Profit (-2FY)"                              text,
    "Gross Profit (-3FY)"                              text,
    "Gross Profit (-4FY)"                              text,
    "Inventory (-1FQ)"                                 text,
    "Inventory (-3FQ)"                                 text,
    "Inventory (-4FQ)"                                 text,
    "Inventory (-2FQ)"                                 text,
    "Inventory (-1FY)"                                 text,
    "Inventory (-2FY)"                                 text,
    "Inventory (-4FY)"                                 text,
    "Inventory (-3FY)"                                 text,
    "Goodwill (-1FQ)"                                  text,
    "Goodwill (-4FQ)"                                  text,
    "Goodwill (-2FQ)"                                  text,
    "Goodwill (-3FQ)"                                  text,
    "Goodwill (-2FY)"                                  text,
    "Goodwill (-3FY)"                                  text,
    "Goodwill (-4FY)"                                  text,
    "Operating Income (-1FQFQ)"                        text,
    "Operating Income (-3FQFQ)"                        text,
    "Operating Income (-4FQFQ)"                        text,
    "Operating Income (-2FQFQ)"                        text,
    "Operating Income (-1FY)"                          text,
    "Operating Income (-2FY)"                          text,
    "Operating Income (-4FY)"                          text,
    "Operating Income (-3FY)"                          text,
    "Retained Earnings (-1FQ)"                         text,
    "Retained Earnings (-2FQ)"                         text,
    "Retained Earnings (-3FQ)"                         text,
    "Retained Earnings (-4FQ)"                         text,
    "Retained Earnings (-1FY)"                         text,
    "Retained Earnings (-2FY)"                         text,
    "Retained Earnings (-3FY)"                         text,
    "Retained Earnings (-4FY)"                         text,
    "R&D Expenses (FQ)"                                text,
    "R&D Expenses (FY)"                                text,
    "R&D Expenses (-1FQFQ)"                            text,
    "R&D Expenses (-2FQFQ)"                            text,
    "R&D Expenses (-3FQFQ)"                            text,
    "R&D Expenses (-4FQFQ)"                            text,
    "R&D Expenses (-1FY)"                              text,
    "R&D Expenses (-2FY)"                              text,
    "R&D Expenses (-4FY)"                              text,
    "R&D Expenses (-3FY)"                              text,
    "Merger & Restructuring Charges (-1FQFQ)"          text,
    "Merger & Restructuring Charges (-3FQFQ)"          text,
    "Merger & Restructuring Charges (-4FQFQ)"          text,
    "Merger & Restructuring Charges (-2FQFQ)"          text,
    "Merger & Restructuring Charges (-1FY)"            text,
    "Merger & Restructuring Charges (-3FY)"            text,
    "Merger & Restructuring Charges (-4FY)"            text,
    "Merger & Restructuring Charges (-2FY)"            text,
    "Cash And Equivalents (-1FQ)"                      text,
    "Cash And Equivalents (-3FQ)"                      text,
    "Cash And Equivalents (-4FQ)"                      text,
    "Cash And Equivalents (-2FQ)"                      text,
    "Cash And Equivalents (-1FY)"                      text,
    "Cash And Equivalents (-2FY)"                      text,
    "Cash And Equivalents (-3FY)"                      text,
    "Cash And Equivalents (-4FY)"                      text,
    "Gross Intangible Assets (FQ)"                     text,
    "Gross Intangible Assets (-1FQ)"                   text,
    "Gross Intangible Assets (-3FQ)"                   text,
    "Gross Intangible Assets (-4FQ)"                   text,
    "Gross Intangible Assets (-2FQ)"                   text,
    "Gross Intangible Assets (-1FY)"                   text,
    "Gross Intangible Assets (-2FY)"                   text,
    "Gross Intangible Assets (-3FY)"                   text,
    "Gross Intangible Assets (-4FY)"                   text
);

alter table screening_us
    owner to postgres;

