create table screening_us
(
    ticker                                             text,
    isin                                               text,
    name                                               text,
    description                                        text,
    exchange                                           text,
    unit                                               text,
    sector                                             text,
    industry                                           text,
    "Last Updated"                                     text,
    "Income Statement Report Date"                     text,
    "Next Earnings"                                    text,
    "Style Class"                                      text,
    "Next Earnings (Status)"                           text,
    "Size Class"                                       text,
    region                                             text,
    country                                            text,
    "Trading Country"                                  text,
    "Market Cap"                                       double precision,
    "Enterprise Value"                                 double precision,
    "Last Price"                                       double precision,
    "Price Target (YTD Ago)"                           double precision,
    "Total Return (YTD)"                               double precision,
    "Price Target"                                     double precision,
    "Price Target - Low"                               double precision,
    "Price Target - Median"                            double precision,
    "Price Target - High"                              double precision,
    "Price Target - #"                                 double precision,
    "P/E (NTM)"                                        double precision,
    "P/E (LTM)"                                        double precision,
    "Altman Z-Score (FY)"                              double precision,
    "Altman Z-Score (FQ)"                              double precision,
    "Altman Z-Score (LTM)"                             double precision,
    "Beta (1Y)"                                        double precision,
    "Beta (2Y)"                                        double precision,
    "Beta (5Y)"                                        double precision,
    "Analyst Rating"                                   double precision,
    "# Strong Sell Ratings"                            integer,
    "# Strong Buys Ratings"                            integer,
    "# Hold Ratings"                                   integer,
    "# Buys Ratings"                                   integer,
    "# Sell Ratings"                                   integer,
    "Total Revenues/CAGR (5Y FY)"                      double precision,
    "Total Revenues (FQ)"                              double precision,
    "Total Revenues (-1FY)"                            double precision,
    "Total Revenues (FY)"                              double precision,
    "Total Revenues (LTM)"                             double precision,
    "Total Operating Expenses (LTM)"                   double precision,
    "P/TBV (LTM)"                                      double precision,
    "TBV (FY)"                                         double precision,
    "TBV (LTM)"                                        double precision,
    "Market Cap (Country R)"                           integer,
    "Tot. Return %/CAGR (3Y)"                          double precision,
    "Tot. Return %/CAGR (10Y)"                         double precision,
    "Total Return (5Y)"                                double precision,
    "Total Return (10Y)"                               double precision,
    "Net Income/Adj. (-1FY)"                           double precision,
    "CFF (LTM)"                                        double precision,
    "CFI (LTM)"                                        double precision,
    "FCF (LTM)"                                        double precision,
    "CFO (LTM)"                                        double precision,
    "EBITDA (FQ)"                                      double precision,
    "EBITDA (LTM)"                                     double precision,
    "EBITDA (FY)"                                      double precision,
    "EBITDA (-1FY)"                                    double precision,
    "EBITDA/Adj. (LTM)"                                double precision,
    "EBITDA/Adj. (FY)"                                 double precision,
    "EBITDA/Adj. (-1FY)"                               double precision,
    "EBIT (FQ)"                                        double precision,
    "EBIT (LTM)"                                       double precision,
    "EBIT (FY)"                                        double precision,
    "EBIT (-1FY)"                                      double precision,
    "EBIT/Adj. (-1FY)"                                 double precision,
    "EBIT/Adj. (FY)"                                   double precision,
    "EBIT/Adj. (LTM)"                                  double precision,
    "EBIT - Est Med (FY1E)"                            double precision,
    "EBIT - Est Med (NTM)"                             double precision,
    "Return On Equity % (LTM)"                         double precision,
    "Return On Equity % (FY)"                          double precision,
    "Net Income - (IS) (FY)"                           double precision,
    "Net Income - (IS) (LTM)"                          double precision,
    "Normalized Net Income (FY)"                       double precision,
    "Normalized Net Income (LTM)"                      double precision,
    "Net Income/Adj. (FY)"                             double precision,
    "Net Income/Adj. (LTM)"                            double precision,
    "Net Income Margin % (FY)"                         double precision,
    "Net Income Margin % (LTM)"                        double precision,
    "Volatility (1M)"                                  double precision,
    "Volatility (3M)"                                  double precision,
    "Volatility (6M)"                                  double precision,
    "Volatility (1Y)"                                  double precision,
    "Volume (Shrs)"                                    integer,
    "Dividend Per Share (LTM)"                         double precision,
    "Div Yield (Ind)"                                  double precision,
    "Div Yield (LTM)"                                  double precision,
    "Total Debt (FY)"                                  double precision,
    "Total Equity (FY)"                                double precision,
    "Total Equity (LTM)"                               double precision,
    "Total Debt (LTM)"                                 double precision,
    "Total Assets (LTM)"                               double precision,
    "Total Assets (FY)"                                double precision,
    "Current Ratio (FY)"                               double precision,
    "Current Ratio (LTM)"                              double precision,
    "Gross Profit Margin % (FY)"                       double precision,
    "Gross Profit Margin % (LTM)"                      double precision,
    "Asset Turnover (FY)"                              double precision,
    "Asset Turnover (LTM)"                             double precision,
    "Gross Profit (LTM)"                               double precision,
    "Gross Profit (FY)"                                double precision,
    "EPS Norm - Est Avg (NTM)"                         double precision,
    "EPS/Adj. (-1FY)"                                  double precision,
    "EPS/Adj. (FY)"                                    double precision,
    "EPS/Adj. (LTM)"                                   double precision,
    "EPS Norm - Est Avg (FY1E)"                        double precision,
    "Gain (Loss) On Sale Of Assets (LTM)"              text,
    "Cost Of Revenues (LTM)"                           double precision,
    "Cash Acquisitions (LTM)"                          double precision,
    "Cash Acquisitions (FY)"                           double precision,
    "Cash Acquisitions (-1FY)"                         double precision,
    "Inventory (LTM)"                                  double precision,
    "Goodwill (FQ)"                                    double precision,
    "Goodwill (LTM)"                                   double precision,
    "Goodwill (FY)"                                    double precision,
    "Goodwill (-1FY)"                                  double precision,
    "Impairment of Goodwill (FQ)"                      text,
    "Impairment of Goodwill (LTM)"                     text,
    "Impairment of Goodwill (-1FY)"                    text,
    "Impairment of Goodwill (FY)"                      text,
    "Operating Income (LTM)"                           double precision,
    "Asset Writedown (LTM)"                            text,
    "Asset Writedown (FY)"                             text,
    "Asset Writedown (-1FY)"                           text,
    "Operating Income (FY)"                            double precision,
    "Capital Expenditure (LTM)"                        double precision,
    "Capital Expenditure (-1FY)"                       double precision,
    "Capital Expenditure (FY)"                         double precision,
    "Retained Earnings (LTM)"                          double precision,
    "Total Current Assets (LTM)"                       double precision,
    "Total Current Liabilities (LTM)"                  double precision,
    "R&D Expenses (LTM)"                               double precision,
    "Restructuring Charges (LTM)"                      double precision,
    "Restructuring Charges (FQ)"                       text,
    "Restructuring Charges (-1FY)"                     text,
    "Restructuring Charges (FY)"                       double precision,
    "Interest Expense/Total (LTM)"                     double precision,
    "Merger & Restructuring Charges (LTM)"             double precision,
    "Working Capital (LTM)"                            double precision,
    "Other Unusual Items/Total (LTM)"                  text,
    "Interest Income On Investments (LTM)"             text,
    "Buyback Yield (LTM)"                              double precision,
    "Return on Assets (ROA) % (LTM)"                   double precision,
    "Return on Assets (ROA) % (FY)"                    double precision,
    "Net Income - (IS) (-1FY)"                         double precision,
    "Normalized Net Income (-1FY)"                     double precision,
    "CFF (FY)"                                         double precision,
    "CFF (-1FY)"                                       double precision,
    "CFI (FY)"                                         text,
    "CFI (-1FY)"                                       text,
    "CFO (FY)"                                         text,
    "CFO (-1FY)"                                       text,
    "Div Yield (-1FYInd)"                              text,
    "FCF (FY)"                                         text,
    "Capital Expenditure (FQ)"                         text,
    "Capital Expenditure (5YAVGFQ)"                    text,
    "CFF (FQ)"                                         text,
    "CFI (FQ)"                                         text,
    "CFO (FQ)"                                         text,
    "FCF (FQ)"                                         text,
    "Total Revenues (5YAVGFQ)"                         text,
    "EBITDA (5YAVGFQ)"                                 text,
    "EBIT (5YAVGFQ)"                                   text,
    "FCF (5YAVGFQ)"                                    text,
    "Cash Acquisitions (FQ)"                           text,
    "Cash Acquisitions (5YAVGFQ)"                      text,
    "Asset Writedown (FQ)"                             text,
    "Asset Writedown (5YAVGFQ)"                        text,
    "Impairment of Goodwill (5YAVGFQ)"                 text,
    "Operating Income (FQ)"                            text,
    "Operating Income (5YAVGFQ)"                       text,
    "P/B (LTM)"                                        text,
    "P/B (-1FY)"                                       text,
    "P/B (5YAVG)"                                      text,
    "Cash And Equivalents (LTM)"                       text,
    "Cash And Equivalents (FQ)"                        text,
    "Cash And Equivalents (FY)"                        text,
    "Cash And Equivalents (5YAVGFQ)"                   text,
    "Inventory (FQ)"                                   text,
    "Inventory (FY)"                                   text,
    "Goodwill (5YAVGFQ)"                               text,
    "Inventory (5YAVGFQ)"                              text,
    "Avg Employees (LTM)"                              text,
    "Avg Employees (FY)"                               text,
    "Avg Employees (5YAVGFY)"                          text,
    "Retained Earnings (FQ)"                           text,
    "Retained Earnings (FY)"                           text,
    "Retained Earnings (5YAVGFQ)"                      text,
    "Working Capital (FQ)"                             text,
    "Working Capital (FY)"                             text,
    "Working Capital (5YAVGFY)"                        text,
    "Div Yield (TTM)"                                  text,
    "Div Yield (NTM)"                                  text,
    "Div Yield (5YAVGLTM)"                             text,
    "Gross Intangible Assets (LTM)"                    text,
    "Gross Intangible Assets (FY)"                     text,
    "Gross Intangible Assets (5YAVGFQ)"                text,
    "Restructuring Charges (5YAVGFQ)"                  text,
    "Merger & Restructuring Charges (FQ)"              text,
    "Merger & Restructuring Charges (FY)"              text,
    "Merger & Restructuring Charges (5YAVGFQ)"         text,
    "Normalized Net Income (FQ)"                       text,
    "Normalized Net Income (5YAVGFQ)"                  text,
    "Net Income/Adj. (FQ)"                             text,
    "Net Income/Adj. (5YAVGFQ)"                        text,
    "Net Income - (IS) (FQ)"                           text,
    "Net Income - (IS) (5YAVGFQ)"                      text,
    "Net Income - (IS) (5YAVGLTM)"                     text,
    "Normalized Net Income (5YAVGLTM)"                 text,
    "EBITDA (5YAVGLTM)"                                text,
    "EBIT (5YAVGLTM)"                                  text,
    "Total Revenues (5YAVGLTM)"                        text,
    "Revenues - Est YoY % (FY1E)"                      text,
    "Price Chg. % (1M)"                                text,
    "Price Chg. % (3M)"                                text,
    "1-Day %"                                          text,
    "Price (5D Ago)"                                   text,
    "Price (1W Ago)"                                   text,
    "Price (1M Ago)"                                   text,
    "Price (3M Ago)"                                   text,
    "Price (6M Ago)"                                   text,
    "Price (1Y Ago)"                                   text,
    "Price (3Y Ago)"                                   text,
    "Price (5Y Ago)"                                   text,
    "Price (QTD Ago)"                                  text,
    "Rel. Volume"                                      text,
    "Shrs Out"                                         text,
    "Shrs Out (-1FY)"                                  text,
    "Common Dividends Paid (LTM)"                      text,
    "Common Dividends Paid (FY)"                       text,
    "Selling General & Admin Expenses/Total (FQ)"      text,
    "Selling General & Admin Expenses/Total (FY)"      text,
    "Selling General & Admin Expenses/Total (-1FY)"    text,
    "Selling General & Admin Expenses/Total (5YAVGFQ)" text,
    "Accounts Receivable/Total (FY)"                   text,
    "Accounts Receivable/Total (-1FY)"                 text,
    "Accounts Receivable/Total (5YAVGFQ)"              text,
    "Marketing Expenses (FQ)"                          text,
    "Marketing Expenses (FY)"                          text,
    "Marketing Expenses (-1FY)"                        text,
    "Marketing Expenses (5YAVGLTM)"                    text,
    "Revenues - Est Avg (NTM)"                         text,
    "Revenues - Est Avg (FY1E)"                        text,
    "Revenues - Est Med (NTM)"                         text,
    "Revenues - Est Med (FY1E)"                        text,
    "EV/Sales (EST FY1)"                               text,
    "EV/Sales (LTM)"                                   text,
    "EV/Sales (NTM)"                                   text,
    "EV/Sales (-1FYLTM)"                               text,
    "EV/Sales (-2FYLTM)"                               text,
    "EV/Sales (-3FYLTM)"                               text,
    "EV/Sales (3YAVGLTM)"                              text,
    "EV/Sales (-1FQLTM)"                               text,
    "EV/Sales (-2FQLTM)"                               text,
    "EV/Sales (-3FQLTM)"                               text,
    "EV/Sales (-4FQLTM)"                               text,
    "Total Employees (FY)"                             text,
    "Total Employees (FQ)"                             text,
    "52W High/Adj"                                     text,
    "52W Low/Adj"                                      text,
    "EMA (20D)"                                        text,
    "EMA (50D)"                                        text,
    "EMA (100D)"                                       text,
    "EMA (250D)"                                       text,
    "EV/EBITDA (LTM)"                                  text,
    "EV/EBITDA (NTM)"                                  text,
    "EV/EBITDA (-1FYLTM)"                              text,
    "EV/EBITDA (-1FQLTM)"                              text,
    "EV/EBITDA (3YAVGLTM)"                             text,
    "EV/EBITDA (EST FY1)"                              text,
    "P/E (EST FY1)"                                    text,
    "P/E (-1FYLTM)"                                    text,
    "P/E (-2FYLTM)"                                    text,
    "P/E (-3FYLTM)"                                    text,
    "P/E (3YAVGLTM)"                                   text,
    "P/E (-1FQLTM)"                                    text,
    "P/E (-2FQLTM)"                                    text,
    "P/E (-3FQLTM)"                                    text,
    "P/E (5YAVGLTM)"                                   text,
    "P/E (-0FQQoQLTM)"                                 text,
    "P/E (-0FYYoYLTM)"                                 text,
    "P/E (-1FYYoYLTM)"                                 text,
    "P/E (-0FQYoYLTM)"                                 text,
    "Dividend Record (Announce Date)"                  text,
    "Dividend Record (Ex Date)"                        text,
    "Dividend Record (Payable Date)"                   text,
    "Dividend Record (Record Date)"                    text,
    "Dividend Record (Frequency)"                      text,
    "Dividend Record (Currency)"                       text,
    "Dividend Record (Amount)"                         text,
    "Dividend Streak"                                  text
);

alter table screening_us
    owner to postgres;

