create table screening_csv
(
    ticker                                     text,
    isin                                       text,
    name                                       text,
    description                                text,
    region                                     text,
    country                                    text,
    "Trading Country"                          text,
    exchange                                   text,
    unit                                       text,
    sector                                     text,
    industry                                   text,
    "Style Class"                              text,
    "Size Class"                               text,
    "Last Updated"                             date,
    "Income Statement Report Date"             date,
    "FY End"                                   text,
    "Next Earnings"                            date,
    "Next Earnings (When)"                             text,
    "Next Earnings (Status)"                           text,
    "Dividend Record (Currency)"                       text,
    "Dividend Record (Amount)"                 double precision,
    "Dividend Record (Frequency)"                      text,
    "Dividend Streak"                          integer,
    "Dividend Record (Announce Date)"                  date,
    "Dividend Record (Payable Date)"                   date,
    "Dividend Record (Record Date)"                    date,
    "Dividend Record (Ex Date)"                        date,
    "Market Cap"                                       double precision,
    "Enterprise Value"                                 double precision,
    "Last Price"                                       double precision,
    "Price Target (YTD Ago)"                           double precision,
    "Total Return (YTD)"                       double precision,
    "Price Target"                             double precision,
    "Price Target - Low"                               double precision,
    "Price Target - Median"                    double precision,
    "Price Target - High"                              double precision,
    "Price Target - #"                         integer,
    "P/E (NTM)"                                double precision,
    "P/E (LTM)"                                double precision,
    "Altman Z-Score (FY)"                      double precision,
    "Altman Z-Score (FQ)"                      double precision,
    "Altman Z-Score (LTM)"                     double precision,
    "Beta (1Y)"                                double precision,
    "Beta (2Y)"                                double precision,
    "Beta (5Y)"                                double precision,
    "Analyst Rating"                           double precision,
    "# Strong Sell Ratings"                    integer,
    "# Strong Buys Ratings"                    integer,
    "# Hold Ratings"                           integer,
    "# Buys Ratings"                           integer,
    "# Sell Ratings"                           integer,
    "Total Revenues/CAGR (5Y FY)"              double precision,
    "Total Revenues (FQ)"                              double precision,
    "Total Revenues (-1FY)"                            double precision,
    "Total Revenues (FY)"                              double precision,
    "Total Revenues (LTM)"                             double precision,
    "Total Operating Expenses (LTM)"                   double precision,
    "P/TBV (LTM)"                              double precision,
    "TBV (FY)"                                 double precision,
    "TBV (LTM)"                                double precision,
    "Market Cap (Country R)"                   integer,
    "Tot. Return %/CAGR (3Y)"                  double precision,
    "Tot. Return %/CAGR (10Y)"                 double precision,
    "Total Return (5Y)"                        double precision,
    "Total Return (10Y)"                       double precision,
    "Net Income/Adj. (-1FY)"                           double precision,
    "CFF (LTM)"                                double precision,
    "CFI (LTM)"                                double precision,
    "FCF (LTM)"                                double precision,
    "CFO (LTM)"                                double precision,
    "EBITDA (FQ)"                                      double precision,
    "EBITDA (LTM)"                                     double precision,
    "EBITDA (FY)"                                      double precision,
    "EBITDA (-1FY)"                                    double precision,
    "EBITDA/Adj. (LTM)"                                double precision,
    "EBITDA/Adj. (FY)"                                 double precision,
    "EBITDA/Adj. (-1FY)"                               double precision,
    "EBIT (FQ)"                                        double precision,
    "EBIT (LTM)"                                       double precision,
    "EBIT (FY)"                                        double precision,
    "EBIT (-1FY)"                                      double precision,
    "EBIT/Adj. (-1FY)"                                 double precision,
    "EBIT/Adj. (FY)"                                   double precision,
    "EBIT/Adj. (LTM)"                                  double precision,
    "EBIT - Est Med (FY1E)"                            double precision,
    "EBIT - Est Med (NTM)"                             double precision,
    "Return On Equity % (LTM)"                 double precision,
    "Return On Equity % (FY)"                  double precision,
    "Net Income - (IS) (FY)"                           double precision,
    "Net Income - (IS) (LTM)"                          double precision,
    "Normalized Net Income (FY)"                       double precision,
    "Normalized Net Income (LTM)"                      double precision,
    "Net Income/Adj. (FY)"                             double precision,
    "Net Income/Adj. (LTM)"                            double precision,
    "Net Income Margin % (FY)"                 double precision,
    "Net Income Margin % (LTM)"                double precision,
    "Volatility (1M)"                          double precision,
    "Volatility (3M)"                          double precision,
    "Volatility (6M)"                          double precision,
    "Volatility (1Y)"                          double precision,
    "Volume (Shrs)"                            bigint,
    "Dividend Per Share (LTM)"                 double precision,
    "Div Yield (Ind)"                          double precision,
    "Div Yield (LTM)"                          double precision,
    "Total Debt (FY)"                          double precision,
    "Total Equity (FY)"                        double precision,
    "Total Equity (LTM)"                       double precision,
    "Total Debt (LTM)"                         double precision,
    "Total Assets (LTM)"                       double precision,
    "Total Assets (FY)"                        double precision,
    "Current Ratio (FY)"                       double precision,
    "Current Ratio (LTM)"                      double precision,
    "Gross Profit Margin % (FY)"               double precision,
    "Gross Profit Margin % (LTM)"              double precision,
    "Asset Turnover (FY)"                      double precision,
    "Asset Turnover (LTM)"                     double precision,
    "Gross Profit (LTM)"                               double precision,
    "Gross Profit (FY)"                                double precision,
    "EPS Norm - Est Avg (NTM)"                 double precision,
    "EPS/Adj. (-1FY)"                          double precision,
    "EPS/Adj. (FY)"                            double precision,
    "EPS/Adj. (LTM)"                           double precision,
    "EPS Norm - Est Avg (FY1E)"                double precision,
    "Gain (Loss) On Sale Of Assets (LTM)"      double precision,
    "Cost Of Revenues (LTM)"                           double precision,
    "Cash Acquisitions (LTM)"                  double precision,
    "Cash Acquisitions (FY)"                   double precision,
    "Cash Acquisitions (-1FY)"                 double precision,
    "Inventory (LTM)"                          double precision,
    "Goodwill (FQ)"                            double precision,
    "Goodwill (LTM)"                           double precision,
    "Goodwill (FY)"                            double precision,
    "Goodwill (-1FY)"                          double precision,
    "Impairment of Goodwill (FQ)"              double precision,
    "Impairment of Goodwill (LTM)"             double precision,
    "Impairment of Goodwill (-1FY)"            double precision,
    "Impairment of Goodwill (FY)"              double precision,
    "Operating Income (LTM)"                           double precision,
    "Asset Writedown (LTM)"                    double precision,
    "Asset Writedown (FY)"                     double precision,
    "Asset Writedown (-1FY)"                   double precision,
    "Operating Income (FY)"                            double precision,
    "Capital Expenditure (LTM)"                double precision,
    "Capital Expenditure (-1FY)"               double precision,
    "Capital Expenditure (FY)"                 double precision,
    "Retained Earnings (LTM)"                  double precision,
    "Total Current Assets (LTM)"               double precision,
    "Total Current Liabilities (LTM)"          double precision,
    "R&D Expenses (LTM)"                               double precision,
    "Restructuring Charges (LTM)"              double precision,
    "Restructuring Charges (FQ)"               double precision,
    "Restructuring Charges (-1FY)"             double precision,
    "Restructuring Charges (FY)"               double precision,
    "Interest Expense/Total (LTM)"                     double precision,
    "Merger & Restructuring Charges (LTM)"     double precision,
    "Working Capital (LTM)"                    double precision,
    "Other Unusual Items/Total (LTM)"          double precision,
    "Interest Income On Investments (LTM)"             double precision,
    "Buyback Yield (LTM)"                      double precision,
    "Return on Assets (ROA) % (LTM)"           double precision,
    "Return on Assets (ROA) % (FY)"            double precision,
    "Net Income - (IS) (-1FY)"                         double precision,
    "Normalized Net Income (-1FY)"                     double precision,
    "CFF (FY)"                                 double precision,
    "CFF (-1FY)"                               double precision,
    "CFI (FY)"                                 double precision,
    "CFI (-1FY)"                               double precision,
    "CFO (FY)"                                 double precision,
    "CFO (-1FY)"                               double precision,
    "Div Yield (-1FYInd)"                      double precision,
    "FCF (FY)"                                 double precision,
    "FCF (-1FY)"                               double precision,
    "Capital Expenditure (FQ)"                 double precision,
    "Capital Expenditure (5YAVGFQ)"            double precision,
    "CFF (FQ)"                                 double precision,
    "CFI (FQ)"                                 double precision,
    "CFO (FQ)"                                 double precision,
    "FCF (FQ)"                                 double precision,
    "Total Revenues (5YAVGFQ)"                         double precision,
    "EBITDA (5YAVGFQ)"                                 double precision,
    "EBIT (5YAVGFQ)"                                   double precision,
    "FCF (5YAVGFQ)"                            double precision,
    "Cash Acquisitions (FQ)"                   double precision,
    "Cash Acquisitions (5YAVGFQ)"              double precision,
    "Asset Writedown (FQ)"                     double precision,
    "Asset Writedown (5YAVGFQ)"                double precision,
    "Impairment of Goodwill (5YAVGFQ)"         double precision,
    "Operating Income (FQ)"                            double precision,
    "Operating Income (5YAVGFQ)"                       double precision,
    "P/B (LTM)"                                double precision,
    "P/B (-1FY)"                               double precision,
    "P/B (5YAVG)"                              double precision,
    "Cash And Equivalents (LTM)"               double precision,
    "Cash And Equivalents (FQ)"                double precision,
    "Cash And Equivalents (FY)"                double precision,
    "Cash And Equivalents (5YAVGFQ)"           double precision,
    "Inventory (FQ)"                           double precision,
    "Inventory (FY)"                           double precision,
    "Goodwill (5YAVGFQ)"                       double precision,
    "Inventory (5YAVGFQ)"                      double precision,
    "Retained Earnings (FQ)"                   double precision,
    "Retained Earnings (FY)"                   double precision,
    "Retained Earnings (5YAVGFQ)"              double precision,
    "Working Capital (FQ)"                     double precision,
    "Working Capital (FY)"                     double precision,
    "Working Capital (5YAVGFY)"                double precision,
    "Div Yield (TTM)"                          double precision,
    "Div Yield (NTM)"                          double precision,
    "Div Yield (5YAVGLTM)"                     double precision,
    "Gross Intangible Assets (LTM)"            double precision,
    "Gross Intangible Assets (FY)"             double precision,
    "Gross Intangible Assets (5YAVGFQ)"        double precision,
    "Restructuring Charges (5YAVGFQ)"          double precision,
    "Merger & Restructuring Charges (FQ)"      double precision,
    "Merger & Restructuring Charges (FY)"      double precision,
    "Merger & Restructuring Charges (5YAVGFQ)" double precision,
    "Normalized Net Income (FQ)"                       double precision,
    "Normalized Net Income (5YAVGFQ)"                  double precision,
    "Net Income/Adj. (FQ)"                             double precision,
    "Net Income/Adj. (5YAVGFQ)"                        double precision,
    "Net Income - (IS) (FQ)"                           double precision,
    "Net Income - (IS) (5YAVGFQ)"                      double precision,
    "Net Income - (IS) (5YAVGLTM)"                     double precision,
    "Normalized Net Income (5YAVGLTM)"                 double precision,
    "EBITDA (5YAVGLTM)"                                double precision,
    "EBIT (5YAVGLTM)"                                  double precision,
    "Total Revenues (5YAVGLTM)"                        double precision,
    "Revenues - Est YoY % (FY1E)"              double precision,
    "Price Chg. % (1M)"                        double precision,
    "Price Chg. % (3M)"                        double precision,
    "1-Day %"                                  double precision,
    "Price (5D Ago)"                           double precision,
    "Price (1W Ago)"                           double precision,
    "Price (1M Ago)"                           double precision,
    "Price (3M Ago)"                           double precision,
    "Price (6M Ago)"                           double precision,
    "Price (1Y Ago)"                           double precision,
    "Price (3Y Ago)"                           double precision,
    "Price (5Y Ago)"                           double precision,
    "Price (QTD Ago)"                          double precision,
    "Rel. Volume"                              double precision,
    "Shrs Out"                                 bigint,
    "Shrs Out (-1FY)"                          bigint,
    "Common Dividends Paid (LTM)"              double precision,
    "Common Dividends Paid (FY)"               double precision,
    "Selling General & Admin Expenses/Total (FQ)"      double precision,
    "Selling General & Admin Expenses/Total (FY)"      double precision,
    "Selling General & Admin Expenses/Total (-1FY)"    double precision,
    "Selling General & Admin Expenses/Total (5YAVGFQ)" double precision,
    "Accounts Receivable/Total (FY)"           double precision,
    "Accounts Receivable/Total (-1FY)"         double precision,
    "Accounts Receivable/Total (5YAVGFQ)"      double precision,
    "Marketing Expenses (FQ)"                          double precision,
    "Marketing Expenses (FY)"                          double precision,
    "Marketing Expenses (-1FY)"                        double precision,
    "Marketing Expenses (5YAVGLTM)"                    double precision,
    "Revenues - Est Avg (NTM)"                         double precision,
    "Revenues - Est Avg (FY1E)"                        double precision,
    "Revenues - Est Med (NTM)"                         double precision,
    "Revenues - Est Med (FY1E)"                        double precision,
    "EV/Sales (EST FY1)"                               double precision,
    "EV/Sales (LTM)"                                   double precision,
    "EV/Sales (NTM)"                                   double precision,
    "EV/Sales (-1FYLTM)"                               double precision,
    "EV/Sales (-2FYLTM)"                               double precision,
    "EV/Sales (-3FYLTM)"                               double precision,
    "EV/Sales (3YAVGLTM)"                              double precision,
    "EV/Sales (-1FQLTM)"                               double precision,
    "EV/Sales (-2FQLTM)"                               double precision,
    "EV/Sales (-3FQLTM)"                               double precision,
    "EV/Sales (-4FQLTM)"                               double precision,
    "52W High/Adj"                             double precision,
    "52W Low/Adj"                              double precision,
    "EMA (20D)"                                double precision,
    "EMA (50D)"                                double precision,
    "EMA (100D)"                               double precision,
    "EMA (250D)"                               double precision,
    "EV/EBITDA (LTM)"                                  double precision,
    "EV/EBITDA (NTM)"                                  double precision,
    "EV/EBITDA (-1FYLTM)"                              double precision,
    "EV/EBITDA (-1FQLTM)"                              double precision,
    "EV/EBITDA (3YAVGLTM)"                             double precision,
    "EV/EBITDA (EST FY1)"                              double precision,
    "P/E (EST FY1)"                                    double precision,
    "P/E (-1FYLTM)"                                    double precision,
    "P/E (-2FYLTM)"                                    double precision,
    "P/E (-3FYLTM)"                                    double precision,
    "P/E (3YAVGLTM)"                                   double precision,
    "P/E (-1FQLTM)"                                    double precision,
    "P/E (-2FQLTM)"                                    double precision,
    "P/E (-3FQLTM)"                                    double precision,
    "P/E (5YAVGLTM)"                                   double precision,
    "P/E (-0FQQoQLTM)"                                 double precision,
    "P/E (-0FYYoYLTM)"                                 double precision,
    "P/E (-1FYYoYLTM)"                                 double precision,
    "P/E (-0FQYoYLTM)"                                 double precision,
    "Full Time Employees (FQ)"                 integer,
    "Full Time Employees (FY)"                 integer,
    "Full Time Employees (-1FY)"               integer,
    "Full Time Employees (-2FY)"               integer,
    "Full Time Employees (-3FY)"               integer,
    "Avg Employees (5YAVGFY)"                  integer,
    "Net EPS - Basic (LTM)"                            double precision,
    "Net EPS - Basic (FQ)"                             double precision,
    "Net EPS - Basic (FY)"                             double precision,
    "Net EPS - Basic (-1FQFQ)"                         double precision,
    "Net EPS - Basic (-2FQFQ)"                         double precision,
    "Net EPS - Basic (-3FQFQ)"                         double precision,
    "Net EPS - Basic (-4FQFQ)"                         double precision,
    "Net EPS - Basic (-1FY)"                           double precision,
    "Net EPS - Basic (-2FY)"                           double precision,
    "Net EPS - Basic (-3FY)"                           double precision,
    "Net EPS - Basic (-4FY)"                           double precision,
    "Net EPS - Basic (-5FY)"                           double precision,
    "EPS Est Avg Rev % (FY1E - 1W)"                    double precision,
    "EPS Est Avg Rev % (FY1E - 1M)"                    double precision,
    "EPS Est Avg Rev % (FY1E - 3M)"                    double precision,
    "EPS Est Avg Rev % (FY1E - 6M)"                    double precision,
    "EPS Est Avg Rev % (FY1E - 1Y)"                    double precision,
    "Div Yield (-2FYInd)"                              double precision,
    "Div Yield (-3FYInd)"                              double precision,
    "Div Yield (-4FYInd)"                              double precision,
    "Div Yield (-5FYInd)"                              double precision,
    "EBITDA - Est Avg (NTM)"                   double precision,
    "EBITDA - Est Avg (FY1E)"                  double precision,
    "EPS GAAP - Est Avg (NTM)"                 double precision,
    "EPS GAAP - Est Avg (FY1E)"                double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 1M)"               double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 3M)"               double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 6M)"               double precision,
    "EPS GAAP Est Avg Rev % (FY1E - 1Y)"               double precision,
    "EPS Norm - Est # (FY1E)"                          integer,
    "CFO (-1FQFQ)"                             double precision,
    "CFO (-2FQFQ)"                             double precision,
    "CFO (-3FQFQ)"                             double precision,
    "CFO (-4FQFQ)"                             double precision,
    "CFI (-1FQFQ)"                             double precision,
    "CFI (-2FQFQ)"                             double precision,
    "CFI (-3FQFQ)"                             double precision,
    "CFI (-4FQFQ)"                             double precision,
    "CFI (-2FY)"                               double precision,
    "CFI (-3FY)"                               double precision,
    "CFI (-4FY)"                               double precision,
    "FCF (-1FQFQ)"                             double precision,
    "FCF (-2FQFQ)"                             double precision,
    "FCF (-3FQFQ)"                             double precision,
    "FCF (-4FQFQ)"                             double precision,
    "CFF (-2FY)"                               double precision,
    "CFF (-3FY)"                               double precision,
    "CFF (-4FY)"                               double precision,
    "CFF (-1FQFQ)"                             double precision,
    "CFF (-2FQFQ)"                             double precision,
    "CFF (-3FQFQ)"                             double precision,
    "CFF (-4FQFQ)"                             double precision,
    "CFO (-2FY)"                               double precision,
    "CFO (-3FY)"                               double precision,
    "CFO (-4FY)"                               double precision,
    "Cash Acquisitions (-1FQFQ)"               double precision,
    "Cash Acquisitions (-2FQFQ)"               double precision,
    "Cash Acquisitions (-3FQFQ)"               double precision,
    "Cash Acquisitions (-4FQFQ)"               double precision,
    "FCF (-2FY)"                               double precision,
    "FCF (-3FY)"                               double precision,
    "FCF (-4FY)"                               double precision,
    "Price Target (1W Ago)"                    double precision,
    "Price Target (1M Ago)"                    double precision,
    "Price Target (3M Ago)"                    double precision,
    "Price Target (6M Ago)"                    double precision,
    "Price Target (MTD Ago)"                   double precision,
    "Price Target (QTD Ago)"                   double precision,
    "Price Target (1Y Ago)"                    double precision,
    "Price Target - # (3M Ago)"                        integer,
    "Price Target - # (6M Ago)"                        integer,
    "Price Target - # (YTD Ago)"                       integer,
    "Price Target - # (1Y Ago)"                        integer,
    "Price Target - # (1W Ago)"                        integer,
    "Price Target - # (1M Ago)"                        integer,
    "Price Target - # (MTD Ago)"                       integer,
    "Price Target - # (QTD Ago)"                       integer,
    "Price Target - High (1W Ago)"             double precision,
    "Price Target - High (1M Ago)"             double precision,
    "Price Target - High (6M Ago)"             double precision,
    "Price Target - High (MTD Ago)"            double precision,
    "Price Target - High (3M Ago)"             double precision,
    "Price Target - High (QTD Ago)"            double precision,
    "Price Target - High (1Y Ago)"             double precision,
    "Price Target - High (YTD Ago)"            double precision,
    "Price Target - Low (1W Ago)"              double precision,
    "Price Target - Low (1M Ago)"              double precision,
    "Price Target - Low (3M Ago)"              double precision,
    "Price Target - Low (6M Ago)"              double precision,
    "Price Target - Low (MTD Ago)"             double precision,
    "Price Target - Low (QTD Ago)"             double precision,
    "Price Target - Low (YTD Ago)"             double precision,
    "Price Target - Low (1Y Ago)"              double precision,
    "Price Target - Median (1W Ago)"           double precision,
    "Price Target - Median (1M Ago)"           double precision,
    "Price Target - Median (3M Ago)"           double precision,
    "Price Target - Median (6M Ago)"           double precision,
    "Price Target - Median (MTD Ago)"          double precision,
    "Price Target - Median (QTD Ago)"          double precision,
    "Price Target - Median (YTD Ago)"          double precision,
    "Price Target - Median (1Y Ago)"           double precision,
    "Impairment of Goodwill (-1FQFQ)"                  double precision,
    "Impairment of Goodwill (-2FQFQ)"                  double precision,
    "Impairment of Goodwill (-3FQFQ)"                  double precision,
    "Impairment of Goodwill (-4FQFQ)"                  double precision,
    "Impairment of Goodwill (-2FY)"                    double precision,
    "Impairment of Goodwill (-3FY)"                    double precision,
    "Impairment of Goodwill (-4FY)"                    double precision,
    "Asset Writedown (-1FQFQ)"                         double precision,
    "Asset Writedown (-2FQFQ)"                         double precision,
    "Asset Writedown (-3FQFQ)"                         double precision,
    "Asset Writedown (-4FQFQ)"                         double precision,
    "Asset Writedown (-2FY)"                           double precision,
    "Asset Writedown (-3FY)"                           double precision,
    "Asset Writedown (-4FY)"                           double precision,
    "Asset Writedown (-5FY)"                           double precision,
    "Gain (Loss) On Sale Of Assets (FQ)"               double precision,
    "Gain (Loss) On Sale Of Assets (FY)"               double precision,
    "Gain (Loss) On Sale Of Assets (-1FQFQ)"           double precision,
    "Gain (Loss) On Sale Of Assets (-2FQFQ)"           double precision,
    "Gain (Loss) On Sale Of Assets (-3FQFQ)"           double precision,
    "Gain (Loss) On Sale Of Assets (-4FQFQ)"           double precision,
    "Gain (Loss) On Sale Of Assets (-1FY)"             double precision,
    "Gain (Loss) On Sale Of Assets (-2FY)"             double precision,
    "Gain (Loss) On Sale Of Assets (-3FY)"             double precision,
    "Gain (Loss) On Sale Of Assets (-4FY)"             double precision,
    "Restructuring Charges (-1FQFQ)"                   double precision,
    "Restructuring Charges (-2FQFQ)"                   double precision,
    "Restructuring Charges (-3FQFQ)"                   double precision,
    "Restructuring Charges (-4FQFQ)"                   double precision,
    "Restructuring Charges (-2FY)"                     double precision,
    "Restructuring Charges (-3FY)"                     double precision,
    "Restructuring Charges (-4FY)"                     double precision,
    "Net Income - (IS) (-1FQFQ)"                       double precision,
    "Net Income - (IS) (-2FQFQ)"                       double precision,
    "Net Income - (IS) (-3FQFQ)"                       double precision,
    "Net Income - (IS) (-4FQFQ)"                       double precision,
    "Net Income - (IS) (-2FY)"                         double precision,
    "Net Income - (IS) (-3FY)"                         double precision,
    "Net Income - (IS) (-4FY)"                         double precision,
    "Normalized Net Income (-1FQFQ)"                   double precision,
    "Normalized Net Income (-2FQFQ)"                   double precision,
    "Normalized Net Income (-3FQFQ)"                   double precision,
    "Normalized Net Income (-4FQFQ)"                   double precision,
    "Normalized Net Income (-2FY)"                     double precision,
    "Normalized Net Income (-3FY)"                     double precision,
    "Normalized Net Income (-4FY)"                     double precision,
    "Net Income/Adj. (-1FQFQ)"                         double precision,
    "Net Income/Adj. (-2FQFQ)"                         double precision,
    "Net Income/Adj. (-3FQFQ)"                         double precision,
    "Net Income/Adj. (-4FQFQ)"                         double precision,
    "Net Income/Adj. (-2FY)"                           double precision,
    "Net Income/Adj. (-3FY)"                           double precision,
    "Net Income/Adj. (-4FY)"                           double precision,
    "EBIT (-1FQFQ)"                                    double precision,
    "EBIT (-2FQFQ)"                                    double precision,
    "EBIT (-3FQFQ)"                                    double precision,
    "EBIT (-4FQFQ)"                                    double precision,
    "EBIT (-2FY)"                                      double precision,
    "EBIT (-3FY)"                                      double precision,
    "EBIT (-4FY)"                                      double precision,
    "EBIT/Adj. (FQ)"                                   double precision,
    "EBIT/Adj. (-1FQFQ)"                               double precision,
    "EBIT/Adj. (-2FQFQ)"                               double precision,
    "EBIT/Adj. (-3FQFQ)"                               double precision,
    "EBIT/Adj. (-4FQFQ)"                               double precision,
    "EBIT/Adj. (-2FY)"                                 double precision,
    "EBIT/Adj. (-3FY)"                                 double precision,
    "EBIT/Adj. (-4FY)"                                 double precision,
    "EBITDA (-1FQFQ)"                                  double precision,
    "EBITDA (-2FQFQ)"                                  double precision,
    "EBITDA (-3FQFQ)"                                  double precision,
    "EBITDA (-4FQFQ)"                                  double precision,
    "EBITDA (-2FY)"                                    double precision,
    "EBITDA (-4FY)"                                    double precision,
    "EBITDA (-3FY)"                                    double precision,
    "EBITDA/Adj. (FQ)"                                 double precision,
    "EBITDA/Adj. (-1FQFQ)"                             double precision,
    "EBITDA/Adj. (-2FQFQ)"                             double precision,
    "EBITDA/Adj. (-3FQFQ)"                             double precision,
    "EBITDA/Adj. (-4FQFQ)"                             double precision,
    "EBITDA/Adj. (-2FY)"                               double precision,
    "EBITDA/Adj. (-3FY)"                               double precision,
    "EBITDA/Adj. (-4FY)"                               double precision,
    "Basic EPS - Cont (LTM)"                           double precision,
    "Basic EPS - Cont (FQ)"                            double precision,
    "Basic EPS - Cont (FY)"                            double precision,
    "Basic EPS - Cont (-1FQFQ)"                        double precision,
    "Basic EPS - Cont (-2FQFQ)"                        double precision,
    "Basic EPS - Cont (-4FQFQ)"                        double precision,
    "Basic EPS - Cont (-3FQFQ)"                        double precision,
    "Basic EPS - Cont (-1FY)"                          double precision,
    "Basic EPS - Cont (-2FY)"                          double precision,
    "Basic EPS - Cont (-3FY)"                          double precision,
    "Basic EPS - Cont (-4FY)"                          double precision,
    "EPS/Adj. (FQ)"                                    double precision,
    "EPS/Adj. (-1FQFQ)"                                double precision,
    "EPS/Adj. (-3FQFQ)"                                double precision,
    "EPS/Adj. (-4FQFQ)"                                double precision,
    "EPS/Adj. (-2FQFQ)"                                double precision,
    "EPS/Adj. (-2FY)"                                  double precision,
    "EPS/Adj. (-3FY)"                                  double precision,
    "EPS/Adj. (-4FY)"                                  double precision
);

alter table screening_csv
    owner to postgres;

