create table analytics.balance_sheet_distributions
(
    assets_fq                  text,
    assets_fy                  text,
    assets_ltm                 text,
    assets_1fq                 text,
    assets_2fq                 text,
    assets_3fq                 text,
    assets_4fq                 text,
    assets_1fy                 text,
    assets_2fy                 text,
    assets_3fy                 text,
    assets_4fy                 text,
    assets_qoq_growth          text,
    assets_yoy_growth          text,
    assets_3y_cagr             text,
    asset_growth_accel         text,
    asset_base_stable          text,
    inventory_ltm              text,
    inventory_fq               text,
    inventory_fy               text,
    inventory_1fq              text,
    inventory_2fq              text,
    inventory_3fq              text,
    inventory_4fq              text,
    inventory_1fy              text,
    inventory_2fy              text,
    inventory_3fy              text,
    inventory_4fy              text,
    inventory_qoq_change       text,
    inventory_yoy_change       text,
    inventory_4q_trend         text,
    inventory_vs_5y_avg        text,
    inventory_days             text,
    inventory_turnover         text,
    inventory_to_revenue       text,
    inventory_to_assets        text,
    inventory_buildup_flag     text,
    inventory_reduction_flag   text,
    inventory_volatility       text,
    goodwill_fq                text,
    goodwill_ltm               text,
    goodwill_fy                text,
    goodwill_1fq               text,
    goodwill_2fq               text,
    goodwill_3fq               text,
    goodwill_4fq               text,
    goodwill_1fy               text,
    goodwill_2fy               text,
    goodwill_3fy               text,
    goodwill_4fy               text,
    goodwill_qoq_change        text,
    goodwill_yoy_change        text,
    goodwill_3y_growth         text,
    goodwill_vs_5y_avg         text,
    recent_acquisition_flag    text,
    goodwill_accumulation_rate text,
    goodwill_to_assets_trend   text,
    impairment_risk_score      text,
    goodwill_concentration     text
);

alter table analytics.balance_sheet_distributions
    owner to postgres;

