create table analytics.cost_structure_distributions
(
    cogs_to_revenue             text,
    opex_to_revenue             text,
    sga_to_revenue              text,
    rnd_to_revenue              text,
    interest_to_revenue         text,
    sga_trend_yoy               text,
    operating_leverage_proxy    text,
    cost_efficiency_score       text,
    marketing_to_revenue        text,
    marketing_trend_yoy         text,
    marketing_vs_5y_avg         text,
    sga_vs_5y_avg               text,
    sga_efficiency_trend        text,
    rnd_ltm                     text,
    rnd_fq                      text,
    rnd_fy                      text,
    rnd_1fqfq                   text,
    rnd_2fqfq                   text,
    rnd_3fqfq                   text,
    rnd_4fqfq                   text,
    rnd_1fy                     text,
    rnd_2fy                     text,
    rnd_3fy                     text,
    rnd_4fy                     text,
    rnd_intensity_ltm           text,
    rnd_intensity_fy            text,
    rnd_intensity_trend         text,
    rnd_qoq_growth              text,
    rnd_yoy_growth              text,
    rnd_cagr_3y                 text,
    rnd_per_employee            text,
    rnd_to_gross_profit         text,
    rnd_roi_proxy               text,
    rnd_increasing_flag         text,
    rnd_cut_flag                text,
    high_rnd_intensity_flag     text,
    interest_income_ltm         text,
    interest_expense_ltm        text,
    net_interest_income         text,
    interest_coverage_ratio     text,
    interest_income_to_revenue  text,
    interest_expense_to_revenue text,
    net_interest_margin_proxy   text
);

alter table analytics.cost_structure_distributions
    owner to postgres;

