create table analytics.credit_risk_analysis
(
    isin                              text,
    ticker                            text,
    name                              text,
    region                            text,
    country                           text,
    trading_country                   text,
    exchange                          text,
    sector                            text,
    industry                          text,
    dividend_record_frequency         text,
    earnings_report_frequency         text,
    fy_end                            text,
    next_earnings_report              text,
    next_earnings_status              text,
    next_earnings_when                text,
    next_fiscal_quarter               text,
    reporting_interval                double precision,
    size_class                        text,
    style_class                       text,
    unit                              text,
    dividend_record_announce_date     date,
    dividend_record_ex_date           date,
    dividend_record_payable_date      date,
    dividend_record_record_date       date,
    fy_end_date                       date,
    income_statement_report_date      date,
    last_updated                      date,
    next_earnings                     date,
    next_fy_end_date                  date,
    next_income_statement_report_date date,
    reference_date                    date,
    distress_probability              double precision,
    liquidity_stress_score            double precision,
    cash_runway_months                double precision,
    altman_z_score                    double precision,
    altman_z_trend                    double precision,
    interest_coverage                 double precision,
    quick_ratio                       double precision,
    risk_level                        text,
    ci_lower                          double precision,
    ci_upper                          double precision,
    data_quality_score                double precision
);

alter table analytics.credit_risk_analysis
    owner to postgres;

