create table analytics.earnings_distributions
(
    eps_surprise_pct                text,
    revenue_surprise_pct            text,
    eps_adjustment_ratio            text,
    gaap_adj_eps_gap_pct            text,
    ebitda_adjustment_ratio         text,
    eps_quarterly_trend             text,
    eps_yoy_growth                  text,
    eps_qoq_growth                  text,
    eps_yoy_quarterly               text,
    eps_positive_streak             text,
    eps_cagr_3y                     text,
    eps_cagr_5y                     text,
    eps_growth_accel                text,
    eps_vs_5y_avg                   text,
    eps_improvement_count           text,
    eps_trajectory_score            text,
    eps_stability                   text,
    eps_basic_fq                    text,
    eps_basic_ltm                   text,
    eps_basic_fy                    text,
    eps_adj_ltm                     text,
    eps_norm_est_fy1e               text,
    eps_growth_yoy_comp             text,
    eps_cagr_3y_comp                text,
    eps_adjustment_ratio_comp       text,
    eps_positive_years              text,
    eps_trajectory_score_comp       text,
    eps_cont_ltm                    text,
    eps_cont_fq                     text,
    eps_cont_fy                     text,
    eps_cont_1fqfq                  text,
    eps_cont_2fqfq                  text,
    eps_cont_3fqfq                  text,
    eps_cont_4fqfq                  text,
    eps_cont_1fy                    text,
    eps_cont_2fy                    text,
    eps_cont_3fy                    text,
    eps_cont_4fy                    text,
    eps_cont_qoq_growth             text,
    eps_cont_yoy_growth             text,
    eps_cont_cagr_3y                text,
    eps_cont_vs_total_eps           text,
    eps_cont_positive_streak        text,
    eps_cont_trajectory_score       text,
    discontinued_ops_impact         text,
    core_earnings_stability         text,
    eps_adjustment_spread_ltm       text,
    eps_adjustment_spread_fy        text,
    eps_adjustment_pct              text,
    net_income_adjustment_ratio_ltm text,
    net_income_adjustment_ratio_fy  text,
    net_income_adjustment_pct       text,
    ebitda_adjustment_pct_ltm       text,
    ebitda_adjustment_pct_fy        text,
    ebit_adjustment_pct_ltm         text,
    ebit_adjustment_pct_fy          text,
    earnings_quality_score          text,
    earnings_quality_warning        text,
    forward_eps_gaap_adj_spread     text,
    gaap_revision_momentum          text,
    gaap_revision_1m                text,
    gaap_revision_3m                text,
    gaap_revision_6m                text,
    gaap_revision_1y                text,
    gaap_vs_norm_revision_spread    text,
    gaap_revision_acceleration      text,
    gaap_positive_revision_flag     text,
    revision_quality_divergence     text
);

alter table analytics.earnings_distributions
    owner to postgres;

