create table analytics.earnings_probability_analysis
(
    isin                              text,
    ticker                            text,
    name                              text,
    region                            text,
    country                           text,
    trading_country                   text,
    exchange                          text,
    sector                            text,
    industry                          text,
    dividend_record_frequency         text,
    earnings_report_frequency         text,
    fy_end                            text,
    next_earnings_report              text,
    next_earnings_status              text,
    next_earnings_when                text,
    next_fiscal_quarter               text,
    reporting_interval                double precision,
    size_class                        text,
    style_class                       text,
    unit                              text,
    dividend_record_announce_date     date,
    dividend_record_ex_date           date,
    dividend_record_payable_date      date,
    dividend_record_record_date       date,
    fy_end_date                       date,
    income_statement_report_date      date,
    last_updated                      date,
    next_earnings                     date,
    next_fy_end_date                  date,
    next_income_statement_report_date date,
    reference_date                    date,
    historical_beats                  bigint,
    total_reports                     bigint,
    dynamic_total_reports             bigint,
    historical_beat_rate              double precision,
    prior_alpha                       double precision,
    prior_beta                        double precision,
    posterior_alpha                   double precision,
    posterior_beta                    double precision,
    posterior_beat_prob               double precision,
    posterior_std                     double precision,
    ci_90_lower                       double precision,
    ci_90_upper                       double precision,
    ci_95_lower                       double precision,
    ci_95_upper                       double precision,
    confidence_score                  double precision,
    prior_influence_pct               double precision,
    effective_sample_size             double precision,
    classification_confidence         text,
    beat_classification               text,
    gaap_revision_momentum            double precision,
    gaap_norm_spread                  double precision,
    revision_trend_short              double precision,
    revision_trend_medium             double precision,
    eps_norm_est_fy1e                 double precision,
    eps_norm_est_ntm                  double precision,
    eps_gaap_est_ntm                  double precision,
    eps_gaap_est_fy1e                 double precision,
    analyst_count                     bigint,
    quarterly_beat_streak             bigint,
    data_source                       text,
    current_streak                    bigint,
    streak_type                       text,
    continuation_probability          double precision,
    mean_reversion_probability        double precision,
    expected_next_outcome             text,
    prediction_confidence             double precision,
    base_posterior_mean               double precision,
    resampled_posterior_mean          double precision,
    technical_adjustment              double precision,
    momentum_signal                   double precision,
    volatility_regime_score           double precision,
    credible_interval_90              text,
    credible_interval_95              text,
    prob_beat_given_momentum          double precision,
    earnings_season_flag              bigint,
    pre_earnings_window               bigint,
    ess_bulk                          double precision,
    r_hat                             double precision,
    eps_positive_streak               bigint,
    model_confidence                  double precision,
    map_estimate                      double precision
);

alter table analytics.earnings_probability_analysis
    owner to postgres;

