create table analytics.eps_streak_analysis
(
    isin                              text,
    ticker                            text,
    name                              text,
    region                            text,
    country                           text,
    trading_country                   text,
    exchange                          text,
    sector                            text,
    industry                          text,
    dividend_record_frequency         text,
    earnings_report_frequency         text,
    fy_end                            text,
    next_earnings_report              text,
    next_earnings_status              text,
    next_earnings_when                text,
    next_fiscal_quarter               text,
    reporting_interval                double precision,
    size_class                        text,
    style_class                       text,
    unit                              text,
    dividend_record_announce_date     date,
    dividend_record_ex_date           date,
    dividend_record_payable_date      date,
    dividend_record_record_date       date,
    fy_end_date                       date,
    income_statement_report_date      date,
    last_updated                      date,
    next_earnings                     date,
    next_fy_end_date                  date,
    next_income_statement_report_date date,
    reference_date                    date,
    current_streak                    bigint,
    streak_type                       text,
    continuation_probability          double precision,
    mean_reversion_probability        double precision,
    expected_next_outcome             text,
    prediction_confidence             double precision,
    dynamic_total_reports             bigint,
    historical_beat_rate              double precision,
    gaap_revision_momentum            text
);

alter table analytics.eps_streak_analysis
    owner to postgres;

