create table analytics.expected_returns_summary
(
    isin                              text,
    ticker                            text,
    name                              text,
    region                            text,
    country                           text,
    trading_country                   text,
    exchange                          text,
    sector                            text,
    industry                          text,
    dividend_record_frequency         text,
    earnings_report_frequency         text,
    fy_end                            text,
    next_earnings_report              text,
    next_earnings_status              text,
    next_earnings_when                text,
    next_fiscal_quarter               text,
    reporting_interval                double precision,
    size_class                        text,
    style_class                       text,
    unit                              text,
    dividend_record_announce_date     date,
    dividend_record_ex_date           date,
    dividend_record_payable_date      date,
    dividend_record_record_date       date,
    fy_end_date                       date,
    income_statement_report_date      date,
    last_updated                      date,
    next_earnings                     date,
    next_fy_end_date                  date,
    next_income_statement_report_date date,
    reference_date                    date,
    enterprise_value                  double precision,
    volume_shrs                       double precision,
    market_cap                        double precision,
    price_target_high                 double precision,
    price_target_low                  double precision,
    price_target                      double precision,
    expected_upside_pct               double precision,
    price_target_median               double precision,
    prob_positive_upside              double precision,
    shares_outstanding                double precision,
    last_price                        double precision,
    filtered_upside                   double precision,
    expected_return_prob_weighted     double precision,
    achievement_probability           double precision,
    confidence_level                  text,
    posterior_beat_prob               double precision,
    confidence_score                  double precision,
    beat_classification               text,
    mc_bullish                        boolean,
    kal_bullish                       boolean,
    pt_bullish                        boolean,
    earn_bullish                      boolean,
    agreement_score                   bigint,
    signal                            text
);

alter table analytics.expected_returns_summary
    owner to postgres;

