create table analytics.expected_returns_summary
(
    isin                                     text,
    ticker                                   text,
    name                                     text,
    region                                   text,
    country                                  text,
    trading_country                          text,
    exchange                                 text,
    sector                                   text,
    industry                                 text,
    dividend_record_frequency                text,
    earnings_report_frequency                text,
    fy_end                                   text,
    next_earnings_report                     text,
    next_earnings_status                     text,
    next_earnings_when                       text,
    next_fiscal_quarter                      text,
    reporting_interval                       double precision,
    size_class                               text,
    style_class                              text,
    unit                                     text,
    dividend_record_announce_date            date,
    dividend_record_ex_date                  date,
    dividend_record_payable_date             date,
    dividend_record_record_date              date,
    fy_end_date                              date,
    income_statement_report_date             date,
    last_updated                             date,
    next_earnings                            date,
    next_fy_end_date                         date,
    next_income_statement_report_date        date,
    reference_date                           date,
    prob_positive_upside                     double precision,
    price_target_mc                          double precision,
    expected_upside_pct                      double precision,
    last_price                               double precision,
    risk_reward_ratio                        double precision,
    var_5_pct                                double precision,
    filtered_upside                          double precision,
    kalman_estimate                          double precision,
    expected_return_prob_weighted            double precision,
    price_target_prob_weighted               double precision,
    achievement_probability                  double precision,
    confidence_level                         text,
    analyst_conviction                       double precision,
    eps_revision_momentum                    double precision,
    analyst_rating_normalized                double precision,
    posterior_beat_prob                      double precision,
    confidence_score                         double precision,
    beat_classification                      text,
    exceptional_items_frequency_anomaly_flag boolean,
    gaap_adj_eps_gap_pct_anomaly_flag        boolean,
    asset_sale_boost_anomaly_flag            boolean,
    ebitda_adjustment_ratio_anomaly_flag     boolean,
    eps_adjustment_ratio_anomaly_flag        boolean,
    exceptional_items_to_ebitda_anomaly_flag boolean,
    restructuring_intensity_anomaly_flag     boolean,
    goodwill_change_rate_anomaly_flag        boolean,
    accounting_anomaly_score                 double precision,
    sector_relative_anomaly                  double precision,
    anomaly_feature_count                    bigint,
    accounting_anomaly_tier                  text,
    anomaly_severity_score                   double precision,
    anomaly_risk_rank                        double precision,
    sector_anomaly_percentile                double precision,
    multi_flag_alert                         boolean,
    market_cap                               double precision,
    enterprise_value                         double precision,
    price_target                             double precision,
    price_target_high                        double precision,
    price_target_low                         double precision,
    price_target_median                      double precision,
    volume_shrs                              double precision,
    shares_outstanding                       double precision,
    mc_bullish                               boolean,
    kal_bullish                              boolean,
    pt_bullish                               boolean,
    earn_bullish                             boolean,
    agreement_score                          bigint,
    signal                                   text,
    weighted_agreement                       double precision,
    composite_score                          double precision,
    quality_tier                             text,
    expected_upside_pct_zscore               double precision,
    filtered_upside_zscore                   double precision,
    expected_return_prob_weighted_zscore     double precision,
    expected_upside_pct_pctile               double precision,
    filtered_upside_pctile                   double precision,
    expected_return_prob_weighted_pctile     double precision
);

alter table analytics.expected_returns_summary
    owner to postgres;

