create table analytics.growth_distributions
(
    revenue_growth_yoy          text,
    ebitda_growth_yoy           text,
    operating_income_growth     text,
    fcf_growth                  text,
    revenue_cagr_5y             text,
    forward_revenue_growth      text,
    revenue_vs_5y_avg           text,
    revenue_est_spread          text,
    revenue_beat_potential      text,
    revenue_est_revision_trend  text,
    ebitda_est_vs_actual        text,
    forward_revenue_multiple    text,
    revenue_estimate_count      text,
    revenue_guidance_gap        text,
    consensus_revenue_growth    text,
    ebit_estimate_spread        text,
    forward_ebitda_margin       text,
    revenue_acceleration        text,
    estimate_confidence_score   text,
    revenue_est_avg_fy1e        text,
    revenue_est_med_fy1e        text,
    revenue_est_avg_ntm         text,
    revenue_est_med_ntm         text,
    revenue_avg_med_diff_pct    text,
    revenue_consensus_strength  text,
    revenue_revision_trend_rec  text,
    revenue_vs_current          text,
    revenue_fq                  text,
    revenue_fy                  text,
    revenue_ltm                 text,
    revenue_5y_avg              text,
    revenue_1fqfq               text,
    revenue_2fqfq               text,
    revenue_3fqfq               text,
    revenue_4fqfq               text,
    revenue_1fy                 text,
    revenue_2fy                 text,
    revenue_3fy                 text,
    revenue_4fy                 text,
    revenue_qoq_growth          text,
    revenue_qoq_2q              text,
    revenue_qoq_3q              text,
    revenue_qoq_4q              text,
    revenue_yoy_quarterly       text,
    revenue_2y_growth           text,
    revenue_3y_growth           text,
    revenue_4y_growth           text,
    revenue_cagr_3y             text,
    revenue_cagr_4y             text,
    revenue_4q_trend            text,
    revenue_4q_avg              text,
    revenue_fq_vs_4q_avg        text,
    revenue_growth_flag         text,
    revenue_stability_score     text,
    revenue_accelerating_flag   text,
    revenue_positive_qoq_streak text,
    revenue_5yavgfq             text,
    revenue_5yavgltm            text,
    revenue_vs_5y_avg_fq        text,
    revenue_vs_5y_avg_ltm       text,
    revenue_fq_vs_avg           text,
    revenue_momentum            text
);

alter table analytics.growth_distributions
    owner to postgres;

