create table analytics.leverage_liquidity_distributions
(
    debt_to_equity            text,
    debt_to_assets            text,
    equity_ratio              text,
    interest_coverage         text,
    current_ratio             text,
    cash_ratio                text,
    working_capital_ratio     text,
    asset_turnover            text,
    inventory_turnover        text,
    receivables_days          text,
    working_capital_turns     text,
    cash_to_assets_pct        text,
    cash_change_qoq           text,
    cash_vs_5y_avg            text,
    inventory_change_yoy      text,
    inventory_vs_5y_avg       text,
    receivables_change_yoy    text,
    receivables_vs_5y_avg     text,
    working_capital_vs_5y_avg text,
    retained_earnings_vs_5y   text,
    intangibles_growth_flag   text,
    asset_quality_score       text,
    balance_sheet_strength    text,
    debt_maturity_risk        text,
    wc_fq                     text,
    wc_fy                     text,
    wc_ltm                    text,
    wc_5yavgfy                text,
    wc_1fq                    text,
    wc_2fq                    text,
    wc_3fq                    text,
    wc_4fq                    text,
    wc_1fy                    text,
    wc_2fy                    text,
    wc_3fy                    text,
    wc_4fy                    text,
    wc_qoq_change             text,
    wc_yoy_change             text,
    wc_4q_trend               text,
    wc_vs_5y_avg              text,
    wc_positive_quarters      text,
    wc_improving_flag         text,
    wc_volatility             text,
    debt_fq                   text,
    debt_fy                   text,
    debt_ltm                  text,
    debt_1fq                  text,
    debt_2fq                  text,
    debt_3fq                  text,
    debt_4fq                  text,
    debt_1fy                  text,
    debt_2fy                  text,
    debt_3fy                  text,
    debt_4fy                  text,
    debt_qoq_change           text,
    debt_yoy_change           text,
    debt_4q_trend             text,
    debt_3y_cagr              text,
    debt_deleveraging         text,
    debt_to_equity_trend      text,
    wc_ltm_deep               text,
    wc_fq_deep                text,
    wc_fy_deep                text,
    wc_to_revenue             text,
    wc_to_assets              text,
    wc_change_qoq_deep        text,
    wc_change_yoy_deep        text,
    days_working_capital      text,
    wc_efficiency_score       text,
    negative_wc_flag          text,
    wc_improvement_flag_deep  text
);

alter table analytics.leverage_liquidity_distributions
    owner to postgres;

