create table analytics.monte_carlo_simulation
(
    dividend_record_announce_date     date,
    ticker                            text,
    exchange                          text,
    income_statement_report_date      date,
    reference_date                    date,
    dividend_record_ex_date           date,
    dividend_record_record_date       date,
    trading_country                   text,
    industry                          text,
    style_class                       text,
    unit                              text,
    isin                              text,
    sector                            text,
    size_class                        text,
    reporting_interval                double precision,
    name                              text,
    country                           text,
    next_earnings                     date,
    dividend_record_frequency         text,
    next_earnings_report              text,
    next_earnings_status              text,
    next_fy_end_date                  date,
    next_fiscal_quarter               text,
    earnings_report_frequency         text,
    last_updated                      date,
    fy_end                            text,
    region                            text,
    next_income_statement_report_date date,
    fy_end_date                       date,
    next_earnings_when                text,
    dividend_record_payable_date      date,
    market_cap                        double precision,
    enterprise_value                  double precision,
    last_price                        double precision,
    price_target                      double precision,
    price_target_high                 double precision,
    price_target_low                  double precision,
    price_target_median               double precision,
    shares_outstanding                double precision,
    pt_median                         double precision,
    pt_spread                         double precision,
    expected_upside_pct               double precision,
    upside_std                        double precision,
    var_5_pct                         double precision,
    prob_positive_upside              double precision,
    risk_reward_ratio                 double precision,
    volume_shrs                       double precision
);

alter table analytics.monte_carlo_simulation
    owner to postgres;

