create table analytics.price_target_achievement
(
    isin                              text,
    ticker                            text,
    name                              text,
    region                            text,
    country                           text,
    trading_country                   text,
    exchange                          text,
    sector                            text,
    industry                          text,
    dividend_record_frequency         text,
    earnings_report_frequency         text,
    fy_end                            text,
    next_earnings_report              text,
    next_earnings_status              text,
    next_earnings_when                text,
    next_fiscal_quarter               text,
    reporting_interval                double precision,
    size_class                        text,
    style_class                       text,
    unit                              text,
    dividend_record_announce_date     date,
    dividend_record_ex_date           date,
    dividend_record_payable_date      date,
    dividend_record_record_date       date,
    fy_end_date                       date,
    income_statement_report_date      date,
    last_updated                      date,
    next_earnings                     date,
    next_fy_end_date                  date,
    next_income_statement_report_date date,
    reference_date                    date,
    achievement_probability           double precision,
    upside_potential                  double precision,
    price_target_spread_pct           double precision,
    analyst_conviction                double precision,
    eps_revision_momentum             double precision,
    analyst_rating_normalized         double precision,
    expected_return_prob_weighted     double precision,
    confidence_level                  text,
    last_price                        double precision,
    price_target_prob_weighted        double precision
);

alter table analytics.price_target_achievement
    owner to postgres;

