create table analytics.profitability_distributions
(
    roe                    text,
    roa                    text,
    gross_margin_pct       text,
    operating_margin_pct   text,
    net_margin_pct         text,
    ebitda_margin_pct      text,
    roic                   text,
    rnd_intensity          text,
    equity_multiplier      text,
    gross_margin_trend_yoy text,
    operating_margin_trend text,
    net_margin_trend_yoy   text,
    ebitda_margin_trend    text,
    margin_expansion_flag  text,
    margin_stability_score text,
    ebit_fq                text,
    ebit_ltm               text,
    ebit_fy                text,
    ebit_1fy               text,
    ebit_2fy               text,
    ebit_3fy               text,
    ebit_4fy               text,
    ebitda_fq              text,
    ebitda_ltm             text,
    ebitda_fy              text,
    ebitda_1fy             text,
    ebitda_2fy             text,
    ebitda_3fy             text,
    ebitda_4fy             text,
    ebit_5yavgfq           text,
    ebit_5yavgltm          text,
    ebitda_5yavgfq         text,
    ebitda_5yavgltm        text,
    ebit_adj_fq            text,
    ebit_adj_ltm           text,
    ebit_adj_fy            text,
    ebitda_adj_fq          text,
    ebitda_adj_ltm         text,
    ebitda_adj_fy          text,
    ebit_growth_yoy        text,
    ebitda_growth_yoy      text,
    ebit_margin_ltm        text,
    ebitda_margin_ltm      text,
    ebit_positive_years    text,
    ebitda_positive_years  text,
    ebit_qoq_growth        text,
    ebitda_qoq_growth      text,
    ebit_cagr_3y           text,
    ebitda_cagr_3y         text,
    ebit_vs_5y_avg         text,
    ebitda_vs_5y_avg       text,
    gp_fq                  text,
    gp_fy                  text,
    gp_ltm                 text,
    gp_1fqfq               text,
    gp_2fqfq               text,
    gp_3fqfq               text,
    gp_4fqfq               text,
    gp_1fy                 text,
    gp_2fy                 text,
    gp_3fy                 text,
    gp_4fy                 text,
    gp_qoq_growth          text,
    gp_yoy_growth          text,
    gp_margin_fq           text,
    gp_margin_trend        text,
    gp_positive_quarters   text,
    gp_margin_expansion    text
);

alter table analytics.profitability_distributions
    owner to postgres;

