create table analytics.quality_risk_distributions
(
    has_goodwill_impairment          text,
    has_asset_writedown              text,
    has_restructuring                text,
    goodwill_to_assets_pct           text,
    intangible_intensity             text,
    exceptional_items_to_ebitda      text,
    altman_z_score                   text,
    altman_z_trend                   text,
    current_ratio                    text,
    quick_ratio                      text,
    beta_1y                          text,
    beta_5y                          text,
    beta_spread                      text,
    beta_trend                       text,
    high_beta_flag                   text,
    low_beta_flag                    text,
    beta_stability_score             text,
    distress_risk_score              text,
    liquidity_stress_score           text,
    working_capital_trend            text,
    cash_runway_months               text,
    combined_distress_score          text,
    wc_deteriorating_flag            text,
    retained_earnings_growth         text,
    accumulated_deficit_flag         text,
    adequate_cash_buffer             text,
    goodwill_change_rate             text,
    restructuring_intensity          text,
    exceptional_items_frequency      text,
    merger_impact_ratio              text,
    non_operating_income_share       text,
    asset_sale_boost                 text,
    accounting_quality_score         text,
    goodwill_impairment_ltm          text,
    asset_writedown_ltm              text,
    restructuring_ltm                text,
    has_goodwill_impairment_ltm      text,
    goodwill_impairment_frequency    text,
    asset_writedown_frequency        text,
    restructuring_frequency          text,
    exceptional_items_total_ltm      text,
    exceptional_items_to_ebitda_comp text,
    quality_issues_count_5y          text,
    accounting_quality_score_comp    text
);

alter table analytics.quality_risk_distributions
    owner to postgres;

