create table analytics.sector_relative_ranking
(
    isin                              text,
    ticker                            text,
    name                              text,
    region                            text,
    country                           text,
    trading_country                   text,
    exchange                          text,
    sector                            text,
    industry                          text,
    dividend_record_frequency         text,
    earnings_report_frequency         text,
    fy_end                            text,
    next_earnings_report              text,
    next_earnings_status              text,
    next_earnings_when                text,
    next_fiscal_quarter               text,
    reporting_interval                double precision,
    size_class                        text,
    style_class                       text,
    unit                              text,
    dividend_record_announce_date     date,
    dividend_record_ex_date           date,
    dividend_record_payable_date      date,
    dividend_record_record_date       date,
    fy_end_date                       date,
    income_statement_report_date      date,
    last_updated                      date,
    next_earnings                     date,
    next_fy_end_date                  date,
    next_income_statement_report_date date,
    reference_date                    date,
    analyst_bullish_pct               double precision,
    analyst_bearish_pct               double precision,
    analyst_neutral_pct               double precision,
    analyst_conviction                double precision,
    upside_potential                  double precision,
    price_target_spread_pct           double precision,
    price_target_revision_1m          double precision,
    price_target_revision_3m          double precision,
    eps_revision_momentum             double precision,
    analyst_rating_normalized         double precision,
    analyst_coverage_quality          double precision,
    pt_momentum_1w                    double precision,
    pt_momentum_1m                    double precision,
    pt_momentum_3m                    double precision,
    pt_momentum_6m                    double precision,
    pt_momentum_1y                    double precision,
    pt_median_momentum_1m             double precision,
    pt_median_momentum_3m             double precision,
    pt_acceleration_short             double precision,
    pt_acceleration_long              double precision,
    pt_consensus_convergence          double precision,
    analyst_coverage_change_1m        bigint,
    analyst_coverage_change_3m        bigint,
    analyst_coverage_change_1y        bigint,
    pt_vs_price_momentum              double precision,
    analyst_coverage_trend            double precision,
    assets_fq                         double precision,
    assets_fy                         double precision,
    assets_ltm                        double precision,
    assets_1fq                        double precision,
    assets_2fq                        double precision,
    assets_3fq                        double precision,
    assets_4fq                        double precision,
    assets_1fy                        double precision,
    assets_2fy                        double precision,
    assets_3fy                        double precision,
    assets_4fy                        double precision,
    assets_qoq_growth                 double precision,
    assets_yoy_growth                 double precision,
    assets_3y_cagr                    double precision,
    asset_growth_accel                double precision,
    asset_base_stable                 bigint,
    inventory_ltm                     double precision,
    inventory_fq                      double precision,
    inventory_fy                      double precision,
    inventory_1fq                     double precision,
    inventory_2fq                     double precision,
    inventory_3fq                     double precision,
    inventory_4fq                     double precision,
    inventory_1fy                     double precision,
    inventory_2fy                     double precision,
    inventory_3fy                     double precision,
    inventory_4fy                     double precision,
    inventory_qoq_change              double precision,
    inventory_yoy_change              double precision,
    inventory_4q_trend                double precision,
    inventory_vs_5y_avg               double precision,
    inventory_days                    double precision,
    inventory_turnover                double precision,
    inventory_to_revenue              double precision,
    inventory_to_assets               double precision,
    inventory_buildup_flag            bigint,
    inventory_reduction_flag          bigint,
    inventory_volatility              double precision,
    goodwill_fq                       double precision,
    goodwill_ltm                      double precision,
    goodwill_fy                       double precision,
    goodwill_1fq                      double precision,
    goodwill_2fq                      double precision,
    goodwill_3fq                      double precision,
    goodwill_4fq                      double precision,
    goodwill_1fy                      double precision,
    goodwill_2fy                      double precision,
    goodwill_3fy                      double precision,
    goodwill_4fy                      double precision,
    goodwill_qoq_change               double precision,
    goodwill_yoy_change               double precision,
    goodwill_3y_growth                double precision,
    goodwill_vs_5y_avg                double precision,
    recent_acquisition_flag           bigint,
    goodwill_accumulation_rate        double precision,
    goodwill_to_assets_trend          double precision,
    impairment_risk_score             double precision,
    goodwill_concentration            double precision,
    cfo_to_net_income                 double precision,
    fcf_to_net_income                 double precision,
    fcf_margin                        double precision,
    cfo_growth_yoy                    double precision,
    fcf_positive_ratio                double precision,
    acquisition_intensity             double precision,
    self_funding_ratio                double precision,
    fcf_positive_years                bigint,
    fcf_always_positive               bigint,
    capex_vs_5y_avg                   double precision,
    underinvestment_flag              bigint,
    cfo_share_of_cf                   double precision,
    cfi_share_of_cf                   double precision,
    cff_share_of_cf                   double precision,
    self_funding_flag                 bigint,
    acquisition_to_fcf                double precision,
    sustainable_ma_flag               bigint,
    fcf_4q_improvement                double precision,
    cash_flow_quality_score           double precision,
    capex_yoy_growth                  double precision,
    capex_qoq_growth                  double precision,
    capex_3y_trend                    double precision,
    capex_volatility                  double precision,
    capex_acceleration                bigint,
    capex_cut_flag                    bigint,
    overinvestment_flag               bigint,
    acquisitions_yoy_growth           double precision,
    acquisitions_vs_5y_avg            double precision,
    acquisitions_ltm_total            double precision,
    ma_intensity_score                double precision,
    serial_acquirer_flag              bigint,
    acquisition_pause_flag            bigint,
    total_investment_to_cfo           double precision,
    organic_vs_inorganic              double precision,
    investment_efficiency             double precision,
    cfo_quarterly_trend               double precision,
    cfo_yoy_quarterly                 double precision,
    cfi_quarterly_trend               double precision,
    cff_quarterly_trend               double precision,
    fcf_quarterly_trend               double precision,
    cfo_positive_quarters             bigint,
    cfi_negative_quarters             bigint,
    cff_pattern_score                 double precision,
    cash_burn_rate                    double precision,
    cf_volatility_score               double precision,
    operating_cf_momentum             double precision,
    financing_dependency              double precision,
    cfo_fq                            double precision,
    cfo_ltm                           double precision,
    cfo_fy                            double precision,
    fcf_fq                            double precision,
    fcf_ltm                           double precision,
    fcf_fy                            double precision,
    cfo_growth_yoy_comp               double precision,
    fcf_growth_yoy                    double precision,
    cfo_to_net_income_comp            double precision,
    fcf_margin_comp                   double precision,
    fcf_yield                         double precision,
    cfo_positive_years                bigint,
    fcf_positive_years_comp           bigint,
    cash_flow_quality_score_comp      double precision,
    fcf_est_fy1                       double precision,
    fcf_est_fy2                       double precision,
    fcf_est_fy3                       double precision,
    fcf_est_fy4                       double precision,
    fcf_est_fy5                       double precision,
    fcf_est_growth_fy1_vs_ltm         double precision,
    fcf_est_growth_fy2_vs_fy1         double precision,
    fcf_est_growth_fy3_vs_fy2         double precision,
    fcf_est_growth_fy4_vs_fy3         double precision,
    fcf_est_growth_fy5_vs_fy4         double precision,
    fcf_est_cagr_3y                   double precision,
    fcf_est_cagr_5y                   double precision,
    fcf_est_margin_fy1                double precision,
    fcf_est_yield_fy1                 double precision,
    fcf_est_growth_acceleration       double precision,
    fcf_est_growth_deceleration       bigint,
    fcf_est_trajectory_score          double precision,
    fcf_est_always_positive           bigint,
    fcf_est_vs_historical             double precision,
    fcf_est_capex_implied_ratio       double precision,
    piotroski_f_score                 bigint,
    eps_trajectory_score              double precision,
    dilution_score                    double precision,
    quality_momentum_score            double precision,
    net_income_is_fq                  double precision,
    net_income_is_ltm                 double precision,
    net_income_is_fy                  double precision,
    net_income_adj_ltm                double precision,
    normalized_ni_ltm                 double precision,
    net_income_is_1fqfq               double precision,
    net_income_is_2fqfq               double precision,
    net_income_is_3fqfq               double precision,
    net_income_is_4fqfq               double precision,
    net_income_is_1fy                 double precision,
    net_income_is_2fy                 double precision,
    net_income_is_3fy                 double precision,
    net_income_is_4fy                 double precision,
    net_income_is_5yavgfq             double precision,
    net_income_is_5yavgltm            double precision,
    normalized_ni_5yavgfq             double precision,
    normalized_ni_5yavgltm            double precision,
    net_income_growth_yoy             double precision,
    net_income_margin_ltm             double precision,
    ni_adjustment_ratio               double precision,
    net_income_positive_years         bigint,
    earnings_quality_composite        double precision,
    net_income_qoq_growth             double precision,
    net_income_yoy_quarterly          double precision,
    net_income_vs_5y_avg              double precision,
    normalized_ni_vs_5y_avg           double precision,
    cogs_to_revenue                   double precision,
    opex_to_revenue                   double precision,
    sga_to_revenue                    double precision,
    rnd_to_revenue                    double precision,
    interest_to_revenue               double precision,
    sga_trend_yoy                     double precision,
    operating_leverage_proxy          double precision,
    cost_efficiency_score             double precision,
    marketing_to_revenue              double precision,
    marketing_trend_yoy               double precision,
    marketing_vs_5y_avg               double precision,
    sga_vs_5y_avg                     double precision,
    sga_efficiency_trend              double precision,
    rnd_ltm                           double precision,
    rnd_fq                            double precision,
    rnd_fy                            double precision,
    rnd_1fqfq                         double precision,
    rnd_2fqfq                         double precision,
    rnd_3fqfq                         double precision,
    rnd_4fqfq                         double precision,
    rnd_1fy                           double precision,
    rnd_2fy                           double precision,
    rnd_3fy                           double precision,
    rnd_4fy                           double precision,
    rnd_intensity_ltm                 double precision,
    rnd_intensity_fy                  double precision,
    rnd_intensity_trend               double precision,
    rnd_qoq_growth                    double precision,
    rnd_yoy_growth                    double precision,
    rnd_cagr_3y                       double precision,
    rnd_per_employee                  double precision,
    rnd_to_gross_profit               double precision,
    rnd_roi_proxy                     double precision,
    rnd_increasing_flag               bigint,
    rnd_cut_flag                      bigint,
    high_rnd_intensity_flag           bigint,
    interest_income_ltm               double precision,
    interest_expense_ltm              double precision,
    net_interest_income               double precision,
    interest_coverage_ratio           double precision,
    interest_income_to_revenue        double precision,
    interest_expense_to_revenue       double precision,
    net_interest_margin_proxy         double precision,
    dividend_streak                   bigint,
    dividend_yield_ltm                double precision,
    dividend_yield_ntm                double precision,
    dividend_payout_ratio             double precision,
    fcf_dividend_coverage             double precision,
    buyback_yield                     double precision,
    total_shareholder_yield           double precision,
    dividend_growth_expectation       double precision,
    days_since_ex_date                double precision,
    days_to_payment                   double precision,
    dividend_announced_flag           bigint,
    ex_date_approaching_flag          bigint,
    dividend_frequency_score          bigint,
    dividend_consistency              double precision,
    recent_dividend_change            double precision,
    dividend_yield_vs_5y_avg          double precision,
    div_yield_ltm                     double precision,
    div_yield_ntm                     double precision,
    div_yield_ind                     double precision,
    div_yield_1fy_ind                 double precision,
    div_yield_5y_avg                  double precision,
    div_yield_vs_5y_avg               double precision,
    div_yield_growth_expected         double precision,
    dividend_streak_comp              bigint,
    high_yield_flag                   bigint,
    sustainable_dividend_flag         bigint,
    eps_surprise_pct                  double precision,
    revenue_surprise_pct              double precision,
    eps_adjustment_ratio              double precision,
    gaap_adj_eps_gap_pct              double precision,
    ebitda_adjustment_ratio           double precision,
    eps_quarterly_trend               double precision,
    eps_yoy_growth                    double precision,
    eps_qoq_growth                    double precision,
    eps_yoy_quarterly                 double precision,
    eps_positive_streak               bigint,
    eps_cagr_3y                       double precision,
    eps_cagr_5y                       double precision,
    eps_growth_accel                  double precision,
    eps_vs_5y_avg                     double precision,
    eps_improvement_count             bigint,
    eps_stability                     double precision,
    eps_basic_fq                      double precision,
    eps_basic_ltm                     double precision,
    eps_basic_fy                      double precision,
    eps_adj_ltm                       double precision,
    eps_norm_est_fy1e                 double precision,
    eps_growth_yoy_comp               double precision,
    eps_cagr_3y_comp                  double precision,
    eps_adjustment_ratio_comp         double precision,
    eps_positive_years                bigint,
    eps_trajectory_score_comp         double precision,
    eps_cont_ltm                      double precision,
    eps_cont_fq                       double precision,
    eps_cont_fy                       double precision,
    eps_cont_1fqfq                    double precision,
    eps_cont_2fqfq                    double precision,
    eps_cont_3fqfq                    double precision,
    eps_cont_4fqfq                    double precision,
    eps_cont_1fy                      double precision,
    eps_cont_2fy                      double precision,
    eps_cont_3fy                      double precision,
    eps_cont_4fy                      double precision,
    eps_cont_qoq_growth               double precision,
    eps_cont_yoy_growth               double precision,
    eps_cont_cagr_3y                  double precision,
    eps_cont_vs_total_eps             double precision,
    eps_cont_positive_streak          bigint,
    eps_cont_trajectory_score         double precision,
    discontinued_ops_impact           double precision,
    core_earnings_stability           double precision,
    eps_adjustment_spread_ltm         double precision,
    eps_adjustment_spread_fy          double precision,
    eps_adjustment_pct                double precision,
    net_income_adjustment_ratio_ltm   double precision,
    net_income_adjustment_ratio_fy    double precision,
    net_income_adjustment_pct         double precision,
    ebitda_adjustment_pct_ltm         double precision,
    ebitda_adjustment_pct_fy          double precision,
    ebit_adjustment_pct_ltm           double precision,
    ebit_adjustment_pct_fy            double precision,
    earnings_quality_score            double precision,
    earnings_quality_warning          bigint,
    forward_eps_gaap_adj_spread       double precision,
    gaap_revision_momentum            double precision,
    gaap_revision_1m                  double precision,
    gaap_revision_3m                  double precision,
    gaap_revision_6m                  double precision,
    gaap_revision_1y                  double precision,
    gaap_vs_norm_revision_spread      double precision,
    gaap_revision_acceleration        double precision,
    gaap_positive_revision_flag       bigint,
    revision_quality_divergence       double precision,
    revenue_per_employee              double precision,
    profit_per_employee               double precision,
    ebitda_per_employee               double precision,
    assets_per_employee               double precision,
    fte_growth_1y_pct                 double precision,
    fte_growth_3y_pct                 double precision,
    workforce_stability               double precision,
    fte_growth_2y_pct                 double precision,
    fte_acceleration                  double precision,
    workforce_volatility              double precision,
    hiring_intensity                  double precision,
    productivity_trend                double precision,
    headcount_vs_revenue              double precision,
    workforce_efficiency_gain         double precision,
    layoff_risk_flag                  bigint,
    rapid_hiring_flag                 bigint,
    sustainable_growth_flag           bigint,
    revenue_growth_yoy                double precision,
    ebitda_growth_yoy                 double precision,
    operating_income_growth           double precision,
    fcf_growth                        double precision,
    revenue_cagr_5y                   double precision,
    forward_revenue_growth            double precision,
    revenue_vs_5y_avg                 double precision,
    revenue_est_spread                double precision,
    revenue_beat_potential            double precision,
    revenue_est_revision_trend        double precision,
    ebitda_est_vs_actual              double precision,
    forward_revenue_multiple          double precision,
    revenue_estimate_count            double precision,
    revenue_guidance_gap              double precision,
    consensus_revenue_growth          double precision,
    ebit_estimate_spread              double precision,
    forward_ebitda_margin             double precision,
    revenue_acceleration              double precision,
    estimate_confidence_score         double precision,
    revenue_est_avg_fy1e              double precision,
    revenue_est_med_fy1e              double precision,
    revenue_est_avg_ntm               double precision,
    revenue_est_med_ntm               double precision,
    revenue_avg_med_diff_pct          double precision,
    revenue_consensus_strength        double precision,
    revenue_revision_trend_rec        double precision,
    revenue_vs_current                double precision,
    revenue_fq                        double precision,
    revenue_fy                        double precision,
    revenue_ltm                       double precision,
    revenue_5y_avg                    double precision,
    revenue_1fqfq                     double precision,
    revenue_2fqfq                     double precision,
    revenue_3fqfq                     double precision,
    revenue_4fqfq                     double precision,
    revenue_1fy                       double precision,
    revenue_2fy                       double precision,
    revenue_3fy                       double precision,
    revenue_4fy                       double precision,
    revenue_qoq_growth                double precision,
    revenue_qoq_2q                    double precision,
    revenue_qoq_3q                    double precision,
    revenue_qoq_4q                    double precision,
    revenue_yoy_quarterly             double precision,
    revenue_2y_growth                 double precision,
    revenue_3y_growth                 double precision,
    revenue_4y_growth                 double precision,
    revenue_cagr_3y                   double precision,
    revenue_cagr_4y                   double precision,
    revenue_4q_trend                  double precision,
    revenue_4q_avg                    double precision,
    revenue_fq_vs_4q_avg              double precision,
    revenue_growth_flag               bigint,
    revenue_stability_score           double precision,
    revenue_accelerating_flag         bigint,
    revenue_positive_qoq_streak       bigint,
    revenue_5yavgfq                   double precision,
    revenue_5yavgltm                  double precision,
    revenue_vs_5y_avg_fq              double precision,
    revenue_vs_5y_avg_ltm             double precision,
    revenue_fq_vs_avg                 double precision,
    revenue_momentum                  double precision,
    debt_to_equity                    double precision,
    debt_to_assets                    double precision,
    equity_ratio                      double precision,
    interest_coverage                 double precision,
    current_ratio                     double precision,
    cash_ratio                        double precision,
    working_capital_ratio             double precision,
    asset_turnover                    double precision,
    receivables_days                  double precision,
    working_capital_turns             double precision,
    cash_to_assets_pct                double precision,
    cash_change_qoq                   double precision,
    cash_vs_5y_avg                    double precision,
    inventory_change_yoy              double precision,
    receivables_change_yoy            double precision,
    receivables_vs_5y_avg             double precision,
    working_capital_vs_5y_avg         double precision,
    retained_earnings_vs_5y           double precision,
    intangibles_growth_flag           bigint,
    asset_quality_score               double precision,
    balance_sheet_strength            double precision,
    debt_maturity_risk                double precision,
    wc_fq                             double precision,
    wc_fy                             double precision,
    wc_ltm                            double precision,
    wc_5yavgfy                        double precision,
    wc_1fq                            double precision,
    wc_2fq                            double precision,
    wc_3fq                            double precision,
    wc_4fq                            double precision,
    wc_1fy                            double precision,
    wc_2fy                            double precision,
    wc_3fy                            double precision,
    wc_4fy                            double precision,
    wc_qoq_change                     double precision,
    wc_yoy_change                     double precision,
    wc_4q_trend                       double precision,
    wc_vs_5y_avg                      double precision,
    wc_positive_quarters              bigint,
    wc_improving_flag                 bigint,
    wc_volatility                     double precision,
    debt_fq                           double precision,
    debt_fy                           double precision,
    debt_ltm                          double precision,
    debt_1fq                          double precision,
    debt_2fq                          double precision,
    debt_3fq                          double precision,
    debt_4fq                          double precision,
    debt_1fy                          double precision,
    debt_2fy                          double precision,
    debt_3fy                          double precision,
    debt_4fy                          double precision,
    debt_qoq_change                   double precision,
    debt_yoy_change                   double precision,
    debt_4q_trend                     double precision,
    debt_3y_cagr                      double precision,
    debt_deleveraging                 bigint,
    debt_to_equity_trend              double precision,
    wc_ltm_deep                       double precision,
    wc_fq_deep                        double precision,
    wc_fy_deep                        double precision,
    wc_to_revenue                     double precision,
    wc_to_assets                      double precision,
    wc_change_qoq_deep                double precision,
    wc_change_yoy_deep                double precision,
    days_working_capital              double precision,
    wc_efficiency_score               double precision,
    negative_wc_flag                  bigint,
    wc_improvement_flag_deep          bigint,
    price_momentum_1m                 double precision,
    price_momentum_3m                 double precision,
    price_momentum_6m                 double precision,
    price_momentum_1y                 double precision,
    price_momentum_5d                 double precision,
    ema_crossover_20_50               bigint,
    ema_crossover_50_250              bigint,
    price_vs_ema_20d                  double precision,
    price_vs_ema_250d                 double precision,
    pct_off_52w_high                  double precision,
    pct_above_52w_low                 double precision,
    range_52w_position                double precision,
    beta_momentum                     double precision,
    volatility_regime                 double precision,
    price_momentum_1y_long            double precision,
    price_momentum_3y                 double precision,
    price_momentum_5y                 double precision,
    long_term_trend_score             double precision,
    price_vs_ema_250d_long            double precision,
    multi_year_high_flag              bigint,
    secular_trend_flag                bigint,
    roe                               double precision,
    roa                               double precision,
    gross_margin_pct                  double precision,
    operating_margin_pct              double precision,
    net_margin_pct                    double precision,
    ebitda_margin_pct                 double precision,
    roic                              double precision,
    rnd_intensity                     double precision,
    equity_multiplier                 double precision,
    gross_margin_trend_yoy            double precision,
    operating_margin_trend            double precision,
    net_margin_trend_yoy              double precision,
    ebitda_margin_trend               double precision,
    margin_expansion_flag             bigint,
    margin_stability_score            double precision,
    ebit_fq                           double precision,
    ebit_ltm                          double precision,
    ebit_fy                           double precision,
    ebit_1fy                          double precision,
    ebit_2fy                          double precision,
    ebit_3fy                          double precision,
    ebit_4fy                          double precision,
    ebitda_fq                         double precision,
    ebitda_ltm                        double precision,
    ebitda_fy                         double precision,
    ebitda_1fy                        double precision,
    ebitda_2fy                        double precision,
    ebitda_3fy                        double precision,
    ebitda_4fy                        double precision,
    ebit_5yavgfq                      double precision,
    ebit_5yavgltm                     double precision,
    ebitda_5yavgfq                    double precision,
    ebitda_5yavgltm                   double precision,
    ebit_adj_fq                       double precision,
    ebit_adj_ltm                      double precision,
    ebit_adj_fy                       double precision,
    ebitda_adj_fq                     double precision,
    ebitda_adj_ltm                    double precision,
    ebitda_adj_fy                     double precision,
    ebit_growth_yoy                   double precision,
    ebit_margin_ltm                   double precision,
    ebitda_margin_ltm                 double precision,
    ebit_positive_years               bigint,
    ebitda_positive_years             bigint,
    ebit_qoq_growth                   double precision,
    ebitda_qoq_growth                 double precision,
    ebit_cagr_3y                      double precision,
    ebitda_cagr_3y                    double precision,
    ebit_vs_5y_avg                    double precision,
    ebitda_vs_5y_avg                  double precision,
    gp_fq                             double precision,
    gp_fy                             double precision,
    gp_ltm                            double precision,
    gp_1fqfq                          double precision,
    gp_2fqfq                          double precision,
    gp_3fqfq                          double precision,
    gp_4fqfq                          double precision,
    gp_1fy                            double precision,
    gp_2fy                            double precision,
    gp_3fy                            double precision,
    gp_4fy                            double precision,
    gp_qoq_growth                     double precision,
    gp_yoy_growth                     double precision,
    gp_margin_fq                      double precision,
    gp_margin_trend                   double precision,
    gp_positive_quarters              bigint,
    gp_margin_expansion               bigint,
    has_goodwill_impairment           bigint,
    has_asset_writedown               bigint,
    has_restructuring                 bigint,
    goodwill_to_assets_pct            double precision,
    intangible_intensity              double precision,
    exceptional_items_to_ebitda       double precision,
    altman_z_score                    double precision,
    altman_z_trend                    double precision,
    quick_ratio                       double precision,
    beta_1y                           double precision,
    beta_5y                           double precision,
    beta_spread                       double precision,
    beta_trend                        double precision,
    high_beta_flag                    bigint,
    low_beta_flag                     bigint,
    beta_stability_score              double precision,
    distress_risk_score               double precision,
    liquidity_stress_score            double precision,
    working_capital_trend             double precision,
    cash_runway_months                double precision,
    combined_distress_score           double precision,
    wc_deteriorating_flag             bigint,
    retained_earnings_growth          double precision,
    accumulated_deficit_flag          bigint,
    adequate_cash_buffer              bigint,
    goodwill_change_rate              double precision,
    restructuring_intensity           double precision,
    exceptional_items_frequency       bigint,
    merger_impact_ratio               double precision,
    non_operating_income_share        double precision,
    asset_sale_boost                  bigint,
    accounting_quality_score          double precision,
    goodwill_impairment_ltm           double precision,
    asset_writedown_ltm               double precision,
    restructuring_ltm                 double precision,
    has_goodwill_impairment_ltm       bigint,
    goodwill_impairment_frequency     bigint,
    asset_writedown_frequency         bigint,
    restructuring_frequency           bigint,
    exceptional_items_total_ltm       double precision,
    exceptional_items_to_ebitda_comp  double precision,
    quality_issues_count_5y           bigint,
    accounting_quality_score_comp     double precision,
    ema_slope_20d                     double precision,
    ema_trend_consistency             bigint,
    price_vs_ema_100d                 double precision,
    near_52w_high_flag                bigint,
    near_52w_low_flag                 bigint,
    volume_momentum_score             double precision,
    breakout_signal                   bigint,
    high_volume_flag                  bigint,
    low_volume_flag                   bigint,
    volatility_compression            double precision,
    volatility_term_structure         double precision,
    fiscal_quarter                    double precision,
    fiscal_month                      double precision,
    fiscal_year                       double precision,
    days_to_earnings                  bigint,
    earnings_report_recency           double precision,
    reporting_lag                     double precision,
    fiscal_year_progress              double precision,
    days_since_last_report            double precision,
    days_to_fy_end                    double precision,
    is_quarter_end_month              bigint,
    is_fy_end_month                   bigint,
    earnings_season_flag              bigint,
    pre_earnings_window               bigint,
    post_earnings_window              bigint,
    reporting_freshness_score         double precision,
    fiscal_quarter_progress           double precision,
    other_unusual_items_ltm           double precision,
    impairment_goodwill_ltm           double precision,
    restructuring_charges_ltm         double precision,
    total_unusual_items               double precision,
    unusual_items_to_revenue          double precision,
    unusual_items_to_ebitda           double precision,
    has_unusual_items_flag            bigint,
    earnings_quality_impact           double precision,
    p_e_ratio                         double precision,
    p_b_ratio                         double precision,
    ev_ebitda_ratio                   double precision,
    ev_sales_ratio                    double precision,
    dividend_yield                    double precision,
    peg_ratio                         double precision,
    ev_sales_trend_1y                 double precision,
    ev_ebitda_momentum                double precision,
    p_e_momentum_yoy                  double precision,
    p_e_momentum_qoq                  double precision,
    ev_sales_vs_3y_avg                double precision,
    ev_ebitda_vs_3y_avg               double precision,
    p_e_vs_3y_avg                     double precision,
    ev_sales_forward_discount         double precision,
    ev_ebitda_forward_discount        double precision,
    p_e_forward_discount              double precision,
    p_b_vs_5y_avg                     double precision,
    ev_sales_qoq_1q                   double precision,
    ev_sales_qoq_2q                   double precision,
    ev_sales_qoq_3q                   double precision,
    ev_sales_qoq_4q                   double precision,
    p_e_vs_5y_avg                     double precision,
    p_e_percentile_proxy              double precision,
    valuation_mean_reversion          double precision,
    ev_ebitda_qoq_trend               double precision,
    p_b_momentum_yoy                  double precision,
    valuation_compression             double precision,
    forward_pe_premium                double precision,
    tangible_book_value_fy            double precision,
    tangible_book_value_ltm           double precision,
    tangible_book_per_share           double precision,
    price_to_tangible_book            double precision,
    tangible_equity_ratio             double precision,
    intangibles_to_equity             double precision,
    goodwill_to_equity                double precision,
    tangible_asset_quality            double precision,
    tbv_yoy_growth                    double precision,
    tbv_vs_calculated                 double precision,
    inventory_turnover_mv             double precision,
    price_momentum_1m_filtered        double precision,
    price_momentum_1m_variance        double precision,
    price_momentum_3m_filtered        double precision,
    price_momentum_3m_variance        double precision,
    price_momentum_6m_filtered        double precision,
    price_momentum_6m_variance        double precision,
    price_momentum_1y_filtered        double precision,
    price_momentum_1y_variance        double precision,
    price_momentum_5d_filtered        double precision,
    price_momentum_5d_variance        double precision,
    profit_per_employee_sector_z      double precision,
    ebitda_per_employee_sector_z      double precision,
    revenue_per_employee_sector_z     double precision,
    productivity_frontier_score       double precision,
    productivity_rank                 double precision,
    sector_rank                       double precision,
    sector_percentile                 double precision
);

alter table analytics.sector_relative_ranking
    owner to postgres;

