create table analytics.valuation_ratios_distributions
(
    p_e_ratio                  text,
    p_b_ratio                  text,
    ev_ebitda_ratio            text,
    ev_sales_ratio             text,
    dividend_yield             text,
    peg_ratio                  text,
    ev_sales_trend_1y          text,
    ev_ebitda_momentum         text,
    p_e_momentum_yoy           text,
    p_e_momentum_qoq           text,
    ev_sales_vs_3y_avg         text,
    ev_ebitda_vs_3y_avg        text,
    p_e_vs_3y_avg              text,
    ev_sales_forward_discount  text,
    ev_ebitda_forward_discount text,
    p_e_forward_discount       text,
    p_b_vs_5y_avg              text,
    ev_sales_qoq_1q            text,
    ev_sales_qoq_2q            text,
    ev_sales_qoq_3q            text,
    ev_sales_qoq_4q            text,
    p_e_vs_5y_avg              text,
    p_e_percentile_proxy       text,
    valuation_mean_reversion   text,
    ev_ebitda_qoq_trend        text,
    p_b_momentum_yoy           text,
    valuation_compression      text,
    forward_pe_premium         text,
    tangible_book_value_fy     text,
    tangible_book_value_ltm    text,
    tangible_book_per_share    text,
    price_to_tangible_book     text,
    tangible_equity_ratio      text,
    intangibles_to_equity      text,
    goodwill_to_equity         text,
    tangible_asset_quality     text,
    tbv_yoy_growth             text,
    tbv_vs_calculated          text
);

alter table analytics.valuation_ratios_distributions
    owner to postgres;

