# ... existing code ...

# Price Columns - NEVER transform (critical for business metric)
# These columns must remain in original dollar units for valuation analysis
PRICE_COLUMNS: Set[str] = {
    # Current prices and targets
    "last_price",  # Current market price (critical)
    "price_target",  # Analyst consensus target (critical)
    "price_target_median",  # Median analyst target
    "price_target_ytd_ago",  # Historical target (YTD)
    "price_target_low",  # Low analyst target
    "price_target_high",  # High analyst target
    # Historical price targets (for dynamics)
    "price_target_1w_ago",
    "price_target_1m_ago",
    "price_target_3m_ago",
    "price_target_6m_ago",
    "price_target_mtd_ago",
    "price_target_qtd_ago",
    "price_target_1y_ago",
    "price_target_high_1w_ago",
    "price_target_high_1m_ago",
    "price_target_high_3m_ago",
    "price_target_high_6m_ago",
    "price_target_high_mtd_ago",
    "price_target_high_qtd_ago",
    "price_target_high_ytd_ago",
    "price_target_high_1y_ago",
    "price_target_low_1w_ago",
    "price_target_low_1m_ago",
    "price_target_low_3m_ago",
    "price_target_low_6m_ago",
    "price_target_low_mtd_ago",
    "price_target_low_qtd_ago",
    "price_target_low_ytd_ago",
    "price_target_low_1y_ago",
    "price_target_median_1w_ago",
    "price_target_median_1m_ago",
    "price_target_median_3m_ago",
    "price_target_median_6m_ago",
    "price_target_median_mtd_ago",
    "price_target_median_qtd_ago",
    "price_target_median_ytd_ago",
    "price_target_median_1y_ago",
    # Historical prices (for momentum calculations)
    "price_5d_ago",  # Price 5 days ago
    "price_1w_ago",  # Price 1 week ago
    "price_1m_ago",  # Price 1 month ago
    "price_3m_ago",  # Price 3 months ago
    "price_6m_ago",  # Price 6 months ago
    "price_1y_ago",  # Price 1 year ago
    "price_3y_ago",  # Price 3 years ago
    "price_5y_ago",  # Price 5 years ago
    "price_qtd_ago",  # Price at quarter-to-date start
    # 52-week bounds (for relative positioning)
    "52w_high_adj",  # 52-week adjusted high
    "52w_low_adj",  # 52-week adjusted low
    # Exponential moving averages (technical indicators)
    "ema_20d",  # 20-day EMA
    "ema_50d",  # 50-day EMA
    "ema_100d",  # 100-day EMA
    "ema_250d",  # 250-day EMA (1-year trend proxy)
    "ma_20d_simple",  # 20-day simple MA
    "ma_50d_simple",  # 50-day simple MA
    # Dividend per share (price-like)
    "dividend_per_share_ltm",
    "dividend_record_amount",
}


# Market Value Columns - Log-transform to handle high skewness
# These columns typically have skewness > 2.0 and need log-transforms
# instead of winsorization to preserve information about valid extremes
MARKET_VALUE_COLUMNS: Set[str] = {
    # Market capitalization and enterprise value
    "market_cap",  # Market capitalization (highly skewed)
    "ev",  # Enterprise value
    "enterprise_value",  # Enterprise value (alternative name)
    "market_cap_country_r",  # Market cap (country relative)
    # Balance sheet items (role: balance_sheet in schema)
    "total_assets_ltm",
    "total_assets_fy",
    "total_debt_fy",
    "total_debt_ltm",
    "total_equity_fy",
    "total_equity_ltm",
    "total_current_assets_ltm",
    "total_current_liabilities_ltm",
    "tbv_fy",
    "tbv_ltm",
    "cash_and_equivalents_ltm",
    "cash_and_equivalents_fq",
    "cash_and_equivalents_fy",
    "cash_and_equivalents_5yavgfq",
    "working_capital_ltm",
    "working_capital_fq",
    "working_capital_fy",
    "working_capital_5yavgfy",
    "inventory_ltm",
    "inventory_fq",
    "inventory_fy",
    "inventory_5yavgfq",
    "goodwill_fq",
    "goodwill_ltm",
    "goodwill_fy",
    "goodwill_1fy",
    "goodwill_5yavgfq",
    "retained_earnings_ltm",
    "retained_earnings_fq",
    "retained_earnings_fy",
    "retained_earnings_5yavgfq",
    "gross_intangible_assets_ltm",
    "gross_intangible_assets_fy",
    "gross_intangible_assets_5yavgfq",
    "accounts_receivable_total_fy",
    "accounts_receivable_total_1fy",
    "accounts_receivable_total_5yavgfq",
    # Income statement items (role: financial_statement in schema)
    "total_revenues_fy",
    "total_revenues_ltm",
    "total_revenues_fq",
    "total_revenues_1fy",
    "total_revenues_5yavgfq",
    "total_revenues_5yavgltm",
    "revenues_est_avg_ntm",
    "revenues_est_avg_fy1e",
    "revenues_est_med_ntm",
    "revenues_est_med_fy1e",
    "total_operating_expenses_ltm",
    "gross_profit_ltm",
    "gross_profit_fy",
    "cost_of_revenues_ltm",
    "operating_income_ltm",
    "operating_income_fy",
    "operating_income_fq",
    "operating_income_5yavgfq",
    "ebitda_fy",
    "ebitda_ltm",
    "ebitda_fq",
    "ebitda_1fy",
    "ebitda_adj_ltm",
    "ebitda_adj_fy",
    "ebitda_adj_1fy",
    "ebitda_5yavgfq",
    "ebitda_5yavgltm",
    "ebitda_est_avg_fy1e",
    "ebitda_est_avg_ntm",
    "ebit_fy",
    "ebit_ltm",
    "ebit_fq",
    "ebit_1fy",
    "ebit_adj_ltm",
    "ebit_adj_fy",
    "ebit_adj_1fy",
    "ebit_est_med_fy1e",
    "ebit_est_med_ntm",
    "ebit_5yavgfq",
    "ebit_5yavgltm",
    "net_income_is_fy",
    "net_income_is_ltm",
    "net_income_is_fq",
    "net_income_is_1fy",
    "net_income_is_5yavgfq",
    "net_income_is_5yavgltm",
    "normalized_net_income_fy",
    "normalized_net_income_ltm",
    "normalized_net_income_fq",
    "normalized_net_income_1fy",
    "normalized_net_income_5yavgfq",
    "normalized_net_income_5yavgltm",
    "net_income_adj_fy",
    "net_income_adj_ltm",
    "net_income_adj_fq",
    "net_income_adj_1fy",
    "net_income_adj_5yavgfq",
    "r_and_d_expenses_ltm",
    "interest_expense_total_ltm",
    "interest_income_on_investments_ltm",
    "selling_general_and_admin_expenses_total_fq",
    "selling_general_and_admin_expenses_total_fy",
    "selling_general_and_admin_expenses_total_1fy",
    "selling_general_and_admin_expenses_total_5yavgfq",
    "marketing_expenses_fq",
    "marketing_expenses_fy",
    "marketing_expenses_1fy",
    "marketing_expenses_5yavgltm",
    # Cash flow items (role: cash_flow in schema)
    "cfo_ltm",
    "cfo_fy",
    "cfo_fq",
    "cfo_1fy",
    "cfo_2fy",
    "cfo_3fy",
    "cfo_4fy",
    "cfo_1fqfq",
    "cfo_2fqfq",
    "cfo_3fqfq",
    "cfo_4fqfq",
    "fcf_ltm",
    "fcf_fy",
    "fcf_fq",
    "fcf_1fy",
    "fcf_2fy",
    "fcf_3fy",
    "fcf_4fy",
    "fcf_5yavgfq",
    "fcf_1fqfq",
    "fcf_2fqfq",
    "fcf_3fqfq",
    "fcf_4fqfq",
    "cfi_ltm",
    "cfi_fy",
    "cfi_fq",
    "cfi_1fy",
    "cfi_2fy",
    "cfi_3fy",
    "cfi_4fy",
    "cfi_1fqfq",
    "cfi_2fqfq",
    "cfi_3fqfq",
    "cfi_4fqfq",
    "cff_ltm",
    "cff_fy",
    "cff_fq",
    "cff_1fy",
    "cff_2fy",
    "cff_3fy",
    "cff_4fy",
    "cff_1fqfq",
    "cff_2fqfq",
    "cff_3fqfq",
    "cff_4fqfq",
    "capital_expenditure_ltm",
    "capital_expenditure_fy",
    "capital_expenditure_fq",
    "capital_expenditure_1fy",
    "capital_expenditure_5yavgfq",
    "cash_acquisitions_ltm",
    "cash_acquisitions_fy",
    "cash_acquisitions_fq",
    "cash_acquisitions_1fy",
    "cash_acquisitions_5yavgfq",
    "cash_acquisitions_1fqfq",
    "cash_acquisitions_2fqfq",
    "cash_acquisitions_3fqfq",
    "cash_acquisitions_4fqfq",
    "common_dividends_paid_ltm",
    "common_dividends_paid_fy",
    # Deprecated/legacy aliases
    "revenue",
    "ebitda",
    "operating_income",
    "net_income",
    "gross_profit",
    "total_assets",
    "total_debt",
    "net_debt",
    "cash_and_equivalents",
    "total_equity",
    "tangible_book_value",
    "operating_cash_flow",
    "free_cash_flow",
    "capex",
}


# Ratio Columns - Pre-normalized, may not need winsorization
# Financial ratios are already relative metrics
RATIO_COLUMNS: Set[str] = {
    # Valuation ratios (role: ratio in schema)
    "p_e_ntm",
    "p_e_ltm",
    "p_e_1fyltm",
    "p_e_2fyltm",
    "p_e_3fyltm",
    "p_e_3yavgltm",
    "p_e_1fqltm",
    "p_e_2fqltm",
    "p_e_3fqltm",
    "p_e_5yavgltm",
    "p_e_0fqqoqltm",
    "p_e_0fyyoyltm",
    "p_e_1fyyoyltm",
    "p_e_0fqyoyltm",
    "p_e_est_fy1",
    "p_b_ltm",
    "p_b_1fy",
    "p_b_5yavg",
    "p_tbv_ltm",
    "ev_sales_ltm",
    "ev_sales_ntm",
    "ev_sales_est_fy1",
    "ev_sales_1fyltm",
    "ev_sales_2fyltm",
    "ev_sales_3fyltm",
    "ev_sales_3yavgltm",
    "ev_sales_1fqltm",
    "ev_sales_2fqltm",
    "ev_sales_3fqltm",
    "ev_sales_4fqltm",
    "ev_ebitda_ltm",
    "ev_ebitda_ntm",
    "ev_ebitda_est_fy1",
    "ev_ebitda_1fyltm",
    "ev_ebitda_1fqltm",
    "ev_ebitda_3yavgltm",
    "altman_z_score_fy",
    "altman_z_score_fq",
    "altman_z_score_ltm",
    # Profitability ratios (role: ratio in schema)
    "return_on_equity_pct_ltm",
    "return_on_equity_pct_fy",
    "return_on_assets_roa_pct_ltm",
    "return_on_assets_roa_pct_fy",
    # Liquidity/efficiency ratios (role: ratio in schema)
    "current_ratio_fy",
    "current_ratio_ltm",
    "asset_turnover_fy",
    "asset_turnover_ltm",
    # Derived ratio features (Phase 9.3)
    "p_e",
    "p_b",
    "p_s",
    "p_fcf",
    "p_tbv",
    "p_e_ratio",
    "p_b_ratio",
    "p_s_ratio",
    "ev_ebitda",
    "ev_sales",
    "ev_fcf",
    "ev_ebitda_ratio",
    "ev_sales_ratio",
    "roe",
    "roa",
    "roic",
    "roce",
    "roe_ltm",
    "roa_ltm",
    "roic_ltm",
    "debt_equity",
    "debt_to_equity",
    "net_debt_ebitda",
    "net_debt_to_ebitda",
    "debt_to_assets",
    "interest_coverage",
    "current_ratio",
    "quick_ratio",
    "cash_ratio",
    "asset_turnover",
    "inventory_turnover",
    "receivables_turnover",
    "equity_ratio",
    "working_capital_to_sales",
    "peg_ratio",
    # EPS ratios (role: ratio in schema)
    "eps_adj_fy",
    "eps_adj_1fy",
    "eps_adj_ltm",
    "eps_norm_est_avg_ntm",
    "eps_norm_est_avg_fy1e",
    "eps_gaap_est_avg_ntm",
    "eps_gaap_est_avg_fy1e",
    "net_eps_basic_ltm",
    "net_eps_basic_fq",
    "net_eps_basic_fy",
    "net_eps_basic_1fqfq",
    "net_eps_basic_2fqfq",
    "net_eps_basic_3fqfq",
    "net_eps_basic_4fqfq",
    "net_eps_basic_1fy",
    "net_eps_basic_2fy",
    "net_eps_basic_3fy",
    "net_eps_basic_4fy",
    "net_eps_basic_5fy",
}


# Percentage Columns - Bounded [0, 100], inappropriate for percentile capping
# These are already normalized as percentages
PERCENTAGE_COLUMNS: Set[str] = {
    # Beta and volatility (role: percentage in schema)
    "beta_1y",
    "beta_2y",
    "beta_5y",
    "beta",
    "beta_stability",
    "volatility_1m",
    "volatility_30d",
    "volatility_3m",
    "volatility_60d",
    "volatility_6m",
    "volatility_90d",
    "volatility_1y",
    "volatility_20d",
    # Returns and price changes (role: percentage in schema)
    "total_return_ytd",
    "total_return_5y",
    "total_return_10y",
    "tot_return_pct_cagr_3y",
    "tot_return_pct_cagr_10y",
    "price_chg_pct_1m",
    "price_chg_pct_3m",
    "1_day_pct",
    "one_day_pct",
    "total_revenues_cagr_5y_fy",
    "revenues_est_yoy_pct_fy1e",
    # Margin metrics
    "gross_margin",
    "operating_margin",
    "net_margin",
    "ebitda_margin",
    "gross_margin_ltm",
    "operating_margin_ltm",
    "net_margin_ltm",
    "ebitda_margin_ltm",
    "gross_margin_pct",
    "operating_margin_pct",
    "net_margin_pct",
    "gross_profit_margin_pct_fy",
    "gross_profit_margin_pct_ltm",
    "net_income_margin_pct_fy",
    "net_income_margin_pct_ltm",
    # Growth rates
    "revenue_growth_yoy",
    "earnings_growth_yoy",
    "ebitda_growth_yoy",
    "eps_growth_yoy",
    "revenue_growth_3y_cagr",
    "revenue_growth_5y_cagr",
    "earnings_growth_3y_cagr",
    "earnings_growth_5y_cagr",
    "revenue_growth",
    "earnings_growth",
    "ebitda_growth",
    "fcf_growth",
    "book_value_growth",
    "operating_income_growth",
    "cfo_growth_yoy",
    # Yield / payout
    "dividend_payout_ratio",
    "payout_ratio",
    "div_yield_ind",
    "div_yield_ltm",
    "div_yield_ttm",
    "div_yield_ntm",
    "div_yield_1fyind",
    "div_yield_2fyind",
    "div_yield_3fyind",
    "div_yield_4fyind",
    "div_yield_5fyind",
    "div_yield_5yavgltm",
    "buyback_yield_ltm",
    "dividend_yield",
    "dividend_yield_stability",
    # EPS revision percentages (role: percentage in schema)
    "eps_est_avg_rev_pct_fy1e_1w",
    "eps_est_avg_rev_pct_fy1e_1m",
    "eps_est_avg_rev_pct_fy1e_3m",
    "eps_est_avg_rev_pct_fy1e_6m",
    "eps_est_avg_rev_pct_fy1e_1y",
    "eps_gaap_est_avg_rev_pct_fy1e_1m",
    "eps_gaap_est_avg_rev_pct_fy1e_3m",
    "eps_gaap_est_avg_rev_pct_fy1e_6m",
    "eps_gaap_est_avg_rev_pct_fy1e_1y",
    # Employee growth rates
    "fte_cagr_3y_pct",
    "fte_growth_1y_pct",
    "fte_growth_2y_pct",
    "fte_growth_3y_pct",
    "employee_growth_yoy_pct",
    "workforce_volatility_pct",
    "revenue_per_employee_vs_5y_pct",
    "employee_growth_yoy",
    "employee_growth_cagr_5y",
    # Momentum and return features (Phase 9.3)
    "price_momentum_1m",
    "price_momentum_3m",
    "price_momentum_6m",
    "price_momentum_1y",
    "total_return_1y_pct",
    "sharpe_proxy",
    "return_stability_score",
    # Analyst sentiment percentages
    "analyst_bullish_pct",
    "analyst_bearish_pct",
    "price_target_spread_pct",
    "target_price_upside_pct",
    "upside_potential",
    "consensus_strength",
    "analyst_conviction",
    # Quality metrics as percentages
    "eps_surprise_pct",
    "ebitda_surprise_pct",
    "revenue_surprise_pct",
    "net_income_adjustment_pct_ltm",
    "exceptional_items_to_ni_pct",
    "goodwill_to_assets_pct",
    "intangibles_to_assets_pct",
    # Phase 9.3 v1.14 temporal & cycle features
    "fiscal_year_progress",
    "dividend_cycle_position",
    "fcf_positive_ratio",
    # Price target dynamics (percentages)
    "pt_momentum_1w",
    "pt_momentum_1m",
    "pt_momentum_3m",
    "pt_momentum_6m",
    "pt_momentum_1y",
    "pt_qtd_momentum",
    "pt_ytd_momentum",
    "pt_acceleration_short",
    "pt_acceleration_long",
    "analyst_coverage_change_1m",
    "analyst_coverage_change_3m",
    "pt_vs_price_momentum",
    # EPS trajectory (CAGRs as percentages)
    "eps_cagr_5y",
    "eps_cagr_3y",
    "eps_growth_acceleration",
}


# Count Columns - Discrete integer counts, inappropriate for continuous scaling
COUNT_COLUMNS: Set[str] = {
    # Analyst coverage (role: count in schema)
    "analyst_rating",
    "num_strong_sell_ratings",
    "num_strong_buys_ratings",
    "num_hold_ratings",
    "num_buys_ratings",
    "num_sell_ratings",
    "price_target_num",
    "price_target_count",
    "price_target_num_3m_ago",
    "price_target_num_6m_ago",
    "price_target_num_ytd_ago",
    "price_target_num_1y_ago",
    "price_target_num_1w_ago",
    "price_target_num_1m_ago",
    "price_target_num_mtd_ago",
    "price_target_num_qtd_ago",
    "eps_norm_est_num_fy1e",
    "num_analysts",
    # Shares and employee counts (role: count in schema)
    "shrs_out",
    "shares_outstanding",
    "shrs_out_1fy",
    "full_time_employees_fq",
    "full_time_employees_fy",
    "full_time_employees_1fy",
    "full_time_employees_2fy",
    "full_time_employees_3fy",
    "avg_employees_5yavgfy",
    "num_employees",
    "num_employees_total",
    "total_employees_fy",
    "total_employees_fq",
    # Dividend tracking (role: count in schema)
    "dividend_streak",
    # Fiscal period integers
    "fiscal_month",
    "fiscal_quarter",
    "fiscal_year",
    "reporting_lag",
    # Phase 9.3 v1.14 temporal counts
    "eps_positive_streak",
    "dividend_cycle_days",
    "acquisition_quarters_active",
}


# ... existing code ...
