"""Dashboard widgets subpackage."""

from .base import (
    EarningsMode,
    EarningsAlertConfig,
    add_formatted_date_columns,
    resolve_reference_date,
)
from .correlation import (
    create_category_comparison_chart,
    create_technical_valuation_dashboard,
    create_category_correlation_network,
)
from .earnings import (
    get_category_metrics,
    create_earnings_calendar_dashboard,
    display_earnings_dashboard,
    create_earnings_metrics_chart,
    create_earnings_surprise_dashboard,
    create_earnings_calendar_analytics,
    analyze_earnings_quality,
    create_gaap_adjusted_comparison_chart,
    generate_earnings_quality_alerts,
    # New v1.14 dashboard functions
    create_price_target_dynamics_dashboard,
    create_eps_trajectory_dashboard,
    create_cashflow_temporal_dashboard,
    create_fiscal_calendar_dashboard,
    create_analyst_sentiment_dashboard,
)
from .portfolio import (
    create_analyst_recommendation_heatmap,
    create_market_movers_dashboard,
    create_price_target_scorecard,
    create_dividend_sustainability_scorecard,
    create_employee_productivity_scorecard,
    create_dividend_reliability_scorecard,
    create_leverage_liquidity_scorecard,
    create_analyst_consensus_scorecard,
    create_earnings_quality_scorecard,
    create_revenue_forecast_scorecard,
    create_cash_flow_quality_scorecard,
    create_momentum_technical_scorecard,
    get_scorecard_generators,
    generate_all_scorecards,
)

__all__ = [
    "EarningsMode",
    "EarningsAlertConfig",
    "add_formatted_date_columns",
    "resolve_reference_date",
    "get_category_metrics",
    "create_earnings_calendar_dashboard",
    "display_earnings_dashboard",
    "create_earnings_metrics_chart",
    "create_earnings_surprise_dashboard",
    "create_earnings_calendar_analytics",
    "analyze_earnings_quality",
    "create_gaap_adjusted_comparison_chart",
    "generate_earnings_quality_alerts",
    "create_analyst_recommendation_heatmap",
    "create_market_movers_dashboard",
    "create_price_target_scorecard",
    "create_dividend_sustainability_scorecard",
    "create_employee_productivity_scorecard",
    "create_category_comparison_chart",
    "create_technical_valuation_dashboard",
    "create_category_correlation_network",
    "create_dividend_reliability_scorecard",
    "create_leverage_liquidity_scorecard",
    "create_analyst_consensus_scorecard",
    "create_earnings_quality_scorecard",
    "create_revenue_forecast_scorecard",
    "create_cash_flow_quality_scorecard",
    "create_momentum_technical_scorecard",
    "get_scorecard_generators",
    "generate_all_scorecards",
    # New v1.14 dashboard functions
    "create_price_target_dynamics_dashboard",
    "create_eps_trajectory_dashboard",
    "create_cashflow_temporal_dashboard",
    "create_fiscal_calendar_dashboard",
    "create_analyst_sentiment_dashboard",
]
