create table equities
(
    "Ticker"                                           text,
    "ISIN"                                             text,
    "Name"                                             text,
    "Region"                                   text    default 'n/a'::text,
    "Country"                                  text    default 'n/a'::text,
    "Trading Country"                          text    default 'n/a'::text,
    "Exchange"                                 text    default 'n/a'::text,
    "Unit"                                     text    default 'n/a'::text,
    "Sector"                                   text    default 'n/a'::text,
    "Industry"                                 text    default 'n/a'::text,
    "Style Class"                              text    default 'n/a'::text,
    "Size Class"                               text    default 'n/a'::text,
    "FY End"                                   text    default 'n/a'::text,
    "Next Earnings (When)"                     text    default 'n/a'::text,
    "Next Earnings (Status)"                   text    default 'n/a'::text,
    "Dividend Record (Currency)"               text    default 'n/a'::text,
    "Dividend Record (Frequency)"              text    default 'n/a'::text,
    "Current Fiscal Quarter"                   text    default 'n/a'::text,
    "Next Fiscal Quarter"                      text    default 'n/a'::text,
    "Next Earnings (Report)"                   text    default 'n/a'::text,
    "Last Updated"                                     date,
    "Income Statement Report Date"                     date,
    "Next Earnings"                                    date,
    "Dividend Record (Announce Date)"                  date,
    "Dividend Record (Payable Date)"                   date,
    "Dividend Record (Record Date)"                    date,
    "Dividend Record (Ex Date)"                        date,
    "Reference Date"                                   date    default CURRENT_DATE,
    "FY End Date"                                      date,
    "Next FY End Date"                                 date,
    "Price Target"                                     numeric,
    "Price Target - Median"                            numeric,
    "Dividend Record (Amount)"                 numeric default 0,
    "Market Cap"                                       numeric,
    "Enterprise Value"                                 numeric,
    "Last Price"                                       numeric,
    "Price Target (YTD Ago)"                           numeric,
    "Price Target - Low"                               numeric,
    "Price Target - High"                              numeric,
    "Market Cap (Country R)"                           numeric,
    "Volume (Shrs)"                            numeric default 0,
    "Dividend Per Share (LTM)"                 numeric default 0,
    "Price (5D Ago)"                                   numeric,
    "Price (1W Ago)"                                   numeric,
    "Price (1M Ago)"                                   numeric,
    "Price (3M Ago)"                                   numeric,
    "Price (6M Ago)"                                   numeric,
    "Price (1Y Ago)"                                   numeric,
    "Price (3Y Ago)"                                   numeric,
    "Price (5Y Ago)"                                   numeric,
    "Price (QTD Ago)"                                  numeric,
    "Rel. Volume"                                      numeric,
    "52W High/Adj"                                     numeric,
    "52W Low/Adj"                                      numeric,
    "EMA (20D)"                                        numeric,
    "EMA (50D)"                                        numeric,
    "EMA (100D)"                                       numeric,
    "EMA (250D)"                                       numeric,
    "Price Target (1W Ago)"                            numeric,
    "Price Target (1M Ago)"                            numeric,
    "Price Target (3M Ago)"                            numeric,
    "Price Target (6M Ago)"                            numeric,
    "Price Target (MTD Ago)"                           numeric,
    "Price Target (QTD Ago)"                           numeric,
    "Price Target (1Y Ago)"                            numeric,
    "Price Target - High (1W Ago)"                     numeric,
    "Price Target - High (1M Ago)"                     numeric,
    "Price Target - High (6M Ago)"                     numeric,
    "Price Target - High (MTD Ago)"                    numeric,
    "Price Target - High (3M Ago)"                     numeric,
    "Price Target - High (QTD Ago)"                    numeric,
    "Price Target - High (1Y Ago)"                     numeric,
    "Price Target - High (YTD Ago)"                    numeric,
    "Price Target - Low (1W Ago)"                      numeric,
    "Price Target - Low (1M Ago)"                      numeric,
    "Price Target - Low (3M Ago)"                      numeric,
    "Price Target - Low (6M Ago)"                      numeric,
    "Price Target - Low (MTD Ago)"                     numeric,
    "Price Target - Low (QTD Ago)"                     numeric,
    "Price Target - Low (YTD Ago)"                     numeric,
    "Price Target - Low (1Y Ago)"                      numeric,
    "Price Target - Median (1W Ago)"                   numeric,
    "Price Target - Median (1M Ago)"                   numeric,
    "Price Target - Median (3M Ago)"                   numeric,
    "Price Target - Median (6M Ago)"                   numeric,
    "Price Target - Median (MTD Ago)"                  numeric,
    "Price Target - Median (QTD Ago)"                  numeric,
    "Price Target - Median (YTD Ago)"                  numeric,
    "Price Target - Median (1Y Ago)"                   numeric,
    "Total Revenues (FQ)"                              numeric default 0,
    "Total Revenues (-1FY)"                            numeric default 0,
    "Total Revenues (FY)"                              numeric default 0,
    "Total Revenues (LTM)"                             numeric default 0,
    "Total Operating Expenses (LTM)"                   numeric default 0,
    "Net Income/Adj. (-1FY)"                           numeric default 0,
    "EBITDA (FQ)"                                      numeric default 0,
    "EBITDA (LTM)"                                     numeric default 0,
    "EBITDA (FY)"                                      numeric default 0,
    "EBITDA (-1FY)"                                    numeric default 0,
    "EBITDA/Adj. (LTM)"                                numeric default 0,
    "EBITDA/Adj. (FY)"                                 numeric default 0,
    "EBITDA/Adj. (-1FY)"                               numeric default 0,
    "EBIT (FQ)"                                        numeric default 0,
    "EBIT (LTM)"                                       numeric default 0,
    "EBIT (FY)"                                        numeric default 0,
    "EBIT (-1FY)"                                      numeric default 0,
    "EBIT/Adj. (-1FY)"                                 numeric default 0,
    "EBIT/Adj. (FY)"                                   numeric default 0,
    "EBIT/Adj. (LTM)"                                  numeric default 0,
    "EBIT - Est Med (FY1E)"                            numeric default 0,
    "EBIT - Est Med (NTM)"                             numeric default 0,
    "Net Income - (IS) (FY)"                           numeric default 0,
    "Net Income - (IS) (LTM)"                          numeric default 0,
    "Normalized Net Income (FY)"                       numeric default 0,
    "Normalized Net Income (LTM)"                      numeric default 0,
    "Net Income/Adj. (FY)"                             numeric default 0,
    "Net Income/Adj. (LTM)"                            numeric default 0,
    "Gross Profit (LTM)"                               numeric default 0,
    "Gross Profit (FY)"                                numeric default 0,
    "Cost Of Revenues (LTM)"                           numeric default 0,
    "Operating Income (LTM)"                           numeric default 0,
    "Operating Income (FY)"                            numeric default 0,
    "R&D Expenses (LTM)"                               numeric default 0,
    "Interest Expense/Total (LTM)"                     numeric default 0,
    "Interest Income On Investments (LTM)"             numeric default 0,
    "Net Income - (IS) (-1FY)"                         numeric default 0,
    "Normalized Net Income (-1FY)"                     numeric default 0,
    "Total Revenues (5YAVGFQ)"                         numeric default 0,
    "EBITDA (5YAVGFQ)"                                 numeric default 0,
    "EBIT (5YAVGFQ)"                                   numeric default 0,
    "Operating Income (FQ)"                            numeric default 0,
    "Operating Income (5YAVGFQ)"                       numeric default 0,
    "Normalized Net Income (FQ)"                       numeric default 0,
    "Normalized Net Income (5YAVGFQ)"                  numeric default 0,
    "Net Income/Adj. (FQ)"                             numeric default 0,
    "Net Income/Adj. (5YAVGFQ)"                        numeric default 0,
    "Net Income - (IS) (FQ)"                           numeric default 0,
    "Net Income - (IS) (5YAVGFQ)"                      numeric default 0,
    "Net Income - (IS) (5YAVGLTM)"                     numeric default 0,
    "Normalized Net Income (5YAVGLTM)"                 numeric default 0,
    "EBITDA (5YAVGLTM)"                                numeric default 0,
    "EBIT (5YAVGLTM)"                                  numeric default 0,
    "Total Revenues (5YAVGLTM)"                        numeric default 0,
    "Selling General & Admin Expenses/Total (FQ)"      numeric default 0,
    "Selling General & Admin Expenses/Total (FY)"      numeric default 0,
    "Selling General & Admin Expenses/Total (-1FY)"    numeric default 0,
    "Selling General & Admin Expenses/Total (5YAVGFQ)" numeric default 0,
    "Marketing Expenses (FQ)"                          numeric default 0,
    "Marketing Expenses (FY)"                          numeric default 0,
    "Marketing Expenses (-1FY)"                        numeric default 0,
    "Marketing Expenses (5YAVGLTM)"                    numeric default 0,
    "Revenues - Est Avg (NTM)"                         numeric default 0,
    "Revenues - Est Avg (FY1E)"                        numeric default 0,
    "Revenues - Est Med (NTM)"                         numeric default 0,
    "Revenues - Est Med (FY1E)"                        numeric default 0,
    "EBITDA - Est Avg (NTM)"                           numeric default 0,
    "EBITDA - Est Avg (FY1E)"                          numeric default 0,
    "TBV (FY)"                                         numeric default 0,
    "TBV (LTM)"                                        numeric default 0,
    "Total Debt (FY)"                                  numeric default 0,
    "Total Equity (FY)"                                numeric default 0,
    "Total Equity (LTM)"                               numeric default 0,
    "Total Debt (LTM)"                                 numeric default 0,
    "Total Assets (LTM)"                               numeric default 0,
    "Total Assets (FY)"                                numeric default 0,
    "Inventory (LTM)"                                  numeric default 0,
    "Goodwill (FQ)"                                    numeric default 0,
    "Goodwill (LTM)"                                   numeric default 0,
    "Goodwill (FY)"                                    numeric default 0,
    "Goodwill (-1FY)"                                  numeric default 0,
    "Retained Earnings (LTM)"                          numeric default 0,
    "Total Current Assets (LTM)"                       numeric default 0,
    "Total Current Liabilities (LTM)"                  numeric default 0,
    "Working Capital (LTM)"                            numeric default 0,
    "Cash And Equivalents (LTM)"                       numeric default 0,
    "Cash And Equivalents (FQ)"                        numeric default 0,
    "Cash And Equivalents (FY)"                        numeric default 0,
    "Cash And Equivalents (5YAVGFQ)"                   numeric default 0,
    "Inventory (FQ)"                                   numeric default 0,
    "Inventory (FY)"                                   numeric default 0,
    "Goodwill (5YAVGFQ)"                               numeric default 0,
    "Inventory (5YAVGFQ)"                              numeric default 0,
    "Retained Earnings (FQ)"                           numeric default 0,
    "Retained Earnings (FY)"                           numeric default 0,
    "Retained Earnings (5YAVGFQ)"                      numeric default 0,
    "Working Capital (FQ)"                             numeric default 0,
    "Working Capital (FY)"                             numeric default 0,
    "Working Capital (5YAVGFY)"                        numeric default 0,
    "Gross Intangible Assets (LTM)"                    numeric default 0,
    "Gross Intangible Assets (FY)"                     numeric default 0,
    "Gross Intangible Assets (5YAVGFQ)"                numeric default 0,
    "Accounts Receivable/Total (FY)"                   numeric default 0,
    "Accounts Receivable/Total (-1FY)"                 numeric default 0,
    "Accounts Receivable/Total (5YAVGFQ)"              numeric default 0,
    "CFF (LTM)"                                        numeric default 0,
    "CFI (LTM)"                                        numeric default 0,
    "FCF (LTM)"                                        numeric default 0,
    "CFO (LTM)"                                        numeric default 0,
    "Cash Acquisitions (LTM)"                          numeric default 0,
    "Cash Acquisitions (FY)"                           numeric default 0,
    "Cash Acquisitions (-1FY)"                         numeric default 0,
    "Capital Expenditure (LTM)"                        numeric default 0,
    "Capital Expenditure (-1FY)"                       numeric default 0,
    "Capital Expenditure (FY)"                         numeric default 0,
    "CFF (FY)"                                         numeric default 0,
    "CFF (-1FY)"                                       numeric default 0,
    "CFI (FY)"                                         numeric default 0,
    "CFI (-1FY)"                                       numeric default 0,
    "CFO (FY)"                                         numeric default 0,
    "CFO (-1FY)"                                       numeric default 0,
    "FCF (FY)"                                         numeric default 0,
    "FCF (-1FY)"                                       numeric default 0,
    "Capital Expenditure (FQ)"                         numeric default 0,
    "Capital Expenditure (5YAVGFQ)"                    numeric default 0,
    "CFF (FQ)"                                         numeric default 0,
    "CFI (FQ)"                                         numeric default 0,
    "CFO (FQ)"                                         numeric default 0,
    "FCF (FQ)"                                         numeric default 0,
    "FCF (5YAVGFQ)"                                    numeric default 0,
    "Cash Acquisitions (FQ)"                           numeric default 0,
    "Cash Acquisitions (5YAVGFQ)"                      numeric default 0,
    "Common Dividends Paid (LTM)"                      numeric default 0,
    "Common Dividends Paid (FY)"                       numeric default 0,
    "CFO (-1FQFQ)"                                     numeric default 0,
    "CFO (-2FQFQ)"                                     numeric default 0,
    "CFO (-3FQFQ)"                                     numeric default 0,
    "CFO (-4FQFQ)"                                     numeric default 0,
    "CFI (-1FQFQ)"                                     numeric default 0,
    "CFI (-2FQFQ)"                                     numeric default 0,
    "CFI (-3FQFQ)"                                     numeric default 0,
    "CFI (-4FQFQ)"                                     numeric default 0,
    "CFI (-2FY)"                                       numeric default 0,
    "CFI (-3FY)"                                       numeric default 0,
    "CFI (-4FY)"                                       numeric default 0,
    "FCF (-1FQFQ)"                                     numeric default 0,
    "FCF (-2FQFQ)"                                     numeric default 0,
    "FCF (-3FQFQ)"                                     numeric default 0,
    "FCF (-4FQFQ)"                                     numeric default 0,
    "CFF (-2FY)"                                       numeric default 0,
    "CFF (-3FY)"                                       numeric default 0,
    "CFF (-4FY)"                                       numeric default 0,
    "CFF (-1FQFQ)"                                     numeric default 0,
    "CFF (-2FQFQ)"                                     numeric default 0,
    "CFF (-3FQFQ)"                                     numeric default 0,
    "CFF (-4FQFQ)"                                     numeric default 0,
    "CFO (-2FY)"                                       numeric default 0,
    "CFO (-3FY)"                                       numeric default 0,
    "CFO (-4FY)"                                       numeric default 0,
    "Cash Acquisitions (-1FQFQ)"                       numeric default 0,
    "Cash Acquisitions (-2FQFQ)"                       numeric default 0,
    "Cash Acquisitions (-3FQFQ)"                       numeric default 0,
    "Cash Acquisitions (-4FQFQ)"                       numeric default 0,
    "FCF (-2FY)"                                       numeric default 0,
    "FCF (-3FY)"                                       numeric default 0,
    "FCF (-4FY)"                                       numeric default 0,
    "P/E (NTM)"                                        numeric,
    "P/E (LTM)"                                        numeric,
    "Altman Z-Score (FY)"                              numeric,
    "Altman Z-Score (FQ)"                              numeric,
    "Altman Z-Score (LTM)"                             numeric,
    "P/TBV (LTM)"                                      numeric,
    "Return On Equity % (LTM)"                         numeric,
    "Return On Equity % (FY)"                          numeric,
    "Current Ratio (FY)"                               numeric,
    "Current Ratio (LTM)"                              numeric,
    "Asset Turnover (FY)"                              numeric,
    "Asset Turnover (LTM)"                             numeric,
    "EPS Norm - Est Avg (NTM)"                         numeric,
    "EPS/Adj. (-1FY)"                                  numeric,
    "EPS/Adj. (FY)"                                    numeric,
    "EPS/Adj. (LTM)"                                   numeric,
    "EPS Norm - Est Avg (FY1E)"                        numeric,
    "Return on Assets (ROA) % (LTM)"                   numeric,
    "Return on Assets (ROA) % (FY)"                    numeric,
    "P/B (LTM)"                                        numeric,
    "P/B (-1FY)"                                       numeric,
    "P/B (5YAVG)"                                      numeric,
    "EV/Sales (EST FY1)"                               numeric,
    "EV/Sales (LTM)"                                   numeric,
    "EV/Sales (NTM)"                                   numeric,
    "EV/Sales (-1FYLTM)"                               numeric,
    "EV/Sales (-2FYLTM)"                               numeric,
    "EV/Sales (-3FYLTM)"                               numeric,
    "EV/Sales (3YAVGLTM)"                              numeric,
    "EV/Sales (-1FQLTM)"                               numeric,
    "EV/Sales (-2FQLTM)"                               numeric,
    "EV/Sales (-3FQLTM)"                               numeric,
    "EV/Sales (-4FQLTM)"                               numeric,
    "EV/EBITDA (LTM)"                                  numeric,
    "EV/EBITDA (NTM)"                                  numeric,
    "EV/EBITDA (-1FYLTM)"                              numeric,
    "EV/EBITDA (-1FQLTM)"                              numeric,
    "EV/EBITDA (3YAVGLTM)"                             numeric,
    "EV/EBITDA (EST FY1)"                              numeric,
    "P/E (EST FY1)"                                    numeric,
    "P/E (-1FYLTM)"                                    numeric,
    "P/E (-2FYLTM)"                                    numeric,
    "P/E (-3FYLTM)"                                    numeric,
    "P/E (3YAVGLTM)"                                   numeric,
    "P/E (-1FQLTM)"                                    numeric,
    "P/E (-2FQLTM)"                                    numeric,
    "P/E (-3FQLTM)"                                    numeric,
    "P/E (5YAVGLTM)"                                   numeric,
    "P/E (-0FQQoQLTM)"                                 numeric,
    "P/E (-0FYYoYLTM)"                                 numeric,
    "P/E (-1FYYoYLTM)"                                 numeric,
    "P/E (-0FQYoYLTM)"                                 numeric,
    "Net EPS - Basic (LTM)"                            numeric,
    "Net EPS - Basic (FQ)"                             numeric,
    "Net EPS - Basic (FY)"                             numeric,
    "Net EPS - Basic (-1FQFQ)"                         numeric,
    "Net EPS - Basic (-2FQFQ)"                         numeric,
    "Net EPS - Basic (-3FQFQ)"                         numeric,
    "Net EPS - Basic (-4FQFQ)"                         numeric,
    "Net EPS - Basic (-1FY)"                           numeric,
    "Net EPS - Basic (-2FY)"                           numeric,
    "Net EPS - Basic (-3FY)"                           numeric,
    "Net EPS - Basic (-4FY)"                           numeric,
    "Net EPS - Basic (-5FY)"                           numeric,
    "EPS GAAP - Est Avg (NTM)"                         numeric,
    "EPS GAAP - Est Avg (FY1E)"                        numeric,
    "Total Return (YTD)"                               numeric,
    "Beta (1Y)"                                        numeric,
    "Beta (2Y)"                                        numeric,
    "Beta (5Y)"                                        numeric,
    "Total Revenues/CAGR (5Y FY)"                      numeric,
    "Tot. Return %/CAGR (3Y)"                          numeric,
    "Tot. Return %/CAGR (10Y)"                         numeric,
    "Total Return (5Y)"                                numeric,
    "Total Return (10Y)"                               numeric,
    "Net Income Margin % (FY)"                         numeric,
    "Net Income Margin % (LTM)"                        numeric,
    "Volatility (1M)"                                  numeric,
    "Volatility (3M)"                                  numeric,
    "Volatility (6M)"                                  numeric,
    "Volatility (1Y)"                                  numeric,
    "Div Yield (Ind)"                          numeric default 0,
    "Div Yield (LTM)"                          numeric default 0,
    "Gross Profit Margin % (FY)"                       numeric,
    "Gross Profit Margin % (LTM)"                      numeric,
    "Buyback Yield (LTM)"                              numeric,
    "Div Yield (-1FYInd)"                      numeric default 0,
    "Div Yield (TTM)"                          numeric default 0,
    "Div Yield (NTM)"                          numeric default 0,
    "Div Yield (5YAVGLTM)"                     numeric default 0,
    "Revenues - Est YoY % (FY1E)"                      numeric,
    "Price Chg. % (1M)"                                numeric,
    "Price Chg. % (3M)"                                numeric,
    "1-Day %"                                          numeric,
    "EPS Est Avg Rev % (FY1E - 1W)"                    numeric,
    "EPS Est Avg Rev % (FY1E - 1M)"                    numeric,
    "EPS Est Avg Rev % (FY1E - 3M)"                    numeric,
    "EPS Est Avg Rev % (FY1E - 6M)"                    numeric,
    "EPS Est Avg Rev % (FY1E - 1Y)"                    numeric,
    "Div Yield (-2FYInd)"                      numeric default 0,
    "Div Yield (-3FYInd)"                      numeric default 0,
    "Div Yield (-4FYInd)"                      numeric default 0,
    "Div Yield (-5FYInd)"                      numeric default 0,
    "EPS GAAP Est Avg Rev % (FY1E - 1M)"               numeric,
    "EPS GAAP Est Avg Rev % (FY1E - 3M)"               numeric,
    "EPS GAAP Est Avg Rev % (FY1E - 6M)"               numeric,
    "EPS GAAP Est Avg Rev % (FY1E - 1Y)"               numeric,
    "Dividend Streak"                                  numeric default 0,
    "Price Target - #"                                 numeric default 0,
    "Analyst Rating"                                   numeric default 0,
    "# Strong Sell Ratings"                            numeric default 0,
    "# Strong Buys Ratings"                            numeric default 0,
    "# Hold Ratings"                                   numeric default 0,
    "# Buys Ratings"                                   numeric default 0,
    "# Sell Ratings"                                   numeric default 0,
    "Shrs Out"                                         numeric default 0,
    "Shrs Out (-1FY)"                                  numeric default 0,
    "Full Time Employees (FQ)"                         numeric default 0,
    "Full Time Employees (FY)"                         numeric default 0,
    "Full Time Employees (-1FY)"                       numeric default 0,
    "Full Time Employees (-2FY)"                       numeric default 0,
    "Full Time Employees (-3FY)"                       numeric default 0,
    "Avg Employees (5YAVGFY)"                          numeric default 0,
    "EPS Norm - Est # (FY1E)"                          numeric default 0,
    "Price Target - # (3M Ago)"                        numeric default 0,
    "Price Target - # (6M Ago)"                        numeric default 0,
    "Price Target - # (YTD Ago)"                       numeric default 0,
    "Price Target - # (1Y Ago)"                        numeric default 0,
    "Price Target - # (1W Ago)"                        numeric default 0,
    "Price Target - # (1M Ago)"                        numeric default 0,
    "Price Target - # (MTD Ago)"                       numeric default 0,
    "Price Target - # (QTD Ago)"                       numeric default 0,
    "Gain (Loss) On Sale Of Assets (LTM)"      numeric default 0,
    "Impairment of Goodwill (FQ)"              numeric default 0,
    "Impairment of Goodwill (LTM)"             numeric default 0,
    "Impairment of Goodwill (-1FY)"            numeric default 0,
    "Impairment of Goodwill (FY)"              numeric default 0,
    "Asset Writedown (LTM)"                    numeric default 0,
    "Asset Writedown (FY)"                     numeric default 0,
    "Asset Writedown (-1FY)"                   numeric default 0,
    "Restructuring Charges (LTM)"              numeric default 0,
    "Restructuring Charges (FQ)"               numeric default 0,
    "Restructuring Charges (-1FY)"             numeric default 0,
    "Restructuring Charges (FY)"               numeric default 0,
    "Merger & Restructuring Charges (LTM)"     numeric default 0,
    "Other Unusual Items/Total (LTM)"          numeric default 0,
    "Asset Writedown (FQ)"                     numeric default 0,
    "Asset Writedown (5YAVGFQ)"                numeric default 0,
    "Impairment of Goodwill (5YAVGFQ)"         numeric default 0,
    "Restructuring Charges (5YAVGFQ)"          numeric default 0,
    "Merger & Restructuring Charges (FQ)"      numeric default 0,
    "Merger & Restructuring Charges (FY)"      numeric default 0,
    "Merger & Restructuring Charges (5YAVGFQ)" numeric default 0,
    "Description"                                      text,
    "Fiscal Month"                                     integer,
    "Fiscal Quarter"                                   integer,
    "Fiscal Year"                                      integer,
    "Reporting Lag"                            numeric,
    "Next Income Statement Report Date"        date,
    "Reporting Interval"                       integer,
    "Earnings Report (Frequency)"              text
);

comment on table equities is 'Equities screening data with financial metrics and company information';

alter table equities
    owner to postgres;

