create view vw_features_efficiency_ratios
            (isin, cogs_to_revenue, opex_to_revenue, sga_to_revenue, rnd_to_revenue, interest_to_revenue, sga_trend_yoy,
             operating_leverage_proxy, cost_efficiency_score, marketing_to_revenue, marketing_trend_yoy,
             marketing_vs_5y_avg, sga_vs_5y_avg, sga_efficiency_trend, rnd_ltm, rnd_fq, rnd_fy, rnd_1fqfq, rnd_2fqfq,
             rnd_3fqfq, rnd_4fqfq, rnd_1fy, rnd_2fy, rnd_3fy, rnd_4fy, rnd_intensity_ltm, rnd_intensity_fy,
             rnd_intensity_trend, rnd_qoq_growth, rnd_yoy_growth, rnd_cagr_3y, rnd_per_employee, rnd_to_gross_profit,
             rnd_roi_proxy, rnd_increasing_flag, rnd_cut_flag, high_rnd_intensity_flag)
as
SELECT isin,
       csf.cogs_to_revenue,
       csf.opex_to_revenue,
       csf.sga_to_revenue,
       csf.rnd_to_revenue,
       csf.interest_to_revenue,
       csf.sga_trend_yoy,
       csf.operating_leverage_proxy,
       csf.cost_efficiency_score,
       csf.marketing_to_revenue,
       csf.marketing_trend_yoy,
       csf.marketing_vs_5y_avg,
       csf.sga_vs_5y_avg,
       csf.sga_efficiency_trend,
       rtf.rnd_ltm,
       rtf.rnd_fq,
       rtf.rnd_fy,
       rtf.rnd_1fqfq,
       rtf.rnd_2fqfq,
       rtf.rnd_3fqfq,
       rtf.rnd_4fqfq,
       rtf.rnd_1fy,
       rtf.rnd_2fy,
       rtf.rnd_3fy,
       rtf.rnd_4fy,
       rtf.rnd_intensity_ltm,
       rtf.rnd_intensity_fy,
       rtf.rnd_intensity_trend,
       rtf.rnd_qoq_growth,
       rtf.rnd_yoy_growth,
       rtf.rnd_cagr_3y,
       rtf.rnd_per_employee,
       rtf.rnd_to_gross_profit,
       rtf.rnd_roi_proxy,
       rtf.rnd_increasing_flag,
       rtf.rnd_cut_flag,
       rtf.high_rnd_intensity_flag
FROM calc_cost_structure_features()             csf(isin, cogs_to_revenue, opex_to_revenue, sga_to_revenue,
                                                    rnd_to_revenue, interest_to_revenue, sga_trend_yoy,
                                                    operating_leverage_proxy, cost_efficiency_score,
                                                    marketing_to_revenue, marketing_trend_yoy, marketing_vs_5y_avg,
                                                    sga_vs_5y_avg, sga_efficiency_trend)
         FULL JOIN calc_rnd_temporal_features() rtf(isin, rnd_ltm, rnd_fq, rnd_fy, rnd_1fqfq, rnd_2fqfq, rnd_3fqfq,
                                                    rnd_4fqfq, rnd_1fy, rnd_2fy, rnd_3fy, rnd_4fy, rnd_intensity_ltm,
                                                    rnd_intensity_fy, rnd_intensity_trend, rnd_qoq_growth,
                                                    rnd_yoy_growth, rnd_cagr_3y, rnd_per_employee, rnd_to_gross_profit,
                                                    rnd_roi_proxy, rnd_increasing_flag, rnd_cut_flag,
                                                    high_rnd_intensity_flag) USING (isin);

alter table vw_features_efficiency_ratios
    owner to postgres;

