create view vw_features_revenue_forecasting
            (isin, revenue_est_spread, revenue_beat_potential, revenue_est_revision_trend, ebitda_est_vs_actual,
             forward_revenue_multiple, revenue_estimate_count, revenue_guidance_gap, consensus_revenue_growth,
             ebit_estimate_spread, forward_ebitda_margin, revenue_acceleration, estimate_confidence_score,
             revenue_est_avg_fy1e, revenue_est_med_fy1e, revenue_est_avg_ntm, revenue_est_med_ntm,
             revenue_avg_med_diff_pct, revenue_consensus_strength, revenue_revision_trend, revenue_vs_current,
             revenue_fq, revenue_fy, revenue_ltm, revenue_5y_avg, revenue_1fqfq, revenue_2fqfq, revenue_3fqfq,
             revenue_4fqfq, revenue_1fy, revenue_2fy, revenue_3fy, revenue_4fy, revenue_yoy_growth, revenue_vs_5y_avg,
             revenue_ltm_vs_fy, revenue_fq_vs_5y_avg_fq, revenue_qoq_growth, revenue_qoq_2q, revenue_qoq_3q,
             revenue_qoq_4q, revenue_yoy_quarterly, revenue_2y_growth, revenue_3y_growth, revenue_4y_growth,
             revenue_cagr_3y, revenue_cagr_4y, revenue_4q_trend, revenue_4q_avg, revenue_fq_vs_4q_avg,
             revenue_growth_flag, revenue_stability_score, revenue_accelerating_flag, revenue_positive_qoq_streak)
as
SELECT isin,
       rff.revenue_est_spread,
       rff.revenue_beat_potential,
       rff.revenue_est_revision_trend,
       rff.ebitda_est_vs_actual,
       rff.forward_revenue_multiple,
       rff.revenue_estimate_count,
       rff.revenue_guidance_gap,
       rff.consensus_revenue_growth,
       rff.ebit_estimate_spread,
       rff.forward_ebitda_margin,
       rff.revenue_acceleration,
       rff.estimate_confidence_score,
       rec.revenue_est_avg_fy1e,
       rec.revenue_est_med_fy1e,
       rec.revenue_est_avg_ntm,
       rec.revenue_est_med_ntm,
       rec.revenue_avg_med_diff_pct,
       rec.revenue_consensus_strength,
       rec.revenue_revision_trend,
       rec.revenue_vs_current,
       rqf.revenue_fq,
       rqf.revenue_fy,
       rqf.revenue_ltm,
       rqf.revenue_5y_avg,
       rqf.revenue_1fqfq,
       rqf.revenue_2fqfq,
       rqf.revenue_3fqfq,
       rqf.revenue_4fqfq,
       rqf.revenue_1fy,
       rqf.revenue_2fy,
       rqf.revenue_3fy,
       rqf.revenue_4fy,
       rqf.revenue_yoy_growth,
       rqf.revenue_vs_5y_avg,
       rqf.revenue_ltm_vs_fy,
       rqf.revenue_fq_vs_5y_avg_fq,
       rqf.revenue_qoq_growth,
       rqf.revenue_qoq_2q,
       rqf.revenue_qoq_3q,
       rqf.revenue_qoq_4q,
       rqf.revenue_yoy_quarterly,
       rqf.revenue_2y_growth,
       rqf.revenue_3y_growth,
       rqf.revenue_4y_growth,
       rqf.revenue_cagr_3y,
       rqf.revenue_cagr_4y,
       rqf.revenue_4q_trend,
       rqf.revenue_4q_avg,
       rqf.revenue_fq_vs_4q_avg,
       rqf.revenue_growth_flag,
       rqf.revenue_stability_score,
       rqf.revenue_accelerating_flag,
       rqf.revenue_positive_qoq_streak
FROM calc_revenue_forecast_features()                rff(isin, revenue_est_spread, revenue_beat_potential,
                                                         revenue_est_revision_trend, ebitda_est_vs_actual,
                                                         forward_revenue_multiple, revenue_estimate_count,
                                                         revenue_guidance_gap, consensus_revenue_growth,
                                                         ebit_estimate_spread, forward_ebitda_margin,
                                                         revenue_acceleration, estimate_confidence_score)
         FULL JOIN calc_revenue_estimate_consensus() rec(isin, revenue_est_avg_fy1e, revenue_est_med_fy1e,
                                                         revenue_est_avg_ntm, revenue_est_med_ntm,
                                                         revenue_avg_med_diff_pct, revenue_consensus_strength,
                                                         revenue_revision_trend, revenue_vs_current) USING (isin)
         FULL JOIN calc_revenue_quarterly_features() rqf(isin, revenue_fq, revenue_fy, revenue_ltm, revenue_5y_avg,
                                                         revenue_1fqfq, revenue_2fqfq, revenue_3fqfq, revenue_4fqfq,
                                                         revenue_1fy, revenue_2fy, revenue_3fy, revenue_4fy,
                                                         revenue_yoy_growth, revenue_vs_5y_avg, revenue_ltm_vs_fy,
                                                         revenue_fq_vs_5y_avg_fq, revenue_qoq_growth, revenue_qoq_2q,
                                                         revenue_qoq_3q, revenue_qoq_4q, revenue_yoy_quarterly,
                                                         revenue_2y_growth, revenue_3y_growth, revenue_4y_growth,
                                                         revenue_cagr_3y, revenue_cagr_4y, revenue_4q_trend,
                                                         revenue_4q_avg, revenue_fq_vs_4q_avg, revenue_growth_flag,
                                                         revenue_stability_score, revenue_accelerating_flag,
                                                         revenue_positive_qoq_streak) USING (isin);

alter table vw_features_revenue_forecasting
    owner to postgres;

