create view vw_features_earnings_quality_extended
            (isin, net_income_is_fq, net_income_is_ltm, net_income_is_fy, net_income_adj_ltm, normalized_ni_ltm,
             net_income_is_1fqfq, net_income_is_2fqfq, net_income_is_3fqfq, net_income_is_4fqfq, net_income_is_1fy,
             net_income_is_2fy, net_income_is_3fy, net_income_is_4fy, net_income_is_5yavgfq, net_income_is_5yavgltm,
             normalized_ni_5yavgfq, normalized_ni_5yavgltm, net_income_growth_yoy, net_income_margin_ltm,
             ni_adjustment_ratio, net_income_positive_years, earnings_quality_composite, net_income_qoq_growth,
             net_income_yoy_quarterly, net_income_vs_5y_avg, normalized_ni_vs_5y_avg, other_unusual_items_ltm,
             impairment_goodwill_ltm, asset_writedown_ltm, restructuring_charges_ltm, total_unusual_items,
             unusual_items_to_revenue, unusual_items_to_ebitda, has_unusual_items_flag, earnings_quality_impact,
             eps_cont_ltm, eps_cont_fq, eps_cont_fy, eps_cont_1fqfq, eps_cont_2fqfq, eps_cont_3fqfq, eps_cont_4fqfq,
             eps_cont_1fy, eps_cont_2fy, eps_cont_3fy, eps_cont_4fy, eps_cont_qoq_growth, eps_cont_yoy_growth,
             eps_cont_cagr_3y, eps_cont_vs_total_eps, eps_cont_positive_streak, eps_cont_trajectory_score,
             discontinued_ops_impact, core_earnings_stability)
as
SELECT isin,
       nic.net_income_is_fq,
       nic.net_income_is_ltm,
       nic.net_income_is_fy,
       nic.net_income_adj_ltm,
       nic.normalized_ni_ltm,
       nic.net_income_is_1fqfq,
       nic.net_income_is_2fqfq,
       nic.net_income_is_3fqfq,
       nic.net_income_is_4fqfq,
       nic.net_income_is_1fy,
       nic.net_income_is_2fy,
       nic.net_income_is_3fy,
       nic.net_income_is_4fy,
       nic.net_income_is_5yavgfq,
       nic.net_income_is_5yavgltm,
       nic.normalized_ni_5yavgfq,
       nic.normalized_ni_5yavgltm,
       nic.net_income_growth_yoy,
       nic.net_income_margin_ltm,
       nic.ni_adjustment_ratio,
       nic.net_income_positive_years,
       nic.earnings_quality_composite,
       nic.net_income_qoq_growth,
       nic.net_income_yoy_quarterly,
       nic.net_income_vs_5y_avg,
       nic.normalized_ni_vs_5y_avg,
       uif.other_unusual_items_ltm,
       uif.impairment_goodwill_ltm,
       uif.asset_writedown_ltm,
       uif.restructuring_charges_ltm,
       uif.total_unusual_items,
       uif.unusual_items_to_revenue,
       uif.unusual_items_to_ebitda,
       uif.has_unusual_items_flag,
       uif.earnings_quality_impact,
       ecf.eps_cont_ltm,
       ecf.eps_cont_fq,
       ecf.eps_cont_fy,
       ecf.eps_cont_1fqfq,
       ecf.eps_cont_2fqfq,
       ecf.eps_cont_3fqfq,
       ecf.eps_cont_4fqfq,
       ecf.eps_cont_1fy,
       ecf.eps_cont_2fy,
       ecf.eps_cont_3fy,
       ecf.eps_cont_4fy,
       ecf.eps_cont_qoq_growth,
       ecf.eps_cont_yoy_growth,
       ecf.eps_cont_cagr_3y,
       ecf.eps_cont_vs_total_eps,
       ecf.eps_cont_positive_streak,
       ecf.eps_cont_trajectory_score,
       ecf.discontinued_ops_impact,
       ecf.core_earnings_stability
FROM calc_net_income_comprehensive()              nic(isin, net_income_is_fq, net_income_is_ltm, net_income_is_fy,
                                                      net_income_adj_ltm, normalized_ni_ltm, net_income_is_1fqfq,
                                                      net_income_is_2fqfq, net_income_is_3fqfq, net_income_is_4fqfq,
                                                      net_income_is_1fy, net_income_is_2fy, net_income_is_3fy,
                                                      net_income_is_4fy, net_income_is_5yavgfq, net_income_is_5yavgltm,
                                                      normalized_ni_5yavgfq, normalized_ni_5yavgltm,
                                                      net_income_growth_yoy, net_income_margin_ltm, ni_adjustment_ratio,
                                                      net_income_positive_years, earnings_quality_composite,
                                                      net_income_qoq_growth, net_income_yoy_quarterly,
                                                      net_income_vs_5y_avg, normalized_ni_vs_5y_avg)
         FULL JOIN calc_unusual_items_features()  uif(isin, other_unusual_items_ltm, impairment_goodwill_ltm,
                                                      asset_writedown_ltm, restructuring_charges_ltm,
                                                      total_unusual_items, unusual_items_to_revenue,
                                                      unusual_items_to_ebitda, has_unusual_items_flag,
                                                      earnings_quality_impact) USING (isin)
         FULL JOIN calc_eps_continuing_features() ecf(isin, eps_cont_ltm, eps_cont_fq, eps_cont_fy, eps_cont_1fqfq,
                                                      eps_cont_2fqfq, eps_cont_3fqfq, eps_cont_4fqfq, eps_cont_1fy,
                                                      eps_cont_2fy, eps_cont_3fy, eps_cont_4fy, eps_cont_qoq_growth,
                                                      eps_cont_yoy_growth, eps_cont_cagr_3y, eps_cont_vs_total_eps,
                                                      eps_cont_positive_streak, eps_cont_trajectory_score,
                                                      discontinued_ops_impact, core_earnings_stability) USING (isin);

alter table vw_features_earnings_quality_extended
    owner to postgres;

