create view vw_features_balance_sheet
            (isin, ticker, name, industry, sector, trading_country, region, country, exchange, assets_fq, assets_fy,
             assets_ltm, assets_1fq, assets_2fq, assets_3fq, assets_4fq, assets_1fy, assets_2fy, assets_3fy, assets_4fy,
             assets_qoq_growth, assets_yoy_growth, assets_3y_cagr, asset_growth_accel, asset_base_stable, inventory_ltm,
             inventory_fq, inventory_fy, inventory_1fq, inventory_2fq, inventory_3fq, inventory_4fq, inventory_1fy,
             inventory_2fy, inventory_3fy, inventory_4fy, inventory_qoq_change, inventory_yoy_change,
             inventory_4q_trend, inventory_vs_5y_avg, inventory_days, inventory_turnover, inventory_to_revenue,
             inventory_to_assets, inventory_buildup_flag, inventory_reduction_flag, inventory_volatility, goodwill_fq,
             goodwill_ltm, goodwill_fy, goodwill_1fq, goodwill_2fq, goodwill_3fq, goodwill_4fq, goodwill_1fy,
             goodwill_2fy, goodwill_3fy, goodwill_4fy, goodwill_qoq_change, goodwill_yoy_change, goodwill_3y_growth,
             goodwill_vs_5y_avg, recent_acquisition_flag, goodwill_accumulation_rate, goodwill_to_assets_trend,
             impairment_risk_score, goodwill_concentration)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.industry,
       id.sector,
       id.trading_country,
       id.region,
       id.country,
       id.exchange,
       tat.assets_fq,
       tat.assets_fy,
       tat.assets_ltm,
       tat.assets_1fq,
       tat.assets_2fq,
       tat.assets_3fq,
       tat.assets_4fq,
       tat.assets_1fy,
       tat.assets_2fy,
       tat.assets_3fy,
       tat.assets_4fy,
       tat.assets_qoq_growth,
       tat.assets_yoy_growth,
       tat.assets_3y_cagr,
       tat.asset_growth_accel,
       tat.asset_base_stable,
       itf.inventory_ltm,
       itf.inventory_fq,
       itf.inventory_fy,
       itf.inventory_1fq,
       itf.inventory_2fq,
       itf.inventory_3fq,
       itf.inventory_4fq,
       itf.inventory_1fy,
       itf.inventory_2fy,
       itf.inventory_3fy,
       itf.inventory_4fy,
       itf.inventory_qoq_change,
       itf.inventory_yoy_change,
       itf.inventory_4q_trend,
       itf.inventory_vs_5y_avg,
       itf.inventory_days,
       itf.inventory_turnover,
       itf.inventory_to_revenue,
       itf.inventory_to_assets,
       itf.inventory_buildup_flag,
       itf.inventory_reduction_flag,
       itf.inventory_volatility,
       gtf.goodwill_fq,
       gtf.goodwill_ltm,
       gtf.goodwill_fy,
       gtf.goodwill_1fq,
       gtf.goodwill_2fq,
       gtf.goodwill_3fq,
       gtf.goodwill_4fq,
       gtf.goodwill_1fy,
       gtf.goodwill_2fy,
       gtf.goodwill_3fy,
       gtf.goodwill_4fy,
       gtf.goodwill_qoq_change,
       gtf.goodwill_yoy_change,
       gtf.goodwill_3y_growth,
       gtf.goodwill_vs_5y_avg,
       gtf.recent_acquisition_flag,
       gtf.goodwill_accumulation_rate,
       gtf.goodwill_to_assets_trend,
       gtf.impairment_risk_score,
       gtf.goodwill_concentration
FROM vw_identifier_columns                            id
         LEFT JOIN calc_total_assets_temporal()       tat(isin, assets_fq, assets_fy, assets_ltm, assets_1fq,
                                                          assets_2fq, assets_3fq, assets_4fq, assets_1fy, assets_2fy,
                                                          assets_3fy, assets_4fy, assets_qoq_growth, assets_yoy_growth,
                                                          assets_3y_cagr, asset_growth_accel, asset_base_stable)
                   USING (isin)
         LEFT JOIN calc_inventory_temporal_features() itf(isin, inventory_ltm, inventory_fq, inventory_fy,
                                                          inventory_1fq, inventory_2fq, inventory_3fq, inventory_4fq,
                                                          inventory_1fy, inventory_2fy, inventory_3fy, inventory_4fy,
                                                          inventory_qoq_change, inventory_yoy_change,
                                                          inventory_4q_trend, inventory_vs_5y_avg, inventory_days,
                                                          inventory_turnover, inventory_to_revenue, inventory_to_assets,
                                                          inventory_buildup_flag, inventory_reduction_flag,
                                                          inventory_volatility) USING (isin)
         LEFT JOIN calc_goodwill_temporal_features()  gtf(isin, goodwill_fq, goodwill_ltm, goodwill_fy, goodwill_1fq,
                                                          goodwill_2fq, goodwill_3fq, goodwill_4fq, goodwill_1fy,
                                                          goodwill_2fy, goodwill_3fy, goodwill_4fy, goodwill_qoq_change,
                                                          goodwill_yoy_change, goodwill_3y_growth, goodwill_vs_5y_avg,
                                                          recent_acquisition_flag, goodwill_accumulation_rate,
                                                          goodwill_to_assets_trend, impairment_risk_score,
                                                          goodwill_concentration) USING (isin);

comment on view vw_features_balance_sheet is 'Balance sheet temporal analysis including assets, inventory, and goodwill trends.
    Source functions: calc_total_assets_temporal, calc_inventory_temporal_features, calc_goodwill_temporal_features';

alter table vw_features_balance_sheet
    owner to postgres;

