create view vw_features_cost_structure
            (isin, ticker, name, industry, sector, trading_country, region, country, exchange, cogs_to_revenue,
             opex_to_revenue, sga_to_revenue, rnd_to_revenue, interest_to_revenue, sga_trend_yoy,
             operating_leverage_proxy, cost_efficiency_score, marketing_to_revenue, marketing_trend_yoy,
             marketing_vs_5y_avg, sga_vs_5y_avg, sga_efficiency_trend, rnd_ltm, rnd_fq, rnd_fy, rnd_1fqfq, rnd_2fqfq,
             rnd_3fqfq, rnd_4fqfq, rnd_1fy, rnd_2fy, rnd_3fy, rnd_4fy, rnd_intensity_ltm, rnd_intensity_fy,
             rnd_intensity_trend, rnd_qoq_growth, rnd_yoy_growth, rnd_cagr_3y, rnd_per_employee, rnd_to_gross_profit,
             rnd_roi_proxy, rnd_increasing_flag, rnd_cut_flag, high_rnd_intensity_flag, interest_income_ltm,
             interest_expense_ltm, net_interest_income, interest_coverage_ratio, interest_income_to_revenue,
             interest_expense_to_revenue, net_interest_margin_proxy)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.industry,
       id.sector,
       id.trading_country,
       id.region,
       id.country,
       id.exchange,
       csf.cogs_to_revenue,
       csf.opex_to_revenue,
       csf.sga_to_revenue,
       csf.rnd_to_revenue,
       csf.interest_to_revenue,
       csf.sga_trend_yoy,
       csf.operating_leverage_proxy,
       csf.cost_efficiency_score,
       csf.marketing_to_revenue,
       csf.marketing_trend_yoy,
       csf.marketing_vs_5y_avg,
       csf.sga_vs_5y_avg,
       csf.sga_efficiency_trend,
       rtf.rnd_ltm,
       rtf.rnd_fq,
       rtf.rnd_fy,
       rtf.rnd_1fqfq,
       rtf.rnd_2fqfq,
       rtf.rnd_3fqfq,
       rtf.rnd_4fqfq,
       rtf.rnd_1fy,
       rtf.rnd_2fy,
       rtf.rnd_3fy,
       rtf.rnd_4fy,
       rtf.rnd_intensity_ltm,
       rtf.rnd_intensity_fy,
       rtf.rnd_intensity_trend,
       rtf.rnd_qoq_growth,
       rtf.rnd_yoy_growth,
       rtf.rnd_cagr_3y,
       rtf.rnd_per_employee,
       rtf.rnd_to_gross_profit,
       rtf.rnd_roi_proxy,
       rtf.rnd_increasing_flag,
       rtf.rnd_cut_flag,
       rtf.high_rnd_intensity_flag,
       iif.interest_income_ltm,
       iif.interest_expense_ltm,
       iif.net_interest_income,
       iif.interest_coverage_ratio,
       iif.interest_income_to_revenue,
       iif.interest_expense_to_revenue,
       iif.net_interest_margin_proxy
FROM vw_identifier_columns                         id
         LEFT JOIN calc_cost_structure_features()  csf(isin, cogs_to_revenue, opex_to_revenue, sga_to_revenue,
                                                       rnd_to_revenue, interest_to_revenue, sga_trend_yoy,
                                                       operating_leverage_proxy, cost_efficiency_score,
                                                       marketing_to_revenue, marketing_trend_yoy, marketing_vs_5y_avg,
                                                       sga_vs_5y_avg, sga_efficiency_trend) USING (isin)
         LEFT JOIN calc_rnd_temporal_features()    rtf(isin, rnd_ltm, rnd_fq, rnd_fy, rnd_1fqfq, rnd_2fqfq, rnd_3fqfq,
                                                       rnd_4fqfq, rnd_1fy, rnd_2fy, rnd_3fy, rnd_4fy, rnd_intensity_ltm,
                                                       rnd_intensity_fy, rnd_intensity_trend, rnd_qoq_growth,
                                                       rnd_yoy_growth, rnd_cagr_3y, rnd_per_employee,
                                                       rnd_to_gross_profit, rnd_roi_proxy, rnd_increasing_flag,
                                                       rnd_cut_flag, high_rnd_intensity_flag) USING (isin)
         LEFT JOIN calc_interest_income_features() iif(isin, interest_income_ltm, interest_expense_ltm,
                                                       net_interest_income, interest_coverage_ratio,
                                                       interest_income_to_revenue, interest_expense_to_revenue,
                                                       net_interest_margin_proxy) USING (isin);

comment on view vw_features_cost_structure is 'Cost structure metrics including SG&A, R&D intensity, and interest analysis.
    Source functions: calc_cost_structure_features, calc_rnd_temporal_features, calc_interest_income_features';

alter table vw_features_cost_structure
    owner to postgres;

