create view vw_features_materialized_view
            (ticker, isin, name, region, country, trading_country, exchange, sector, industry, next_earnings_when,
             next_earnings_status, dividend_record_currency, dividend_record_frequency, current_fiscal_quarter,
             next_fiscal_quarter, next_earnings_report, earnings_report_frequency, last_updated,
             income_statement_report_date, next_earnings, fy_end_date, next_fy_end_date,
             next_income_statement_report_date, price_target, price_target_median, dividend_record_amount, market_cap,
             enterprise_value, last_price, price_target_low, price_target_high, price_target_high_1w_ago,
             price_target_high_1m_ago, price_target_high_6m_ago, price_target_high_mtd_ago, price_target_high_3m_ago,
             price_target_high_qtd_ago, price_target_high_1y_ago, price_target_high_ytd_ago, price_target_low_1w_ago,
             price_target_low_1m_ago, price_target_low_3m_ago, price_target_low_6m_ago, price_target_low_mtd_ago,
             price_target_low_qtd_ago, price_target_low_ytd_ago, price_target_low_1y_ago, price_target_median_1w_ago,
             price_target_median_1m_ago, price_target_median_3m_ago, price_target_median_6m_ago,
             price_target_median_mtd_ago, price_target_median_qtd_ago, price_target_median_ytd_ago,
             price_target_median_1y_ago, price_target_count, price_target_count_3m_ago, price_target_count_6m_ago,
             price_target_count_ytd_ago, price_target_count_1y_ago, price_target_count_1w_ago,
             price_target_count_1m_ago, price_target_count_mtd_ago, price_target_count_qtd_ago, p_e_ratio, p_b_ratio,
             ev_ebitda_ratio, ev_sales_ratio, dividend_yield, peg_ratio, ev_sales_trend_1y, ev_ebitda_momentum,
             p_e_momentum_yoy, p_e_momentum_qoq, ev_sales_vs_3y_avg, ev_ebitda_vs_3y_avg, p_e_vs_3y_avg,
             ev_sales_forward_discount, ev_ebitda_forward_discount, p_e_forward_discount, p_b_vs_5y_avg,
             ev_sales_qoq_1q, p_e_vs_5y_avg_ext, p_b_momentum_yoy, forward_pe_premium, price_momentum_1m,
             price_momentum_3m, price_momentum_6m, price_momentum_1y, price_momentum_5d, ema_crossover_20_50,
             ema_crossover_50_250, price_vs_ema_20d, price_vs_ema_250d, pct_off_52w_high, pct_above_52w_low,
             range_52w_position, beta_momentum, volatility_regime, ema_slope_20d, ema_trend_consistency,
             price_vs_ema_100d, near_52w_high_flag, near_52w_low_flag, volume_momentum_score, breakout_signal,
             high_volume_flag, low_volume_flag, volatility_compression, volatility_term_structure, roe, roa,
             gross_margin_pct, operating_margin_pct, net_margin_pct, ebitda_margin_pct, roic, rnd_intensity,
             equity_multiplier, gross_margin_trend_yoy, operating_margin_trend, net_margin_trend_yoy,
             ebitda_margin_trend, margin_expansion_flag, has_goodwill_impairment, has_asset_writedown,
             has_restructuring, goodwill_to_assets_pct, intangible_intensity, exceptional_items_to_ebitda,
             altman_z_score, altman_z_trend, current_ratio, quick_ratio, distress_risk_score, liquidity_stress_score,
             working_capital_trend, cash_runway_months, accumulated_deficit_flag, adequate_cash_buffer,
             goodwill_change_rate, restructuring_intensity, exceptional_items_frequency, merger_impact_ratio,
             non_operating_income_share, asset_sale_boost, accounting_quality_score, debt_to_equity, debt_to_assets,
             equity_ratio, interest_coverage, cash_ratio, working_capital_ratio, asset_turnover, inventory_turnover,
             receivables_days, working_capital_turns, cash_to_assets_pct, cash_change_qoq, cash_vs_5y_avg,
             inventory_change_yoy, inventory_vs_5y_avg, working_capital_vs_5y_avg, retained_earnings_vs_5y,
             intangibles_growth_flag, asset_quality_score, balance_sheet_strength, debt_maturity_risk,
             analyst_bullish_pct, analyst_bearish_pct, analyst_neutral_pct, upside_potential, price_target_spread_pct,
             price_target_revision_1m, price_target_revision_3m, eps_revision_momentum, analyst_rating_normalized,
             analyst_coverage_quality, pt_momentum_1w, pt_momentum_1m, pt_momentum_3m, pt_momentum_6m, pt_momentum_1y,
             analyst_coverage_change_1m, analyst_coverage_change_3m, analyst_coverage_change_1y, eps_surprise_pct,
             revenue_surprise_pct, eps_adjustment_ratio, gaap_adj_eps_gap_pct, ebitda_adjustment_ratio,
             eps_quarterly_trend, eps_yoy_growth, eps_qoq_growth, eps_yoy_quarterly, eps_positive_streak, eps_cagr_3y,
             eps_cagr_5y, eps_improvement_count, eps_trajectory_score, eps_adjustment_spread_ltm,
             eps_adjustment_spread_fy, eps_adjustment_spread_1fy, eps_adjustment_spread_fq, eps_adjustment_spread_1fqfq,
             eps_adjustment_spread_2fqfq, eps_adjustment_spread_3fqfq, eps_adjustment_spread_4fqfq,
             eps_adjustment_spread_2fy, eps_adjustment_spread_3fy, eps_adjustment_spread_4fy, eps_adjustment_pct,
             net_income_adjustment_ratio_ltm, net_income_adjustment_ratio_fy, net_income_adjustment_ratio_1fy,
             net_income_adjustment_ratio_fq, net_income_adjustment_ratio_5yavgfq, net_income_adjustment_ratio_1fqfq,
             net_income_adjustment_ratio_2fqfq, net_income_adjustment_ratio_3fqfq, net_income_adjustment_ratio_4fqfq,
             net_income_adjustment_ratio_2fy, net_income_adjustment_ratio_3fy, net_income_adjustment_ratio_4fy,
             net_income_adjustment_pct, ebitda_adjustment_pct_ltm, ebitda_adjustment_pct_fy, ebitda_adjustment_pct_1fy,
             ebitda_adjustment_pct_fq, ebitda_adjustment_pct_1fqfq, ebitda_adjustment_pct_2fqfq,
             ebitda_adjustment_pct_3fqfq, ebitda_adjustment_pct_4fqfq, ebitda_adjustment_pct_2fy,
             ebitda_adjustment_pct_3fy, ebitda_adjustment_pct_4fy, ebit_adjustment_pct_ltm, ebit_adjustment_pct_fy,
             ebit_adjustment_pct_1fy, ebit_adjustment_pct_fq, ebit_adjustment_pct_1fqfq, ebit_adjustment_pct_2fqfq,
             ebit_adjustment_pct_3fqfq, ebit_adjustment_pct_4fqfq, ebit_adjustment_pct_2fy, ebit_adjustment_pct_3fy,
             ebit_adjustment_pct_4fy, earnings_quality_score, earnings_quality_warning, forward_eps_gaap_adj_spread,
             gaap_revision_momentum, gaap_revision_1m, gaap_revision_3m, gaap_revision_6m, gaap_revision_1y,
             gaap_vs_norm_revision_spread, gaap_revision_acceleration, gaap_positive_revision_flag, revenue_growth_yoy,
             ebitda_growth_yoy, operating_income_growth, fcf_growth, revenue_cagr_5y, forward_revenue_growth,
             revenue_vs_5y_avg, revenue_est_spread, revenue_beat_potential, revenue_est_revision_trend,
             ebitda_est_vs_actual, forward_revenue_multiple, revenue_estimate_count, revenue_guidance_gap,
             consensus_revenue_growth, forward_ebitda_margin, revenue_acceleration, estimate_confidence_score,
             dividend_streak, dividend_yield_ltm, dividend_yield_ntm, dividend_payout_ratio, fcf_dividend_coverage,
             buyback_yield, total_shareholder_yield, dividend_growth_expectation, days_since_ex_date, days_to_payment,
             dividend_announced_flag, ex_date_approaching_flag, dividend_frequency_score, dividend_consistency,
             dividend_yield_vs_5y_avg, revenue_per_employee, profit_per_employee, ebitda_per_employee,
             assets_per_employee, fte_growth_1y_pct, fte_growth_3y_pct, workforce_stability, fte_growth_2y_pct,
             layoff_risk_flag, rapid_hiring_flag, sustainable_growth_flag, cfo_to_net_income, fcf_to_net_income,
             fcf_margin, cfo_growth_yoy, fcf_positive_ratio, acquisition_intensity, self_funding_ratio,
             fcf_positive_years, fcf_always_positive, capex_vs_5y_avg, underinvestment_flag, cfo_share_of_cf,
             cfi_share_of_cf, cff_share_of_cf, self_funding_flag, fcf_4q_improvement, cash_flow_quality_score,
             acquisition_to_fcf, sustainable_ma_flag, capex_yoy_growth, capex_qoq_growth, capex_3y_trend,
             capex_volatility, capex_acceleration, capex_cut_flag, overinvestment_flag, acquisitions_yoy_growth,
             acquisitions_vs_5y_avg, acquisitions_ltm_total, ma_intensity_score, serial_acquirer_flag,
             acquisition_pause_flag, total_investment_to_cfo, organic_vs_inorganic, investment_efficiency,
             cfo_quarterly_trend, cfi_quarterly_trend, cff_quarterly_trend, fcf_quarterly_trend, cfo_positive_quarters,
             cfi_negative_quarters, cash_burn_rate, financing_dependency, fiscal_quarter, fiscal_month, fiscal_year,
             days_to_earnings, earnings_report_recency, reporting_lag, fiscal_year_progress, days_since_last_report,
             days_to_fy_end, is_quarter_end_month, is_fy_end_month, earnings_season_flag, pre_earnings_window,
             post_earnings_window, reporting_freshness_score, piotroski_f_score, dilution_score, ebit_fq, ebit_ltm,
             ebit_fy, ebit_1fy, ebitda_fq, ebitda_ltm, ebitda_fy, ebitda_1fy, ebit_2fy, ebit_3fy, ebit_4fy, ebitda_2fy,
             ebitda_3fy, ebitda_4fy, ebit_1fqfq, ebit_2fqfq, ebit_3fqfq, ebit_4fqfq, ebitda_1fqfq, ebitda_2fqfq,
             ebitda_3fqfq, ebitda_4fqfq, ebit_5yavgfq, ebit_5yavgltm, ebitda_5yavgfq, ebitda_5yavgltm, ebit_adj_fq,
             ebit_adj_ltm, ebit_adj_fy, ebitda_adj_fq, ebitda_adj_ltm, ebitda_adj_fy, ebit_growth_yoy,
             ebitda_growth_yoy_comp, ebit_margin_ltm, ebitda_margin_ltm, ebit_positive_years, ebitda_positive_years,
             ebit_qoq_growth, ebitda_qoq_growth, ebit_cagr_3y, ebitda_cagr_3y, ebit_vs_5y_avg, ebitda_vs_5y_avg,
             net_income_is_fq, net_income_is_ltm, net_income_is_fy, net_income_adj_ltm, normalized_ni_ltm,
             net_income_is_1fqfq, net_income_is_2fqfq, net_income_is_3fqfq, net_income_is_4fqfq, net_income_is_1fy,
             net_income_is_2fy, net_income_is_3fy, net_income_is_4fy, net_income_is_5yavgfq, net_income_is_5yavgltm,
             normalized_ni_5yavgfq, normalized_ni_5yavgltm, net_income_growth_yoy, net_income_margin_ltm,
             ni_adjustment_ratio, net_income_positive_years, earnings_quality_composite_comp, net_income_qoq_growth,
             net_income_yoy_quarterly, net_income_vs_5y_avg, normalized_ni_vs_5y_avg, cfo_fq, cfo_ltm, cfo_fy, fcf_fq,
             fcf_ltm, fcf_fy, cfo_growth_yoy_comp, fcf_growth_yoy, fcf_margin_pct, fcf_yield, cfo_positive_years,
             beta_1y, beta_5y, beta_spread, beta_trend, high_beta_flag, low_beta_flag, beta_stability_score,
             cogs_to_revenue, opex_to_revenue, sga_to_revenue, rnd_to_revenue, interest_to_revenue, interest_income_ltm,
             interest_expense_ltm, net_interest_income, interest_coverage_ratio, interest_income_to_revenue,
             interest_expense_to_revenue, price_momentum_3y, price_momentum_5y, long_term_trend_score,
             multi_year_high_flag, secular_trend_flag, tangible_book_value, tangible_book_per_share,
             price_to_tangible_book, tangible_equity_ratio, intangibles_to_equity, goodwill_to_equity,
             working_capital_ltm, working_capital_fq, working_capital_fy, wc_to_revenue, wc_to_assets, wc_change_qoq,
             wc_change_yoy, days_working_capital, negative_wc_flag, wc_improvement_flag, other_unusual_items_ltm,
             total_unusual_items, unusual_items_to_revenue, unusual_items_to_ebitda, has_unusual_items_flag,
             revenue_est_avg_fy1e, revenue_est_med_fy1e, revenue_est_avg_ntm, revenue_est_med_ntm,
             revenue_avg_med_diff_pct, revenue_consensus_strength, revenue_vs_current, revenue_fq, revenue_1fq,
             revenue_2fq, revenue_3q, revenue_4q, revenue_fy, revenue_1fy, revenue_2fy, revenue_3fy, revenue_4fy,
             revenue_ltm, revenue_5y_avg, revenue_yoy_growth, revenue_1fy_vs_2fy, revenue_2fy_vs_3fy,
             revenue_3fy_vs_4fy, revenue_growth_flag, revenue_5yavgfq, revenue_5yavgltm, revenue_growth_yoy_temp,
             revenue_vs_5y_avg_fq_temp, revenue_vs_5y_avg_ltm_temp, revenue_fq_vs_avg_temp, revenue_momentum_temp,
             wc_fq_temp, wc_fy_temp, wc_ltm_temp, wc_5yavgfy, wc_1fq, wc_2fq, wc_3fq, wc_4fq, wc_1fy, wc_2fy, wc_3fy,
             wc_4fy, wc_qoq_change, wc_yoy_change, wc_4q_trend, wc_vs_5y_avg_temp, wc_positive_quarters,
             wc_improving_flag_temp, wc_volatility, debt_fq, debt_fy, debt_ltm, debt_1fq, debt_2fq, debt_3fq, debt_4fq,
             debt_1fy_temp, debt_2fy, debt_3fy, debt_4fy, debt_qoq_change, debt_yoy_change, debt_4q_trend, debt_3y_cagr,
             debt_deleveraging, debt_to_equity_trend, assets_fq, assets_fy, assets_ltm_temp, assets_1fq, assets_2fq,
             assets_3fq, assets_4fq, assets_1fy, assets_2fy, assets_3fy, assets_4fy, assets_qoq_growth,
             assets_yoy_growth, assets_3y_cagr, asset_growth_accel, asset_base_stable, gp_fq, gp_fy, gp_ltm_temp,
             gp_1fqfq, gp_2fqfq, gp_3fqfq, gp_4fqfq, gp_1fy, gp_2fy, gp_3fy, gp_4fy, gp_qoq_growth, gp_yoy_growth,
             gp_margin_fq, gp_margin_trend, gp_positive_quarters, gp_margin_expansion_temp, div_yield_ind,
             div_yield_1fy_ind, div_yield_5y_avg, div_yield_vs_5y_avg, div_yield_growth_expected, high_yield_flag,
             sustainable_dividend_flag, eps_cont_ltm, eps_cont_fq, eps_cont_fy, eps_cont_1fy, eps_cont_2fy,
             eps_cont_3fy, eps_cont_4fy, eps_cont_qoq_growth, eps_cont_yoy_growth, eps_cont_vs_total_eps,
             discontinued_ops_impact, rnd_fq, rnd_fy, rnd_1fy, rnd_2fy, rnd_3fy, rnd_4fy, rnd_intensity_ltm,
             rnd_yoy_growth, rnd_per_employee, high_rnd_intensity_flag, inventory_1fq, inventory_2fq, inventory_3fq,
             inventory_4fq, inventory_1fy, inventory_2fy, inventory_3fy, inventory_4fy, inventory_qoq_change,
             inventory_yoy_change, inventory_days, inventory_turnover_mv, goodwill_1fq, goodwill_2fq, goodwill_3fq,
             goodwill_4fq, goodwill_1fy, goodwill_2fy, goodwill_3fy, goodwill_4fy, goodwill_qoq_change,
             goodwill_yoy_change, goodwill_3y_growth, goodwill_concentration, recent_acquisition_flag,
             marketing_to_revenue, marketing_trend_yoy, marketing_vs_5y_avg, sga_vs_5y_avg, tangible_book_value_fy,
             tangible_book_value_ltm, tbv_yoy_growth, calculated_at)
as
SELECT ticker,
       isin,
       name,
       region,
       country,
       trading_country,
       exchange,
       sector,
       industry,
       next_earnings_when,
       next_earnings_status,
       dividend_record_currency,
       dividend_record_frequency,
       current_fiscal_quarter,
       next_fiscal_quarter,
       next_earnings_report,
       earnings_report_frequency,
       last_updated,
       income_statement_report_date,
       next_earnings,
       fy_end_date,
       next_fy_end_date,
       next_income_statement_report_date,
       price_target,
       price_target_median,
       dividend_record_amount,
       market_cap,
       enterprise_value,
       last_price,
       price_target_low,
       price_target_high,
       price_target_high_1w_ago,
       price_target_high_1m_ago,
       price_target_high_6m_ago,
       price_target_high_mtd_ago,
       price_target_high_3m_ago,
       price_target_high_qtd_ago,
       price_target_high_1y_ago,
       price_target_high_ytd_ago,
       price_target_low_1w_ago,
       price_target_low_1m_ago,
       price_target_low_3m_ago,
       price_target_low_6m_ago,
       price_target_low_mtd_ago,
       price_target_low_qtd_ago,
       price_target_low_ytd_ago,
       price_target_low_1y_ago,
       price_target_median_1w_ago,
       price_target_median_1m_ago,
       price_target_median_3m_ago,
       price_target_median_6m_ago,
       price_target_median_mtd_ago,
       price_target_median_qtd_ago,
       price_target_median_ytd_ago,
       price_target_median_1y_ago,
       price_target_count,
       price_target_count_3m_ago,
       price_target_count_6m_ago,
       price_target_count_ytd_ago,
       price_target_count_1y_ago,
       price_target_count_1w_ago,
       price_target_count_1m_ago,
       price_target_count_mtd_ago,
       price_target_count_qtd_ago,
       p_e_ratio,
       p_b_ratio,
       ev_ebitda_ratio,
       ev_sales_ratio,
       dividend_yield,
       peg_ratio,
       ev_sales_trend_1y,
       ev_ebitda_momentum,
       p_e_momentum_yoy,
       p_e_momentum_qoq,
       ev_sales_vs_3y_avg,
       ev_ebitda_vs_3y_avg,
       p_e_vs_3y_avg,
       ev_sales_forward_discount,
       ev_ebitda_forward_discount,
       p_e_forward_discount,
       p_b_vs_5y_avg,
       ev_sales_qoq_1q,
       p_e_vs_5y_avg_ext,
       p_b_momentum_yoy,
       forward_pe_premium,
       price_momentum_1m,
       price_momentum_3m,
       price_momentum_6m,
       price_momentum_1y,
       price_momentum_5d,
       ema_crossover_20_50,
       ema_crossover_50_250,
       price_vs_ema_20d,
       price_vs_ema_250d,
       pct_off_52w_high,
       pct_above_52w_low,
       range_52w_position,
       beta_momentum,
       volatility_regime,
       ema_slope_20d,
       ema_trend_consistency,
       price_vs_ema_100d,
       near_52w_high_flag,
       near_52w_low_flag,
       volume_momentum_score,
       breakout_signal,
       high_volume_flag,
       low_volume_flag,
       volatility_compression,
       volatility_term_structure,
       roe,
       roa,
       gross_margin_pct,
       operating_margin_pct,
       net_margin_pct,
       ebitda_margin_pct,
       roic,
       rnd_intensity,
       equity_multiplier,
       gross_margin_trend_yoy,
       operating_margin_trend,
       net_margin_trend_yoy,
       ebitda_margin_trend,
       margin_expansion_flag,
       has_goodwill_impairment,
       has_asset_writedown,
       has_restructuring,
       goodwill_to_assets_pct,
       intangible_intensity,
       exceptional_items_to_ebitda,
       altman_z_score,
       altman_z_trend,
       current_ratio,
       quick_ratio,
       distress_risk_score,
       liquidity_stress_score,
       working_capital_trend,
       cash_runway_months,
       accumulated_deficit_flag,
       adequate_cash_buffer,
       goodwill_change_rate,
       restructuring_intensity,
       exceptional_items_frequency,
       merger_impact_ratio,
       non_operating_income_share,
       asset_sale_boost,
       accounting_quality_score,
       debt_to_equity,
       debt_to_assets,
       equity_ratio,
       interest_coverage,
       cash_ratio,
       working_capital_ratio,
       asset_turnover,
       inventory_turnover,
       receivables_days,
       working_capital_turns,
       cash_to_assets_pct,
       cash_change_qoq,
       cash_vs_5y_avg,
       inventory_change_yoy,
       inventory_vs_5y_avg,
       working_capital_vs_5y_avg,
       retained_earnings_vs_5y,
       intangibles_growth_flag,
       asset_quality_score,
       balance_sheet_strength,
       debt_maturity_risk,
       analyst_bullish_pct,
       analyst_bearish_pct,
       analyst_neutral_pct,
       upside_potential,
       price_target_spread_pct,
       price_target_revision_1m,
       price_target_revision_3m,
       eps_revision_momentum,
       analyst_rating_normalized,
       analyst_coverage_quality,
       pt_momentum_1w,
       pt_momentum_1m,
       pt_momentum_3m,
       pt_momentum_6m,
       pt_momentum_1y,
       analyst_coverage_change_1m,
       analyst_coverage_change_3m,
       analyst_coverage_change_1y,
       eps_surprise_pct,
       revenue_surprise_pct,
       eps_adjustment_ratio,
       gaap_adj_eps_gap_pct,
       ebitda_adjustment_ratio,
       eps_quarterly_trend,
       eps_yoy_growth,
       eps_qoq_growth,
       eps_yoy_quarterly,
       eps_positive_streak,
       eps_cagr_3y,
       eps_cagr_5y,
       eps_improvement_count,
       eps_trajectory_score,
       eps_adjustment_spread_ltm,
       eps_adjustment_spread_fy,
       eps_adjustment_spread_1fy,
       eps_adjustment_spread_fq,
       eps_adjustment_spread_1fqfq,
       eps_adjustment_spread_2fqfq,
       eps_adjustment_spread_3fqfq,
       eps_adjustment_spread_4fqfq,
       eps_adjustment_spread_2fy,
       eps_adjustment_spread_3fy,
       eps_adjustment_spread_4fy,
       eps_adjustment_pct,
       net_income_adjustment_ratio_ltm,
       net_income_adjustment_ratio_fy,
       net_income_adjustment_ratio_1fy,
       net_income_adjustment_ratio_fq,
       net_income_adjustment_ratio_5yavgfq,
       net_income_adjustment_ratio_1fqfq,
       net_income_adjustment_ratio_2fqfq,
       net_income_adjustment_ratio_3fqfq,
       net_income_adjustment_ratio_4fqfq,
       net_income_adjustment_ratio_2fy,
       net_income_adjustment_ratio_3fy,
       net_income_adjustment_ratio_4fy,
       net_income_adjustment_pct,
       ebitda_adjustment_pct_ltm,
       ebitda_adjustment_pct_fy,
       ebitda_adjustment_pct_1fy,
       ebitda_adjustment_pct_fq,
       ebitda_adjustment_pct_1fqfq,
       ebitda_adjustment_pct_2fqfq,
       ebitda_adjustment_pct_3fqfq,
       ebitda_adjustment_pct_4fqfq,
       ebitda_adjustment_pct_2fy,
       ebitda_adjustment_pct_3fy,
       ebitda_adjustment_pct_4fy,
       ebit_adjustment_pct_ltm,
       ebit_adjustment_pct_fy,
       ebit_adjustment_pct_1fy,
       ebit_adjustment_pct_fq,
       ebit_adjustment_pct_1fqfq,
       ebit_adjustment_pct_2fqfq,
       ebit_adjustment_pct_3fqfq,
       ebit_adjustment_pct_4fqfq,
       ebit_adjustment_pct_2fy,
       ebit_adjustment_pct_3fy,
       ebit_adjustment_pct_4fy,
       earnings_quality_score,
       earnings_quality_warning,
       forward_eps_gaap_adj_spread,
       gaap_revision_momentum,
       gaap_revision_1m,
       gaap_revision_3m,
       gaap_revision_6m,
       gaap_revision_1y,
       gaap_vs_norm_revision_spread,
       gaap_revision_acceleration,
       gaap_positive_revision_flag,
       revenue_growth_yoy,
       ebitda_growth_yoy,
       operating_income_growth,
       fcf_growth,
       revenue_cagr_5y,
       forward_revenue_growth,
       revenue_vs_5y_avg,
       revenue_est_spread,
       revenue_beat_potential,
       revenue_est_revision_trend,
       ebitda_est_vs_actual,
       forward_revenue_multiple,
       revenue_estimate_count,
       revenue_guidance_gap,
       consensus_revenue_growth,
       forward_ebitda_margin,
       revenue_acceleration,
       estimate_confidence_score,
       dividend_streak,
       dividend_yield_ltm,
       dividend_yield_ntm,
       dividend_payout_ratio,
       fcf_dividend_coverage,
       buyback_yield,
       total_shareholder_yield,
       dividend_growth_expectation,
       days_since_ex_date,
       days_to_payment,
       dividend_announced_flag,
       ex_date_approaching_flag,
       dividend_frequency_score,
       dividend_consistency,
       dividend_yield_vs_5y_avg,
       revenue_per_employee,
       profit_per_employee,
       ebitda_per_employee,
       assets_per_employee,
       fte_growth_1y_pct,
       fte_growth_3y_pct,
       workforce_stability,
       fte_growth_2y_pct,
       layoff_risk_flag,
       rapid_hiring_flag,
       sustainable_growth_flag,
       cfo_to_net_income,
       fcf_to_net_income,
       fcf_margin,
       cfo_growth_yoy,
       fcf_positive_ratio,
       acquisition_intensity,
       self_funding_ratio,
       fcf_positive_years,
       fcf_always_positive,
       capex_vs_5y_avg,
       underinvestment_flag,
       cfo_share_of_cf,
       cfi_share_of_cf,
       cff_share_of_cf,
       self_funding_flag,
       fcf_4q_improvement,
       cash_flow_quality_score,
       acquisition_to_fcf,
       sustainable_ma_flag,
       capex_yoy_growth,
       capex_qoq_growth,
       capex_3y_trend,
       capex_volatility,
       capex_acceleration,
       capex_cut_flag,
       overinvestment_flag,
       acquisitions_yoy_growth,
       acquisitions_vs_5y_avg,
       acquisitions_ltm_total,
       ma_intensity_score,
       serial_acquirer_flag,
       acquisition_pause_flag,
       total_investment_to_cfo,
       organic_vs_inorganic,
       investment_efficiency,
       cfo_quarterly_trend,
       cfi_quarterly_trend,
       cff_quarterly_trend,
       fcf_quarterly_trend,
       cfo_positive_quarters,
       cfi_negative_quarters,
       cash_burn_rate,
       financing_dependency,
       fiscal_quarter,
       fiscal_month,
       fiscal_year,
       days_to_earnings,
       earnings_report_recency,
       reporting_lag,
       fiscal_year_progress,
       days_since_last_report,
       days_to_fy_end,
       is_quarter_end_month,
       is_fy_end_month,
       earnings_season_flag,
       pre_earnings_window,
       post_earnings_window,
       reporting_freshness_score,
       piotroski_f_score,
       dilution_score,
       ebit_fq,
       ebit_ltm,
       ebit_fy,
       ebit_1fy,
       ebitda_fq,
       ebitda_ltm,
       ebitda_fy,
       ebitda_1fy,
       ebit_2fy,
       ebit_3fy,
       ebit_4fy,
       ebitda_2fy,
       ebitda_3fy,
       ebitda_4fy,
       ebit_1fqfq,
       ebit_2fqfq,
       ebit_3fqfq,
       ebit_4fqfq,
       ebitda_1fqfq,
       ebitda_2fqfq,
       ebitda_3fqfq,
       ebitda_4fqfq,
       ebit_5yavgfq,
       ebit_5yavgltm,
       ebitda_5yavgfq,
       ebitda_5yavgltm,
       ebit_adj_fq,
       ebit_adj_ltm,
       ebit_adj_fy,
       ebitda_adj_fq,
       ebitda_adj_ltm,
       ebitda_adj_fy,
       ebit_growth_yoy,
       ebitda_growth_yoy_comp,
       ebit_margin_ltm,
       ebitda_margin_ltm,
       ebit_positive_years,
       ebitda_positive_years,
       ebit_qoq_growth,
       ebitda_qoq_growth,
       ebit_cagr_3y,
       ebitda_cagr_3y,
       ebit_vs_5y_avg,
       ebitda_vs_5y_avg,
       net_income_is_fq,
       net_income_is_ltm,
       net_income_is_fy,
       net_income_adj_ltm,
       normalized_ni_ltm,
       net_income_is_1fqfq,
       net_income_is_2fqfq,
       net_income_is_3fqfq,
       net_income_is_4fqfq,
       net_income_is_1fy,
       net_income_is_2fy,
       net_income_is_3fy,
       net_income_is_4fy,
       net_income_is_5yavgfq,
       net_income_is_5yavgltm,
       normalized_ni_5yavgfq,
       normalized_ni_5yavgltm,
       net_income_growth_yoy,
       net_income_margin_ltm,
       ni_adjustment_ratio,
       net_income_positive_years,
       earnings_quality_composite_comp,
       net_income_qoq_growth,
       net_income_yoy_quarterly,
       net_income_vs_5y_avg,
       normalized_ni_vs_5y_avg,
       cfo_fq,
       cfo_ltm,
       cfo_fy,
       fcf_fq,
       fcf_ltm,
       fcf_fy,
       cfo_growth_yoy_comp,
       fcf_growth_yoy,
       fcf_margin_pct,
       fcf_yield,
       cfo_positive_years,
       beta_1y,
       beta_5y,
       beta_spread,
       beta_trend,
       high_beta_flag,
       low_beta_flag,
       beta_stability_score,
       cogs_to_revenue,
       opex_to_revenue,
       sga_to_revenue,
       rnd_to_revenue,
       interest_to_revenue,
       interest_income_ltm,
       interest_expense_ltm,
       net_interest_income,
       interest_coverage_ratio,
       interest_income_to_revenue,
       interest_expense_to_revenue,
       price_momentum_3y,
       price_momentum_5y,
       long_term_trend_score,
       multi_year_high_flag,
       secular_trend_flag,
       tangible_book_value,
       tangible_book_per_share,
       price_to_tangible_book,
       tangible_equity_ratio,
       intangibles_to_equity,
       goodwill_to_equity,
       working_capital_ltm,
       working_capital_fq,
       working_capital_fy,
       wc_to_revenue,
       wc_to_assets,
       wc_change_qoq,
       wc_change_yoy,
       days_working_capital,
       negative_wc_flag,
       wc_improvement_flag,
       other_unusual_items_ltm,
       total_unusual_items,
       unusual_items_to_revenue,
       unusual_items_to_ebitda,
       has_unusual_items_flag,
       revenue_est_avg_fy1e,
       revenue_est_med_fy1e,
       revenue_est_avg_ntm,
       revenue_est_med_ntm,
       revenue_avg_med_diff_pct,
       revenue_consensus_strength,
       revenue_vs_current,
       revenue_fq,
       revenue_1fq,
       revenue_2fq,
       revenue_3q,
       revenue_4q,
       revenue_fy,
       revenue_1fy,
       revenue_2fy,
       revenue_3fy,
       revenue_4fy,
       revenue_ltm,
       revenue_5y_avg,
       revenue_yoy_growth,
       revenue_1fy_vs_2fy,
       revenue_2fy_vs_3fy,
       revenue_3fy_vs_4fy,
       revenue_growth_flag,
       revenue_5yavgfq,
       revenue_5yavgltm,
       revenue_growth_yoy_temp,
       revenue_vs_5y_avg_fq_temp,
       revenue_vs_5y_avg_ltm_temp,
       revenue_fq_vs_avg_temp,
       revenue_momentum_temp,
       wc_fq_temp,
       wc_fy_temp,
       wc_ltm_temp,
       wc_5yavgfy,
       wc_1fq,
       wc_2fq,
       wc_3fq,
       wc_4fq,
       wc_1fy,
       wc_2fy,
       wc_3fy,
       wc_4fy,
       wc_qoq_change,
       wc_yoy_change,
       wc_4q_trend,
       wc_vs_5y_avg_temp,
       wc_positive_quarters,
       wc_improving_flag_temp,
       wc_volatility,
       debt_fq,
       debt_fy,
       debt_ltm,
       debt_1fq,
       debt_2fq,
       debt_3fq,
       debt_4fq,
       debt_1fy_temp,
       debt_2fy,
       debt_3fy,
       debt_4fy,
       debt_qoq_change,
       debt_yoy_change,
       debt_4q_trend,
       debt_3y_cagr,
       debt_deleveraging,
       debt_to_equity_trend,
       assets_fq,
       assets_fy,
       assets_ltm_temp,
       assets_1fq,
       assets_2fq,
       assets_3fq,
       assets_4fq,
       assets_1fy,
       assets_2fy,
       assets_3fy,
       assets_4fy,
       assets_qoq_growth,
       assets_yoy_growth,
       assets_3y_cagr,
       asset_growth_accel,
       asset_base_stable,
       gp_fq,
       gp_fy,
       gp_ltm_temp,
       gp_1fqfq,
       gp_2fqfq,
       gp_3fqfq,
       gp_4fqfq,
       gp_1fy,
       gp_2fy,
       gp_3fy,
       gp_4fy,
       gp_qoq_growth,
       gp_yoy_growth,
       gp_margin_fq,
       gp_margin_trend,
       gp_positive_quarters,
       gp_margin_expansion_temp,
       div_yield_ind,
       div_yield_1fy_ind,
       div_yield_5y_avg,
       div_yield_vs_5y_avg,
       div_yield_growth_expected,
       high_yield_flag,
       sustainable_dividend_flag,
       eps_cont_ltm,
       eps_cont_fq,
       eps_cont_fy,
       eps_cont_1fy,
       eps_cont_2fy,
       eps_cont_3fy,
       eps_cont_4fy,
       eps_cont_qoq_growth,
       eps_cont_yoy_growth,
       eps_cont_vs_total_eps,
       discontinued_ops_impact,
       rnd_fq,
       rnd_fy,
       rnd_1fy,
       rnd_2fy,
       rnd_3fy,
       rnd_4fy,
       rnd_intensity_ltm,
       rnd_yoy_growth,
       rnd_per_employee,
       high_rnd_intensity_flag,
       inventory_1fq,
       inventory_2fq,
       inventory_3fq,
       inventory_4fq,
       inventory_1fy,
       inventory_2fy,
       inventory_3fy,
       inventory_4fy,
       inventory_qoq_change,
       inventory_yoy_change,
       inventory_days,
       inventory_turnover_mv,
       goodwill_1fq,
       goodwill_2fq,
       goodwill_3fq,
       goodwill_4fq,
       goodwill_1fy,
       goodwill_2fy,
       goodwill_3fy,
       goodwill_4fy,
       goodwill_qoq_change,
       goodwill_yoy_change,
       goodwill_3y_growth,
       goodwill_concentration,
       recent_acquisition_flag,
       marketing_to_revenue,
       marketing_trend_yoy,
       marketing_vs_5y_avg,
       sga_vs_5y_avg,
       tangible_book_value_fy,
       tangible_book_value_ltm,
       tbv_yoy_growth,
       calculated_at
FROM mv_all_stock_features;

alter table vw_features_materialized_view
    owner to postgres;

