create view vw_features_gaap_vs_adjusted
            (isin, eps_adjustment_spread_ltm, eps_adjustment_spread_fy, eps_adjustment_spread_1fy,
             eps_adjustment_spread_fq, eps_adjustment_spread_1fqfq, eps_adjustment_spread_2fqfq,
             eps_adjustment_spread_3fqfq, eps_adjustment_spread_4fqfq, eps_adjustment_spread_2fy,
             eps_adjustment_spread_3fy, eps_adjustment_spread_4fy, eps_adjustment_pct, net_income_adjustment_ratio_ltm,
             net_income_adjustment_ratio_fy, net_income_adjustment_ratio_1fy, net_income_adjustment_ratio_fq,
             net_income_adjustment_ratio_5yavgfq, net_income_adjustment_ratio_1fqfq, net_income_adjustment_ratio_2fqfq,
             net_income_adjustment_ratio_3fqfq, net_income_adjustment_ratio_4fqfq, net_income_adjustment_ratio_2fy,
             net_income_adjustment_ratio_3fy, net_income_adjustment_ratio_4fy, net_income_adjustment_pct,
             ebitda_adjustment_pct_ltm, ebitda_adjustment_pct_fy, ebitda_adjustment_pct_1fy, ebitda_adjustment_pct_fq,
             ebitda_adjustment_pct_1fqfq, ebitda_adjustment_pct_2fqfq, ebitda_adjustment_pct_3fqfq,
             ebitda_adjustment_pct_4fqfq, ebitda_adjustment_pct_2fy, ebitda_adjustment_pct_3fy,
             ebitda_adjustment_pct_4fy, ebit_adjustment_pct_ltm, ebit_adjustment_pct_fy, ebit_adjustment_pct_1fy,
             ebit_adjustment_pct_fq, ebit_adjustment_pct_1fqfq, ebit_adjustment_pct_2fqfq, ebit_adjustment_pct_3fqfq,
             ebit_adjustment_pct_4fqfq, ebit_adjustment_pct_2fy, ebit_adjustment_pct_3fy, ebit_adjustment_pct_4fy,
             earnings_quality_score, earnings_quality_warning, forward_eps_gaap_adj_spread)
as
SELECT isin,
       eps_adjustment_spread_ltm,
       eps_adjustment_spread_fy,
       eps_adjustment_spread_1fy,
       eps_adjustment_spread_fq,
       eps_adjustment_spread_1fqfq,
       eps_adjustment_spread_2fqfq,
       eps_adjustment_spread_3fqfq,
       eps_adjustment_spread_4fqfq,
       eps_adjustment_spread_2fy,
       eps_adjustment_spread_3fy,
       eps_adjustment_spread_4fy,
       eps_adjustment_pct,
       net_income_adjustment_ratio_ltm,
       net_income_adjustment_ratio_fy,
       net_income_adjustment_ratio_1fy,
       net_income_adjustment_ratio_fq,
       net_income_adjustment_ratio_5yavgfq,
       net_income_adjustment_ratio_1fqfq,
       net_income_adjustment_ratio_2fqfq,
       net_income_adjustment_ratio_3fqfq,
       net_income_adjustment_ratio_4fqfq,
       net_income_adjustment_ratio_2fy,
       net_income_adjustment_ratio_3fy,
       net_income_adjustment_ratio_4fy,
       net_income_adjustment_pct,
       ebitda_adjustment_pct_ltm,
       ebitda_adjustment_pct_fy,
       ebitda_adjustment_pct_1fy,
       ebitda_adjustment_pct_fq,
       ebitda_adjustment_pct_1fqfq,
       ebitda_adjustment_pct_2fqfq,
       ebitda_adjustment_pct_3fqfq,
       ebitda_adjustment_pct_4fqfq,
       ebitda_adjustment_pct_2fy,
       ebitda_adjustment_pct_3fy,
       ebitda_adjustment_pct_4fy,
       ebit_adjustment_pct_ltm,
       ebit_adjustment_pct_fy,
       ebit_adjustment_pct_1fy,
       ebit_adjustment_pct_fq,
       ebit_adjustment_pct_1fqfq,
       ebit_adjustment_pct_2fqfq,
       ebit_adjustment_pct_3fqfq,
       ebit_adjustment_pct_4fqfq,
       ebit_adjustment_pct_2fy,
       ebit_adjustment_pct_3fy,
       ebit_adjustment_pct_4fy,
       earnings_quality_score,
       earnings_quality_warning,
       forward_eps_gaap_adj_spread
FROM calc_gaap_adjusted_analytics() calc_gaap_adjusted_analytics(isin, eps_adjustment_spread_ltm,
                                                                 eps_adjustment_spread_fy, eps_adjustment_spread_1fy,
                                                                 eps_adjustment_spread_fq, eps_adjustment_spread_1fqfq,
                                                                 eps_adjustment_spread_2fqfq,
                                                                 eps_adjustment_spread_3fqfq,
                                                                 eps_adjustment_spread_4fqfq, eps_adjustment_spread_2fy,
                                                                 eps_adjustment_spread_3fy, eps_adjustment_spread_4fy,
                                                                 eps_adjustment_pct, net_income_adjustment_ratio_ltm,
                                                                 net_income_adjustment_ratio_fy,
                                                                 net_income_adjustment_ratio_1fy,
                                                                 net_income_adjustment_ratio_fq,
                                                                 net_income_adjustment_ratio_5yavgfq,
                                                                 net_income_adjustment_ratio_1fqfq,
                                                                 net_income_adjustment_ratio_2fqfq,
                                                                 net_income_adjustment_ratio_3fqfq,
                                                                 net_income_adjustment_ratio_4fqfq,
                                                                 net_income_adjustment_ratio_2fy,
                                                                 net_income_adjustment_ratio_3fy,
                                                                 net_income_adjustment_ratio_4fy,
                                                                 net_income_adjustment_pct, ebitda_adjustment_pct_ltm,
                                                                 ebitda_adjustment_pct_fy, ebitda_adjustment_pct_1fy,
                                                                 ebitda_adjustment_pct_fq, ebitda_adjustment_pct_1fqfq,
                                                                 ebitda_adjustment_pct_2fqfq,
                                                                 ebitda_adjustment_pct_3fqfq,
                                                                 ebitda_adjustment_pct_4fqfq, ebitda_adjustment_pct_2fy,
                                                                 ebitda_adjustment_pct_3fy, ebitda_adjustment_pct_4fy,
                                                                 ebit_adjustment_pct_ltm, ebit_adjustment_pct_fy,
                                                                 ebit_adjustment_pct_1fy, ebit_adjustment_pct_fq,
                                                                 ebit_adjustment_pct_1fqfq, ebit_adjustment_pct_2fqfq,
                                                                 ebit_adjustment_pct_3fqfq, ebit_adjustment_pct_4fqfq,
                                                                 ebit_adjustment_pct_2fy, ebit_adjustment_pct_3fy,
                                                                 ebit_adjustment_pct_4fy, earnings_quality_score,
                                                                 earnings_quality_warning, forward_eps_gaap_adj_spread);

alter table vw_features_gaap_vs_adjusted
    owner to postgres;

