create view vw_features_leverage_liquidity
            (isin, wc_fq, wc_fy, wc_ltm, wc_5yavgfy, wc_1fq, wc_2fq, wc_3fq, wc_4fq, wc_1fy, wc_2fy, wc_3fy, wc_4fy,
             wc_qoq_change, wc_yoy_change, wc_4q_trend, wc_vs_5y_avg, wc_positive_quarters, wc_improving_flag,
             wc_volatility, debt_fq, debt_fy, debt_ltm, debt_1fq, debt_2fq, debt_3fq, debt_4fq, debt_1fy, debt_2fy,
             debt_3fy, debt_4fy, debt_qoq_change, debt_yoy_change, debt_4q_trend, debt_3y_cagr, debt_deleveraging,
             debt_to_equity_trend, debt_to_equity, debt_to_assets, equity_ratio, interest_coverage, current_ratio,
             cash_ratio, working_capital_ratio, working_capital_ltm, working_capital_fq, working_capital_fy,
             wc_to_revenue, wc_to_assets, wc_change_qoq, wc_change_yoy, days_working_capital, wc_efficiency_score,
             negative_wc_flag, wc_improvement_flag)
as
SELECT isin,
       wct.wc_fq,
       wct.wc_fy,
       wct.wc_ltm,
       wct.wc_5yavgfy,
       wct.wc_1fq,
       wct.wc_2fq,
       wct.wc_3fq,
       wct.wc_4fq,
       wct.wc_1fy,
       wct.wc_2fy,
       wct.wc_3fy,
       wct.wc_4fy,
       wct.wc_qoq_change,
       wct.wc_yoy_change,
       wct.wc_4q_trend,
       wct.wc_vs_5y_avg,
       wct.wc_positive_quarters,
       wct.wc_improving_flag,
       wct.wc_volatility,
       tdt.debt_fq,
       tdt.debt_fy,
       tdt.debt_ltm,
       tdt.debt_1fq,
       tdt.debt_2fq,
       tdt.debt_3fq,
       tdt.debt_4fq,
       tdt.debt_1fy,
       tdt.debt_2fy,
       tdt.debt_3fy,
       tdt.debt_4fy,
       tdt.debt_qoq_change,
       tdt.debt_yoy_change,
       tdt.debt_4q_trend,
       tdt.debt_3y_cagr,
       tdt.debt_deleveraging,
       tdt.debt_to_equity_trend,
       lf.debt_to_equity,
       lf.debt_to_assets,
       lf.equity_ratio,
       lf.interest_coverage,
       lf.current_ratio,
       lf.cash_ratio,
       lf.working_capital_ratio,
       wcd.working_capital_ltm,
       wcd.working_capital_fq,
       wcd.working_capital_fy,
       wcd.wc_to_revenue,
       wcd.wc_to_assets,
       wcd.wc_change_qoq,
       wcd.wc_change_yoy,
       wcd.days_working_capital,
       wcd.wc_efficiency_score,
       wcd.negative_wc_flag,
       wcd.wc_improvement_flag
FROM calc_working_capital_temporal()                    wct(isin, wc_fq, wc_fy, wc_ltm, wc_5yavgfy, wc_1fq, wc_2fq,
                                                            wc_3fq, wc_4fq, wc_1fy, wc_2fy, wc_3fy, wc_4fy,
                                                            wc_qoq_change, wc_yoy_change, wc_4q_trend, wc_vs_5y_avg,
                                                            wc_positive_quarters, wc_improving_flag, wc_volatility)
         FULL JOIN calc_total_debt_temporal()           tdt(isin, debt_fq, debt_fy, debt_ltm, debt_1fq, debt_2fq,
                                                            debt_3fq, debt_4fq, debt_1fy, debt_2fy, debt_3fy, debt_4fy,
                                                            debt_qoq_change, debt_yoy_change, debt_4q_trend,
                                                            debt_3y_cagr, debt_deleveraging, debt_to_equity_trend)
                   USING (isin)
         FULL JOIN calc_leverage_features()             lf(isin, debt_to_equity, debt_to_assets, equity_ratio,
                                                           interest_coverage, current_ratio, cash_ratio,
                                                           working_capital_ratio) USING (isin)
         FULL JOIN calc_working_capital_deep_features() wcd(isin, working_capital_ltm, working_capital_fq,
                                                            working_capital_fy, wc_to_revenue, wc_to_assets,
                                                            wc_change_qoq, wc_change_yoy, days_working_capital,
                                                            wc_efficiency_score, negative_wc_flag, wc_improvement_flag)
                   USING (isin);

alter table vw_features_leverage_liquidity
    owner to postgres;

