create view vw_features_enhanced_cash_flow
            (isin, fcf_positive_years, fcf_always_positive, capex_vs_5y_avg, underinvestment_flag, cfo_share_of_cf,
             cfi_share_of_cf, cff_share_of_cf, self_funding_flag, acquisition_to_fcf, sustainable_ma_flag,
             fcf_4q_improvement, cash_flow_quality_score, capex_yoy_growth, capex_qoq_growth, capex_3y_trend,
             capex_volatility, capex_acceleration, capex_cut_flag, overinvestment_flag, acquisitions_yoy_growth,
             acquisitions_vs_5y_avg, acquisitions_ltm_total, ma_intensity_score, serial_acquirer_flag,
             acquisition_pause_flag, total_investment_to_cfo, organic_vs_inorganic, investment_efficiency)
as
SELECT isin,
       fcf_positive_years,
       fcf_always_positive,
       capex_vs_5y_avg,
       underinvestment_flag,
       cfo_share_of_cf,
       cfi_share_of_cf,
       cff_share_of_cf,
       self_funding_flag,
       acquisition_to_fcf,
       sustainable_ma_flag,
       fcf_4q_improvement,
       cash_flow_quality_score,
       capex_yoy_growth,
       capex_qoq_growth,
       capex_3y_trend,
       capex_volatility,
       capex_acceleration,
       capex_cut_flag,
       overinvestment_flag,
       acquisitions_yoy_growth,
       acquisitions_vs_5y_avg,
       acquisitions_ltm_total,
       ma_intensity_score,
       serial_acquirer_flag,
       acquisition_pause_flag,
       total_investment_to_cfo,
       organic_vs_inorganic,
       investment_efficiency
FROM calc_enhanced_cashflow_features() calc_enhanced_cashflow_features(isin, fcf_positive_years, fcf_always_positive,
                                                                       capex_vs_5y_avg, underinvestment_flag,
                                                                       cfo_share_of_cf, cfi_share_of_cf,
                                                                       cff_share_of_cf, self_funding_flag,
                                                                       acquisition_to_fcf, sustainable_ma_flag,
                                                                       fcf_4q_improvement, cash_flow_quality_score,
                                                                       capex_yoy_growth, capex_qoq_growth,
                                                                       capex_3y_trend, capex_volatility,
                                                                       capex_acceleration, capex_cut_flag,
                                                                       overinvestment_flag, acquisitions_yoy_growth,
                                                                       acquisitions_vs_5y_avg, acquisitions_ltm_total,
                                                                       ma_intensity_score, serial_acquirer_flag,
                                                                       acquisition_pause_flag, total_investment_to_cfo,
                                                                       organic_vs_inorganic, investment_efficiency);

alter table vw_features_enhanced_cash_flow
    owner to postgres;

