create view vw_features_growth
            (isin, ticker, name, industry, sector, trading_country, region, country, exchange, revenue_growth_yoy,
             ebitda_growth_yoy, operating_income_growth, fcf_growth, revenue_cagr_5y, forward_revenue_growth,
             revenue_vs_5y_avg, revenue_est_spread, revenue_beat_potential, revenue_est_revision_trend,
             ebitda_est_vs_actual, forward_revenue_multiple, revenue_estimate_count, revenue_guidance_gap,
             consensus_revenue_growth, ebit_estimate_spread, forward_ebitda_margin, revenue_acceleration,
             estimate_confidence_score, revenue_fq, revenue_fy, revenue_ltm, revenue_5y_avg, revenue_1fqfq,
             revenue_2fqfq, revenue_3fqfq, revenue_4fqfq, revenue_1fy, revenue_2fy, revenue_3fy, revenue_4fy,
             revenue_yoy_growth_qf, revenue_vs_5y_avg_qf, revenue_ltm_vs_fy, revenue_fq_vs_5y_avg_fq,
             revenue_qoq_growth, revenue_qoq_2q, revenue_qoq_3q, revenue_qoq_4q, revenue_yoy_quarterly,
             revenue_2y_growth, revenue_3y_growth, revenue_4y_growth, revenue_cagr_3y, revenue_cagr_4y,
             revenue_4q_trend, revenue_4q_avg, revenue_fq_vs_4q_avg, revenue_growth_flag, revenue_stability_score,
             revenue_accelerating_flag, revenue_positive_qoq_streak, revenue_fq_temp, revenue_ltm_temp, revenue_fy_temp,
             revenue_1fy_temp, revenue_5yavgfq, revenue_5yavgltm, revenue_growth_yoy_temp, revenue_vs_5y_avg_fq,
             revenue_vs_5y_avg_ltm, revenue_fq_vs_avg, revenue_momentum)
as
SELECT id.isin,
       id.ticker,
       id.name,
       id.industry,
       id.sector,
       id.trading_country,
       id.region,
       id.country,
       id.exchange,
       gf.revenue_growth_yoy,
       gf.ebitda_growth_yoy,
       gf.operating_income_growth,
       gf.fcf_growth,
       gf.revenue_cagr_5y,
       gf.forward_revenue_growth,
       gf.revenue_vs_5y_avg,
       rff.revenue_est_spread,
       rff.revenue_beat_potential,
       rff.revenue_est_revision_trend,
       rff.ebitda_est_vs_actual,
       rff.forward_revenue_multiple,
       rff.revenue_estimate_count,
       rff.revenue_guidance_gap,
       rff.consensus_revenue_growth,
       rff.ebit_estimate_spread,
       rff.forward_ebitda_margin,
       rff.revenue_acceleration,
       rff.estimate_confidence_score,
       rqf.revenue_fq,
       rqf.revenue_fy,
       rqf.revenue_ltm,
       rqf.revenue_5y_avg,
       rqf.revenue_1fqfq,
       rqf.revenue_2fqfq,
       rqf.revenue_3fqfq,
       rqf.revenue_4fqfq,
       rqf.revenue_1fy,
       rqf.revenue_2fy,
       rqf.revenue_3fy,
       rqf.revenue_4fy,
       rqf.revenue_yoy_growth AS revenue_yoy_growth_qf,
       rqf.revenue_vs_5y_avg  AS revenue_vs_5y_avg_qf,
       rqf.revenue_ltm_vs_fy,
       rqf.revenue_fq_vs_5y_avg_fq,
       rqf.revenue_qoq_growth,
       rqf.revenue_qoq_2q,
       rqf.revenue_qoq_3q,
       rqf.revenue_qoq_4q,
       rqf.revenue_yoy_quarterly,
       rqf.revenue_2y_growth,
       rqf.revenue_3y_growth,
       rqf.revenue_4y_growth,
       rqf.revenue_cagr_3y,
       rqf.revenue_cagr_4y,
       rqf.revenue_4q_trend,
       rqf.revenue_4q_avg,
       rqf.revenue_fq_vs_4q_avg,
       rqf.revenue_growth_flag,
       rqf.revenue_stability_score,
       rqf.revenue_accelerating_flag,
       rqf.revenue_positive_qoq_streak,
       trt.revenue_fq         AS revenue_fq_temp,
       trt.revenue_ltm        AS revenue_ltm_temp,
       trt.revenue_fy         AS revenue_fy_temp,
       trt.revenue_1fy        AS revenue_1fy_temp,
       trt.revenue_5yavgfq,
       trt.revenue_5yavgltm,
       trt.revenue_growth_yoy AS revenue_growth_yoy_temp,
       trt.revenue_vs_5y_avg_fq,
       trt.revenue_vs_5y_avg_ltm,
       trt.revenue_fq_vs_avg,
       trt.revenue_momentum
FROM vw_identifier_columns                           id
         LEFT JOIN calc_growth_features()            gf(isin, revenue_growth_yoy, ebitda_growth_yoy,
                                                        operating_income_growth, fcf_growth, revenue_cagr_5y,
                                                        forward_revenue_growth, revenue_vs_5y_avg) USING (isin)
         LEFT JOIN calc_revenue_forecast_features()  rff(isin, revenue_est_spread, revenue_beat_potential,
                                                         revenue_est_revision_trend, ebitda_est_vs_actual,
                                                         forward_revenue_multiple, revenue_estimate_count,
                                                         revenue_guidance_gap, consensus_revenue_growth,
                                                         ebit_estimate_spread, forward_ebitda_margin,
                                                         revenue_acceleration, estimate_confidence_score) USING (isin)
         LEFT JOIN calc_revenue_quarterly_features() rqf(isin, revenue_fq, revenue_fy, revenue_ltm, revenue_5y_avg,
                                                         revenue_1fqfq, revenue_2fqfq, revenue_3fqfq, revenue_4fqfq,
                                                         revenue_1fy, revenue_2fy, revenue_3fy, revenue_4fy,
                                                         revenue_yoy_growth, revenue_vs_5y_avg, revenue_ltm_vs_fy,
                                                         revenue_fq_vs_5y_avg_fq, revenue_qoq_growth, revenue_qoq_2q,
                                                         revenue_qoq_3q, revenue_qoq_4q, revenue_yoy_quarterly,
                                                         revenue_2y_growth, revenue_3y_growth, revenue_4y_growth,
                                                         revenue_cagr_3y, revenue_cagr_4y, revenue_4q_trend,
                                                         revenue_4q_avg, revenue_fq_vs_4q_avg, revenue_growth_flag,
                                                         revenue_stability_score, revenue_accelerating_flag,
                                                         revenue_positive_qoq_streak) USING (isin)
         LEFT JOIN calc_total_revenues_temporal()    trt(isin, revenue_fq, revenue_ltm, revenue_fy, revenue_1fy,
                                                         revenue_5yavgfq, revenue_5yavgltm, revenue_growth_yoy,
                                                         revenue_vs_5y_avg_fq, revenue_vs_5y_avg_ltm, revenue_fq_vs_avg,
                                                         revenue_momentum) USING (isin);

comment on view vw_features_growth is 'Growth metrics including revenue, EBITDA, FCF growth rates and forecasts.
    Source functions: calc_growth_features, calc_revenue_forecast_features,
    calc_revenue_quarterly_features, calc_total_revenues_temporal';

alter table vw_features_growth
    owner to postgres;

