"""
Fix Phase 9.3 feature registry to match actual generator outputs.

This script updates phase93_categories.py with the actual feature names
extracted from the generator functions in advanced.py.
"""

import json
from pathlib import Path
from datetime import datetime


def update_registry():
    """Update phase93_categories.py with actual feature names."""

    # Load actual features from JSON
    actual_features_path = Path("phase93_actual_features.json")
    if not actual_features_path.exists():
        print(f"Error: {actual_features_path} not found")
        print("Please run audit_phase93_features.py first")
        return

    with open(actual_features_path, "r", encoding="utf-8") as f:
        actual_features = json.load(f)

    # Read current registry file
    registry_path = Path("finance_ml/ml_workflow/eda/phase93_categories.py")
    if not registry_path.exists():
        print(f"Error: {registry_path} not found")
        return

    # Create backup
    backup_path = registry_path.with_suffix(
        f'.py.backup_{datetime.now().strftime("%Y%m%d_%H%M%S")}'
    )
    with open(registry_path, "r", encoding="utf-8") as f:
        original_content = f.read()
    with open(backup_path, "w", encoding="utf-8") as f:
        f.write(original_content)
    print(f"✓ Created backup: {backup_path}")

    # Build new registry dict content
    new_dict_lines = []
    new_dict_lines.append("PHASE93_FEATURE_CATEGORIES: Dict[str, List[str]] = {")

    # Category order (to maintain original order)
    category_order = [
        "Momentum & Technical",
        "Valuation Ratios",
        "Profitability",
        "Quality & Risk",
        "Cash Flow",
        "Capital Allocation",
        "Analyst Sentiment",
        "Market Sentiment",
        "Leverage & Liquidity",
        "Temporal Patterns",
        "Composite Scores",
    ]

    for i, category in enumerate(category_order):
        features = actual_features.get(category, [])
        new_dict_lines.append(f'    "{category}": [')

        # Add features
        for feat in features:
            new_dict_lines.append(f'        "{feat}",')

        # Close category (with or without trailing comma)
        if i < len(category_order) - 1:
            new_dict_lines.append("    ],")
        else:
            new_dict_lines.append("    ]")
        new_dict_lines.append("")

    new_dict_lines.append("}")

    # Build complete new file content
    header = '''"""
Phase 9.3 Feature Category Registry

Maps Phase 9.3 engineered features to their categorical families for
EDA, evaluation, and reporting purposes.

This module provides a centralized registry of Phase 9.3 feature families
to enable explicit tracking and analysis in EDA summaries, dashboards,
and analytics workflows.

UPDATED: Registry synchronized with actual generator outputs from advanced.py
All feature names verified to match what generator functions actually produce.
"""

from typing import Dict, List, Optional
import pandas as pd


# Phase 9.3 Feature Categories Registry
# Maps category names to lists of feature column names generated by advanced.py functions
'''

    # Keep the helper functions (everything after the PHASE93_FEATURE_CATEGORIES dict)
    # Find where the dict ends and functions begin
    dict_start = original_content.find("PHASE93_FEATURE_CATEGORIES")
    if dict_start == -1:
        print("Error: Could not find PHASE93_FEATURE_CATEGORIES in original file")
        return

    # Find the closing brace of the dict
    dict_portion = original_content[dict_start:]
    brace_count = 0
    dict_end_relative = -1
    in_dict = False

    for i, char in enumerate(dict_portion):
        if char == "{":
            brace_count += 1
            in_dict = True
        elif char == "}" and in_dict:
            brace_count -= 1
            if brace_count == 0:
                dict_end_relative = i + 1
                break

    if dict_end_relative == -1:
        print("Error: Could not find end of PHASE93_FEATURE_CATEGORIES dict")
        return

    dict_end = dict_start + dict_end_relative

    # Get everything after the dict (helper functions)
    functions_portion = original_content[dict_end:]

    # Build new content
    new_content = header + "\n".join(new_dict_lines) + "\n" + functions_portion

    # Write updated file
    with open(registry_path, "w", encoding="utf-8") as f:
        f.write(new_content)

    print(f"\n✓ Updated {registry_path}")

    # Print summary
    print("\n" + "=" * 80)
    print("REGISTRY UPDATE SUMMARY")
    print("=" * 80)

    total_actual = sum(len(feats) for feats in actual_features.values())
    print(f"Total features in updated registry: {total_actual}")
    print("\nFeatures per category:")

    for category in category_order:
        features = actual_features.get(category, [])
        print(f"  {category}: {len(features)} features")

    print("\n✓ Registry update complete!")
    print(f"✓ Backup saved to: {backup_path}")
    print("\nNext steps:")
    print("1. Run tests: python -m unittest tests.test_phase93_eda_integration -v")
    print("2. Run benchmarking in notebook to verify coverage improvement")
    print("3. Update CHANGELOG.md with registry fixes")


if __name__ == "__main__":
    update_registry()
