#!/usr/bin/env python3
"""
Generate complete import_equities_data.sql from CSV headers.

This script creates a proper import SQL file with:
1. Staging tables using TEXT columns matching CSV column order
2. INSERT statements that map staging columns to equities table
3. Proper NULL handling and region assignment
4. All 4 regions (US, EU, APAC, ROTW)

Usage:
    python tools/generate_import_sql.py
    python tools/generate_import_sql.py --output import_equities_data.sql
"""

import argparse
import csv
from pathlib import Path


def read_csv_header(csv_path: Path) -> list[str]:
    """Read the header row from a CSV file."""
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.reader(f)
        return next(reader)


def generate_staging_columns(columns: list[str]) -> str:
    """Generate column definitions for staging table (all TEXT)."""
    lines = []
    for i, col in enumerate(columns):
        suffix = "," if i < len(columns) - 1 else ""
        lines.append(f'    "{col}" TEXT{suffix}')
    return "\n".join(lines)


def generate_select_columns(columns: list[str]) -> str:
    """Generate column list for SELECT statement."""
    lines = []
    for i, col in enumerate(columns):
        suffix = "," if i < len(columns) - 1 else ""
        lines.append(f'       "{col}"{suffix}')
    return "\n".join(lines)


def generate_import_sql(columns: list[str]) -> str:
    """Generate complete import SQL script."""
    staging_cols = generate_staging_columns(columns)
    select_cols = generate_select_columns(columns)

    regions = [
        ("US", "screening_us.csv", "screening_us_raw"),
        ("EU", "screening_eu.csv", "screening_eu_raw"),
        ("APAC", "screening_apac.csv", "screening_apac_raw"),
        ("ROTW", "screening_rotw.csv", "screening_rotw_raw"),
    ]

    sql_parts = []

    # Header
    sql_parts.append(
        """-- =============================================================================
-- Import Script for Equities Data from Regional CSV Files
-- =============================================================================
-- This script provides a robust approach to importing CSV data into the
-- equities table with proper NULL handling, encoding, and error checking.
--
-- IMPORTANT: This script uses explicit TEXT column definitions for staging
-- tables to match the exact CSV column order. This prevents type mismatch
-- errors during COPY operations.
--
-- Usage (from project root):
--   psql -h localhost -p 5432 -U postgres -d postgres -f import_equities_data.sql
--
-- Generated by: tools/generate_import_sql.py
-- =============================================================================

-- =============================================================================
-- SECTION 1: Pre-Import Validation
-- =============================================================================

-- Check if equities table exists
DO
$$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'equities') THEN
            RAISE EXCEPTION 'Table equities does not exist. Please run create_equities_schema.sql first.';
        END IF;
    END
$$;

-- Display current row count (before import)
SELECT 'Current equities table row count:' AS status, COUNT(*) AS row_count
FROM equities;
"""
    )

    # Generate section for each region
    for region_code, csv_file, table_name in regions:
        region_section = f"""
-- =============================================================================
-- SECTION: Import {region_code} Region Data
-- =============================================================================

\\echo '==================================================================='
\\echo 'Importing {region_code} Region Data...'
\\echo '==================================================================='

-- Create staging table with explicit TEXT columns matching CSV order
-- This ensures proper column alignment during COPY
DROP TABLE IF EXISTS {table_name};
CREATE TEMP TABLE {table_name}
(
{staging_cols}
);

-- Import CSV with proper NULL handling and encoding
-- Key parameters:
--   NULL '' - treats empty strings as NULL values
--   ENCODING 'UTF8' - ensures proper character handling
--   HEADER true - skips the CSV header row
\\copy {table_name} FROM 'data/{csv_file}' WITH (FORMAT csv, HEADER true, NULL '', ENCODING 'UTF8')

-- Display staging table statistics
SELECT '{region_code} staging table loaded:' AS status, COUNT(*) AS row_count
FROM {table_name};

-- Set Region for all records (if not already set in CSV)
UPDATE {table_name}
SET "Region" = '{region_code}'
WHERE "Region" IS NULL
   OR "Region" = '';

-- Insert into main equities table
-- Columns are selected in the order defined in equities table schema
INSERT INTO equities
SELECT {select_cols}
FROM {table_name}
ON CONFLICT DO NOTHING;

-- Display insert statistics
SELECT '{region_code} data inserted:' AS status, COUNT(*) AS row_count
FROM equities WHERE "Region" = '{region_code}';

-- Cleanup staging table
DROP TABLE IF EXISTS {table_name};

\\echo '{region_code} Region import completed.'
"""
        sql_parts.append(region_section)

    # Summary section
    sql_parts.append(
        """
-- =============================================================================
-- SECTION: Import Summary and Validation
-- =============================================================================

\\echo '==================================================================='
\\echo 'Import Summary and Validation'
\\echo '==================================================================='

-- Total row count
SELECT 'Total rows in equities table:' AS status, COUNT(*) AS row_count
FROM equities;

-- Row count by region
SELECT "Region", COUNT(*) AS row_count
FROM equities
GROUP BY "Region"
ORDER BY "Region";

-- Data quality checks
SELECT 'Records with missing Ticker:' AS check_name, COUNT(*) AS count
FROM equities
WHERE "Ticker" IS NULL OR "Ticker" = '';

SELECT 'Records with missing Sector:' AS check_name, COUNT(*) AS count
FROM equities
WHERE "Sector" IS NULL OR "Sector" = '';

SELECT 'Records with missing Last Price:' AS check_name, COUNT(*) AS count
FROM equities
WHERE "Last Price" IS NULL;

-- Sample records from each region
\\echo ''
\\echo 'Sample records from each region:'
SELECT "Region", "Ticker", "Name", "Sector", "Last Price", "Market Cap"
FROM equities
WHERE "Region" = 'US'
LIMIT 3;

SELECT "Region", "Ticker", "Name", "Sector", "Last Price", "Market Cap"
FROM equities
WHERE "Region" = 'EU'
LIMIT 3;

SELECT "Region", "Ticker", "Name", "Sector", "Last Price", "Market Cap"
FROM equities
WHERE "Region" = 'APAC'
LIMIT 3;

SELECT "Region", "Ticker", "Name", "Sector", "Last Price", "Market Cap"
FROM equities
WHERE "Region" = 'ROTW'
LIMIT 3;

\\echo '==================================================================='
\\echo 'Import process completed successfully!'
\\echo '==================================================================='
"""
    )

    return "\n".join(sql_parts)


def main():
    parser = argparse.ArgumentParser(
        description="Generate complete import_equities_data.sql from CSV headers"
    )
    parser.add_argument(
        "--csv",
        type=Path,
        default=Path("data/screening_us.csv"),
        help="Path to reference CSV file (default: data/screening_us.csv)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("import_equities_data.sql"),
        help="Output file (default: import_equities_data.sql)",
    )

    args = parser.parse_args()

    # Read CSV header
    if not args.csv.exists():
        print(f"Error: CSV file not found: {args.csv}")
        return 1

    columns = read_csv_header(args.csv)
    print(f"Read {len(columns)} columns from {args.csv}")

    # Generate SQL
    sql = generate_import_sql(columns)

    # Write output
    args.output.write_text(sql, encoding="utf-8")
    print(f"Generated import SQL written to {args.output}")
    print(f"Total SQL length: {len(sql):,} characters")

    return 0


if __name__ == "__main__":
    exit(main())
