-- Generated INSERT statements with proper type casting
-- This fixes the ERROR: column "Market Cap" is of type numeric but expression is of type text

-- Schema contains 299 columns:
--   16 TEXT columns (no cast needed)
--   7 DATE columns (cast with NULLIF)
--   276 NUMERIC columns (cast with NULLIF)

-- SCREENING_US REGION
--------------------------------------------------------------------------------
INSERT INTO equities
("Ticker",
 "ISIN",
 "Name",
 "Description",
 "Exchange",
 "Unit",
 "Sector",
 "Industry",
 "Last Updated",
 "Income Statement Report Date",
 "Next Earnings",
 "Style Class",
 "Next Earnings (Status)",
 "Size Class",
 "Region",
 "Country",
 "Trading Country",
 "Market Cap",
 "Enterprise Value",
 "Last Price",
 "Price Target (YTD Ago)",
 "Total Return (YTD)",
 "Price Target",
 "Price Target - Low",
 "Price Target - Median",
 "Price Target - High",
 "Price Target - #",
 "P/E (NTM)",
 "P/E (LTM)",
 "Altman Z-Score (FY)",
 "Altman Z-Score (FQ)",
 "Altman Z-Score (LTM)",
 "Beta (1Y)",
 "Beta (2Y)",
 "Beta (5Y)",
 "Analyst Rating",
 "# Strong Sell Ratings",
 "# Strong Buys Ratings",
 "# Hold Ratings",
 "# Buys Ratings",
 "# Sell Ratings",
 "Total Revenues/CAGR (5Y FY)",
 "Total Revenues (FQ)",
 "Total Revenues (-1FY)",
 "Total Revenues (FY)",
 "Total Revenues (LTM)",
 "Total Operating Expenses (LTM)",
 "P/TBV (LTM)",
 "TBV (FY)",
 "TBV (LTM)",
 "Market Cap (Country R)",
 "Tot. Return %/CAGR (3Y)",
 "Tot. Return %/CAGR (10Y)",
 "Total Return (5Y)",
 "Total Return (10Y)",
 "Net Income/Adj. (-1FY)",
 "CFF (LTM)",
 "CFI (LTM)",
 "FCF (LTM)",
 "CFO (LTM)",
 "EBITDA (FQ)",
 "EBITDA (LTM)",
 "EBITDA (FY)",
 "EBITDA (-1FY)",
 "EBITDA/Adj. (LTM)",
 "EBITDA/Adj. (FY)",
 "EBITDA/Adj. (-1FY)",
 "EBIT (FQ)",
 "EBIT (LTM)",
 "EBIT (FY)",
 "EBIT (-1FY)",
 "EBIT/Adj. (-1FY)",
 "EBIT/Adj. (FY)",
 "EBIT/Adj. (LTM)",
 "EBIT - Est Med (FY1E)",
 "EBIT - Est Med (NTM)",
 "Return On Equity % (LTM)",
 "Return On Equity % (FY)",
 "Net Income - (IS) (FY)",
 "Net Income - (IS) (LTM)",
 "Normalized Net Income (FY)",
 "Normalized Net Income (LTM)",
 "Net Income/Adj. (FY)",
 "Net Income/Adj. (LTM)",
 "Net Income Margin % (FY)",
 "Net Income Margin % (LTM)",
 "Volatility (1M)",
 "Volatility (3M)",
 "Volatility (6M)",
 "Volatility (1Y)",
 "Volume (Shrs)",
 "Dividend Per Share (LTM)",
 "Div Yield (Ind)",
 "Div Yield (LTM)",
 "Total Debt (FY)",
 "Total Equity (FY)",
 "Total Equity (LTM)",
 "Total Debt (LTM)",
 "Total Assets (LTM)",
 "Total Assets (FY)",
 "Current Ratio (FY)",
 "Current Ratio (LTM)",
 "Gross Profit Margin % (FY)",
 "Gross Profit Margin % (LTM)",
 "Asset Turnover (FY)",
 "Asset Turnover (LTM)",
 "Gross Profit (LTM)",
 "Gross Profit (FY)",
 "EPS Norm - Est Avg (NTM)",
 "EPS/Adj. (-1FY)",
 "EPS/Adj. (FY)",
 "EPS/Adj. (LTM)",
 "EPS Norm - Est Avg (FY1E)",
 "Gain (Loss) On Sale Of Assets (LTM)",
 "Cost Of Revenues (LTM)",
 "Cash Acquisitions (LTM)",
 "Cash Acquisitions (FY)",
 "Cash Acquisitions (-1FY)",
 "Inventory (LTM)",
 "Goodwill (FQ)",
 "Goodwill (LTM)",
 "Goodwill (FY)",
 "Goodwill (-1FY)",
 "Impairment of Goodwill (FQ)",
 "Impairment of Goodwill (LTM)",
 "Impairment of Goodwill (-1FY)",
 "Impairment of Goodwill (FY)",
 "Operating Income (LTM)",
 "Asset Writedown (LTM)",
 "Asset Writedown (FY)",
 "Asset Writedown (-1FY)",
 "Operating Income (FY)",
 "Capital Expenditure (LTM)",
 "Capital Expenditure (-1FY)",
 "Capital Expenditure (FY)",
 "Retained Earnings (LTM)",
 "Total Current Assets (LTM)",
 "Total Current Liabilities (LTM)",
 "R&D Expenses (LTM)",
 "Restructuring Charges (LTM)",
 "Restructuring Charges (FQ)",
 "Restructuring Charges (-1FY)",
 "Restructuring Charges (FY)",
 "Interest Expense/Total (LTM)",
 "Merger & Restructuring Charges (LTM)",
 "Working Capital (LTM)",
 "Other Unusual Items/Total (LTM)",
 "Interest Income On Investments (LTM)",
 "Buyback Yield (LTM)",
 "Return on Assets (ROA) % (LTM)",
 "Return on Assets (ROA) % (FY)",
 "Net Income - (IS) (-1FY)",
 "Normalized Net Income (-1FY)",
 "P/E (-1FYLTM)",
 "CFF (FY)",
 "CFF (-1FY)",
 "CFI (FY)",
 "CFI (-1FY)",
 "CFO (FY)",
 "CFO (-1FY)",
 "Div Yield (-1FYInd)",
 "FCF (FY)",
 "Capital Expenditure (FQ)",
 "Capital Expenditure (5YAVGFQ)",
 "CFF (FQ)",
 "CFI (FQ)",
 "CFO (FQ)",
 "FCF (FQ)",
 "Total Revenues (5YAVGFQ)",
 "EBITDA (5YAVGFQ)",
 "EBIT (5YAVGFQ)",
 "P/E (5YAVGLTM)",
 "FCF (5YAVGFQ)",
 "Cash Acquisitions (FQ)",
 "Cash Acquisitions (5YAVGFQ)",
 "Asset Writedown (FQ)",
 "Asset Writedown (5YAVGFQ)",
 "Impairment of Goodwill (5YAVGFQ)",
 "Operating Income (FQ)",
 "Operating Income (5YAVGFQ)",
 "P/B (LTM)",
 "P/B (-1FY)",
 "P/B (5YAVG)",
 "Cash And Equivalents (LTM)",
 "Cash And Equivalents (FQ)",
 "Cash And Equivalents (FY)",
 "Cash And Equivalents (5YAVGFQ)",
 "Inventory (FQ)",
 "Inventory (FY)",
 "Goodwill (5YAVGFQ)",
 "Inventory (5YAVGFQ)",
 "Retained Earnings (FQ)",
 "Retained Earnings (FY)",
 "Retained Earnings (5YAVGFQ)",
 "Working Capital (FQ)",
 "Working Capital (FY)",
 "Working Capital (5YAVGFY)",
 "Div Yield (TTM)",
 "Div Yield (NTM)",
 "Div Yield (5YAVGLTM)",
 "Gross Intangible Assets (LTM)",
 "Gross Intangible Assets (FY)",
 "Gross Intangible Assets (5YAVGFQ)",
 "Restructuring Charges (5YAVGFQ)",
 "Merger & Restructuring Charges (FQ)",
 "Merger & Restructuring Charges (FY)",
 "Merger & Restructuring Charges (5YAVGFQ)",
 "Normalized Net Income (FQ)",
 "Normalized Net Income (5YAVGFQ)",
 "Net Income/Adj. (FQ)",
 "Net Income/Adj. (5YAVGFQ)",
 "Net Income - (IS) (FQ)",
 "Net Income - (IS) (5YAVGFQ)",
 "Net Income - (IS) (5YAVGLTM)",
 "Normalized Net Income (5YAVGLTM)",
 "EBITDA (5YAVGLTM)",
 "EBIT (5YAVGLTM)",
 "Total Revenues (5YAVGLTM)",
 "Revenues - Est YoY % (FY1E)",
 "Price Chg. % (1M)",
 "Price Chg. % (3M)",
 "1-Day %",
 "Price (5D Ago)",
 "Price (1W Ago)",
 "Price (1M Ago)",
 "Price (3M Ago)",
 "Price (6M Ago)",
 "Price (1Y Ago)",
 "Price (3Y Ago)",
 "Price (5Y Ago)",
 "Price (QTD Ago)",
 "Rel. Volume",
 "Shrs Out",
 "Shrs Out (-1FY)",
 "Common Dividends Paid (LTM)",
 "Common Dividends Paid (FY)",
 "Selling General & Admin Expenses/Total (FQ)",
 "Selling General & Admin Expenses/Total (FY)",
 "Selling General & Admin Expenses/Total (-1FY)",
 "Selling General & Admin Expenses/Total (5YAVGFQ)",
 "Accounts Receivable/Total (FY)",
 "Accounts Receivable/Total (-1FY)",
 "Accounts Receivable/Total (5YAVGFQ)",
 "Marketing Expenses (FQ)",
 "Marketing Expenses (FY)",
 "Marketing Expenses (-1FY)",
 "Marketing Expenses (5YAVGLTM)",
 "Revenues - Est Avg (NTM)",
 "Revenues - Est Avg (FY1E)",
 "Revenues - Est Med (NTM)",
 "Revenues - Est Med (FY1E)",
 "EV/Sales (EST FY1)",
 "EV/Sales (LTM)",
 "EV/Sales (NTM)",
 "EV/Sales (-1FYLTM)",
 "EV/Sales (-2FYLTM)",
 "EV/Sales (-3FYLTM)",
 "EV/Sales (3YAVGLTM)",
 "EV/Sales (-1FQLTM)",
 "EV/Sales (-2FQLTM)",
 "EV/Sales (-3FQLTM)",
 "EV/Sales (-4FQLTM)",
 "Full Time Employees (FQ)",
 "Full Time Employees (FY)",
 "Full Time Employees (-1FY)",
 "Full Time Employees (-2FY)",
 "Full Time Employees (-3FY)",
 "Avg Employees (5YAVGFY)",
 "52W High/Adj",
 "52W Low/Adj",
 "EMA (20D)",
 "EMA (50D)",
 "EMA (100D)",
 "EMA (250D)",
 "EV/EBITDA (LTM)",
 "EV/EBITDA (NTM)",
 "EV/EBITDA (-1FYLTM)",
 "EV/EBITDA (-1FQLTM)",
 "EV/EBITDA (3YAVGLTM)",
 "EV/EBITDA (EST FY1)",
 "P/E (EST FY1)",
 "P/E (-2FYLTM)",
 "P/E (-3FYLTM)",
 "P/E (3YAVGLTM)",
 "P/E (-1FQLTM)",
 "P/E (-2FQLTM)",
 "P/E (-3FQLTM)",
 "P/E (-0FQQoQLTM)",
 "P/E (-0FYYoYLTM)",
 "P/E (-1FYYoYLTM)",
 "P/E (-0FQYoYLTM)",
 "Dividend Record (Announce Date)",
 "Dividend Record (Ex Date)",
 "Dividend Record (Payable Date)",
 "Dividend Record (Record Date)",
 "Dividend Record (Frequency)",
 "Dividend Record (Currency)",
 "Dividend Record (Amount)",
 "Dividend Streak")
SELECT "Ticker",
       "ISIN",
       "Name",
       "Description",
       "Exchange",
       "Unit",
       "Sector",
       "Industry",
       NULLIF("Last Updated", '')::DATE,
       NULLIF("Income Statement Report Date", '')::DATE,
       NULLIF("Next Earnings", '')::DATE,
       "Style Class",
       "Next Earnings (Status)",
       "Size Class",
       "Region",
       "Country",
       "Trading Country",
       NULLIF("Market Cap", '')::NUMERIC,
       NULLIF("Enterprise Value", '')::NUMERIC,
       NULLIF("Last Price", '')::NUMERIC,
       NULLIF("Price Target (YTD Ago)", '')::NUMERIC,
       NULLIF("Total Return (YTD)", '')::NUMERIC,
       NULLIF("Price Target", '')::NUMERIC,
       NULLIF("Price Target - Low", '')::NUMERIC,
       NULLIF("Price Target - Median", '')::NUMERIC,
       NULLIF("Price Target - High", '')::NUMERIC,
       NULLIF("Price Target - #", '')::NUMERIC,
       NULLIF("P/E (NTM)", '')::NUMERIC,
       NULLIF("P/E (LTM)", '')::NUMERIC,
       NULLIF("Altman Z-Score (FY)", '')::NUMERIC,
       NULLIF("Altman Z-Score (FQ)", '')::NUMERIC,
       NULLIF("Altman Z-Score (LTM)", '')::NUMERIC,
       NULLIF("Beta (1Y)", '')::NUMERIC,
       NULLIF("Beta (2Y)", '')::NUMERIC,
       NULLIF("Beta (5Y)", '')::NUMERIC,
       NULLIF("Analyst Rating", '')::NUMERIC,
       NULLIF("# Strong Sell Ratings", '')::NUMERIC,
       NULLIF("# Strong Buys Ratings", '')::NUMERIC,
       NULLIF("# Hold Ratings", '')::NUMERIC,
       NULLIF("# Buys Ratings", '')::NUMERIC,
       NULLIF("# Sell Ratings", '')::NUMERIC,
       NULLIF("Total Revenues/CAGR (5Y FY)", '')::NUMERIC,
       NULLIF("Total Revenues (FQ)", '')::NUMERIC,
       NULLIF("Total Revenues (-1FY)", '')::NUMERIC,
       NULLIF("Total Revenues (FY)", '')::NUMERIC,
       NULLIF("Total Revenues (LTM)", '')::NUMERIC,
       NULLIF("Total Operating Expenses (LTM)", '')::NUMERIC,
       NULLIF("P/TBV (LTM)", '')::NUMERIC,
       NULLIF("TBV (FY)", '')::NUMERIC,
       NULLIF("TBV (LTM)", '')::NUMERIC,
       NULLIF("Market Cap (Country R)", '')::NUMERIC,
       NULLIF("Tot. Return %/CAGR (3Y)", '')::NUMERIC,
       NULLIF("Tot. Return %/CAGR (10Y)", '')::NUMERIC,
       NULLIF("Total Return (5Y)", '')::NUMERIC,
       NULLIF("Total Return (10Y)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("CFF (LTM)", '')::NUMERIC,
       NULLIF("CFI (LTM)", '')::NUMERIC,
       NULLIF("FCF (LTM)", '')::NUMERIC,
       NULLIF("CFO (LTM)", '')::NUMERIC,
       NULLIF("EBITDA (FQ)", '')::NUMERIC,
       NULLIF("EBITDA (LTM)", '')::NUMERIC,
       NULLIF("EBITDA (FY)", '')::NUMERIC,
       NULLIF("EBITDA (-1FY)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (FY)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EBIT (FQ)", '')::NUMERIC,
       NULLIF("EBIT (LTM)", '')::NUMERIC,
       NULLIF("EBIT (FY)", '')::NUMERIC,
       NULLIF("EBIT (-1FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EBIT - Est Med (FY1E)", '')::NUMERIC,
       NULLIF("EBIT - Est Med (NTM)", '')::NUMERIC,
       NULLIF("Return On Equity % (LTM)", '')::NUMERIC,
       NULLIF("Return On Equity % (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (LTM)", '')::NUMERIC,
       NULLIF("Normalized Net Income (FY)", '')::NUMERIC,
       NULLIF("Normalized Net Income (LTM)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (FY)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (LTM)", '')::NUMERIC,
       NULLIF("Net Income Margin % (FY)", '')::NUMERIC,
       NULLIF("Net Income Margin % (LTM)", '')::NUMERIC,
       NULLIF("Volatility (1M)", '')::NUMERIC,
       NULLIF("Volatility (3M)", '')::NUMERIC,
       NULLIF("Volatility (6M)", '')::NUMERIC,
       NULLIF("Volatility (1Y)", '')::NUMERIC,
       NULLIF("Volume (Shrs)", '')::NUMERIC,
       NULLIF("Dividend Per Share (LTM)", '')::NUMERIC,
       NULLIF("Div Yield (Ind)", '')::NUMERIC,
       NULLIF("Div Yield (LTM)", '')::NUMERIC,
       NULLIF("Total Debt (FY)", '')::NUMERIC,
       NULLIF("Total Equity (FY)", '')::NUMERIC,
       NULLIF("Total Equity (LTM)", '')::NUMERIC,
       NULLIF("Total Debt (LTM)", '')::NUMERIC,
       NULLIF("Total Assets (LTM)", '')::NUMERIC,
       NULLIF("Total Assets (FY)", '')::NUMERIC,
       NULLIF("Current Ratio (FY)", '')::NUMERIC,
       NULLIF("Current Ratio (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit Margin % (FY)", '')::NUMERIC,
       NULLIF("Gross Profit Margin % (LTM)", '')::NUMERIC,
       NULLIF("Asset Turnover (FY)", '')::NUMERIC,
       NULLIF("Asset Turnover (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit (FY)", '')::NUMERIC,
       NULLIF("EPS Norm - Est Avg (NTM)", '')::NUMERIC,
       NULLIF("EPS/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EPS/Adj. (FY)", '')::NUMERIC,
       NULLIF("EPS/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EPS Norm - Est Avg (FY1E)", '')::NUMERIC,
       NULLIF("Gain (Loss) On Sale Of Assets (LTM)", '')::NUMERIC,
       NULLIF("Cost Of Revenues (LTM)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (LTM)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (FY)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (-1FY)", '')::NUMERIC,
       NULLIF("Inventory (LTM)", '')::NUMERIC,
       NULLIF("Goodwill (FQ)", '')::NUMERIC,
       NULLIF("Goodwill (LTM)", '')::NUMERIC,
       NULLIF("Goodwill (FY)", '')::NUMERIC,
       NULLIF("Goodwill (-1FY)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (FQ)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (LTM)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (-1FY)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (FY)", '')::NUMERIC,
       NULLIF("Operating Income (LTM)", '')::NUMERIC,
       NULLIF("Asset Writedown (LTM)", '')::NUMERIC,
       NULLIF("Asset Writedown (FY)", '')::NUMERIC,
       NULLIF("Asset Writedown (-1FY)", '')::NUMERIC,
       NULLIF("Operating Income (FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (LTM)", '')::NUMERIC,
       NULLIF("Capital Expenditure (-1FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (FY)", '')::NUMERIC,
       NULLIF("Retained Earnings (LTM)", '')::NUMERIC,
       NULLIF("Total Current Assets (LTM)", '')::NUMERIC,
       NULLIF("Total Current Liabilities (LTM)", '')::NUMERIC,
       NULLIF("R&D Expenses (LTM)", '')::NUMERIC,
       NULLIF("Restructuring Charges (LTM)", '')::NUMERIC,
       NULLIF("Restructuring Charges (FQ)", '')::NUMERIC,
       NULLIF("Restructuring Charges (-1FY)", '')::NUMERIC,
       NULLIF("Restructuring Charges (FY)", '')::NUMERIC,
       NULLIF("Interest Expense/Total (LTM)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (LTM)", '')::NUMERIC,
       NULLIF("Working Capital (LTM)", '')::NUMERIC,
       NULLIF("Other Unusual Items/Total (LTM)", '')::NUMERIC,
       NULLIF("Interest Income On Investments (LTM)", '')::NUMERIC,
       NULLIF("Buyback Yield (LTM)", '')::NUMERIC,
       NULLIF("Return on Assets (ROA) % (LTM)", '')::NUMERIC,
       NULLIF("Return on Assets (ROA) % (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (-1FY)", '')::NUMERIC,
       NULLIF("Normalized Net Income (-1FY)", '')::NUMERIC,
       NULLIF("P/E (-1FYLTM)", '')::NUMERIC,
       NULLIF("CFF (FY)", '')::NUMERIC,
       NULLIF("CFF (-1FY)", '')::NUMERIC,
       NULLIF("CFI (FY)", '')::NUMERIC,
       NULLIF("CFI (-1FY)", '')::NUMERIC,
       NULLIF("CFO (FY)", '')::NUMERIC,
       NULLIF("CFO (-1FY)", '')::NUMERIC,
       NULLIF("Div Yield (-1FYInd)", '')::NUMERIC,
       NULLIF("FCF (FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (FQ)", '')::NUMERIC,
       NULLIF("Capital Expenditure (5YAVGFQ)", '')::NUMERIC,
       NULLIF("CFF (FQ)", '')::NUMERIC,
       NULLIF("CFI (FQ)", '')::NUMERIC,
       NULLIF("CFO (FQ)", '')::NUMERIC,
       NULLIF("FCF (FQ)", '')::NUMERIC,
       NULLIF("Total Revenues (5YAVGFQ)", '')::NUMERIC,
       NULLIF("EBITDA (5YAVGFQ)", '')::NUMERIC,
       NULLIF("EBIT (5YAVGFQ)", '')::NUMERIC,
       NULLIF("P/E (5YAVGLTM)", '')::NUMERIC,
       NULLIF("FCF (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (FQ)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Asset Writedown (FQ)", '')::NUMERIC,
       NULLIF("Asset Writedown (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Operating Income (FQ)", '')::NUMERIC,
       NULLIF("Operating Income (5YAVGFQ)", '')::NUMERIC,
       NULLIF("P/B (LTM)", '')::NUMERIC,
       NULLIF("P/B (-1FY)", '')::NUMERIC,
       NULLIF("P/B (5YAVG)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (LTM)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (FQ)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (FY)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Inventory (FQ)", '')::NUMERIC,
       NULLIF("Inventory (FY)", '')::NUMERIC,
       NULLIF("Goodwill (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Inventory (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Retained Earnings (FQ)", '')::NUMERIC,
       NULLIF("Retained Earnings (FY)", '')::NUMERIC,
       NULLIF("Retained Earnings (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Working Capital (FQ)", '')::NUMERIC,
       NULLIF("Working Capital (FY)", '')::NUMERIC,
       NULLIF("Working Capital (5YAVGFY)", '')::NUMERIC,
       NULLIF("Div Yield (TTM)", '')::NUMERIC,
       NULLIF("Div Yield (NTM)", '')::NUMERIC,
       NULLIF("Div Yield (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (LTM)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (FY)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Restructuring Charges (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (FQ)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (FY)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Normalized Net Income (FQ)", '')::NUMERIC,
       NULLIF("Normalized Net Income (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (FQ)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (FQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Normalized Net Income (5YAVGLTM)", '')::NUMERIC,
       NULLIF("EBITDA (5YAVGLTM)", '')::NUMERIC,
       NULLIF("EBIT (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Total Revenues (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Revenues - Est YoY % (FY1E)", '')::NUMERIC,
       NULLIF("Price Chg. % (1M)", '')::NUMERIC,
       NULLIF("Price Chg. % (3M)", '')::NUMERIC,
       NULLIF("1-Day %", '')::NUMERIC,
       NULLIF("Price (5D Ago)", '')::NUMERIC,
       NULLIF("Price (1W Ago)", '')::NUMERIC,
       NULLIF("Price (1M Ago)", '')::NUMERIC,
       NULLIF("Price (3M Ago)", '')::NUMERIC,
       NULLIF("Price (6M Ago)", '')::NUMERIC,
       NULLIF("Price (1Y Ago)", '')::NUMERIC,
       NULLIF("Price (3Y Ago)", '')::NUMERIC,
       NULLIF("Price (5Y Ago)", '')::NUMERIC,
       NULLIF("Price (QTD Ago)", '')::NUMERIC,
       NULLIF("Rel. Volume", '')::NUMERIC,
       NULLIF("Shrs Out", '')::NUMERIC,
       NULLIF("Shrs Out (-1FY)", '')::NUMERIC,
       NULLIF("Common Dividends Paid (LTM)", '')::NUMERIC,
       NULLIF("Common Dividends Paid (FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (FQ)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (-1FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (FY)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (-1FY)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Marketing Expenses (FQ)", '')::NUMERIC,
       NULLIF("Marketing Expenses (FY)", '')::NUMERIC,
       NULLIF("Marketing Expenses (-1FY)", '')::NUMERIC,
       NULLIF("Marketing Expenses (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Avg (NTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Avg (FY1E)", '')::NUMERIC,
       NULLIF("Revenues - Est Med (NTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Med (FY1E)", '')::NUMERIC,
       NULLIF("EV/Sales (EST FY1)", '')::NUMERIC,
       NULLIF("EV/Sales (LTM)", '')::NUMERIC,
       NULLIF("EV/Sales (NTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-1FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-2FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-3FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (3YAVGLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-1FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-2FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-3FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-4FQLTM)", '')::NUMERIC,
       NULLIF("Full Time Employees (FQ)", '')::NUMERIC,
       NULLIF("Full Time Employees (FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-1FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-2FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-3FY)", '')::NUMERIC,
       NULLIF("Avg Employees (5YAVGFY)", '')::NUMERIC,
       NULLIF("52W High/Adj", '')::NUMERIC,
       NULLIF("52W Low/Adj", '')::NUMERIC,
       NULLIF("EMA (20D)", '')::NUMERIC,
       NULLIF("EMA (50D)", '')::NUMERIC,
       NULLIF("EMA (100D)", '')::NUMERIC,
       NULLIF("EMA (250D)", '')::NUMERIC,
       NULLIF("EV/EBITDA (LTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (NTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (-1FYLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (-1FQLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (3YAVGLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (EST FY1)", '')::NUMERIC,
       NULLIF("P/E (EST FY1)", '')::NUMERIC,
       NULLIF("P/E (-2FYLTM)", '')::NUMERIC,
       NULLIF("P/E (-3FYLTM)", '')::NUMERIC,
       NULLIF("P/E (3YAVGLTM)", '')::NUMERIC,
       NULLIF("P/E (-1FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-2FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-3FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FQQoQLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FYYoYLTM)", '')::NUMERIC,
       NULLIF("P/E (-1FYYoYLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FQYoYLTM)", '')::NUMERIC,
       NULLIF("Dividend Record (Announce Date)", '')::DATE,
       NULLIF("Dividend Record (Ex Date)", '')::DATE,
       NULLIF("Dividend Record (Payable Date)", '')::DATE,
       NULLIF("Dividend Record (Record Date)", '')::DATE,
       "Dividend Record (Frequency)",
       "Dividend Record (Currency)",
       NULLIF("Dividend Record (Amount)", '')::NUMERIC,
       NULLIF("Dividend Streak", '')::NUMERIC
FROM screening_us
ON CONFLICT DO NOTHING;


-- SCREENING_EU REGION
--------------------------------------------------------------------------------
INSERT INTO equities
("Ticker",
 "ISIN",
 "Name",
 "Description",
 "Exchange",
 "Unit",
 "Sector",
 "Industry",
 "Last Updated",
 "Income Statement Report Date",
 "Next Earnings",
 "Style Class",
 "Next Earnings (Status)",
 "Size Class",
 "Region",
 "Country",
 "Trading Country",
 "Market Cap",
 "Enterprise Value",
 "Last Price",
 "Price Target (YTD Ago)",
 "Total Return (YTD)",
 "Price Target",
 "Price Target - Low",
 "Price Target - Median",
 "Price Target - High",
 "Price Target - #",
 "P/E (NTM)",
 "P/E (LTM)",
 "Altman Z-Score (FY)",
 "Altman Z-Score (FQ)",
 "Altman Z-Score (LTM)",
 "Beta (1Y)",
 "Beta (2Y)",
 "Beta (5Y)",
 "Analyst Rating",
 "# Strong Sell Ratings",
 "# Strong Buys Ratings",
 "# Hold Ratings",
 "# Buys Ratings",
 "# Sell Ratings",
 "Total Revenues/CAGR (5Y FY)",
 "Total Revenues (FQ)",
 "Total Revenues (-1FY)",
 "Total Revenues (FY)",
 "Total Revenues (LTM)",
 "Total Operating Expenses (LTM)",
 "P/TBV (LTM)",
 "TBV (FY)",
 "TBV (LTM)",
 "Market Cap (Country R)",
 "Tot. Return %/CAGR (3Y)",
 "Tot. Return %/CAGR (10Y)",
 "Total Return (5Y)",
 "Total Return (10Y)",
 "Net Income/Adj. (-1FY)",
 "CFF (LTM)",
 "CFI (LTM)",
 "FCF (LTM)",
 "CFO (LTM)",
 "EBITDA (FQ)",
 "EBITDA (LTM)",
 "EBITDA (FY)",
 "EBITDA (-1FY)",
 "EBITDA/Adj. (LTM)",
 "EBITDA/Adj. (FY)",
 "EBITDA/Adj. (-1FY)",
 "EBIT (FQ)",
 "EBIT (LTM)",
 "EBIT (FY)",
 "EBIT (-1FY)",
 "EBIT/Adj. (-1FY)",
 "EBIT/Adj. (FY)",
 "EBIT/Adj. (LTM)",
 "EBIT - Est Med (FY1E)",
 "EBIT - Est Med (NTM)",
 "Return On Equity % (LTM)",
 "Return On Equity % (FY)",
 "Net Income - (IS) (FY)",
 "Net Income - (IS) (LTM)",
 "Normalized Net Income (FY)",
 "Normalized Net Income (LTM)",
 "Net Income/Adj. (FY)",
 "Net Income/Adj. (LTM)",
 "Net Income Margin % (FY)",
 "Net Income Margin % (LTM)",
 "Volatility (1M)",
 "Volatility (3M)",
 "Volatility (6M)",
 "Volatility (1Y)",
 "Volume (Shrs)",
 "Dividend Per Share (LTM)",
 "Div Yield (Ind)",
 "Div Yield (LTM)",
 "Total Debt (FY)",
 "Total Equity (FY)",
 "Total Equity (LTM)",
 "Total Debt (LTM)",
 "Total Assets (LTM)",
 "Total Assets (FY)",
 "Current Ratio (FY)",
 "Current Ratio (LTM)",
 "Gross Profit Margin % (FY)",
 "Gross Profit Margin % (LTM)",
 "Asset Turnover (FY)",
 "Asset Turnover (LTM)",
 "Gross Profit (LTM)",
 "Gross Profit (FY)",
 "EPS Norm - Est Avg (NTM)",
 "EPS/Adj. (-1FY)",
 "EPS/Adj. (FY)",
 "EPS/Adj. (LTM)",
 "EPS Norm - Est Avg (FY1E)",
 "Gain (Loss) On Sale Of Assets (LTM)",
 "Cost Of Revenues (LTM)",
 "Cash Acquisitions (LTM)",
 "Cash Acquisitions (FY)",
 "Cash Acquisitions (-1FY)",
 "Inventory (LTM)",
 "Goodwill (FQ)",
 "Goodwill (LTM)",
 "Goodwill (FY)",
 "Goodwill (-1FY)",
 "Impairment of Goodwill (FQ)",
 "Impairment of Goodwill (LTM)",
 "Impairment of Goodwill (-1FY)",
 "Impairment of Goodwill (FY)",
 "Operating Income (LTM)",
 "Asset Writedown (LTM)",
 "Asset Writedown (FY)",
 "Asset Writedown (-1FY)",
 "Operating Income (FY)",
 "Capital Expenditure (LTM)",
 "Capital Expenditure (-1FY)",
 "Capital Expenditure (FY)",
 "Retained Earnings (LTM)",
 "Total Current Assets (LTM)",
 "Total Current Liabilities (LTM)",
 "R&D Expenses (LTM)",
 "Restructuring Charges (LTM)",
 "Restructuring Charges (FQ)",
 "Restructuring Charges (-1FY)",
 "Restructuring Charges (FY)",
 "Interest Expense/Total (LTM)",
 "Merger & Restructuring Charges (LTM)",
 "Working Capital (LTM)",
 "Other Unusual Items/Total (LTM)",
 "Interest Income On Investments (LTM)",
 "Buyback Yield (LTM)",
 "Return on Assets (ROA) % (LTM)",
 "Return on Assets (ROA) % (FY)",
 "Net Income - (IS) (-1FY)",
 "Normalized Net Income (-1FY)",
 "P/E (-1FYLTM)",
 "CFF (FY)",
 "CFF (-1FY)",
 "CFI (FY)",
 "CFI (-1FY)",
 "CFO (FY)",
 "CFO (-1FY)",
 "Div Yield (-1FYInd)",
 "FCF (FY)",
 "Capital Expenditure (FQ)",
 "Capital Expenditure (5YAVGFQ)",
 "CFF (FQ)",
 "CFI (FQ)",
 "CFO (FQ)",
 "FCF (FQ)",
 "Total Revenues (5YAVGFQ)",
 "EBITDA (5YAVGFQ)",
 "EBIT (5YAVGFQ)",
 "P/E (5YAVGLTM)",
 "FCF (5YAVGFQ)",
 "Cash Acquisitions (FQ)",
 "Cash Acquisitions (5YAVGFQ)",
 "Asset Writedown (FQ)",
 "Asset Writedown (5YAVGFQ)",
 "Impairment of Goodwill (5YAVGFQ)",
 "Operating Income (FQ)",
 "Operating Income (5YAVGFQ)",
 "P/B (LTM)",
 "P/B (-1FY)",
 "P/B (5YAVG)",
 "Cash And Equivalents (LTM)",
 "Cash And Equivalents (FQ)",
 "Cash And Equivalents (FY)",
 "Cash And Equivalents (5YAVGFQ)",
 "Inventory (FQ)",
 "Inventory (FY)",
 "Goodwill (5YAVGFQ)",
 "Inventory (5YAVGFQ)",
 "Retained Earnings (FQ)",
 "Retained Earnings (FY)",
 "Retained Earnings (5YAVGFQ)",
 "Working Capital (FQ)",
 "Working Capital (FY)",
 "Working Capital (5YAVGFY)",
 "Div Yield (TTM)",
 "Div Yield (NTM)",
 "Div Yield (5YAVGLTM)",
 "Gross Intangible Assets (LTM)",
 "Gross Intangible Assets (FY)",
 "Gross Intangible Assets (5YAVGFQ)",
 "Restructuring Charges (5YAVGFQ)",
 "Merger & Restructuring Charges (FQ)",
 "Merger & Restructuring Charges (FY)",
 "Merger & Restructuring Charges (5YAVGFQ)",
 "Normalized Net Income (FQ)",
 "Normalized Net Income (5YAVGFQ)",
 "Net Income/Adj. (FQ)",
 "Net Income/Adj. (5YAVGFQ)",
 "Net Income - (IS) (FQ)",
 "Net Income - (IS) (5YAVGFQ)",
 "Net Income - (IS) (5YAVGLTM)",
 "Normalized Net Income (5YAVGLTM)",
 "EBITDA (5YAVGLTM)",
 "EBIT (5YAVGLTM)",
 "Total Revenues (5YAVGLTM)",
 "Revenues - Est YoY % (FY1E)",
 "Price Chg. % (1M)",
 "Price Chg. % (3M)",
 "1-Day %",
 "Price (5D Ago)",
 "Price (1W Ago)",
 "Price (1M Ago)",
 "Price (3M Ago)",
 "Price (6M Ago)",
 "Price (1Y Ago)",
 "Price (3Y Ago)",
 "Price (5Y Ago)",
 "Price (QTD Ago)",
 "Rel. Volume",
 "Shrs Out",
 "Shrs Out (-1FY)",
 "Common Dividends Paid (LTM)",
 "Common Dividends Paid (FY)",
 "Selling General & Admin Expenses/Total (FQ)",
 "Selling General & Admin Expenses/Total (FY)",
 "Selling General & Admin Expenses/Total (-1FY)",
 "Selling General & Admin Expenses/Total (5YAVGFQ)",
 "Accounts Receivable/Total (FY)",
 "Accounts Receivable/Total (-1FY)",
 "Accounts Receivable/Total (5YAVGFQ)",
 "Marketing Expenses (FQ)",
 "Marketing Expenses (FY)",
 "Marketing Expenses (-1FY)",
 "Marketing Expenses (5YAVGLTM)",
 "Revenues - Est Avg (NTM)",
 "Revenues - Est Avg (FY1E)",
 "Revenues - Est Med (NTM)",
 "Revenues - Est Med (FY1E)",
 "EV/Sales (EST FY1)",
 "EV/Sales (LTM)",
 "EV/Sales (NTM)",
 "EV/Sales (-1FYLTM)",
 "EV/Sales (-2FYLTM)",
 "EV/Sales (-3FYLTM)",
 "EV/Sales (3YAVGLTM)",
 "EV/Sales (-1FQLTM)",
 "EV/Sales (-2FQLTM)",
 "EV/Sales (-3FQLTM)",
 "EV/Sales (-4FQLTM)",
 "Full Time Employees (FQ)",
 "Full Time Employees (FY)",
 "Full Time Employees (-1FY)",
 "Full Time Employees (-2FY)",
 "Full Time Employees (-3FY)",
 "Avg Employees (5YAVGFY)",
 "52W High/Adj",
 "52W Low/Adj",
 "EMA (20D)",
 "EMA (50D)",
 "EMA (100D)",
 "EMA (250D)",
 "EV/EBITDA (LTM)",
 "EV/EBITDA (NTM)",
 "EV/EBITDA (-1FYLTM)",
 "EV/EBITDA (-1FQLTM)",
 "EV/EBITDA (3YAVGLTM)",
 "EV/EBITDA (EST FY1)",
 "P/E (EST FY1)",
 "P/E (-2FYLTM)",
 "P/E (-3FYLTM)",
 "P/E (3YAVGLTM)",
 "P/E (-1FQLTM)",
 "P/E (-2FQLTM)",
 "P/E (-3FQLTM)",
 "P/E (-0FQQoQLTM)",
 "P/E (-0FYYoYLTM)",
 "P/E (-1FYYoYLTM)",
 "P/E (-0FQYoYLTM)",
 "Dividend Record (Announce Date)",
 "Dividend Record (Ex Date)",
 "Dividend Record (Payable Date)",
 "Dividend Record (Record Date)",
 "Dividend Record (Frequency)",
 "Dividend Record (Currency)",
 "Dividend Record (Amount)",
 "Dividend Streak")
SELECT "Ticker",
       "ISIN",
       "Name",
       "Description",
       "Exchange",
       "Unit",
       "Sector",
       "Industry",
       NULLIF("Last Updated", '')::DATE,
       NULLIF("Income Statement Report Date", '')::DATE,
       NULLIF("Next Earnings", '')::DATE,
       "Style Class",
       "Next Earnings (Status)",
       "Size Class",
       "Region",
       "Country",
       "Trading Country",
       NULLIF("Market Cap", '')::NUMERIC,
       NULLIF("Enterprise Value", '')::NUMERIC,
       NULLIF("Last Price", '')::NUMERIC,
       NULLIF("Price Target (YTD Ago)", '')::NUMERIC,
       NULLIF("Total Return (YTD)", '')::NUMERIC,
       NULLIF("Price Target", '')::NUMERIC,
       NULLIF("Price Target - Low", '')::NUMERIC,
       NULLIF("Price Target - Median", '')::NUMERIC,
       NULLIF("Price Target - High", '')::NUMERIC,
       NULLIF("Price Target - #", '')::NUMERIC,
       NULLIF("P/E (NTM)", '')::NUMERIC,
       NULLIF("P/E (LTM)", '')::NUMERIC,
       NULLIF("Altman Z-Score (FY)", '')::NUMERIC,
       NULLIF("Altman Z-Score (FQ)", '')::NUMERIC,
       NULLIF("Altman Z-Score (LTM)", '')::NUMERIC,
       NULLIF("Beta (1Y)", '')::NUMERIC,
       NULLIF("Beta (2Y)", '')::NUMERIC,
       NULLIF("Beta (5Y)", '')::NUMERIC,
       NULLIF("Analyst Rating", '')::NUMERIC,
       NULLIF("# Strong Sell Ratings", '')::NUMERIC,
       NULLIF("# Strong Buys Ratings", '')::NUMERIC,
       NULLIF("# Hold Ratings", '')::NUMERIC,
       NULLIF("# Buys Ratings", '')::NUMERIC,
       NULLIF("# Sell Ratings", '')::NUMERIC,
       NULLIF("Total Revenues/CAGR (5Y FY)", '')::NUMERIC,
       NULLIF("Total Revenues (FQ)", '')::NUMERIC,
       NULLIF("Total Revenues (-1FY)", '')::NUMERIC,
       NULLIF("Total Revenues (FY)", '')::NUMERIC,
       NULLIF("Total Revenues (LTM)", '')::NUMERIC,
       NULLIF("Total Operating Expenses (LTM)", '')::NUMERIC,
       NULLIF("P/TBV (LTM)", '')::NUMERIC,
       NULLIF("TBV (FY)", '')::NUMERIC,
       NULLIF("TBV (LTM)", '')::NUMERIC,
       NULLIF("Market Cap (Country R)", '')::NUMERIC,
       NULLIF("Tot. Return %/CAGR (3Y)", '')::NUMERIC,
       NULLIF("Tot. Return %/CAGR (10Y)", '')::NUMERIC,
       NULLIF("Total Return (5Y)", '')::NUMERIC,
       NULLIF("Total Return (10Y)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("CFF (LTM)", '')::NUMERIC,
       NULLIF("CFI (LTM)", '')::NUMERIC,
       NULLIF("FCF (LTM)", '')::NUMERIC,
       NULLIF("CFO (LTM)", '')::NUMERIC,
       NULLIF("EBITDA (FQ)", '')::NUMERIC,
       NULLIF("EBITDA (LTM)", '')::NUMERIC,
       NULLIF("EBITDA (FY)", '')::NUMERIC,
       NULLIF("EBITDA (-1FY)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (FY)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EBIT (FQ)", '')::NUMERIC,
       NULLIF("EBIT (LTM)", '')::NUMERIC,
       NULLIF("EBIT (FY)", '')::NUMERIC,
       NULLIF("EBIT (-1FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EBIT - Est Med (FY1E)", '')::NUMERIC,
       NULLIF("EBIT - Est Med (NTM)", '')::NUMERIC,
       NULLIF("Return On Equity % (LTM)", '')::NUMERIC,
       NULLIF("Return On Equity % (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (LTM)", '')::NUMERIC,
       NULLIF("Normalized Net Income (FY)", '')::NUMERIC,
       NULLIF("Normalized Net Income (LTM)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (FY)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (LTM)", '')::NUMERIC,
       NULLIF("Net Income Margin % (FY)", '')::NUMERIC,
       NULLIF("Net Income Margin % (LTM)", '')::NUMERIC,
       NULLIF("Volatility (1M)", '')::NUMERIC,
       NULLIF("Volatility (3M)", '')::NUMERIC,
       NULLIF("Volatility (6M)", '')::NUMERIC,
       NULLIF("Volatility (1Y)", '')::NUMERIC,
       NULLIF("Volume (Shrs)", '')::NUMERIC,
       NULLIF("Dividend Per Share (LTM)", '')::NUMERIC,
       NULLIF("Div Yield (Ind)", '')::NUMERIC,
       NULLIF("Div Yield (LTM)", '')::NUMERIC,
       NULLIF("Total Debt (FY)", '')::NUMERIC,
       NULLIF("Total Equity (FY)", '')::NUMERIC,
       NULLIF("Total Equity (LTM)", '')::NUMERIC,
       NULLIF("Total Debt (LTM)", '')::NUMERIC,
       NULLIF("Total Assets (LTM)", '')::NUMERIC,
       NULLIF("Total Assets (FY)", '')::NUMERIC,
       NULLIF("Current Ratio (FY)", '')::NUMERIC,
       NULLIF("Current Ratio (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit Margin % (FY)", '')::NUMERIC,
       NULLIF("Gross Profit Margin % (LTM)", '')::NUMERIC,
       NULLIF("Asset Turnover (FY)", '')::NUMERIC,
       NULLIF("Asset Turnover (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit (FY)", '')::NUMERIC,
       NULLIF("EPS Norm - Est Avg (NTM)", '')::NUMERIC,
       NULLIF("EPS/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EPS/Adj. (FY)", '')::NUMERIC,
       NULLIF("EPS/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EPS Norm - Est Avg (FY1E)", '')::NUMERIC,
       NULLIF("Gain (Loss) On Sale Of Assets (LTM)", '')::NUMERIC,
       NULLIF("Cost Of Revenues (LTM)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (LTM)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (FY)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (-1FY)", '')::NUMERIC,
       NULLIF("Inventory (LTM)", '')::NUMERIC,
       NULLIF("Goodwill (FQ)", '')::NUMERIC,
       NULLIF("Goodwill (LTM)", '')::NUMERIC,
       NULLIF("Goodwill (FY)", '')::NUMERIC,
       NULLIF("Goodwill (-1FY)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (FQ)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (LTM)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (-1FY)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (FY)", '')::NUMERIC,
       NULLIF("Operating Income (LTM)", '')::NUMERIC,
       NULLIF("Asset Writedown (LTM)", '')::NUMERIC,
       NULLIF("Asset Writedown (FY)", '')::NUMERIC,
       NULLIF("Asset Writedown (-1FY)", '')::NUMERIC,
       NULLIF("Operating Income (FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (LTM)", '')::NUMERIC,
       NULLIF("Capital Expenditure (-1FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (FY)", '')::NUMERIC,
       NULLIF("Retained Earnings (LTM)", '')::NUMERIC,
       NULLIF("Total Current Assets (LTM)", '')::NUMERIC,
       NULLIF("Total Current Liabilities (LTM)", '')::NUMERIC,
       NULLIF("R&D Expenses (LTM)", '')::NUMERIC,
       NULLIF("Restructuring Charges (LTM)", '')::NUMERIC,
       NULLIF("Restructuring Charges (FQ)", '')::NUMERIC,
       NULLIF("Restructuring Charges (-1FY)", '')::NUMERIC,
       NULLIF("Restructuring Charges (FY)", '')::NUMERIC,
       NULLIF("Interest Expense/Total (LTM)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (LTM)", '')::NUMERIC,
       NULLIF("Working Capital (LTM)", '')::NUMERIC,
       NULLIF("Other Unusual Items/Total (LTM)", '')::NUMERIC,
       NULLIF("Interest Income On Investments (LTM)", '')::NUMERIC,
       NULLIF("Buyback Yield (LTM)", '')::NUMERIC,
       NULLIF("Return on Assets (ROA) % (LTM)", '')::NUMERIC,
       NULLIF("Return on Assets (ROA) % (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (-1FY)", '')::NUMERIC,
       NULLIF("Normalized Net Income (-1FY)", '')::NUMERIC,
       NULLIF("P/E (-1FYLTM)", '')::NUMERIC,
       NULLIF("CFF (FY)", '')::NUMERIC,
       NULLIF("CFF (-1FY)", '')::NUMERIC,
       NULLIF("CFI (FY)", '')::NUMERIC,
       NULLIF("CFI (-1FY)", '')::NUMERIC,
       NULLIF("CFO (FY)", '')::NUMERIC,
       NULLIF("CFO (-1FY)", '')::NUMERIC,
       NULLIF("Div Yield (-1FYInd)", '')::NUMERIC,
       NULLIF("FCF (FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (FQ)", '')::NUMERIC,
       NULLIF("Capital Expenditure (5YAVGFQ)", '')::NUMERIC,
       NULLIF("CFF (FQ)", '')::NUMERIC,
       NULLIF("CFI (FQ)", '')::NUMERIC,
       NULLIF("CFO (FQ)", '')::NUMERIC,
       NULLIF("FCF (FQ)", '')::NUMERIC,
       NULLIF("Total Revenues (5YAVGFQ)", '')::NUMERIC,
       NULLIF("EBITDA (5YAVGFQ)", '')::NUMERIC,
       NULLIF("EBIT (5YAVGFQ)", '')::NUMERIC,
       NULLIF("P/E (5YAVGLTM)", '')::NUMERIC,
       NULLIF("FCF (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (FQ)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Asset Writedown (FQ)", '')::NUMERIC,
       NULLIF("Asset Writedown (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Operating Income (FQ)", '')::NUMERIC,
       NULLIF("Operating Income (5YAVGFQ)", '')::NUMERIC,
       NULLIF("P/B (LTM)", '')::NUMERIC,
       NULLIF("P/B (-1FY)", '')::NUMERIC,
       NULLIF("P/B (5YAVG)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (LTM)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (FQ)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (FY)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Inventory (FQ)", '')::NUMERIC,
       NULLIF("Inventory (FY)", '')::NUMERIC,
       NULLIF("Goodwill (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Inventory (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Retained Earnings (FQ)", '')::NUMERIC,
       NULLIF("Retained Earnings (FY)", '')::NUMERIC,
       NULLIF("Retained Earnings (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Working Capital (FQ)", '')::NUMERIC,
       NULLIF("Working Capital (FY)", '')::NUMERIC,
       NULLIF("Working Capital (5YAVGFY)", '')::NUMERIC,
       NULLIF("Div Yield (TTM)", '')::NUMERIC,
       NULLIF("Div Yield (NTM)", '')::NUMERIC,
       NULLIF("Div Yield (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (LTM)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (FY)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Restructuring Charges (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (FQ)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (FY)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Normalized Net Income (FQ)", '')::NUMERIC,
       NULLIF("Normalized Net Income (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (FQ)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (FQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Normalized Net Income (5YAVGLTM)", '')::NUMERIC,
       NULLIF("EBITDA (5YAVGLTM)", '')::NUMERIC,
       NULLIF("EBIT (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Total Revenues (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Revenues - Est YoY % (FY1E)", '')::NUMERIC,
       NULLIF("Price Chg. % (1M)", '')::NUMERIC,
       NULLIF("Price Chg. % (3M)", '')::NUMERIC,
       NULLIF("1-Day %", '')::NUMERIC,
       NULLIF("Price (5D Ago)", '')::NUMERIC,
       NULLIF("Price (1W Ago)", '')::NUMERIC,
       NULLIF("Price (1M Ago)", '')::NUMERIC,
       NULLIF("Price (3M Ago)", '')::NUMERIC,
       NULLIF("Price (6M Ago)", '')::NUMERIC,
       NULLIF("Price (1Y Ago)", '')::NUMERIC,
       NULLIF("Price (3Y Ago)", '')::NUMERIC,
       NULLIF("Price (5Y Ago)", '')::NUMERIC,
       NULLIF("Price (QTD Ago)", '')::NUMERIC,
       NULLIF("Rel. Volume", '')::NUMERIC,
       NULLIF("Shrs Out", '')::NUMERIC,
       NULLIF("Shrs Out (-1FY)", '')::NUMERIC,
       NULLIF("Common Dividends Paid (LTM)", '')::NUMERIC,
       NULLIF("Common Dividends Paid (FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (FQ)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (-1FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (FY)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (-1FY)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Marketing Expenses (FQ)", '')::NUMERIC,
       NULLIF("Marketing Expenses (FY)", '')::NUMERIC,
       NULLIF("Marketing Expenses (-1FY)", '')::NUMERIC,
       NULLIF("Marketing Expenses (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Avg (NTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Avg (FY1E)", '')::NUMERIC,
       NULLIF("Revenues - Est Med (NTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Med (FY1E)", '')::NUMERIC,
       NULLIF("EV/Sales (EST FY1)", '')::NUMERIC,
       NULLIF("EV/Sales (LTM)", '')::NUMERIC,
       NULLIF("EV/Sales (NTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-1FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-2FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-3FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (3YAVGLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-1FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-2FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-3FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-4FQLTM)", '')::NUMERIC,
       NULLIF("Full Time Employees (FQ)", '')::NUMERIC,
       NULLIF("Full Time Employees (FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-1FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-2FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-3FY)", '')::NUMERIC,
       NULLIF("Avg Employees (5YAVGFY)", '')::NUMERIC,
       NULLIF("52W High/Adj", '')::NUMERIC,
       NULLIF("52W Low/Adj", '')::NUMERIC,
       NULLIF("EMA (20D)", '')::NUMERIC,
       NULLIF("EMA (50D)", '')::NUMERIC,
       NULLIF("EMA (100D)", '')::NUMERIC,
       NULLIF("EMA (250D)", '')::NUMERIC,
       NULLIF("EV/EBITDA (LTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (NTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (-1FYLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (-1FQLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (3YAVGLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (EST FY1)", '')::NUMERIC,
       NULLIF("P/E (EST FY1)", '')::NUMERIC,
       NULLIF("P/E (-2FYLTM)", '')::NUMERIC,
       NULLIF("P/E (-3FYLTM)", '')::NUMERIC,
       NULLIF("P/E (3YAVGLTM)", '')::NUMERIC,
       NULLIF("P/E (-1FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-2FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-3FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FQQoQLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FYYoYLTM)", '')::NUMERIC,
       NULLIF("P/E (-1FYYoYLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FQYoYLTM)", '')::NUMERIC,
       NULLIF("Dividend Record (Announce Date)", '')::DATE,
       NULLIF("Dividend Record (Ex Date)", '')::DATE,
       NULLIF("Dividend Record (Payable Date)", '')::DATE,
       NULLIF("Dividend Record (Record Date)", '')::DATE,
       "Dividend Record (Frequency)",
       "Dividend Record (Currency)",
       NULLIF("Dividend Record (Amount)", '')::NUMERIC,
       NULLIF("Dividend Streak", '')::NUMERIC
FROM screening_eu
ON CONFLICT DO NOTHING;


-- SCREENING_APAC REGION
--------------------------------------------------------------------------------
INSERT INTO equities
("Ticker",
 "ISIN",
 "Name",
 "Description",
 "Exchange",
 "Unit",
 "Sector",
 "Industry",
 "Last Updated",
 "Income Statement Report Date",
 "Next Earnings",
 "Style Class",
 "Next Earnings (Status)",
 "Size Class",
 "Region",
 "Country",
 "Trading Country",
 "Market Cap",
 "Enterprise Value",
 "Last Price",
 "Price Target (YTD Ago)",
 "Total Return (YTD)",
 "Price Target",
 "Price Target - Low",
 "Price Target - Median",
 "Price Target - High",
 "Price Target - #",
 "P/E (NTM)",
 "P/E (LTM)",
 "Altman Z-Score (FY)",
 "Altman Z-Score (FQ)",
 "Altman Z-Score (LTM)",
 "Beta (1Y)",
 "Beta (2Y)",
 "Beta (5Y)",
 "Analyst Rating",
 "# Strong Sell Ratings",
 "# Strong Buys Ratings",
 "# Hold Ratings",
 "# Buys Ratings",
 "# Sell Ratings",
 "Total Revenues/CAGR (5Y FY)",
 "Total Revenues (FQ)",
 "Total Revenues (-1FY)",
 "Total Revenues (FY)",
 "Total Revenues (LTM)",
 "Total Operating Expenses (LTM)",
 "P/TBV (LTM)",
 "TBV (FY)",
 "TBV (LTM)",
 "Market Cap (Country R)",
 "Tot. Return %/CAGR (3Y)",
 "Tot. Return %/CAGR (10Y)",
 "Total Return (5Y)",
 "Total Return (10Y)",
 "Net Income/Adj. (-1FY)",
 "CFF (LTM)",
 "CFI (LTM)",
 "FCF (LTM)",
 "CFO (LTM)",
 "EBITDA (FQ)",
 "EBITDA (LTM)",
 "EBITDA (FY)",
 "EBITDA (-1FY)",
 "EBITDA/Adj. (LTM)",
 "EBITDA/Adj. (FY)",
 "EBITDA/Adj. (-1FY)",
 "EBIT (FQ)",
 "EBIT (LTM)",
 "EBIT (FY)",
 "EBIT (-1FY)",
 "EBIT/Adj. (-1FY)",
 "EBIT/Adj. (FY)",
 "EBIT/Adj. (LTM)",
 "EBIT - Est Med (FY1E)",
 "EBIT - Est Med (NTM)",
 "Return On Equity % (LTM)",
 "Return On Equity % (FY)",
 "Net Income - (IS) (FY)",
 "Net Income - (IS) (LTM)",
 "Normalized Net Income (FY)",
 "Normalized Net Income (LTM)",
 "Net Income/Adj. (FY)",
 "Net Income/Adj. (LTM)",
 "Net Income Margin % (FY)",
 "Net Income Margin % (LTM)",
 "Volatility (1M)",
 "Volatility (3M)",
 "Volatility (6M)",
 "Volatility (1Y)",
 "Volume (Shrs)",
 "Dividend Per Share (LTM)",
 "Div Yield (Ind)",
 "Div Yield (LTM)",
 "Total Debt (FY)",
 "Total Equity (FY)",
 "Total Equity (LTM)",
 "Total Debt (LTM)",
 "Total Assets (LTM)",
 "Total Assets (FY)",
 "Current Ratio (FY)",
 "Current Ratio (LTM)",
 "Gross Profit Margin % (FY)",
 "Gross Profit Margin % (LTM)",
 "Asset Turnover (FY)",
 "Asset Turnover (LTM)",
 "Gross Profit (LTM)",
 "Gross Profit (FY)",
 "EPS Norm - Est Avg (NTM)",
 "EPS/Adj. (-1FY)",
 "EPS/Adj. (FY)",
 "EPS/Adj. (LTM)",
 "EPS Norm - Est Avg (FY1E)",
 "Gain (Loss) On Sale Of Assets (LTM)",
 "Cost Of Revenues (LTM)",
 "Cash Acquisitions (LTM)",
 "Cash Acquisitions (FY)",
 "Cash Acquisitions (-1FY)",
 "Inventory (LTM)",
 "Goodwill (FQ)",
 "Goodwill (LTM)",
 "Goodwill (FY)",
 "Goodwill (-1FY)",
 "Impairment of Goodwill (FQ)",
 "Impairment of Goodwill (LTM)",
 "Impairment of Goodwill (-1FY)",
 "Impairment of Goodwill (FY)",
 "Operating Income (LTM)",
 "Asset Writedown (LTM)",
 "Asset Writedown (FY)",
 "Asset Writedown (-1FY)",
 "Operating Income (FY)",
 "Capital Expenditure (LTM)",
 "Capital Expenditure (-1FY)",
 "Capital Expenditure (FY)",
 "Retained Earnings (LTM)",
 "Total Current Assets (LTM)",
 "Total Current Liabilities (LTM)",
 "R&D Expenses (LTM)",
 "Restructuring Charges (LTM)",
 "Restructuring Charges (FQ)",
 "Restructuring Charges (-1FY)",
 "Restructuring Charges (FY)",
 "Interest Expense/Total (LTM)",
 "Merger & Restructuring Charges (LTM)",
 "Working Capital (LTM)",
 "Other Unusual Items/Total (LTM)",
 "Interest Income On Investments (LTM)",
 "Buyback Yield (LTM)",
 "Return on Assets (ROA) % (LTM)",
 "Return on Assets (ROA) % (FY)",
 "Net Income - (IS) (-1FY)",
 "Normalized Net Income (-1FY)",
 "P/E (-1FYLTM)",
 "CFF (FY)",
 "CFF (-1FY)",
 "CFI (FY)",
 "CFI (-1FY)",
 "CFO (FY)",
 "CFO (-1FY)",
 "Div Yield (-1FYInd)",
 "FCF (FY)",
 "Capital Expenditure (FQ)",
 "Capital Expenditure (5YAVGFQ)",
 "CFF (FQ)",
 "CFI (FQ)",
 "CFO (FQ)",
 "FCF (FQ)",
 "Total Revenues (5YAVGFQ)",
 "EBITDA (5YAVGFQ)",
 "EBIT (5YAVGFQ)",
 "P/E (5YAVGLTM)",
 "FCF (5YAVGFQ)",
 "Cash Acquisitions (FQ)",
 "Cash Acquisitions (5YAVGFQ)",
 "Asset Writedown (FQ)",
 "Asset Writedown (5YAVGFQ)",
 "Impairment of Goodwill (5YAVGFQ)",
 "Operating Income (FQ)",
 "Operating Income (5YAVGFQ)",
 "P/B (LTM)",
 "P/B (-1FY)",
 "P/B (5YAVG)",
 "Cash And Equivalents (LTM)",
 "Cash And Equivalents (FQ)",
 "Cash And Equivalents (FY)",
 "Cash And Equivalents (5YAVGFQ)",
 "Inventory (FQ)",
 "Inventory (FY)",
 "Goodwill (5YAVGFQ)",
 "Inventory (5YAVGFQ)",
 "Retained Earnings (FQ)",
 "Retained Earnings (FY)",
 "Retained Earnings (5YAVGFQ)",
 "Working Capital (FQ)",
 "Working Capital (FY)",
 "Working Capital (5YAVGFY)",
 "Div Yield (TTM)",
 "Div Yield (NTM)",
 "Div Yield (5YAVGLTM)",
 "Gross Intangible Assets (LTM)",
 "Gross Intangible Assets (FY)",
 "Gross Intangible Assets (5YAVGFQ)",
 "Restructuring Charges (5YAVGFQ)",
 "Merger & Restructuring Charges (FQ)",
 "Merger & Restructuring Charges (FY)",
 "Merger & Restructuring Charges (5YAVGFQ)",
 "Normalized Net Income (FQ)",
 "Normalized Net Income (5YAVGFQ)",
 "Net Income/Adj. (FQ)",
 "Net Income/Adj. (5YAVGFQ)",
 "Net Income - (IS) (FQ)",
 "Net Income - (IS) (5YAVGFQ)",
 "Net Income - (IS) (5YAVGLTM)",
 "Normalized Net Income (5YAVGLTM)",
 "EBITDA (5YAVGLTM)",
 "EBIT (5YAVGLTM)",
 "Total Revenues (5YAVGLTM)",
 "Revenues - Est YoY % (FY1E)",
 "Price Chg. % (1M)",
 "Price Chg. % (3M)",
 "1-Day %",
 "Price (5D Ago)",
 "Price (1W Ago)",
 "Price (1M Ago)",
 "Price (3M Ago)",
 "Price (6M Ago)",
 "Price (1Y Ago)",
 "Price (3Y Ago)",
 "Price (5Y Ago)",
 "Price (QTD Ago)",
 "Rel. Volume",
 "Shrs Out",
 "Shrs Out (-1FY)",
 "Common Dividends Paid (LTM)",
 "Common Dividends Paid (FY)",
 "Selling General & Admin Expenses/Total (FQ)",
 "Selling General & Admin Expenses/Total (FY)",
 "Selling General & Admin Expenses/Total (-1FY)",
 "Selling General & Admin Expenses/Total (5YAVGFQ)",
 "Accounts Receivable/Total (FY)",
 "Accounts Receivable/Total (-1FY)",
 "Accounts Receivable/Total (5YAVGFQ)",
 "Marketing Expenses (FQ)",
 "Marketing Expenses (FY)",
 "Marketing Expenses (-1FY)",
 "Marketing Expenses (5YAVGLTM)",
 "Revenues - Est Avg (NTM)",
 "Revenues - Est Avg (FY1E)",
 "Revenues - Est Med (NTM)",
 "Revenues - Est Med (FY1E)",
 "EV/Sales (EST FY1)",
 "EV/Sales (LTM)",
 "EV/Sales (NTM)",
 "EV/Sales (-1FYLTM)",
 "EV/Sales (-2FYLTM)",
 "EV/Sales (-3FYLTM)",
 "EV/Sales (3YAVGLTM)",
 "EV/Sales (-1FQLTM)",
 "EV/Sales (-2FQLTM)",
 "EV/Sales (-3FQLTM)",
 "EV/Sales (-4FQLTM)",
 "Full Time Employees (FQ)",
 "Full Time Employees (FY)",
 "Full Time Employees (-1FY)",
 "Full Time Employees (-2FY)",
 "Full Time Employees (-3FY)",
 "Avg Employees (5YAVGFY)",
 "52W High/Adj",
 "52W Low/Adj",
 "EMA (20D)",
 "EMA (50D)",
 "EMA (100D)",
 "EMA (250D)",
 "EV/EBITDA (LTM)",
 "EV/EBITDA (NTM)",
 "EV/EBITDA (-1FYLTM)",
 "EV/EBITDA (-1FQLTM)",
 "EV/EBITDA (3YAVGLTM)",
 "EV/EBITDA (EST FY1)",
 "P/E (EST FY1)",
 "P/E (-2FYLTM)",
 "P/E (-3FYLTM)",
 "P/E (3YAVGLTM)",
 "P/E (-1FQLTM)",
 "P/E (-2FQLTM)",
 "P/E (-3FQLTM)",
 "P/E (-0FQQoQLTM)",
 "P/E (-0FYYoYLTM)",
 "P/E (-1FYYoYLTM)",
 "P/E (-0FQYoYLTM)",
 "Dividend Record (Announce Date)",
 "Dividend Record (Ex Date)",
 "Dividend Record (Payable Date)",
 "Dividend Record (Record Date)",
 "Dividend Record (Frequency)",
 "Dividend Record (Currency)",
 "Dividend Record (Amount)",
 "Dividend Streak")
SELECT "Ticker",
       "ISIN",
       "Name",
       "Description",
       "Exchange",
       "Unit",
       "Sector",
       "Industry",
       NULLIF("Last Updated", '')::DATE,
       NULLIF("Income Statement Report Date", '')::DATE,
       NULLIF("Next Earnings", '')::DATE,
       "Style Class",
       "Next Earnings (Status)",
       "Size Class",
       "Region",
       "Country",
       "Trading Country",
       NULLIF("Market Cap", '')::NUMERIC,
       NULLIF("Enterprise Value", '')::NUMERIC,
       NULLIF("Last Price", '')::NUMERIC,
       NULLIF("Price Target (YTD Ago)", '')::NUMERIC,
       NULLIF("Total Return (YTD)", '')::NUMERIC,
       NULLIF("Price Target", '')::NUMERIC,
       NULLIF("Price Target - Low", '')::NUMERIC,
       NULLIF("Price Target - Median", '')::NUMERIC,
       NULLIF("Price Target - High", '')::NUMERIC,
       NULLIF("Price Target - #", '')::NUMERIC,
       NULLIF("P/E (NTM)", '')::NUMERIC,
       NULLIF("P/E (LTM)", '')::NUMERIC,
       NULLIF("Altman Z-Score (FY)", '')::NUMERIC,
       NULLIF("Altman Z-Score (FQ)", '')::NUMERIC,
       NULLIF("Altman Z-Score (LTM)", '')::NUMERIC,
       NULLIF("Beta (1Y)", '')::NUMERIC,
       NULLIF("Beta (2Y)", '')::NUMERIC,
       NULLIF("Beta (5Y)", '')::NUMERIC,
       NULLIF("Analyst Rating", '')::NUMERIC,
       NULLIF("# Strong Sell Ratings", '')::NUMERIC,
       NULLIF("# Strong Buys Ratings", '')::NUMERIC,
       NULLIF("# Hold Ratings", '')::NUMERIC,
       NULLIF("# Buys Ratings", '')::NUMERIC,
       NULLIF("# Sell Ratings", '')::NUMERIC,
       NULLIF("Total Revenues/CAGR (5Y FY)", '')::NUMERIC,
       NULLIF("Total Revenues (FQ)", '')::NUMERIC,
       NULLIF("Total Revenues (-1FY)", '')::NUMERIC,
       NULLIF("Total Revenues (FY)", '')::NUMERIC,
       NULLIF("Total Revenues (LTM)", '')::NUMERIC,
       NULLIF("Total Operating Expenses (LTM)", '')::NUMERIC,
       NULLIF("P/TBV (LTM)", '')::NUMERIC,
       NULLIF("TBV (FY)", '')::NUMERIC,
       NULLIF("TBV (LTM)", '')::NUMERIC,
       NULLIF("Market Cap (Country R)", '')::NUMERIC,
       NULLIF("Tot. Return %/CAGR (3Y)", '')::NUMERIC,
       NULLIF("Tot. Return %/CAGR (10Y)", '')::NUMERIC,
       NULLIF("Total Return (5Y)", '')::NUMERIC,
       NULLIF("Total Return (10Y)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("CFF (LTM)", '')::NUMERIC,
       NULLIF("CFI (LTM)", '')::NUMERIC,
       NULLIF("FCF (LTM)", '')::NUMERIC,
       NULLIF("CFO (LTM)", '')::NUMERIC,
       NULLIF("EBITDA (FQ)", '')::NUMERIC,
       NULLIF("EBITDA (LTM)", '')::NUMERIC,
       NULLIF("EBITDA (FY)", '')::NUMERIC,
       NULLIF("EBITDA (-1FY)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (FY)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EBIT (FQ)", '')::NUMERIC,
       NULLIF("EBIT (LTM)", '')::NUMERIC,
       NULLIF("EBIT (FY)", '')::NUMERIC,
       NULLIF("EBIT (-1FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EBIT - Est Med (FY1E)", '')::NUMERIC,
       NULLIF("EBIT - Est Med (NTM)", '')::NUMERIC,
       NULLIF("Return On Equity % (LTM)", '')::NUMERIC,
       NULLIF("Return On Equity % (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (LTM)", '')::NUMERIC,
       NULLIF("Normalized Net Income (FY)", '')::NUMERIC,
       NULLIF("Normalized Net Income (LTM)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (FY)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (LTM)", '')::NUMERIC,
       NULLIF("Net Income Margin % (FY)", '')::NUMERIC,
       NULLIF("Net Income Margin % (LTM)", '')::NUMERIC,
       NULLIF("Volatility (1M)", '')::NUMERIC,
       NULLIF("Volatility (3M)", '')::NUMERIC,
       NULLIF("Volatility (6M)", '')::NUMERIC,
       NULLIF("Volatility (1Y)", '')::NUMERIC,
       NULLIF("Volume (Shrs)", '')::NUMERIC,
       NULLIF("Dividend Per Share (LTM)", '')::NUMERIC,
       NULLIF("Div Yield (Ind)", '')::NUMERIC,
       NULLIF("Div Yield (LTM)", '')::NUMERIC,
       NULLIF("Total Debt (FY)", '')::NUMERIC,
       NULLIF("Total Equity (FY)", '')::NUMERIC,
       NULLIF("Total Equity (LTM)", '')::NUMERIC,
       NULLIF("Total Debt (LTM)", '')::NUMERIC,
       NULLIF("Total Assets (LTM)", '')::NUMERIC,
       NULLIF("Total Assets (FY)", '')::NUMERIC,
       NULLIF("Current Ratio (FY)", '')::NUMERIC,
       NULLIF("Current Ratio (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit Margin % (FY)", '')::NUMERIC,
       NULLIF("Gross Profit Margin % (LTM)", '')::NUMERIC,
       NULLIF("Asset Turnover (FY)", '')::NUMERIC,
       NULLIF("Asset Turnover (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit (FY)", '')::NUMERIC,
       NULLIF("EPS Norm - Est Avg (NTM)", '')::NUMERIC,
       NULLIF("EPS/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EPS/Adj. (FY)", '')::NUMERIC,
       NULLIF("EPS/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EPS Norm - Est Avg (FY1E)", '')::NUMERIC,
       NULLIF("Gain (Loss) On Sale Of Assets (LTM)", '')::NUMERIC,
       NULLIF("Cost Of Revenues (LTM)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (LTM)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (FY)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (-1FY)", '')::NUMERIC,
       NULLIF("Inventory (LTM)", '')::NUMERIC,
       NULLIF("Goodwill (FQ)", '')::NUMERIC,
       NULLIF("Goodwill (LTM)", '')::NUMERIC,
       NULLIF("Goodwill (FY)", '')::NUMERIC,
       NULLIF("Goodwill (-1FY)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (FQ)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (LTM)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (-1FY)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (FY)", '')::NUMERIC,
       NULLIF("Operating Income (LTM)", '')::NUMERIC,
       NULLIF("Asset Writedown (LTM)", '')::NUMERIC,
       NULLIF("Asset Writedown (FY)", '')::NUMERIC,
       NULLIF("Asset Writedown (-1FY)", '')::NUMERIC,
       NULLIF("Operating Income (FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (LTM)", '')::NUMERIC,
       NULLIF("Capital Expenditure (-1FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (FY)", '')::NUMERIC,
       NULLIF("Retained Earnings (LTM)", '')::NUMERIC,
       NULLIF("Total Current Assets (LTM)", '')::NUMERIC,
       NULLIF("Total Current Liabilities (LTM)", '')::NUMERIC,
       NULLIF("R&D Expenses (LTM)", '')::NUMERIC,
       NULLIF("Restructuring Charges (LTM)", '')::NUMERIC,
       NULLIF("Restructuring Charges (FQ)", '')::NUMERIC,
       NULLIF("Restructuring Charges (-1FY)", '')::NUMERIC,
       NULLIF("Restructuring Charges (FY)", '')::NUMERIC,
       NULLIF("Interest Expense/Total (LTM)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (LTM)", '')::NUMERIC,
       NULLIF("Working Capital (LTM)", '')::NUMERIC,
       NULLIF("Other Unusual Items/Total (LTM)", '')::NUMERIC,
       NULLIF("Interest Income On Investments (LTM)", '')::NUMERIC,
       NULLIF("Buyback Yield (LTM)", '')::NUMERIC,
       NULLIF("Return on Assets (ROA) % (LTM)", '')::NUMERIC,
       NULLIF("Return on Assets (ROA) % (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (-1FY)", '')::NUMERIC,
       NULLIF("Normalized Net Income (-1FY)", '')::NUMERIC,
       NULLIF("P/E (-1FYLTM)", '')::NUMERIC,
       NULLIF("CFF (FY)", '')::NUMERIC,
       NULLIF("CFF (-1FY)", '')::NUMERIC,
       NULLIF("CFI (FY)", '')::NUMERIC,
       NULLIF("CFI (-1FY)", '')::NUMERIC,
       NULLIF("CFO (FY)", '')::NUMERIC,
       NULLIF("CFO (-1FY)", '')::NUMERIC,
       NULLIF("Div Yield (-1FYInd)", '')::NUMERIC,
       NULLIF("FCF (FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (FQ)", '')::NUMERIC,
       NULLIF("Capital Expenditure (5YAVGFQ)", '')::NUMERIC,
       NULLIF("CFF (FQ)", '')::NUMERIC,
       NULLIF("CFI (FQ)", '')::NUMERIC,
       NULLIF("CFO (FQ)", '')::NUMERIC,
       NULLIF("FCF (FQ)", '')::NUMERIC,
       NULLIF("Total Revenues (5YAVGFQ)", '')::NUMERIC,
       NULLIF("EBITDA (5YAVGFQ)", '')::NUMERIC,
       NULLIF("EBIT (5YAVGFQ)", '')::NUMERIC,
       NULLIF("P/E (5YAVGLTM)", '')::NUMERIC,
       NULLIF("FCF (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (FQ)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Asset Writedown (FQ)", '')::NUMERIC,
       NULLIF("Asset Writedown (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Operating Income (FQ)", '')::NUMERIC,
       NULLIF("Operating Income (5YAVGFQ)", '')::NUMERIC,
       NULLIF("P/B (LTM)", '')::NUMERIC,
       NULLIF("P/B (-1FY)", '')::NUMERIC,
       NULLIF("P/B (5YAVG)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (LTM)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (FQ)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (FY)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Inventory (FQ)", '')::NUMERIC,
       NULLIF("Inventory (FY)", '')::NUMERIC,
       NULLIF("Goodwill (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Inventory (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Retained Earnings (FQ)", '')::NUMERIC,
       NULLIF("Retained Earnings (FY)", '')::NUMERIC,
       NULLIF("Retained Earnings (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Working Capital (FQ)", '')::NUMERIC,
       NULLIF("Working Capital (FY)", '')::NUMERIC,
       NULLIF("Working Capital (5YAVGFY)", '')::NUMERIC,
       NULLIF("Div Yield (TTM)", '')::NUMERIC,
       NULLIF("Div Yield (NTM)", '')::NUMERIC,
       NULLIF("Div Yield (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (LTM)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (FY)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Restructuring Charges (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (FQ)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (FY)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Normalized Net Income (FQ)", '')::NUMERIC,
       NULLIF("Normalized Net Income (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (FQ)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (FQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Normalized Net Income (5YAVGLTM)", '')::NUMERIC,
       NULLIF("EBITDA (5YAVGLTM)", '')::NUMERIC,
       NULLIF("EBIT (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Total Revenues (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Revenues - Est YoY % (FY1E)", '')::NUMERIC,
       NULLIF("Price Chg. % (1M)", '')::NUMERIC,
       NULLIF("Price Chg. % (3M)", '')::NUMERIC,
       NULLIF("1-Day %", '')::NUMERIC,
       NULLIF("Price (5D Ago)", '')::NUMERIC,
       NULLIF("Price (1W Ago)", '')::NUMERIC,
       NULLIF("Price (1M Ago)", '')::NUMERIC,
       NULLIF("Price (3M Ago)", '')::NUMERIC,
       NULLIF("Price (6M Ago)", '')::NUMERIC,
       NULLIF("Price (1Y Ago)", '')::NUMERIC,
       NULLIF("Price (3Y Ago)", '')::NUMERIC,
       NULLIF("Price (5Y Ago)", '')::NUMERIC,
       NULLIF("Price (QTD Ago)", '')::NUMERIC,
       NULLIF("Rel. Volume", '')::NUMERIC,
       NULLIF("Shrs Out", '')::NUMERIC,
       NULLIF("Shrs Out (-1FY)", '')::NUMERIC,
       NULLIF("Common Dividends Paid (LTM)", '')::NUMERIC,
       NULLIF("Common Dividends Paid (FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (FQ)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (-1FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (FY)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (-1FY)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Marketing Expenses (FQ)", '')::NUMERIC,
       NULLIF("Marketing Expenses (FY)", '')::NUMERIC,
       NULLIF("Marketing Expenses (-1FY)", '')::NUMERIC,
       NULLIF("Marketing Expenses (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Avg (NTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Avg (FY1E)", '')::NUMERIC,
       NULLIF("Revenues - Est Med (NTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Med (FY1E)", '')::NUMERIC,
       NULLIF("EV/Sales (EST FY1)", '')::NUMERIC,
       NULLIF("EV/Sales (LTM)", '')::NUMERIC,
       NULLIF("EV/Sales (NTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-1FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-2FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-3FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (3YAVGLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-1FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-2FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-3FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-4FQLTM)", '')::NUMERIC,
       NULLIF("Full Time Employees (FQ)", '')::NUMERIC,
       NULLIF("Full Time Employees (FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-1FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-2FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-3FY)", '')::NUMERIC,
       NULLIF("Avg Employees (5YAVGFY)", '')::NUMERIC,
       NULLIF("52W High/Adj", '')::NUMERIC,
       NULLIF("52W Low/Adj", '')::NUMERIC,
       NULLIF("EMA (20D)", '')::NUMERIC,
       NULLIF("EMA (50D)", '')::NUMERIC,
       NULLIF("EMA (100D)", '')::NUMERIC,
       NULLIF("EMA (250D)", '')::NUMERIC,
       NULLIF("EV/EBITDA (LTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (NTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (-1FYLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (-1FQLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (3YAVGLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (EST FY1)", '')::NUMERIC,
       NULLIF("P/E (EST FY1)", '')::NUMERIC,
       NULLIF("P/E (-2FYLTM)", '')::NUMERIC,
       NULLIF("P/E (-3FYLTM)", '')::NUMERIC,
       NULLIF("P/E (3YAVGLTM)", '')::NUMERIC,
       NULLIF("P/E (-1FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-2FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-3FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FQQoQLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FYYoYLTM)", '')::NUMERIC,
       NULLIF("P/E (-1FYYoYLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FQYoYLTM)", '')::NUMERIC,
       NULLIF("Dividend Record (Announce Date)", '')::DATE,
       NULLIF("Dividend Record (Ex Date)", '')::DATE,
       NULLIF("Dividend Record (Payable Date)", '')::DATE,
       NULLIF("Dividend Record (Record Date)", '')::DATE,
       "Dividend Record (Frequency)",
       "Dividend Record (Currency)",
       NULLIF("Dividend Record (Amount)", '')::NUMERIC,
       NULLIF("Dividend Streak", '')::NUMERIC
FROM screening_apac
ON CONFLICT DO NOTHING;


-- SCREENING_ROTW REGION
--------------------------------------------------------------------------------
INSERT INTO equities
("Ticker",
 "ISIN",
 "Name",
 "Description",
 "Exchange",
 "Unit",
 "Sector",
 "Industry",
 "Last Updated",
 "Income Statement Report Date",
 "Next Earnings",
 "Style Class",
 "Next Earnings (Status)",
 "Size Class",
 "Region",
 "Country",
 "Trading Country",
 "Market Cap",
 "Enterprise Value",
 "Last Price",
 "Price Target (YTD Ago)",
 "Total Return (YTD)",
 "Price Target",
 "Price Target - Low",
 "Price Target - Median",
 "Price Target - High",
 "Price Target - #",
 "P/E (NTM)",
 "P/E (LTM)",
 "Altman Z-Score (FY)",
 "Altman Z-Score (FQ)",
 "Altman Z-Score (LTM)",
 "Beta (1Y)",
 "Beta (2Y)",
 "Beta (5Y)",
 "Analyst Rating",
 "# Strong Sell Ratings",
 "# Strong Buys Ratings",
 "# Hold Ratings",
 "# Buys Ratings",
 "# Sell Ratings",
 "Total Revenues/CAGR (5Y FY)",
 "Total Revenues (FQ)",
 "Total Revenues (-1FY)",
 "Total Revenues (FY)",
 "Total Revenues (LTM)",
 "Total Operating Expenses (LTM)",
 "P/TBV (LTM)",
 "TBV (FY)",
 "TBV (LTM)",
 "Market Cap (Country R)",
 "Tot. Return %/CAGR (3Y)",
 "Tot. Return %/CAGR (10Y)",
 "Total Return (5Y)",
 "Total Return (10Y)",
 "Net Income/Adj. (-1FY)",
 "CFF (LTM)",
 "CFI (LTM)",
 "FCF (LTM)",
 "CFO (LTM)",
 "EBITDA (FQ)",
 "EBITDA (LTM)",
 "EBITDA (FY)",
 "EBITDA (-1FY)",
 "EBITDA/Adj. (LTM)",
 "EBITDA/Adj. (FY)",
 "EBITDA/Adj. (-1FY)",
 "EBIT (FQ)",
 "EBIT (LTM)",
 "EBIT (FY)",
 "EBIT (-1FY)",
 "EBIT/Adj. (-1FY)",
 "EBIT/Adj. (FY)",
 "EBIT/Adj. (LTM)",
 "EBIT - Est Med (FY1E)",
 "EBIT - Est Med (NTM)",
 "Return On Equity % (LTM)",
 "Return On Equity % (FY)",
 "Net Income - (IS) (FY)",
 "Net Income - (IS) (LTM)",
 "Normalized Net Income (FY)",
 "Normalized Net Income (LTM)",
 "Net Income/Adj. (FY)",
 "Net Income/Adj. (LTM)",
 "Net Income Margin % (FY)",
 "Net Income Margin % (LTM)",
 "Volatility (1M)",
 "Volatility (3M)",
 "Volatility (6M)",
 "Volatility (1Y)",
 "Volume (Shrs)",
 "Dividend Per Share (LTM)",
 "Div Yield (Ind)",
 "Div Yield (LTM)",
 "Total Debt (FY)",
 "Total Equity (FY)",
 "Total Equity (LTM)",
 "Total Debt (LTM)",
 "Total Assets (LTM)",
 "Total Assets (FY)",
 "Current Ratio (FY)",
 "Current Ratio (LTM)",
 "Gross Profit Margin % (FY)",
 "Gross Profit Margin % (LTM)",
 "Asset Turnover (FY)",
 "Asset Turnover (LTM)",
 "Gross Profit (LTM)",
 "Gross Profit (FY)",
 "EPS Norm - Est Avg (NTM)",
 "EPS/Adj. (-1FY)",
 "EPS/Adj. (FY)",
 "EPS/Adj. (LTM)",
 "EPS Norm - Est Avg (FY1E)",
 "Gain (Loss) On Sale Of Assets (LTM)",
 "Cost Of Revenues (LTM)",
 "Cash Acquisitions (LTM)",
 "Cash Acquisitions (FY)",
 "Cash Acquisitions (-1FY)",
 "Inventory (LTM)",
 "Goodwill (FQ)",
 "Goodwill (LTM)",
 "Goodwill (FY)",
 "Goodwill (-1FY)",
 "Impairment of Goodwill (FQ)",
 "Impairment of Goodwill (LTM)",
 "Impairment of Goodwill (-1FY)",
 "Impairment of Goodwill (FY)",
 "Operating Income (LTM)",
 "Asset Writedown (LTM)",
 "Asset Writedown (FY)",
 "Asset Writedown (-1FY)",
 "Operating Income (FY)",
 "Capital Expenditure (LTM)",
 "Capital Expenditure (-1FY)",
 "Capital Expenditure (FY)",
 "Retained Earnings (LTM)",
 "Total Current Assets (LTM)",
 "Total Current Liabilities (LTM)",
 "R&D Expenses (LTM)",
 "Restructuring Charges (LTM)",
 "Restructuring Charges (FQ)",
 "Restructuring Charges (-1FY)",
 "Restructuring Charges (FY)",
 "Interest Expense/Total (LTM)",
 "Merger & Restructuring Charges (LTM)",
 "Working Capital (LTM)",
 "Other Unusual Items/Total (LTM)",
 "Interest Income On Investments (LTM)",
 "Buyback Yield (LTM)",
 "Return on Assets (ROA) % (LTM)",
 "Return on Assets (ROA) % (FY)",
 "Net Income - (IS) (-1FY)",
 "Normalized Net Income (-1FY)",
 "P/E (-1FYLTM)",
 "CFF (FY)",
 "CFF (-1FY)",
 "CFI (FY)",
 "CFI (-1FY)",
 "CFO (FY)",
 "CFO (-1FY)",
 "Div Yield (-1FYInd)",
 "FCF (FY)",
 "Capital Expenditure (FQ)",
 "Capital Expenditure (5YAVGFQ)",
 "CFF (FQ)",
 "CFI (FQ)",
 "CFO (FQ)",
 "FCF (FQ)",
 "Total Revenues (5YAVGFQ)",
 "EBITDA (5YAVGFQ)",
 "EBIT (5YAVGFQ)",
 "P/E (5YAVGLTM)",
 "FCF (5YAVGFQ)",
 "Cash Acquisitions (FQ)",
 "Cash Acquisitions (5YAVGFQ)",
 "Asset Writedown (FQ)",
 "Asset Writedown (5YAVGFQ)",
 "Impairment of Goodwill (5YAVGFQ)",
 "Operating Income (FQ)",
 "Operating Income (5YAVGFQ)",
 "P/B (LTM)",
 "P/B (-1FY)",
 "P/B (5YAVG)",
 "Cash And Equivalents (LTM)",
 "Cash And Equivalents (FQ)",
 "Cash And Equivalents (FY)",
 "Cash And Equivalents (5YAVGFQ)",
 "Inventory (FQ)",
 "Inventory (FY)",
 "Goodwill (5YAVGFQ)",
 "Inventory (5YAVGFQ)",
 "Retained Earnings (FQ)",
 "Retained Earnings (FY)",
 "Retained Earnings (5YAVGFQ)",
 "Working Capital (FQ)",
 "Working Capital (FY)",
 "Working Capital (5YAVGFY)",
 "Div Yield (TTM)",
 "Div Yield (NTM)",
 "Div Yield (5YAVGLTM)",
 "Gross Intangible Assets (LTM)",
 "Gross Intangible Assets (FY)",
 "Gross Intangible Assets (5YAVGFQ)",
 "Restructuring Charges (5YAVGFQ)",
 "Merger & Restructuring Charges (FQ)",
 "Merger & Restructuring Charges (FY)",
 "Merger & Restructuring Charges (5YAVGFQ)",
 "Normalized Net Income (FQ)",
 "Normalized Net Income (5YAVGFQ)",
 "Net Income/Adj. (FQ)",
 "Net Income/Adj. (5YAVGFQ)",
 "Net Income - (IS) (FQ)",
 "Net Income - (IS) (5YAVGFQ)",
 "Net Income - (IS) (5YAVGLTM)",
 "Normalized Net Income (5YAVGLTM)",
 "EBITDA (5YAVGLTM)",
 "EBIT (5YAVGLTM)",
 "Total Revenues (5YAVGLTM)",
 "Revenues - Est YoY % (FY1E)",
 "Price Chg. % (1M)",
 "Price Chg. % (3M)",
 "1-Day %",
 "Price (5D Ago)",
 "Price (1W Ago)",
 "Price (1M Ago)",
 "Price (3M Ago)",
 "Price (6M Ago)",
 "Price (1Y Ago)",
 "Price (3Y Ago)",
 "Price (5Y Ago)",
 "Price (QTD Ago)",
 "Rel. Volume",
 "Shrs Out",
 "Shrs Out (-1FY)",
 "Common Dividends Paid (LTM)",
 "Common Dividends Paid (FY)",
 "Selling General & Admin Expenses/Total (FQ)",
 "Selling General & Admin Expenses/Total (FY)",
 "Selling General & Admin Expenses/Total (-1FY)",
 "Selling General & Admin Expenses/Total (5YAVGFQ)",
 "Accounts Receivable/Total (FY)",
 "Accounts Receivable/Total (-1FY)",
 "Accounts Receivable/Total (5YAVGFQ)",
 "Marketing Expenses (FQ)",
 "Marketing Expenses (FY)",
 "Marketing Expenses (-1FY)",
 "Marketing Expenses (5YAVGLTM)",
 "Revenues - Est Avg (NTM)",
 "Revenues - Est Avg (FY1E)",
 "Revenues - Est Med (NTM)",
 "Revenues - Est Med (FY1E)",
 "EV/Sales (EST FY1)",
 "EV/Sales (LTM)",
 "EV/Sales (NTM)",
 "EV/Sales (-1FYLTM)",
 "EV/Sales (-2FYLTM)",
 "EV/Sales (-3FYLTM)",
 "EV/Sales (3YAVGLTM)",
 "EV/Sales (-1FQLTM)",
 "EV/Sales (-2FQLTM)",
 "EV/Sales (-3FQLTM)",
 "EV/Sales (-4FQLTM)",
 "Full Time Employees (FQ)",
 "Full Time Employees (FY)",
 "Full Time Employees (-1FY)",
 "Full Time Employees (-2FY)",
 "Full Time Employees (-3FY)",
 "Avg Employees (5YAVGFY)",
 "52W High/Adj",
 "52W Low/Adj",
 "EMA (20D)",
 "EMA (50D)",
 "EMA (100D)",
 "EMA (250D)",
 "EV/EBITDA (LTM)",
 "EV/EBITDA (NTM)",
 "EV/EBITDA (-1FYLTM)",
 "EV/EBITDA (-1FQLTM)",
 "EV/EBITDA (3YAVGLTM)",
 "EV/EBITDA (EST FY1)",
 "P/E (EST FY1)",
 "P/E (-2FYLTM)",
 "P/E (-3FYLTM)",
 "P/E (3YAVGLTM)",
 "P/E (-1FQLTM)",
 "P/E (-2FQLTM)",
 "P/E (-3FQLTM)",
 "P/E (-0FQQoQLTM)",
 "P/E (-0FYYoYLTM)",
 "P/E (-1FYYoYLTM)",
 "P/E (-0FQYoYLTM)",
 "Dividend Record (Announce Date)",
 "Dividend Record (Ex Date)",
 "Dividend Record (Payable Date)",
 "Dividend Record (Record Date)",
 "Dividend Record (Frequency)",
 "Dividend Record (Currency)",
 "Dividend Record (Amount)",
 "Dividend Streak")
SELECT "Ticker",
       "ISIN",
       "Name",
       "Description",
       "Exchange",
       "Unit",
       "Sector",
       "Industry",
       NULLIF("Last Updated", '')::DATE,
       NULLIF("Income Statement Report Date", '')::DATE,
       NULLIF("Next Earnings", '')::DATE,
       "Style Class",
       "Next Earnings (Status)",
       "Size Class",
       "Region",
       "Country",
       "Trading Country",
       NULLIF("Market Cap", '')::NUMERIC,
       NULLIF("Enterprise Value", '')::NUMERIC,
       NULLIF("Last Price", '')::NUMERIC,
       NULLIF("Price Target (YTD Ago)", '')::NUMERIC,
       NULLIF("Total Return (YTD)", '')::NUMERIC,
       NULLIF("Price Target", '')::NUMERIC,
       NULLIF("Price Target - Low", '')::NUMERIC,
       NULLIF("Price Target - Median", '')::NUMERIC,
       NULLIF("Price Target - High", '')::NUMERIC,
       NULLIF("Price Target - #", '')::NUMERIC,
       NULLIF("P/E (NTM)", '')::NUMERIC,
       NULLIF("P/E (LTM)", '')::NUMERIC,
       NULLIF("Altman Z-Score (FY)", '')::NUMERIC,
       NULLIF("Altman Z-Score (FQ)", '')::NUMERIC,
       NULLIF("Altman Z-Score (LTM)", '')::NUMERIC,
       NULLIF("Beta (1Y)", '')::NUMERIC,
       NULLIF("Beta (2Y)", '')::NUMERIC,
       NULLIF("Beta (5Y)", '')::NUMERIC,
       NULLIF("Analyst Rating", '')::NUMERIC,
       NULLIF("# Strong Sell Ratings", '')::NUMERIC,
       NULLIF("# Strong Buys Ratings", '')::NUMERIC,
       NULLIF("# Hold Ratings", '')::NUMERIC,
       NULLIF("# Buys Ratings", '')::NUMERIC,
       NULLIF("# Sell Ratings", '')::NUMERIC,
       NULLIF("Total Revenues/CAGR (5Y FY)", '')::NUMERIC,
       NULLIF("Total Revenues (FQ)", '')::NUMERIC,
       NULLIF("Total Revenues (-1FY)", '')::NUMERIC,
       NULLIF("Total Revenues (FY)", '')::NUMERIC,
       NULLIF("Total Revenues (LTM)", '')::NUMERIC,
       NULLIF("Total Operating Expenses (LTM)", '')::NUMERIC,
       NULLIF("P/TBV (LTM)", '')::NUMERIC,
       NULLIF("TBV (FY)", '')::NUMERIC,
       NULLIF("TBV (LTM)", '')::NUMERIC,
       NULLIF("Market Cap (Country R)", '')::NUMERIC,
       NULLIF("Tot. Return %/CAGR (3Y)", '')::NUMERIC,
       NULLIF("Tot. Return %/CAGR (10Y)", '')::NUMERIC,
       NULLIF("Total Return (5Y)", '')::NUMERIC,
       NULLIF("Total Return (10Y)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("CFF (LTM)", '')::NUMERIC,
       NULLIF("CFI (LTM)", '')::NUMERIC,
       NULLIF("FCF (LTM)", '')::NUMERIC,
       NULLIF("CFO (LTM)", '')::NUMERIC,
       NULLIF("EBITDA (FQ)", '')::NUMERIC,
       NULLIF("EBITDA (LTM)", '')::NUMERIC,
       NULLIF("EBITDA (FY)", '')::NUMERIC,
       NULLIF("EBITDA (-1FY)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (FY)", '')::NUMERIC,
       NULLIF("EBITDA/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EBIT (FQ)", '')::NUMERIC,
       NULLIF("EBIT (LTM)", '')::NUMERIC,
       NULLIF("EBIT (FY)", '')::NUMERIC,
       NULLIF("EBIT (-1FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (FY)", '')::NUMERIC,
       NULLIF("EBIT/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EBIT - Est Med (FY1E)", '')::NUMERIC,
       NULLIF("EBIT - Est Med (NTM)", '')::NUMERIC,
       NULLIF("Return On Equity % (LTM)", '')::NUMERIC,
       NULLIF("Return On Equity % (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (LTM)", '')::NUMERIC,
       NULLIF("Normalized Net Income (FY)", '')::NUMERIC,
       NULLIF("Normalized Net Income (LTM)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (FY)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (LTM)", '')::NUMERIC,
       NULLIF("Net Income Margin % (FY)", '')::NUMERIC,
       NULLIF("Net Income Margin % (LTM)", '')::NUMERIC,
       NULLIF("Volatility (1M)", '')::NUMERIC,
       NULLIF("Volatility (3M)", '')::NUMERIC,
       NULLIF("Volatility (6M)", '')::NUMERIC,
       NULLIF("Volatility (1Y)", '')::NUMERIC,
       NULLIF("Volume (Shrs)", '')::NUMERIC,
       NULLIF("Dividend Per Share (LTM)", '')::NUMERIC,
       NULLIF("Div Yield (Ind)", '')::NUMERIC,
       NULLIF("Div Yield (LTM)", '')::NUMERIC,
       NULLIF("Total Debt (FY)", '')::NUMERIC,
       NULLIF("Total Equity (FY)", '')::NUMERIC,
       NULLIF("Total Equity (LTM)", '')::NUMERIC,
       NULLIF("Total Debt (LTM)", '')::NUMERIC,
       NULLIF("Total Assets (LTM)", '')::NUMERIC,
       NULLIF("Total Assets (FY)", '')::NUMERIC,
       NULLIF("Current Ratio (FY)", '')::NUMERIC,
       NULLIF("Current Ratio (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit Margin % (FY)", '')::NUMERIC,
       NULLIF("Gross Profit Margin % (LTM)", '')::NUMERIC,
       NULLIF("Asset Turnover (FY)", '')::NUMERIC,
       NULLIF("Asset Turnover (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit (LTM)", '')::NUMERIC,
       NULLIF("Gross Profit (FY)", '')::NUMERIC,
       NULLIF("EPS Norm - Est Avg (NTM)", '')::NUMERIC,
       NULLIF("EPS/Adj. (-1FY)", '')::NUMERIC,
       NULLIF("EPS/Adj. (FY)", '')::NUMERIC,
       NULLIF("EPS/Adj. (LTM)", '')::NUMERIC,
       NULLIF("EPS Norm - Est Avg (FY1E)", '')::NUMERIC,
       NULLIF("Gain (Loss) On Sale Of Assets (LTM)", '')::NUMERIC,
       NULLIF("Cost Of Revenues (LTM)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (LTM)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (FY)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (-1FY)", '')::NUMERIC,
       NULLIF("Inventory (LTM)", '')::NUMERIC,
       NULLIF("Goodwill (FQ)", '')::NUMERIC,
       NULLIF("Goodwill (LTM)", '')::NUMERIC,
       NULLIF("Goodwill (FY)", '')::NUMERIC,
       NULLIF("Goodwill (-1FY)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (FQ)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (LTM)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (-1FY)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (FY)", '')::NUMERIC,
       NULLIF("Operating Income (LTM)", '')::NUMERIC,
       NULLIF("Asset Writedown (LTM)", '')::NUMERIC,
       NULLIF("Asset Writedown (FY)", '')::NUMERIC,
       NULLIF("Asset Writedown (-1FY)", '')::NUMERIC,
       NULLIF("Operating Income (FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (LTM)", '')::NUMERIC,
       NULLIF("Capital Expenditure (-1FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (FY)", '')::NUMERIC,
       NULLIF("Retained Earnings (LTM)", '')::NUMERIC,
       NULLIF("Total Current Assets (LTM)", '')::NUMERIC,
       NULLIF("Total Current Liabilities (LTM)", '')::NUMERIC,
       NULLIF("R&D Expenses (LTM)", '')::NUMERIC,
       NULLIF("Restructuring Charges (LTM)", '')::NUMERIC,
       NULLIF("Restructuring Charges (FQ)", '')::NUMERIC,
       NULLIF("Restructuring Charges (-1FY)", '')::NUMERIC,
       NULLIF("Restructuring Charges (FY)", '')::NUMERIC,
       NULLIF("Interest Expense/Total (LTM)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (LTM)", '')::NUMERIC,
       NULLIF("Working Capital (LTM)", '')::NUMERIC,
       NULLIF("Other Unusual Items/Total (LTM)", '')::NUMERIC,
       NULLIF("Interest Income On Investments (LTM)", '')::NUMERIC,
       NULLIF("Buyback Yield (LTM)", '')::NUMERIC,
       NULLIF("Return on Assets (ROA) % (LTM)", '')::NUMERIC,
       NULLIF("Return on Assets (ROA) % (FY)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (-1FY)", '')::NUMERIC,
       NULLIF("Normalized Net Income (-1FY)", '')::NUMERIC,
       NULLIF("P/E (-1FYLTM)", '')::NUMERIC,
       NULLIF("CFF (FY)", '')::NUMERIC,
       NULLIF("CFF (-1FY)", '')::NUMERIC,
       NULLIF("CFI (FY)", '')::NUMERIC,
       NULLIF("CFI (-1FY)", '')::NUMERIC,
       NULLIF("CFO (FY)", '')::NUMERIC,
       NULLIF("CFO (-1FY)", '')::NUMERIC,
       NULLIF("Div Yield (-1FYInd)", '')::NUMERIC,
       NULLIF("FCF (FY)", '')::NUMERIC,
       NULLIF("Capital Expenditure (FQ)", '')::NUMERIC,
       NULLIF("Capital Expenditure (5YAVGFQ)", '')::NUMERIC,
       NULLIF("CFF (FQ)", '')::NUMERIC,
       NULLIF("CFI (FQ)", '')::NUMERIC,
       NULLIF("CFO (FQ)", '')::NUMERIC,
       NULLIF("FCF (FQ)", '')::NUMERIC,
       NULLIF("Total Revenues (5YAVGFQ)", '')::NUMERIC,
       NULLIF("EBITDA (5YAVGFQ)", '')::NUMERIC,
       NULLIF("EBIT (5YAVGFQ)", '')::NUMERIC,
       NULLIF("P/E (5YAVGLTM)", '')::NUMERIC,
       NULLIF("FCF (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (FQ)", '')::NUMERIC,
       NULLIF("Cash Acquisitions (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Asset Writedown (FQ)", '')::NUMERIC,
       NULLIF("Asset Writedown (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Impairment of Goodwill (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Operating Income (FQ)", '')::NUMERIC,
       NULLIF("Operating Income (5YAVGFQ)", '')::NUMERIC,
       NULLIF("P/B (LTM)", '')::NUMERIC,
       NULLIF("P/B (-1FY)", '')::NUMERIC,
       NULLIF("P/B (5YAVG)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (LTM)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (FQ)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (FY)", '')::NUMERIC,
       NULLIF("Cash And Equivalents (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Inventory (FQ)", '')::NUMERIC,
       NULLIF("Inventory (FY)", '')::NUMERIC,
       NULLIF("Goodwill (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Inventory (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Retained Earnings (FQ)", '')::NUMERIC,
       NULLIF("Retained Earnings (FY)", '')::NUMERIC,
       NULLIF("Retained Earnings (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Working Capital (FQ)", '')::NUMERIC,
       NULLIF("Working Capital (FY)", '')::NUMERIC,
       NULLIF("Working Capital (5YAVGFY)", '')::NUMERIC,
       NULLIF("Div Yield (TTM)", '')::NUMERIC,
       NULLIF("Div Yield (NTM)", '')::NUMERIC,
       NULLIF("Div Yield (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (LTM)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (FY)", '')::NUMERIC,
       NULLIF("Gross Intangible Assets (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Restructuring Charges (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (FQ)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (FY)", '')::NUMERIC,
       NULLIF("Merger & Restructuring Charges (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Normalized Net Income (FQ)", '')::NUMERIC,
       NULLIF("Normalized Net Income (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (FQ)", '')::NUMERIC,
       NULLIF("Net Income/Adj. (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (FQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Net Income - (IS) (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Normalized Net Income (5YAVGLTM)", '')::NUMERIC,
       NULLIF("EBITDA (5YAVGLTM)", '')::NUMERIC,
       NULLIF("EBIT (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Total Revenues (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Revenues - Est YoY % (FY1E)", '')::NUMERIC,
       NULLIF("Price Chg. % (1M)", '')::NUMERIC,
       NULLIF("Price Chg. % (3M)", '')::NUMERIC,
       NULLIF("1-Day %", '')::NUMERIC,
       NULLIF("Price (5D Ago)", '')::NUMERIC,
       NULLIF("Price (1W Ago)", '')::NUMERIC,
       NULLIF("Price (1M Ago)", '')::NUMERIC,
       NULLIF("Price (3M Ago)", '')::NUMERIC,
       NULLIF("Price (6M Ago)", '')::NUMERIC,
       NULLIF("Price (1Y Ago)", '')::NUMERIC,
       NULLIF("Price (3Y Ago)", '')::NUMERIC,
       NULLIF("Price (5Y Ago)", '')::NUMERIC,
       NULLIF("Price (QTD Ago)", '')::NUMERIC,
       NULLIF("Rel. Volume", '')::NUMERIC,
       NULLIF("Shrs Out", '')::NUMERIC,
       NULLIF("Shrs Out (-1FY)", '')::NUMERIC,
       NULLIF("Common Dividends Paid (LTM)", '')::NUMERIC,
       NULLIF("Common Dividends Paid (FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (FQ)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (-1FY)", '')::NUMERIC,
       NULLIF("Selling General & Admin Expenses/Total (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (FY)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (-1FY)", '')::NUMERIC,
       NULLIF("Accounts Receivable/Total (5YAVGFQ)", '')::NUMERIC,
       NULLIF("Marketing Expenses (FQ)", '')::NUMERIC,
       NULLIF("Marketing Expenses (FY)", '')::NUMERIC,
       NULLIF("Marketing Expenses (-1FY)", '')::NUMERIC,
       NULLIF("Marketing Expenses (5YAVGLTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Avg (NTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Avg (FY1E)", '')::NUMERIC,
       NULLIF("Revenues - Est Med (NTM)", '')::NUMERIC,
       NULLIF("Revenues - Est Med (FY1E)", '')::NUMERIC,
       NULLIF("EV/Sales (EST FY1)", '')::NUMERIC,
       NULLIF("EV/Sales (LTM)", '')::NUMERIC,
       NULLIF("EV/Sales (NTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-1FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-2FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-3FYLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (3YAVGLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-1FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-2FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-3FQLTM)", '')::NUMERIC,
       NULLIF("EV/Sales (-4FQLTM)", '')::NUMERIC,
       NULLIF("Full Time Employees (FQ)", '')::NUMERIC,
       NULLIF("Full Time Employees (FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-1FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-2FY)", '')::NUMERIC,
       NULLIF("Full Time Employees (-3FY)", '')::NUMERIC,
       NULLIF("Avg Employees (5YAVGFY)", '')::NUMERIC,
       NULLIF("52W High/Adj", '')::NUMERIC,
       NULLIF("52W Low/Adj", '')::NUMERIC,
       NULLIF("EMA (20D)", '')::NUMERIC,
       NULLIF("EMA (50D)", '')::NUMERIC,
       NULLIF("EMA (100D)", '')::NUMERIC,
       NULLIF("EMA (250D)", '')::NUMERIC,
       NULLIF("EV/EBITDA (LTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (NTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (-1FYLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (-1FQLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (3YAVGLTM)", '')::NUMERIC,
       NULLIF("EV/EBITDA (EST FY1)", '')::NUMERIC,
       NULLIF("P/E (EST FY1)", '')::NUMERIC,
       NULLIF("P/E (-2FYLTM)", '')::NUMERIC,
       NULLIF("P/E (-3FYLTM)", '')::NUMERIC,
       NULLIF("P/E (3YAVGLTM)", '')::NUMERIC,
       NULLIF("P/E (-1FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-2FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-3FQLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FQQoQLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FYYoYLTM)", '')::NUMERIC,
       NULLIF("P/E (-1FYYoYLTM)", '')::NUMERIC,
       NULLIF("P/E (-0FQYoYLTM)", '')::NUMERIC,
       NULLIF("Dividend Record (Announce Date)", '')::DATE,
       NULLIF("Dividend Record (Ex Date)", '')::DATE,
       NULLIF("Dividend Record (Payable Date)", '')::DATE,
       NULLIF("Dividend Record (Record Date)", '')::DATE,
       "Dividend Record (Frequency)",
       "Dividend Record (Currency)",
       NULLIF("Dividend Record (Amount)", '')::NUMERIC,
       NULLIF("Dividend Streak", '')::NUMERIC
FROM screening_rotw
ON CONFLICT DO NOTHING;

