"""
Validation script to test Phase 9.3 feature engineering and event label creation.

This script verifies that:
1. All required features are generated by build_comprehensive_features()
2. Event labels (especially composite_event) produce proper class distributions
3. No event label methods return 100% neutral labels

Usage:
    python validate_event_labels.py
"""

import sys

import numpy as np
import pandas as pd

# Add the project root to the path
sys.path.insert(0, r"C:\Users\markm\PycharmProjects\Finance_ML_Analytics_Platform")

from finance_ml.features.advanced import build_comprehensive_features
from finance_ml.ml_workflow.classification.labels import create_enhanced_event_labels


def create_sample_data(n_samples=1000):
    """Create synthetic financial data for testing."""
    np.random.seed(42)
    
    data = {
        # Basic identifiers
        "ticker": [f"TICK{i:04d}" for i in range(n_samples)],
        "sector": np.random.choice(["Technology", "Healthcare", "Financials", "Energy"], n_samples),
        
        # Price data
        "last_price": np.random.uniform(10, 500, n_samples),
        "price_target": np.random.uniform(10, 500, n_samples),
        
        # Financial metrics for profitability
        "net_income": np.random.uniform(-100, 500, n_samples),
        "total_equity": np.random.uniform(100, 5000, n_samples),
        "total_assets": np.random.uniform(500, 10000, n_samples),
        "total_debt": np.random.uniform(50, 3000, n_samples),
        "revenue": np.random.uniform(100, 5000, n_samples),
        
        # For leverage ratios
        "net_debt": np.random.uniform(-500, 2000, n_samples),
        "ebitda": np.random.uniform(50, 1000, n_samples),
        "ebit": np.random.uniform(40, 900, n_samples),
        
        # For liquidity ratios
        "current_assets": np.random.uniform(200, 3000, n_samples),
        "current_liabilities": np.random.uniform(100, 2000, n_samples),
        "inventory": np.random.uniform(50, 500, n_samples),
        "cash_and_equivalents": np.random.uniform(100, 1500, n_samples),
        
        # For efficiency ratios
        "cogs": np.random.uniform(50, 2000, n_samples),
        "accounts_receivable": np.random.uniform(50, 800, n_samples),
        
        # For growth metrics
        "revenue_previous_year": np.random.uniform(80, 4500, n_samples),
        "eps": np.random.uniform(-2, 10, n_samples),
        "eps_previous_year": np.random.uniform(-2, 10, n_samples),
        "ebitda_previous_year": np.random.uniform(40, 950, n_samples),
        
        # For composite scores
        "working_capital": np.random.uniform(-200, 1000, n_samples),
        "retained_earnings": np.random.uniform(-100, 2000, n_samples),
        "market_cap": np.random.uniform(500, 20000, n_samples),
        "total_liabilities": np.random.uniform(300, 7000, n_samples),
        "cfo_ltm": np.random.uniform(-50, 600, n_samples),
        
        # For Piotroski
        "gross_profit": np.random.uniform(50, 2000, n_samples),
        "operating_income": np.random.uniform(30, 800, n_samples),
        "shares_outstanding": np.random.uniform(10, 500, n_samples),
    }
    
    return pd.DataFrame(data)


def test_feature_engineering():
    """Test that all Phase 9.3 features are generated."""
    print("=" * 80)
    print("TESTING FEATURE ENGINEERING")
    print("=" * 80)
    
    # Create sample data
    df = create_sample_data(1000)
    print(f"\n✓ Created sample data: {df.shape}")
    print(f"  Columns: {len(df.columns)}")
    
    # Apply comprehensive feature engineering
    print("\n🔧 Applying build_comprehensive_features()...")
    df_features = build_comprehensive_features(
        df,
        include_interactions=False,  # Skip interactions for speed
        include_relative_values=False,  # Skip relative values for speed
        preset="comprehensive"
    )
    
    print(f"\n✓ Feature engineering completed: {df_features.shape}")
    print(f"  Total features: {len(df_features.columns)}")
    print(f"  New features added: {len(df_features.columns) - len(df.columns)}")
    
    # Check for critical Phase 9.3 features
    critical_features = {
        "Profitability": ["roe", "roa", "roic"],
        "Leverage": ["debt_to_equity", "net_debt_to_ebitda", "debt_to_assets"],
        "Liquidity": ["current_ratio", "quick_ratio", "cash_ratio"],
        "Efficiency": ["asset_turnover", "inventory_turnover"],
        "Growth": ["revenue_growth", "earnings_growth", "ebitda_growth"],
        "Composite Scores": ["piotroski_f_score", "altman_z_score", "beneish_m_score"],
    }
    
    print("\n📊 Checking critical Phase 9.3 features:")
    all_present = True
    for category, features in critical_features.items():
        present = [f for f in features if f in df_features.columns]
        missing = [f for f in features if f not in df_features.columns]
        
        if missing:
            print(f"  ❌ {category}: {len(present)}/{len(features)} present - MISSING: {missing}")
            all_present = False
        else:
            print(f"  ✅ {category}: {len(present)}/{len(features)} present")
    
    if all_present:
        print("\n✓ All critical Phase 9.3 features are present!")
    else:
        print("\n⚠ Some critical features are missing - event labels may not work properly")
    
    return df_features


def test_event_labels(df_features):
    """Test that event labels produce proper class distributions."""
    print("\n" + "=" * 80)
    print("TESTING EVENT LABEL CREATION")
    print("=" * 80)
    
    event_methods = [
        "profitability_event",
        "leverage_event",
        "liquidity_event",
        "efficiency_event",
        "growth_event",
        "composite_event",
    ]
    
    results = []
    
    for method in event_methods:
        print(f"\n🏷️  Testing method: {method}")
        
        try:
            labels = create_enhanced_event_labels(df_features, method=method)
            
            # Count class distribution
            unique, counts = np.unique(labels, return_counts=True)
            distribution = dict(zip(unique, counts))
            
            neutral = distribution.get(0, 0)
            positive = distribution.get(1, 0)
            negative = distribution.get(2, 0)
            total = len(labels)
            
            # Check if all neutral (the problem we're fixing)
            all_neutral = (neutral == total)
            
            print(f"  Class distribution:")
            print(f"    Neutral (0): {neutral} ({neutral/total*100:.1f}%)")
            print(f"    Positive (1): {positive} ({positive/total*100:.1f}%)")
            print(f"    Negative (2): {negative} ({negative/total*100:.1f}%)")
            
            if all_neutral:
                print(f"  ❌ FAIL: All labels are neutral!")
                results.append((method, False, "All neutral"))
            elif positive == 0 and negative == 0:
                print(f"  ⚠ WARNING: No positive or negative labels generated")
                results.append((method, False, "No variance"))
            else:
                print(f"  ✅ PASS: Proper class distribution generated")
                results.append((method, True, "OK"))
                
        except Exception as e:
            print(f"  ❌ ERROR: {str(e)}")
            results.append((method, False, f"Error: {str(e)[:50]}"))
    
    # Summary
    print("\n" + "=" * 80)
    print("SUMMARY")
    print("=" * 80)
    
    passed = sum(1 for _, success, _ in results if success)
    total = len(results)
    
    print(f"\nEvent Label Methods: {passed}/{total} passed")
    print("\nDetailed Results:")
    for method, success, note in results:
        status = "✅ PASS" if success else "❌ FAIL"
        print(f"  {status}: {method:25s} - {note}")
    
    if passed == total:
        print("\n🎉 SUCCESS! All event label methods generate proper class distributions!")
        return True
    else:
        print(f"\n⚠ {total - passed} event label methods still need attention")
        return False


def main():
    """Run validation tests."""
    print("\n" + "=" * 80)
    print("PHASE 9.3 EVENT LABEL VALIDATION")
    print("=" * 80)
    
    # Test feature engineering
    df_features = test_feature_engineering()
    
    # Test event label creation
    success = test_event_labels(df_features)
    
    # Final status
    print("\n" + "=" * 80)
    if success:
        print("✅ VALIDATION PASSED - All systems operational!")
    else:
        print("❌ VALIDATION FAILED - Some issues remain")
    print("=" * 80 + "\n")
    
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
